/************
The GAIT Tool was developed at the National Geospatial-Intelligence Agency (NGA) in collaboration with the   
Institute for Defense Analyses (IDA) under a Government contract. The government is releasing this software   
to increase the impact of government investments by providing developers with the opportunity to take things   
in new directions. The software use, modification, and distribution rights are stipulated within the MIT license.

As-is warranty is covered within the MIT license but it's re-stated here for clarity: The GAIT tool contains several   
software components. The software is provided "as is," and no warranty, express or implied, including but not limited   
to the implied warranties of merchantability and fitness for particular purpose or arising by statute or otherwise in   
law or from a course of dealing or usage in trade, is made with respect to the accuracy or functioning of the software.   
Neither NGA or IDA are liable for any claims, losses, or damages arising from or connected with the use of the software.   
The user's sole and exclusive remedy is to stop using the software.
************/
int D4_ATTR_NUM=679;

char *D4_attr_codes[] = {
"M_CDV_1U030",
"M_AS1_1U030",
"M_NM8_1U030",
"AGD",
"ATL",
"AUA",
"ACE",
"ACE_EVAL_METHOD_CD",
"M_ACE_2H020",
"M_ACE_2H140",
"M_ACE_1Q131",
"M_ACE_1Q100",
"M_ACE_2H030",
"M_ACE_1P030",
"M_ACE_1P020",
"M_ACE_6C165",
"M_ACE_6C160",
"M_ACE_1U030",
"M_ACE_6C180",
"M_ACE_1P031",
"M_ACE_2H141",
"M_ACE_9D066",
"AHA",
"ALE",
"ALE_EVAL_METHOD_CD",
"M_ALE_1P031",
"M_ALE_6C160",
"M_ALE_2H141",
"M_ALE_9D066",
"M_ALE_6C180",
"M_ALE_1U030",
"M_ALE_6C165",
"M_ALE_1Q131",
"M_ALE_2H020",
"M_ALE_2H030",
"M_ALE_1Q100",
"M_ALE_1P030",
"M_ALE_2H140",
"M_ALE_1P020",
"AVA",
"ACC",
"ACL",
"ACR",
"AHO",
"ORIGINATOR",
"ATN",
"TDT",
"APT",
"ZV3",
"AKY",
"AS1",
"AIA",
"OTM",
"AUB",
"AUL",
"AUR",
"AOO",
"ARR",
"ACP",
"ENT",
"ATC",
"ARE_",
"AGC",
"AGL",
"ARC",
"ARD",
"AHC",
"AFA",
"USI",
"BGL",
"BGR",
"BHL",
"HL1",
"HL3",
"BHR",
"HR1",
"HR3",
"BVL",
"BVR",
"BEN",
"BIT",
"BET",
"BRS",
"BRR",
"BRG",
"BER",
"BMC",
"CFT",
"DMC",
"DSP",
"FBL",
"LSP",
"RPC",
"BST",
"BOT",
"BRN",
"BSP",
"BSM",
"BSC",
"BRF",
"BR2",
"BUD",
"BFC",
"BNF",
"BAC",
"BUT",
"BCC",
"CAB",
"CDP",
"CDV",
"CAP",
"COD",
"COE",
"CHL",
"COL",
"CLR",
"SEC_CLS_AUTHORITY",
"CCC",
"CCR",
"PAT",
"CLT",
"COMMENTS",
"COMM_CPYRT_NOTICE",
"CLI",
"COMPLETENESS_CODE",
"COF",
"COC",
"CCA",
"CPA",
"NA4",
"CDA",
"CDL",
"CRM",
"CSD",
"CRA",
"CSC",
"CFD",
"CTC",
"CTL",
"HS1",
"HS2",
"CRX",
"CRN",
"CUR",
"CET",
"DFT",
"M_DCF",
"HTE",
"GD4",
"DMK",
"DMR",
"DMT",
"DMB",
"DMF",
"DMS",
"DEP",
"CRV",
"CVH",
"CVL",
"DRN",
"DW1",
"YWT",
"OHD",
"DAN",
"DRP",
"D61",
"D70",
"D71",
"D62",
"D63",
"D64",
"D65",
"D66",
"D67",
"D68",
"D69",
"D60",
"DOF",
"DF1",
"DF2",
"DF3",
"DF4",
"DIR",
"COMM_LIC_TIER_NOTICE",
"DCR",
"DGC",
"EBT",
"EDP",
"ELA",
"EOL",
"EXS",
"SOU",
"EHI",
"ELI",
"SPEC_ID",
"TMS",
"FTP",
"FPT",
"FTC",
"FCO",
"FCM",
"CREATION_DATE",
"FEO",
"UID_",
"SCALE",
"FTI",
"FCL",
"FER",
"FEC",
"FRT",
"VA2",
"FL1",
"FL2",
"FLT",
"FDT",
"SIZE_",
"C01",
"FDM",
"B01",
"GW1",
"GW3",
"GNC",
"GTC",
"GAW",
"GPD",
"GEH",
"GTP",
"GEC",
"GFID",
"SGC",
"GHE",
"GSC",
"GUG",
"HNG",
"HDW",
"HTP",
"FHC",
"HAS_INFO",
"HSB",
"HGT",
"HAS",
"HGS",
"HTR",
"M_DCF_1P020",
"M_DFS_1P020",
"M_RIT_1P020",
"M_SGC_1P020",
"M_TUC_1P020",
"M_WID_1P020",
"M_AKY_1U030",
"M_AKY_1P030",
"M_DCF_1P030",
"M_FRK_1P030",
"M_NAM_1P030",
"M_USE_1P030",
"M_AVB_1P031",
"M_SEP_1P031",
"M_DCF_1P031",
"M_ATN_1Q100",
"M_DCF_1Q100",
"M_DVA_1Q100",
"M_UFI_1Q100",
"M_UNI_1Q100",
"M_DCF_1Q131",
"M_UFI_1Q131",
"M_UFI_1P020",
"M_NAM_1U030",
"M_UFI_1P030",
"M_UFI_1U030",
"M_UFI_1P031",
"M_DCF_1U030",
"M_DCF_2H020",
"M_HDP_2H020",
"M_NAM_2H020",
"M_RPA_2H020",
"M_UFI_2H020",
"M_VDC_2H020",
"M_VDR_2H020",
"M_DCF_2H030",
"M_UFI_2H030",
"M_DCF_2H140",
"M_DCF_2H141",
"M_NAM_2H140",
"M_UFI_2H140",
"M_RPA_2H141",
"M_UFI_2H141",
"M_ZV2_2H141",
"M_DCF_6C160",
"M_IAS_6C160",
"M_IAS_6C180",
"M_TMS_6C160",
"M_TSP_6C160",
"M_UFI_6C160",
"M_UQI_6C160",
"M_ATN_6C165",
"M_BRR_6C165",
"M_BRS_6C165",
"M_DAN_6C165",
"M_DCF_6C165",
"M_DOF_6C165",
"M_DRP_6C165",
"M_EXS_6C165",
"M_HDI_6C165",
"M_HDP_6C165",
"M_NAM_6C165",
"M_RTT_6C165",
"M_TMS_6C165",
"M_UFI_6C165",
"M_UQI_6C165",
"M_VDC_6C165",
"M_VDR_6C165",
"M_DCF_6C180",
"M_DOF_6C180",
"M_TSP_6C180",
"M_UFI_6C180",
"M_UQI_6C180",
"M_WID_6C180",
"M_TMS_6C180",
"M_ACP_9D066",
"M_ANT_9D066",
"M_BEN_9D066",
"M_DCF_9D066",
"M_DRI_9D066",
"M_HAF_9D066",
"M_PFL_9D066",
"M_RLN_9D066",
"M_RLT_9D066",
"M_SPL_9D066",
"M_UFI_9D066",
"M_ZV2_9D066",
"AV2",
"AZ2",
"ZV2",
"AVB",
"AAI",
"HCA",
"HCC",
"HZD",
"HWT",
"HTB",
"HTS",
"HTC",
"HTD",
"HTG",
"HTZ",
"HDP",
"HDI",
"HDH",
"HLT",
"HOC",
"HYC",
"HFC",
"HQC",
"IAC",
"ICL",
"IKO",
"IAS",
"IDN",
"IWO",
"IBC",
"KVA",
"LAB",
"LMC",
"LOG",
"LRP",
"LEN_",
"LEG",
"CHA",
"LFA",
"LVN",
"LSA",
"LSI",
"LST",
"LWI",
"LAF",
"LC1",
"LC2",
"LC3",
"LC4",
"LOC",
"AV1",
"AZ1",
"MAG",
"MAS",
"MAC",
"MBL",
"MCC",
"MCS",
"MCU",
"MAA",
"MDU",
"MVC",
"HTH",
"MED",
"MWG",
"MBI",
"WD3",
"MNA",
"MNL",
"MNC",
"MNI",
"MIC",
"MIA",
"MII",
"MIM",
"MIO",
"MID",
"MPC",
"MPG",
"MPM",
"MPO",
"MSI",
"MSH",
"MSR",
"MSW",
"MSD",
"MMT",
"MSU",
"MSC",
"MTN",
"MEA",
"AZ3",
"WD1",
"MIN_",
"MST",
"MCA",
"WMS",
"SEC_CLS_AUTH_MULT",
"MLR",
"NAM",
"NM3",
"NM4",
"NFN",
"NFI",
"NAS",
"NSN",
"NST",
"NS2",
"SEC_CLS_AUTH_DESC",
"RAG",
"E01",
"NPL",
"NOS",
"OLQ",
"OPC",
"ORC",
"OR2",
"OPS",
"OPERATOR",
"ORD",
"OAC",
"OBS",
"OFT",
"ORIG_SOURCE_DATE",
"ORIG_SOURCE_INFO",
"ORIGINATING_SOURCE",
"OWO",
"OHB",
"OHC",
"OCC",
"OOC",
"PER",
"PR1",
"PRC",
"PR2",
"PRM",
"PSC",
"FAC",
"PWC",
"PBV",
"PLT",
"PXT",
"PCI",
"PPL",
"PPT",
"WPI",
"PIA",
"PEC",
"PEV",
"PRT",
"PPC",
"PFE",
"PFG",
"PHT",
"PH4",
"VH1",
"VH3",
"NA8",
"PRO",
"REF_",
"RCC",
"RAD",
"RSA",
"AVR",
"RRC",
"RGC",
"RRA",
"RGS",
"C61",
"C70",
"C71",
"C62",
"C63",
"C64",
"C65",
"C66",
"C67",
"C68",
"C69",
"C60",
"RPD",
"T01",
"QLE",
"RBC",
"REL",
"RPA",
"RTP",
"RSTRN_FOREIGN_GOV",
"RSTRN_DECLASS",
"RSTRN_DCLS_XMPT_CD",
"RSTRN_DSEM_CTRL_IC",
"RSTRN_DSEM_CTRL_NIC",
"RSTRN_RELEASIBILITY",
"RIT",
"SEP",
"RST",
"RKF",
"RTT",
"RTN",
"RCL",
"RFL",
"RAH",
"RHI",
"VPH",
"TSH",
"VSH",
"RID",
"RAL",
"RLI",
"VPL",
"TSL",
"VSL",
"RSL",
"RTH",
"RTL",
"SHC",
"SDO",
"SEA",
"SFC",
"STL",
"NA2",
"VA3",
"CSM",
"SEC",
"SEC_CLASS",
"SEC_CLASS_SYS_ID",
"SEC_CD_CNTRL",
"YSU",
"SOH",
"SHP",
"SBC",
"DDM",
"SHO",
"SLT",
"SHL",
"SHR",
"SL1",
"SR1",
"SPR",
"SIC",
"SDE",
"STG",
"STP",
"SWC",
"SST",
"SND",
"CLS",
"SHA",
"SSI",
"SVC",
"SV1",
"STC",
"WSR",
"SVR",
"SPV",
"SUA",
"SPD",
"SCC",
"STA",
"SD1",
"SD2",
"SDR",
"SSC",
"SSR",
"STY",
"STQ",
"SCB",
"SMC",
"SRD",
"SM1",
"SUR",
"SUE",
"TSR",
"TLA",
"TXR",
"TXP",
"TXT",
"TID",
"TIM",
"TNG",
"TMC",
"WD2",
"TTC",
"LTN",
"TRF",
"TSP",
"TBT",
"TST",
"TUC",
"TRA",
"TS1",
"TS2",
"TS3",
"TSD",
"TRE",
"FHH",
"FHL",
"FON",
"UBC",
"UBD",
"UMC",
"M_UFI",
"UNI",
"UPDATE_SOURCE_DATE",
"UPDATE_SOURCE_INFO",
"UPDATE_SOURCE",
"USP",
"USE_",
"LNU",
"WDU",
"VAL",
"VA4",
"VAV",
"VEG",
"VRC",
"VDC",
"AAW",
"VCD",
"VCR",
"VC3",
"VDR",
"VOI",
"VRR",
"VAC",
"VCA",
"VCT",
"VGT",
"VOL",
"WTI",
"WDA",
"YDH",
"YDL",
"YWQ",
"WV1",
"YVH",
"YVL",
"WPT",
"WTC",
"WFT",
"SWT",
"WID",
"WD5",
"WOC",
"WT2",
"WGP",
"WTR",
"WPC",
"WKT",
"Z_VALUE_TYPE"
};

char *D4_attr_names[] = {
"(unnamed attribute)",
"(unnamed attribute)",
"(unnamed attribute)",
"(unnamed attribute)",
"ATS Route Level",
"ATS Use Attribute",
"Absolute Circular Error",
"Absolute Circular Error Evaluation Method",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Circular Error of Feature Position",
"Absolute Horizontal Accuracy in Meters",
"Absolute Linear Error",
"Absolute Linear Error Evaluation Method",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Linear Error of Feature Position",
"Absolute Vertical Accuracy in Meters",
"Accuracy Category",
"Accuracy Left Bank",
"Accuracy Right Bank",
"Accuracy of Obstruction Height Above Ground Level",
"Agency that Supplied the Data",
"Aids to Navigation",
"Air Facility Terrain or Drainage Type",
"Airfield Type",
"Airfield/Aerodrome elevation",
"Airport Key",
"Airport Strip Type",
"Airspace Identification Attribute",
"Airspace Operating Times",
"Airspace Use Boundary",
"Airspace Use Limitations",
"Airspace Use Routes",
"Angle of Orientation",
"Angle of Radar Reflector",
"Annotation Category Primary",
"Apron/Hardstand Entry Clearance",
"Aqueduct Type Category",
"Area With Greater Than 1 Meter Squared Resolution",
"Arresting Gear Category",
"Arresting Gear Location",
"Artifact Code",
"Artifact Description",
"Associated Hydrographic Category",
"Available Facilities",
"BAD Sounding Identifier",
"Bank Gradient Left",
"Bank Gradient Right",
"Bank Height Left",
"Bank Height Left (1)",
"Bank Height Left (3)",
"Bank Height Right",
"Bank Height Right (1)",
"Bank Height Right (3)",
"Bank Vegetation Left",
"Bank Vegetation Right",
"Basic Encyclopedia Number",
"Beach Indicator Type",
"Beacon Type Category",
"Bearing From Seaward",
"Bearing and Reciprocal Category",
"Bearing of Object",
"Berth Identifier",
"Bottom Materials Composition",
"Boundary Configuration Type Code",
"Boundary Demarcation Code",
"Boundary Dispute Status",
"Boundary Lights",
"Boundary Lines Of Separation Code",
"Boundary Representation Policy Code",
"Boundary Status Type",
"Bridge Opening Type",
"Bridge Reference Number",
"Bridge Span Category",
"Bridge Span Mobility",
"Bridge/Bridge Superstructure Category",
"Broadcast Frequency",
"Broadcast Frequency (2)",
"Brush/Undergrowth Density Code",
"Building Function Category",
"Building Number of Floors",
"Built-Up Area Classification",
"Buoy Type Category",
"Bypass Condition Category",
"Cable Classification",
"Calendar Date Type",
"Calendar Date Value",
"Capacity",
"Certainty of Delineation",
"Certainty of Existence",
"Channel Number",
"Character of Light",
"Class of Rapids",
"Classification Authority",
"Color Code Category",
"Color Code Remarks",
"Color Pattern Category",
"Color of Text",
"Comments",
"Commercial Copyright Notice",
"Communication Lines Isolation",
"Completeness Code",
"Complex Outline Function",
"Conspicuous Category",
"Constriction/Expansion Category",
"Control Point Attribute",
"Country Code (FIPS Pub 10-4)",
"Covered Drain Attribute",
"Covered Drain Length",
"Crane Mobility Type",
"Crane Support Distance",
"Crane Type Category",
"Crossing Control Category",
"Cultural Feature Density",
"Culvert Type Category",
"Cumulative Track Length",
"Current Information (1)",
"Current Information (2)",
"Current Rate Maximum",
"Current Rate Minimum",
"Current Type Category",
"Cut/Embankment Type Category",
"Dam Face Type",
"Data Comparator Flag",
"Date/Dates of Hull Integrity Test Site",
"Defense SAM Site",
"Density Measure (% of Kelp Cover)",
"Density Measure (% of Roof Cover)",
"Density Measure (% of Tree/Canopy Cover)",
"Density Measure (Brush/Undergrowth)",
"Density Measure (Feature Count)",
"Density Measure (Structure Count)",
"Depth Below Surface Level",
"Depth Curve or Contour Value",
"Depth Curve or Contour Value High",
"Depth Curve or Contour Value Low",
"Depth Recorder Name",
"Depth of Water (1)",
"Depth to Water Table",
"Derived Obstacle Height/Depth Category",
"Description of Aids to Navigation",
"Description of Reference Point",
"Direction of Current (1) (IHO)",
"Direction of Current (10) (IHO)",
"Direction of Current (11) (IHO)",
"Direction of Current (2) (IHO)",
"Direction of Current (3) (IHO)",
"Direction of Current (4) (IHO)",
"Direction of Current (5) (IHO)",
"Direction of Current (6) (IHO)",
"Direction of Current (7) (IHO)",
"Direction of Current (8) (IHO)",
"Direction of Current (9) (IHO)",
"Direction of Current (IHO)",
"Direction of Flow",
"Direction of Traffic - 1",
"Direction of Traffic - 2",
"Direction of Traffic - 3",
"Direction of Traffic - 4",
"Directivity",
"Distribution of Commercial Data",
"Draft Correction Indicator",
"Drop Gate Category",
"Educational Building Type",
"Electronic Depth",
"Elevation Accuracy",
"Elevation of Light",
"Existence Category",
"Exposition of Sounding",
"Extracted Runway High Identifier",
"Extracted Runway Low Identifier",
"Extraction Specification ID",
"Extraction Timestamp",
"Fabrication Type",
"Facility Priority Type",
"Farming Type Category",
"Feature Configuration",
"Feature Construction Material Code",
"Feature Creation Date",
"Feature Element Orientation",
"Feature Identification Number",
"Feature Scale (e.g., 50000, 100000)",
"Fence Type Indicator",
"Ferry Crossing Length",
"Ferry Type",
"Final Evaluation Code",
"Firing Range Type",
"First magnetic variation value",
"Flight Level 1",
"Flight Level 2",
"Floodlit Illumination",
"Fog Detector",
"Font Size",
"Fuel Containers Capacity Each",
"Fuel Dispensing Method",
"Fuel Storage Method",
"Gap Width Range (1)",
"Gap Width Range (3)",
"Gate (Nautical) Classification",
"Gate Type Category",
"Gauge Width",
"Geomorphic Depth",
"Geomorphic Height",
"Geomorphic Type",
"Geopolitical Entity Code",
"Global Feature ID",
"Gradient/Slope",
"Greatest Horizontal Extent",
"Ground Slope Category",
"Guyed or Unguyed Category",
"Hangar Door Height",
"Hangar Door Width",
"Hangar Type Category",
"Harbor Facility Classification",
"Has Additional Information Flag",
"Height Above Sea Bottom",
"Height Above Surface Level",
"Height Above Surrounding Features",
"Height Of Spillway",
"Height Range",
"Hierarchy 1P020 DCF",
"Hierarchy 1P020 DFS",
"Hierarchy 1P020 RIT",
"Hierarchy 1P020 SGC",
"Hierarchy 1P020 TUC",
"Hierarchy 1P020 WID",
"Hierarchy 1P030 AKY",
"Hierarchy 1P030 AKY",
"Hierarchy 1P030 DCF",
"Hierarchy 1P030 FRK",
"Hierarchy 1P030 NAM",
"Hierarchy 1P030 USE",
"Hierarchy 1P031 AVB",
"Hierarchy 1P031 SEP",
"Hierarchy 1P131 DCF",
"Hierarchy 1Q100 ATN",
"Hierarchy 1Q100 DCF",
"Hierarchy 1Q100 Distance Value Attribute",
"Hierarchy 1Q100 UFI",
"Hierarchy 1Q100 UNI",
"Hierarchy 1Q131 DCF",
"Hierarchy 1Q131 UFI",
"Hierarchy 1U020 UFI",
"Hierarchy 1U030 NAM",
"Hierarchy 1U030 UFI",
"Hierarchy 1U030 UFI",
"Hierarchy 1U031 UFI",
"Hierarchy 1U130 DCF",
"Hierarchy 2H020 DCF",
"Hierarchy 2H020 HDP",
"Hierarchy 2H020 NAM",
"Hierarchy 2H020 RPA",
"Hierarchy 2H020 UFI",
"Hierarchy 2H020 VDC",
"Hierarchy 2H020 VDR",
"Hierarchy 2H030 DCF",
"Hierarchy 2H030 UFI",
"Hierarchy 2H040 DCF",
"Hierarchy 2H041 DCF",
"Hierarchy 2H140 NAM",
"Hierarchy 2H140 UFI",
"Hierarchy 2H141 RPA",
"Hierarchy 2H141 UFI",
"Hierarchy 2H141 ZV2",
"Hierarchy 6C160 DCF",
"Hierarchy 6C160 IAS",
"Hierarchy 6C160 IAS",
"Hierarchy 6C160 TMS",
"Hierarchy 6C160 TSP",
"Hierarchy 6C160 UFI",
"Hierarchy 6C160 UQI",
"Hierarchy 6C165 ATN",
"Hierarchy 6C165 BRR",
"Hierarchy 6C165 BRS",
"Hierarchy 6C165 DAN",
"Hierarchy 6C165 DCF",
"Hierarchy 6C165 DOF",
"Hierarchy 6C165 DRP",
"Hierarchy 6C165 EXS",
"Hierarchy 6C165 HDI",
"Hierarchy 6C165 HDP",
"Hierarchy 6C165 NAM",
"Hierarchy 6C165 RTT",
"Hierarchy 6C165 TMS",
"Hierarchy 6C165 UFI",
"Hierarchy 6C165 UQI",
"Hierarchy 6C165 VDC",
"Hierarchy 6C165 VDR",
"Hierarchy 6C180 DCF",
"Hierarchy 6C180 DOF",
"Hierarchy 6C180 TSP",
"Hierarchy 6C180 UFI",
"Hierarchy 6C180 UQI",
"Hierarchy 6C180 WID",
"Hierarchy 6C180TMS",
"Hierarchy 9D066 Annotation Category Primary",
"Hierarchy 9D066 Annotation Type",
"Hierarchy 9D066 BEN",
"Hierarchy 9D066 DCF",
"Hierarchy 9D066 Data Reference Identifier",
"Hierarchy 9D066 Horizontal Accuracy Flag",
"Hierarchy 9D066 Proper Name/Function/Location",
"Hierarchy 9D066 RLN",
"Hierarchy 9D066 RLT",
"Hierarchy 9D066 SPL",
"Hierarchy 9D066 UFI",
"Hierarchy 9D066 ZV2",
"Highest Airspace Height",
"Highest Airspace Z-value",
"Highest Z-Value",
"Highway Access Road Category",
"Horizontal Accuracy Category",
"Horizontal Clearance Attribute",
"Horizontal Clearance Code",
"Horizontal Datum",
"House of Worship Type",
"Hull Integrity Test Site - Changes in bottom topography",
"Hull Integrity Test Site - Special features",
"Hull Integrity Test Site Characteristics",
"Hull Integrity Test Site Direction of slope of test site",
"Hull Integrity Test Site Slope Gradient",
"Hull Integrity Test Site Test Zone",
"Hydrographic Depth",
"Hydrographic Depth/Height Information",
"Hydrographic Drying Height",
"Hydrographic Light Type",
"Hydrographic Origin Category",
"Hydrological Category",
"Hydrological Form Category",
"Hypsography Portrayal Category",
"IALA Aid Category",
"ICAO Airspace Classification",
"ICAO Designator",
"IMO Adoption Status",
"Identification Number",
"Inland Water Obstruction",
"Installation Buoy Classification",
"Kilovolt Capacity Attribute",
"Label of Feature",
"Landmark Category",
"Length of Gradient",
"Length of Range With greater than 1 NM resolution",
"Length/Diameter",
"Length/Diameter in Meters With Greater Precision",
"Light Characteristic Category",
"Light Function Aeronautical",
"Light Range, Nominal",
"Light Sector Angle",
"Light Sector Angle Initial",
"Light Sector Angle Terminal",
"Lighted Wind Indicator Availability",
"Line Associated Features",
"Load Class Type 1",
"Load Class Type 2",
"Load Class Type 3",
"Load Class Type 4",
"Location Category",
"Lowest Airspace Height",
"Lowest Airspace Z-value",
"Magnetic Variation",
"Maintenance Status",
"Maritime Area Category",
"Maritime Boundary Limit",
"Material Composition Category",
"Material Composition Secondary",
"Material Composition Underlying",
"Maximum Authorized Altitude",
"Maximum Demonstrated Usage",
"Maximum Vertical Clearance",
"Maximum height of obstacles in a Hull Integrity Test Site",
"Median Category",
"Median Width with greater than 1 meter resolution",
"Military Bridge Information",
"Military Gap Width",
"Mine Actuation Classification",
"Mine Actuation Controlled Cableless Classification",
"Mine Actuation Controlled Classification",
"Mine Actuation Independent Classification",
"Mine Actuation Independent Contact Classification",
"Mine Actuation Independent Influence Acoustic Classification",
"Mine Actuation Independent Influence Classification",
"Mine Actuation Independent Influence Magnetic Classification",
"Mine Actuation Independent Other Classification",
"Mine Identity Classification",
"Mine Position Classification",
"Mine Position Ground Classification",
"Mine Position Moored Classification",
"Mine Position Other Classification",
"Mine Special Information Classification",
"Mine Special Information Special Devices Anti-Hunting Classification",
"Mine Special Information Special Devices Anti-Recovery Classification",
"Mine Special Information Special Devices Anti-Sweep Wire Classification",
"Mine Special Information Special Devices Classification",
"Mine Special Information Special Mine Types Classification",
"Mine Special Information Usefulness Classification",
"Mine Status Classification",
"Mine Track Number",
"Minimum Enroute Altitude",
"Minimum Safe Altitude Sector",
"Minimum Traveled Way Width",
"Mining Category",
"Missile Site Type",
"Morse Code Attribute",
"Movement Surface Width",
"Multiple Classification Authority Sources",
"Multiple Light Ranges",
"Name",
"Name 3",
"Name 4",
"Name Identifier",
"Named Feature Identifier",
"Native Settlement Type",
"Navigation System Name",
"Navigation System Types",
"Navigation System Types (2)",
"Non-standard Classification Authority",
"Non-submarine Contact Reporting Agency Type",
"Number Of Fuel Fill Stands",
"Number of Parallel Lines",
"Number of Spans",
"Obstruction Light Quality",
"Offshore Platform Classification",
"Operating Range Category",
"Operating Range Category (2)",
"Operational Status",
"Operator ID",
"Ordinal Category",
"Ordnance Area Construction Activity",
"Ordnance Bunker Storage",
"Ordnance Facility Type",
"Originating Source Date",
"Originating Source Information",
"Originating Source Name",
"Over Water Obstruction",
"Overall Height of Bridge",
"Overhead Clearance Category",
"Overhead Clearance Category Code",
"Overhead Obstruction Category",
"Period of Light",
"Periodic Restriction Beginning",
"Periodic Restriction Category",
"Periodic Restriction Ending",
"Permanency",
"Physical Surface Characteristics",
"Pier-Wharf-Quay Face Type",
"Pier/Wharf /Quay Classification",
"Pilot Boarding Vehicle",
"Pipeline Type",
"Pipeline or Pipe Crossing Point Type",
"Point of Change Identifier",
"Populated Place Category",
"Populated Place Type",
"Port Index",
"Port Index Attribute",
"Port of Entry Classification",
"Position Evaluation",
"Power Line Category",
"Power Plant Category",
"Predominant Feature Depth With greater than 1 meter resolution",
"Predominant Feature Height With greater than 1 meter resolution",
"Predominant Height",
"Predominant Height (10 m Range)",
"Predominant Vegetation Height Range (1)",
"Predominant Vegetation Height Range (3)",
"Primary Official Name Category",
"Product Category",
"Radar Reflector Attribute",
"Radio Class Code",
"Radius of Sharp Curve",
"Rail Siding/Spur Attribute",
"Railroad Access Category",
"Railroad Categories",
"Railroad Gauge Category",
"Railroad Power Source",
"Range Significance",
"Rate of Current (1) (IHO)",
"Rate of Current (10) (IHO)",
"Rate of Current (11) (IHO)",
"Rate of Current (2) (IHO)",
"Rate of Current (3) (IHO)",
"Rate of Current (4) (IHO)",
"Rate of Current (5) (IHO)",
"Rate of Current (6) (IHO)",
"Rate of Current (7) (IHO)",
"Rate of Current (8) (IHO)",
"Rate of Current (9) (IHO)",
"Rate of Current (IHO)",
"Reference Point Determination Method",
"Refueling Units Type",
"Releasability",
"Reliability of Bridge",
"Religious Denomination",
"Required Port Access",
"Reservoir Type",
"Restrctions on Foreign Government Access",
"Restriction Declassification",
"Restriction Declassification Exemptions",
"Restrictions on Dissemination Control IC",
"Restrictions on Dissemination Control Non-IC",
"Restrictions on Releasibility",
"Road Interchange Type",
"Road Separation Category",
"Road/Runway Surface Type",
"Rock Strata Formation",
"Route Intended Use",
"Route Number",
"Runway Centerline Lights",
"Runway Flood Lights",
"Runway High End Approach Lights",
"Runway High End Identifier Lights",
"Runway High End PAPI Lights",
"Runway High End Threshold Lights",
"Runway High End VASI Lights",
"Runway Identifier",
"Runway Low End Approach Lights",
"Runway Low End Identifier Lights",
"Runway Low End PAPI Lights",
"Runway Low End Threshold Lights",
"Runway Low End VASI Lights",
"Runway Strip Lights",
"Runway True Heading- High",
"Runway True heading - Low",
"Safe Horizontal Clearance",
"Sand Dune Orientation",
"Sea Area Classification",
"Sea Floor Feature Category",
"Seasonal Tent Location",
"Second Name",
"Second magnetic variation value",
"Secondary Material Characteristics",
"Security Classification",
"Security Classification",
"Security Classification System Identifier",
"Security Codeword Control",
"Service Branch",
"Severity of Hazard",
"Shape of Beacon",
"Shelter Belt Condition",
"Ship's Draft",
"Shoreline Category",
"Shoreline Type Category",
"Shoreline Type Left",
"Shoreline Type Right",
"Slope Gradient Left (1)",
"Slope Gradient Right (1)",
"Slope Polygon Range",
"Snow/Ice Category",
"Soil Depth With Greater Precision",
"Soil Trafficability Group (Derived from STP)",
"Soil Types",
"Soil Wetness Condition",
"Sound Signal Type",
"Sounding Category",
"Sounding Classification",
"Sounding Horizontal Accuracy Code",
"Sounding Source ID",
"Sounding Velocity",
"Sounding Vertical Accuracy Code",
"Source Type Code",
"Source of report",
"Special Purpose Vehicle Remarks",
"Special Purpose Vehicle Type",
"Special Use Airspace Altitude Limits",
"Speed Limit (MPH)",
"Spring/Well Characteristic Category",
"Station Type Category (Maritime)",
"Stem Diameter Size Range (1)",
"Stem Diameter Size Range (2)",
"Stem Diameter Size With greater than 1 meter resolution",
"Structure Shape Category",
"Structure Shape of Roof",
"Style of Text",
"Summer Tree Cover Density Code",
"Surface Condition Attribute",
"Surface Material Category",
"Surface Roughness Description",
"Surficial Material Depth Category",
"Survey Category",
"Survey Date - End",
"Tailored Surface Roughness Description",
"Taxiway Lighting Availability.",
"Taxiway Remarks",
"Taxiway Type",
"Text Attribute",
"Tidal/Non-Tidal Category",
"Time Attribute",
"Tonnage",
"Top Mark Characteristic",
"Total Usable Width",
"Tower Type Category",
"Track/Lane Number",
"Traffic Flow",
"Traffic Scheme Part",
"Training/Operations Area Boundary Type",
"Transmission Line Suspension",
"Transportation Use Category",
"Traversability",
"Tree Spacing Range (1)",
"Tree Spacing Range (2)",
"Tree Spacing Range (3)",
"Tree Spacing With greater than 1 meter resolution",
"Tree Type Category",
"True Feature Heading (High End)",
"True Feature Heading (Low End)",
"Type of Font",
"Underbridge Clearance Category",
"Underbridge Clearance With Greater Precision",
"Underlying Material Characteristics",
"Unique Feature ID (MC&G)",
"Units",
"Update/Review Source Date",
"Update/Review Source Information",
"Update/Review Source Name",
"Urban Street Pattern",
"Usage",
"Useable Length",
"Useable Width",
"Value",
"Variation Anomaly String",
"Variation Anomaly Value",
"Vegetation Characteristics",
"Vegetation Roughness Category",
"Vertical (Sounding) Datum Category",
"Vertical Accuracy Category",
"Vertical Clearance Datum",
"Vertical Clearance Remarks",
"Vertical Clearance, Safe With greater than 1 meter resolution",
"Vertical Datum Record",
"Vertical Obstruction Identifier",
"Vertical Reference Category",
"Visual Aids Category",
"Void Collection Attribute",
"Void Collection Type",
"Volcanic Geologic Type",
"Volume",
"Wall Type Identifier",
"Water Depth Average",
"Water Depth Mean (Seasonal High Water)",
"Water Depth Mean (Seasonal Low Water)",
"Water Quality Attribute",
"Water Velocity Average 1",
"Water Velocity Mean (Seasonal High Water)",
"Water Velocity Mean (Seasonal Low Water)",
"Waypoint Description Code",
"Weather Type Category",
"Well Feature Type",
"Well/Spring Feature Type",
"Width",
"Width Top",
"Width of Crest",
"Width of Second Traveled Way",
"Width with greater than 1 meter resolution",
"Winter Tree Cover Density Code",
"Work in Progress Category",
"Wreck Type",
"Z-Coordinate Type"
};

char *D4_attr_types[] = {
"String",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Float",
"Short Integer",
"Short Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Long Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Long Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Float",
"String",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Long Integer",
"Long Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Long Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Date",
"Short Integer",
"Long Integer",
"Long Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Long Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"String",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Long Integer",
"Short Integer",
"Long Integer",
"Short Integer",
"Long Integer",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"String",
"Long Integer",
"String",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"Float",
"String",
"Short Integer",
"String",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"String",
"Long Integer",
"String",
"Short Integer",
"Short Integer",
"Long Integer",
"Short Integer",
"String",
"Long Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"Long Integer",
"String",
"Short Integer",
"Short Integer",
"Float",
"String",
"Short Integer",
"Long Integer",
"String",
"Long Integer",
"Short Integer",
"String",
"String",
"Long Integer",
"Short Integer",
"String",
"Long Integer",
"Long Integer",
"Long Integer",
"String",
"Short Integer",
"String",
"String",
"String",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"Long Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Float",
"Float",
"Short Integer",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Float",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Date",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Long Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"String",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Long Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"String",
"Short Integer",
"Date",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Float",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer"
};

char *D4_attr_defns[] = {
"No Definition Available",
"No Definition Available",
"No Definition Available",
"The direction the aircraft must be moving in order to utilize this feature.",
"Defines the ATS Route Structure of which this route is effective.",
"The particular use of the designated airspace.",
"The absolute horizontal accuracy of the data's coordinates",
"The code that indicates the method by which the absolute circular error was derived.",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"The difference between the recorded horizontal coordinates of features and their true positions expressed as a circular error at 90% probability.",
"The absolute vertical accuracy of the data's coordinates",
"The code that indicates the method by which the absolute linear error was derived.",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"The difference between the recorded elevations of features and their true elevations at a specific point referenced to the same vertical datum at 90% probability.",
"Accuracy of geographic position.",
"Accuracy of the geographic position of the left bank of a watercourse.",
"Accuracy of the geographic position of the right bank of a watercourse.",
"Indicates the difference between the recorded heights above ground level of features and their true heights at 90% probability.",
"This field is used to describe the organization or agency with which the originating author/creator of the data is associated.",
"Indicates whether a feature is marked or unmarked by an aid to navigation.",
"Brief description of the terrain and drainage features located at an air facility.",
"Unique airfield type.",
"The highest point of an airport's usable runways measured in meters from mean sea level.",
"Unique identification of the airport where: 1-2 Country Code, 3-6 WAC, 7-12 Installation Number.",
"If applicable, the type of strip this aircraft facility is.",
"A set of characters which enables an individual airspace to be uniquely identified.",
"A description of the operating times of an airspace.",
"Designated airspace within which some or all aircraft may be subject to air traffic control.",
"Airspace wherein activities must be confined because of their nature and/or wherein limitations may be imposed upon aircraft operations.",
"A specified route designed for channeling the flow of traffic as necessary for the provision of air traffic services.",
"The angular distance measured from true north (0 deg) clockwise to the major axis of the feature. If the feature is square, the axis 0 through 89 deg shall be recorded. If the feature is circular, 360 deg shall be recorded.",
"If DIR = 3 then ARR is the angular distance measured from true north (0 deg) clockwise to the reflective side of the feature.",
"The Primary Target Category Code assigned to this Target.",
"The apron /hardstand access maximum width considering taxiway width plus clearance from such hazards as trees, revetments, buildings, etc.",
"Type of aqueduct.",
"No Definition Available",
"Device used to stop an uncontrolled aircraft at the end of a runway.",
"The distance of the arresting system from the closest threshold of the runway /landing area referenced by Runway Cross Reference Code (RWC).",
"Classification of mapping artifact represented by ZD003 Articact Location.",
"Defines whether the artifact represented by ZD003 Articact Location is positional or attributional or both.",
"The annual water content of the associated hydrographic feature as defined by the Inland Shoreline.",
"Facilities available at or in the near vicinity.",
"Unique identifier for tracking Bathy Archive Data (BAD)",
"Slope of the left bank (facing downstream) above water level.",
"Slope of the right bank (facing downstream) above water level.",
"Height of the left bank above the water level (facing downstream) to the average water level.",
"Predominant height range (1) of the left bank (facing downstream) in meters, measured from mean water level to the first break in slope above the mean water level.",
"The predominant height range of the left bank (facing downstream) with greater precision, measured from mean water level to the top of the first accessible break in slope above the mean water level.",
"Height of the right bank above the water level (facing downstream) to the average water level.",
"Predominant height range (1) of the right bank (facing downstream) in meters, measured from mean water level to the first break in slope above the mean water level.",
"The predominant height range of the right bank (facing downstream) with greater precision, measured from mean water level to the top of the first accessible break in slope above the mean water level.",
"Density of vegetation found on the downstream left bank.",
"Density of vegetation found on the downstream right bank.",
"Unique number associated with a feature which is used to identify the feature in other national or intelligence data bases.",
"Indicates the relative portion of a beach.",
"Type of beacon.",
"True course of a vessel when proceeding from seaward along a track or course.",
"True course of a vessel in 0.1 degree increments, when proceeding along a track or route, followed by its reciprocal bearing (i.e. 053.1-233.1).",
"The bearing of an object from an observer (on any point along the line) towards the object or feature, expressed in degrees and tenths (e.g. 3.0 degrees).",
"The designated number or letter used to identify this feature.",
"Predominant material composition of the bottom of a body of water.",
"Nature of the feature or condition serving as the origin of a boundary.",
"Indicates whether a boundary is demarcated.",
"Indicates whether or not a boundary is in dispute.",
"The availability of boundary lights at the aircraft facility.",
"Classification of Boundaries or Lines of Separation By Type.  See also Boundary Representation Policy Code (RPC).",
"Reflects official State Dept/Foreign Office interpretation of a boundary status to be reflected in the portrayal of that boundary.  See also Boundary Lines Of Separation Code (LSP).",
"Identifies the status of a boundary.",
"The type of structure or mechanism by which a portion of a bridge is moved to allow passage of a vessel.",
"A unique number relating information to bridge and bridge spans.",
"Identifies type of moveable span.",
"Identifies bridge spans that move in some manner allowing passage underneath the span.",
"Structural design characteristics.",
"Broadcast frequency of a communications device.",
"The frequency on which a station broadcasts (second occurrence).",
"Density of brush or undergrowth.",
"Type or purpose of the building.",
"The number of floors in a building.",
"The indication of the relative density of the Built-Up Area.",
"Type of buoy.",
"The ease or ability to circumvent a destroyed section of bridge, tunnel or pass within a 2 kilometer distance on each side of the feature.  Bypass condition will not consider other bridges in bypass determination.",
"Classifies the function of a cable.",
"The type of report or activity.",
"The calendar date as specified by ISO 8601.",
"The capacity of a feature.  Units will be qualified using a structured text approach, e.g. 100 (cars)[per hour] where the unit is in parentheses ( ) and a qualifier is in brackets[ ].",
"Indicates knowledge of the feature's limits or information.",
"Indicates knowledge of the feature's existence.",
"The channel representing the frequency assigned by the controlling authority.",
"Any identifier composed of the class, number and color(s) of flashes or occultations, of a light or lights at one geographic position [e.g. Q(6)+L F1, VQ G, L F1 (3+2)WR].",
"Indicates the relative difficulty in traversing the rapids.  Six Classes based on the International Scale of River Difficulty.",
"The code that represents the type of classification authority used to derive a classification for data.",
"Color of the sea floor, light, buoy, structure, or other feature.",
"Textual description of unique aspects of buoy or beacon coloring.",
"The color breakdown of pattern of buoys, beacons, lights, other aids to navigation, and other features of interest to a mariner.",
"Specifies color to be used when displaying ZD040, and ZD045.",
"An open text field for additional information.",
"This field is used when a data set includes commercial products or any other copyrighted data. Example: Copyright 2000 Space Imaging",
"Distinguishes between communication lines that are in the open by themselves (isolated) and those that are in the midst of other features (not isolated).",
"Identifies if the extraction is 100% complete IAW the specification identified in the SPEC_ID attribute.",
"The primary functional use of the area covered by an AL045 Complex Outline feature.  (See use and attribute values below.)",
"A conspicuous object is easily identifiable and plainly visible under varying conditions of light from harbours, approach channels, or offshore because of its size, shape, or height.",
"The type of a constriction or expansion.",
"Type of control point.",
"A four character country identification code as designated in Federal Information Processing Standard (FIPS)  Pub 10-4, Countries, Dependencies, Areas of Special Sovereignty, and their Principal Administrative Divisions, identifying the country and the principal administrative division in which the feature is located.  The last two characters will be blank filled if principal administrative division information is not required.",
"Condition where an artificial or improved natural drainage way is completely covered over and connects open drainage ways at each end.",
"Length of covered drainage way.",
"Indicates the mobility of a crane type.  (See CRA.)",
"The longest distance between the supports for a gantry/bridge crane (CRA002).",
"Type of crane.",
"Defines the method of traffic control for a road crossing.",
"The measure of the concentration of buildings and other cultural features within the delineation of this feature.",
"Divides culverts into various categories, of which the two main ones are regular culverts and box culverts, either of which can be earth back-filled.",
"Total cumulative length of track contained within confines of the feature, exclusive of the branch or main trunk lines running into and/or out of the feature.",
"Month of appearance of the current.",
"Month of disappearance of the current, if different from HS1.",
"Maximum speed of current.",
"Minimum speed of current.",
"The horizontal movement of a body of water.",
"Identifies the number of sides that are used as a cut or an embankment.",
"Type of face of a dam.",
"No Definition Available",
"Date or dates the Hull Integrity Test Site was surveyed formatted as YYYYMMDD.  If there are multiple dates, the dates will be separated by semicolons.",
"The attribute definition is classified.",
"Concentration of kelp weed in the sea, measured in percent coverage within area of feature.",
"Roof cover measured by percent within area of feature.",
"Canopy cover measured by percent within area of feature during the summer season.",
"Actual percent (%) of ground covered by undergrowth.",
"Indicates the number of features of this type within an area.",
"Density of structures within a square kilometer (1000m x 1000m).",
"Distance measured from the highest point at surface level to the lowest point of the feature below the surface. Recorded values are positive numbers.",
"A specified value assigned to a particular depth curve or contour.",
"The maximum value of a depth curve polygon.",
"The minimum value of a depth curve polygon.",
"Name/Type of device used to record depths.",
"Predominant water depth within delineation of feature, determined in meters at the greatest depth along a cross section of the feature (First Range).",
"Ranges of average depth (meters) of a zone of saturation except where bounded by an impermeable body, in which no water table exists.",
"Categorized maximum height or depth of an obstacle feature, in meters, with delineated segment of area.",
"Textual description of aids to navigation marking a feature, e.g.. Marked by buoys.",
"Description of the feature(s) which form a Leading Line or Clearing Line.",
"Direction of current flow 1 hour after tide reference level.",
"Direction of current flow 2 hours before tide reference level.",
"Direction of current flow 1 hour before tide reference level.",
"Direction of current flow 2 hours after tide reference level.",
"Direction of current flow 3 hours after tide reference level.",
"Direction of current flow 4 hours after tide reference level.",
"Direction of current flow 5 hours after tide reference level.",
"Direction of current flow 6 hours after tide reference level.",
"Direction of current flow 5 hours before tide reference level.",
"Direction of current flow 4 hours before tide reference level.",
"Direction of current flow 3 hours before tide reference level.",
"Direction of current flow at tide reference level.",
"Bearing of movement or direction of the flow.",
"Direction of traffic, first occurrence.",
"Direction of traffic, second occurrence.",
"Direction of traffic, third occurrence.",
"Direction of traffic, fourth occurrence.",
"The side or sides of a feature which produces the greatest reflectivity potential.",
"This field is used to identify the distribution of commercial or other restricted data.",
"Indicates if draft correction has been applied.",
"Distinguishes between two drop gate types.",
"Identifies the type of educational building.",
"Depth of water obtained by electronic depth measuring instruments.",
"Indicates whether the ZVL value is accurately known.",
"The elevation of a light.",
"The state or condition of the feature.",
"Indicated whether the value of a sounding is shallower than, deeper than, or within the range depth of the surrounding depth area.",
"Runway High Identifier.",
"Runway Low Identifier.",
"The particular specification that was used for the extraction process.",
"The date on which the feature was extracted followed by an increment specific to each source.",
"Denotes the type of fabrication industry as light or heavy.  Light fabrication industries are characterized by light steel or woodframe buildings and lack heavy equipment.  Heavy fabrication industries are characterized by large heavy steel frame buildings and may utilize large cranes for heavy lifting.",
"Indicates the priority status of the airfield.",
"Type of field pattern or use.",
"Configuration of feature.",
"A code indicating the construction materials comprising the feature.",
"Calendar date/time when feature was created in the GIFD.",
"The angular distance measured from true north (0 deg) clockwise to the predominant linear pattern of the elements within the feature.",
"No Definition Available",
"The scale to which a feature or feature set was collected.",
"Type of fence.",
"Length of crossing between shore points.",
"Indicates the maneuverability of a ferry vessel.",
"Final code taking accuracy attributes into account.",
"Type of firing range.",
"First magnetic variation value of the disturbance area.",
"A minimum surface of constant atmospheric pressure which is related to a specific pressure datum, (1,013.2 hectopascal (hPa) or 29.92 inches) and is separated from the consecutive flight levels by a pressure interval corresponding to 500 feet (152.4 m.).",
"A maximum surface of constant atmospheric pressure which is related to a specific pressure datum, (1,013.2 hectopascal (hPa) or 29.92 inches) and is separated from the consecutive flight levels by a pressure interval corresponding to 500 feet (152.4 m.).",
"Indication of the presence of floodlighting to illuminate the structure of a light.",
"Indicates whether or not a fog detector light is attached to, or connected with the feature.",
"No Definition Available",
"The capacity of each fuel tank or container containing fuel.",
"The primary method of dispensing fuel at the air facility.",
"Method of aircraft fuel storage for like fuel storage containers.",
"Predominant horizontal gap width range (1) in meters, measured between the top of the first accessible break in slope above mean water level on each bank.",
"The predominant horizontal gap width range with greater precision, measured between the top of the first accessible break in slope above mean water level on each bank.",
"Tabulation of various types of nautical gates.",
"The classification of the type of barrier or gate.",
"The width of a single pair of rails, measured along the shortest distance from inside rail to inside rail.",
"Depth of the feature below average surface level as determined by a corresponding digital elevation matrix.  If not obtainable, the average depth will be used.",
"Height of the feature above average surface level as determined by a corresponding digital elevation matrix.",
"No Definition Available",
"Classification of recognized geopolitical entity types.",
"No Definition Available",
"Percentage of slope.  (i.e. The change in height divided by the horizontal distance over which the change takes place, times one hundred ((h2-h1)/d)*100.)",
"The horizontal distance between the two points of a feature which are the most distant from each other.",
"Range indicating the slope of ground within delineated area of feature usually manually derived, reported in percent.",
"Presence of support wires.",
"The measurement of the vertical extent of the hangar door.",
"The measurement of the horizontal extent of the hangar door.",
"Hangar design code.",
"Tabulates the kind of operation/service.",
"No Definition Available",
"Vertical distance from sea bottom to lowest portion of feature.",
"Distance measured from the lowest point of the base at ground or water level (downhill side/downstream side) to the tallest point of the feature.",
"The height differential between the HGT of the feature and the HGT of the tallest feature within a 300 m radius.",
"Vertical distance above ground or water level on the upstream side of the dam.",
"Height range with greater precision (in meters).",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"No Definition Available",
"Height (AGL - above ground level) above surface level to the highest portion of the feature (used only for Air Information).",
"Measurement to specify highest vertical limits.",
"Elevation above a given datum to the highest portion of the feature.",
"Classification of access roads by the type of road they access.",
"The horizontal accuracy of the geographic position.",
"The distance available to pass a load that extends laterally beyond the wheels of a vehicle.",
"The distance available to pass a load that extends laterally beyond the wheels of a vehicle.",
"Horizontal geodetic datum.   (This attribute should only be used for a feature whose  datum is different from that of the geo data set (see Part 3-6.2).)",
"Type of house of worship used.",
"General description of changes in bottom topography in a Hull Integrity Test Site.",
"Description of any special features of a Hull Integrity Test Site (canyon, pinnacle, flat, etc.)",
"Bottom Characteristics of specific interest to a Hull Integrity Test Site.",
"The orientation of the maximum slope of a Hull Integrity Test Site measured in whole degrees in the downslope direction.",
"The gradient of the maximum slope of a Hull Integrity Test Site in whole degrees.",
"Hull Integrity Test Site test zone.",
"The depth of the feature below water, measured from the top or surface of the feature, referenced to a specified vertical datum.  Recorded values are positive numbers.",
"Information about the accuracy or availability of depth or uncovering height of a feature.",
"The height of the feature, which tidal waters cover and uncover, referenced to a specified vertical datum.",
"The type of light used for marine navigation.",
"Origin of the feature.",
"Identifies the annual water content of the feature.",
"Form or configuration of the hydrological feature.",
"Type of line shown.",
"Conformity of a navigational aid to the IALA system of navigational aids.",
"ICAO designated airspace classification.",
"International Civil Aviation Organization location identifier as designated in ICAO document 7910.",
"Status of International Maritime Organization adoption.    Replaced Approved with Adopted",
"A unique number relating specific interior map/chart features to border information.",
"An indicator that a feature in an inland water body is an obstruction to vessel movement.",
"Tabulates the various types of installation buoys.",
"Maximum voltage available on the line, as reported in kilovolts.",
"Label applied to the feature.",
"Indicates whether a feature  is used for rapid and positive orientation when size, shape, or location make it prominent in relation to surroundings. Easily recognized from line of sight - ground or air.",
"The length of a segment having a gradient > =7 percent for a Road (AP030) or > =3 percent for a Railroad Track (AN010).",
"Length of range, in nautical miles, established by aids to navigation on the shore.",
"No Definition Available",
"A measurement of the longer of two linear axes in meters. For a square feature, measure either axis. For a round feature, measure the diameter. For a bridge, the length is the distance between the bridge abutments.",
"The sequence, grouping, and distinctive character of a light.",
"Type of lighting provided or type of lighting system used.",
"The luminous range when the meteorological range is 10 sea miles.",
"Angular limits of light visibility. Limits of sectors and arcs of visibility are arranged clockwise and shall be given from seaward toward the light.",
"Initial angular limit of light visibility.  Limits of sectors and arcs of visibility are arranged clockwise and shall be given from seaward toward the light.",
"Terminal angular limit of light visibility. Limits of sectors and arcs of visibility are arranged clockwise and shall be given from seaward toward the light.",
"The availability of a lighted wind indicator at this aircraft facility.",
"The type and/or number of features associated with a leading or clearing line.",
"Military Load Classification (weight bearing capacity) Type 1.  (See STANAGs 2021 and 2253 for method of calculation)",
"Military Load Classification (weight bearing capacity) Type 2.  (See STANAGs 2021 and 2253 for method of calculation)",
"Military Load Classification (weight bearing capacity) Type 3.  (See STANAGs 2021 and 2253 for method of calculation)",
"Military Load Classification (weight bearing capacity) Type 4.  (See STANAGs 2021 and 2253 for method of calculation)",
"Status of  feature relative to surrounding area or water.",
"Height (AGL - above ground level) above surface level to the lowest portion of the feature (used only for Air Information).",
"Measurement to specify lowest vertical limits.",
"Horizontal angle between true north and magnetic north measured East (positive value) or West (negative value) according to whether magnetic north lies east or west of true north.",
"Indicates whether the feature is maintained.",
"Area in which certain activities or factors of significance to navigation or operations apply.",
"A line where on either side certain activities or factors of significance to navigation or operations apply.",
"Characteristics of primary material composition of feature.",
"Secondary material composition of feature.",
"Underlying material composition of feature.",
"The highest altitude in an airway or route at which adequate reception of navigation aid signals is assured.",
"The heaviest observed aircraft utilizing the runway.",
"The greatest distance between the traveled way and any obstruction vertically above it.",
"Maximum height above the sea floor of obstacles in a Hull Integrity Test Site.",
"Presence of a divider between multiple lanes/rails.",
"The measured distance at map scale between connecting, adjacent and two-way road centerlines having divided roadbeds.",
"A free text field used to indicate if the bridge is subject to preplanned military interdiction.",
"The minimum horizontal bridging distance between banks (in decimetres).",
"Defines subsidiary mine actuation classifications and tabulates the Mine Actuation types.",
"Tabulates the types of cableless controlled methods and classification.",
"Defines subsidiary mine actuation classification controlled methods and classification.",
"Defines subsidiary mine actuation independent classifications.",
"Tabulates attributes of independent contact mine actuation.",
"Tabulates mine actuation independent influence acoustic types.",
"Defines subsidiary mine actuation independent influence classifications and tabulates mine actuation independent influence types.",
"Tabulates mine actuation independent influence magnetic types.",
"Tabulates mine actuation, independent of other  types.",
"Tabulates mine identity attributes.",
"Defines subsidiary mine position classifications and tabulates mine position types.",
"Tabulates ground mine charge size.",
"Tabulates mine moored position types.",
"Tabulates other mine position types.",
"Defines subsidiary mine special information classifications.",
"Tabulates mine special information special devices anti-hunting types.",
"Tabulates mine special information special devices anti-recovery types.",
"Tabulates mine special information special devices anti-sweep wire types.",
"Tabulates mine special information special devices types and subsidiary mine special information special devices classifications.",
"Tabulates mine special information special mine types.",
"Tabulates mine special information usefulness types.",
"Tabulates types of mine status.",
"Mine track Number.   Expressed by a track number of 4 digits.",
"The lowest altitude published by the host country between radio fixes which assures acceptable navigational signal coverage and meets obstacle clearing clearance requirements.",
"The minimum safe altitude, in feet, above MSL which provides a 1000 foot obstacle clearance within the airspace.",
"Minimum width of the traveled way, excluding hard pavements and shoulders (in decimetres).",
"No Definition Available",
"Class of missile at site.",
"The ASCII (ISO 646) letter that is being emitted by either the Navigation Signal Type (NST), Sound Signal Type (SST), Light Characteristic (CHA), or Electronic Beacon Type (BET).",
"The measurement of the feature's axis perpendicular to normal aircraft movement.",
"This field is used to describe the list of multiple individual sources used to derive a classification for data.",
"A set of two numbers for light ranges of visibility (at a light) expressed in nautical miles; the numbers are separated by a slash (/) if only two visibilities exist, or by a dash (-) separating the greatest and least visibilities if three or more exist.",
"Any identifier or code.",
"Name of the political entity on one side (relative to NM4) of a boundary line.",
"Name of the political entity on the other side (relative to NM3) of a boundary line.",
"Textual identifier of a unique name associated with a feature within an external names database.  (See also NFI)",
"Textual identifier of a unique feature within an external names database.  (See also NFN)",
"The distribution of native dwellings within the delineated area of the feature.",
"No Definition Available",
"Type of equipment or system used in electronic navigation (primary system).",
"Type of equipment or system used in electronic navigation (secondary system).",
"This field is used to describe non-standard classification authority used to derive a classification for data.",
"Classification of Non-submarine contact reporting source based on US Wreck List and NATO STANAG 3715.  Replicates attribute RAG in the Wreck List.",
"The number of fill stands used for the fuel to transfer fuel from storage tanks into trucks.",
"Total number of parallel lines within the feature.",
"Number of spans in a bridge or aqueduct.",
"Indicates whether single or multiple obstruction lights are present.",
"Tabulates types of offshore platforms.",
"The range of the NAVAID beyond which the capture of the signal is not completely assured.",
"The secondary range of the NAVAID beyond which the capture of the signal is not completely assured.",
"Indicates whether or not the feature is in operation.",
"ID of the operator that loaded the data or created the Extraction Record feature.",
"Indicator of relative importance of a feature",
"Construction activity in the ordnance storage area.",
"Indicates whether or not ordnance is stored in a bunker.",
"Ordnance facility brief description.",
"The date/time of the original source that was used for the extraction/ingest/creation of a feature.",
"Details about the originating source of the data.",
"The name of the ORIGINAL source of the data.",
"Indicates the presence of an obstruction over an area of navigable water.",
"Vertical distance measured from the lowest point at ground or water level to the highest portion of bridge (including superstructure).",
"The least distance between the traveled way and any obstruction vertically above it. (Ref. STANAG 2253)",
"The coded distance between the traveled way and any obstruction vertically above it. (Ref. STANAG 2253).",
"Type of overhead obstruction.",
"The time occupied by an entire cycle of intervals of light and eclipse.",
"Beginning month for restrictions due to climate or other limitations.",
"Restriction due to climate or other limitations.",
"Ending month for restrictions due to climate or other limitations.",
"Indicates whether an object is temporary or permanent.  See EXS 11 and EXS 18.",
"Principal characteristic(s) of the surface.",
"Describes whether a pier or quay is of solid, closed construction or of open pile construction.",
"Classification of decked berthing structure, based on configuration and structure.",
"The method by which pilots are transferred to and from ships using pilot services.",
"Identifies function of pipeline.",
"Type of crossing site.",
"Identifies category of feature associated with a point of change.",
"The number of people within a feature (e.g., administrative and built-up areas).",
"The type of populated place.",
"Unique maritime port identifier.",
"Indicates the presence of a port, as identified in the World Port Index.",
"Designates whether a facility is a port of entry for customs and immigration purposes.",
"Evaluation of the position accuracy of a Non-submarine contact.  Reference STANAG 3715.",
"Identifies a alpha alpha code that relates to the construction material and height of the feature for portrayal.",
"Energy source used to generate power.",
"Predominant depth within the delineation of feature.",
"Predominant height within delineation of feature.",
"Height of 51% or more of the feature. If not obtainable, then the average height of the feature will be used.",
"Predominant height range of a specified urban area (reported in 10 meter ranges).",
"Range of predominant height (in meters) of vegetation within delineated area of feature (First Range).",
"A range of predominant height (in meters) of vegetation within delineated area of feature (Third Range).",
"The primary official name as designated by the operating agency, FAA, or by official publications of the country in which the facility is located.",
"Principal material involved or product resulting from activity at site.",
"No Definition Available",
"No Definition Available",
"Radius of curvature of sharp curves, expressed in meters.",
"Type of connecting track.",
"Classification of access roads by the type of railroad they access.",
"The type of railroad system used to support various transportation uses.",
"The type of gauge used.",
"Source of electrical power for railroad.",
"Indicates relative location of a beacon or light in a range.",
"Rate of current flow 1 hour after tide reference level.",
"Rate of current flow 2 hours before tide reference level.",
"Rate of current flow 1 hour before tide reference level.",
"Rate of current flow 2 hours after tide reference level.",
"Rate of current flow 3 hours after tide reference level.",
"Rate of current flow 4 hours after tide reference level.",
"Rate of current flow 5 hours after tide reference level.",
"Rate of current flow 6 hours after tide reference level.",
"Rate of current flow 5 hours before tide reference level.",
"Rate of current flow 4 hours before tide reference level.",
"Rate of current flow 3 hours before tide reference level.",
"Rate of current flow at tide reference level.",
"The method used to derive the reference point (RP) of an airport using operational runways.",
"The methods /units available for dispensing the designated fuel.",
"Releasability statement with regard to the feature.",
"Reliability of bridge characteristics and military load classification based upon data source.",
"Name of religious order at site.",
"An indicator that a water feature is used for access to a required port, or that the feature is in a water body used for access to a required port.",
"Indicates the method of containing the water in a reservoir.",
"Indicates foreign government information is included in U.S. controlled data.",
"The event upon which the declassification of the data occurs. A value of MR (Manual Review) signals that this data must be reviewed at such time that declassification is desired.",
"The code that indicates the reason that an object must remain classified beyond the 10 or 25 years automatic declassification.",
"This field is used when applicable to describe intelligence community dissemination and control of the data set or product.  This will need to reflect dissemination and control restrictions of the ORIGINATING_SOURCE.",
"This field is used when applicable to describe non-intelligence community dissemination and control of the data set or product. This will need to reflect dissemination and control restrictions of the ORIGINATING_SOURCE. This element may contain multiple dissemination control markings.",
"Denotes the countries or organizations that the data is releasable to. (This field is required when the source denotes country or organization releasability restrictions.)",
"The unique interchange design.",
"Indicates whether a roadway is or is not separated into separate roadways.",
"The physical surface composition of a road or runway.",
"The structure of a rock formation.",
"Intended use of the route.",
"Official route number (I-95, M-2, A-1, etc.) assigned to the feature.",
"The availability of runway centerline lights.",
"The availability of runway flood lights.",
"The availability of approach lights on the high end of the runway.",
"The availability of identifier lights at the high end of the runway.",
"The availability of Precision Approach Path Indicator (PAPI) lights at the high end of the runway.",
"The availability of threshold lights at the high end of the runway.",
"The availability of Visual Approach Slope Indicator (VASI) lights of the high end of the runway",
"The  degree identification of the runway in a two-digit identifier ranging from 01-36, derived from the runway heading, rounded to the nearest ten degrees and divided by ten.  For parallel runways a third character is added to differentiate between left (L), right (R), center (C), or STOL (S) runway positions.",
"The availability of approach lights on the low end of the runway.",
"The availability of identifier lights at the low end of the runway.",
"The availability of Precision Approach Path Indicator (PAPI) lights at the low end of the runway.",
"The availability of Threshold lights at the low end of the runway.",
"The availability of Visual Approach Slope Indicator (VASI) lights at the low end of the runway.",
"The availability of Runway Strip lights.",
"True heading of the runway which uses this feature.",
" True heading of the runway which uses this feature.",
"Minimum safe horizontal distance between adjacent structures on either side of a navigable channel.",
"Characteristic alignment of the dune as caused by the prevailing winds.",
"A property of large bodies of water characterized by tidal conditions, swells, or high heavy wave action.  The condition can apply to both fresh and salt water.",
"Type of object or area on the sea floor or below the water surface.",
"The seasonal habitat location of nomadic people.",
"Fundamentally a touristic name for a feature which exists in addition to a geographic name.",
"Second magnetic variation value of the disturbance area.",
"Characteristics of secondary material composition of feature.",
"Defines the highest level of security associated with a feature.",
"This field is used to describe the highest classification of the data. There MUST be one and only one classification for each feature or dataset.",
"The identifier that represents a particular SECURITY-CLASSIFICATION-SYSTEM.",
"This field is used to describe the SCI control system or systems applicable to the data set.",
"Identifies a specific military organization.",
"Severity of hazard.",
"Describes the characteristic geometric form of the beacon.",
"Indicates whether a linear stand of trees functions as a shelter belt, protecting roadways, railroads, cropland, construction, etc., from the effects of adverse weather.",
"The  correction to the depth measurement measured from the hull-mounted transducer to the water surface.   The depth measurement is normally taken from the transducer to the ocean floor. The draft correction brings that measurement to the water surface.",
"Tabulates the topography and material types likely to be found on a shoreline.",
"The physical characteristic of the shoreline area.",
"The physical characteristics of the shoreline of the left bank of a watercourse.",
"The physical characteristics of the shoreline of the right bank of a watercourse.",
"Predominant slope range (1) on the left bank (facing downstream) in percent, measured from mean water level to the first accessible break in slope above the mean water level.",
"Predominant slope range (1) of the right bank (facing downstream) in percent, measured from mean water level to the first break in slope above the mean water level.",
"Range indicating the slope of ground within delineated area of feature, reported in percent.",
"Indicates the composition of the feature.",
"Ranges of detailed depth (meters) of soil or unconsolidated material over bedrock.",
"Soils described by the Unified Soil Classification System categorized by their wet weather trafficability characteristics.",
"Soils described by the Unified Soil Classification System (USCS)",
"General moisture content or condition of a soil.",
"Type of audible signal.",
"Condition of depth.",
"Security Classification of a sounding",
"A relative evaluation of the accuracy of a sounding position based on the Navigation System used.",
"The Bathymetric Document ID combined with the Sheet ID.",
"Indicates type of correction that has been added to, or subtracted from instrument reading to obtain correct depth.",
"The Depth Recorder Evaluation Code.",
"The source from which features are captured or upgraded.",
"The source of a reported non-submarine contact.  Reference STANAG 3715.",
"Remarks on the quantities and types of special purpose vehicles, including: 1) snow removers; 2) wreck removers, quantities and types of wreckers, cranes, hoists, crash dollies, etc.; or 3) crash removers, quantities and types of crash equipment and rescue vehicles.",
"Description of specific function of equipment available at site.",
"Description of the altitude limits of Special Use Airspaces.",
"The maximum speed legally permitted on a given stretch of road.",
"Type of available water.",
"Equipment or activity at site.",
"Estimated range (1) of the average stem diameter within area of feature, determined in centimetres at a distance of 1.4 meters above the ground.",
"Estimated range (2) of the average stem diameter within area of feature, determined in centimetres at a distance of 1.4 meters above the ground.",
"The average diameter of trees in a stand, measured at a height of 1.4 m above the ground.",
"Geometric form, appearance, or configuration of the feature.",
"Roof shape.",
"Text style used to display ZD040 and ZD045.",
"Coded value indicating percent of summer canopy closure within delineated area of feature.",
"Quality of the feature surface.",
"Surface material composition excluding internal structural material.",
"Describes the condition of the surface materials that may be used for mobility prediction, construction material, and landing sites.",
"Estimates general depth of soil or unconsolidated surface materials, expressed in 0.5 meter increments.",
"Tabulates the various qualifiers of the survey carried out for a feature.",
"The end date of the survey. Coded YYYYMMDD.",
"Describes a unique condition of the surface materials or surface geomorphology that may be used for mobility prediction, construction material, and landing sites, and is not covered under the standard SRD values.",
"Availability of taxiway lights.",
"Remarks concerning the taxiway.",
"The type of like taxiways at the air facility.",
"Narrative or other description.",
"Identifies whether a feature is affected by tidal water.",
"The time, expressed in hours of duration, for which an activity is permitted.",
"Tonnage of a sunken or stranded wreck, a hulk, or other vessel.  Reference STANAG 3715.",
"The characteristic shape secured at the top of a buoy or beacon to aid identification.",
"Total usable width including pavements and hard shoulders (in decimetres).",
"Appearance or configuration of the feature.",
"The number of track(s) or lanes of the feature, including both directions.",
"Encodes the general destination of traffic.",
"Component of the traffic routing system.",
"Indicates relative position within heirarchy of training area boundaries.",
"Types of suspension of power transmission lines between pylons.",
"Identifies the primary user, function, or authority of the transportation system.",
"Indicates whether the feature is traversable by foot.",
"Estimated range (1) of the average distance between trees in a stand, determined in decimetres from center to center of adjacent trees.",
"Estimated range (2) of the average distance between trees in a stand, determined in decimetres from center to center of adjacent trees.",
"Estimated range (3) of the average distance between trees in a stand, determined in decimetres from center to center of adjacent trees.",
"Average distance between adjacent tree centerlines within area of feature.",
"Type of tree coverage.",
"The eastern half of the feature centerline alignment measured clockwise from true north.",
"The western half of the feature centerline alignment measured clockwise from true north.",
"Font used to display ZD040 and ZD045.",
"Clearance below bridge, measured from the lowest surface level to the base of the lower of either a cross beam or the lowest bridge deck.",
"Clearance below bridge, measured from the lowest surface level to the base of the lower of either a cross beam or the lowest bridge deck.",
"Characteristics of underlying material composition of feature.",
"No Definition Available",
"Identifies the units of measure. [Reference DIGEST Part 3 for Units associated with DIGEST header data.]",
"The date/time of the source that was used for the review or update of a feature.",
"Details about the update source of the data. This field is normally populated with an Image ID or a Sheet Number.",
"The name of the update source of the data.",
"The predominant geometric configuration of streets found within the delineated area of the feature.",
"No Definition Available",
"The interior length of a feature that is useable by a vehicle, aircraft or watercraft located within that feature.  This would apply to such features as locks and aircraft bunkers which may have different exterior and interior dimensions.  A measurement of the longer of the  two linear axes. For a square feature, measure either axis. For a round feature, measure the diameter.",
"The interior width of a feature that is useable by a vehicle, aircraft or watercraft located within that feature.  This would apply to such features as locks and aircraft bunkers which may have different exterior and interior dimensions.  A measurement of the shorter of the two linear axes.  For a square feature, measure either axis.  For a round feature, width shall be equal to LNU.",
"Generic numeric (integer) value.",
"A description of the difference between the magnetic variation (MVC) of a distrubance area and the magnetic variation of the surrounding area.  Used where more than a numeric value (I.e. VAV) is required.",
"The difference between the magnetic variation of the disturbance area and the magnetic variation of the surrounding area.",
"Type of plant or plantings.",
"An indexed value indicating the roughness of vegetation.",
"The tidal datum to which soundings and drying heights are referenced.  It is usually taken to correspond to a low water stage of the tide.  (Also known as Chart Sounding Datum).",
"The vertical accuracy of the geographic position.",
"The reference water level from which a Vertical Clearance, Safe (VCS or VC3) is measured, if the clearance is measured from a body of water.",
"Name of vertical datum when VCD=999 Other, or other information relating to the safe vertical clearance.",
"Encodes the safe vertical clearance of an object measured from the horizontal plane toward the object.",
"Name of Vertical Datum when VDC (Vertical Datum Category) is 999 (other).",
"Identification code that uniquely identifies a feature that is a vertical obstruction to low-level flight.  (1-2 First two characters of NA4 - Country Code; 3-6 World Aeronautical Chart (WAC) Identifier; 7-10 Unique Obstruction Identification Number; 11 Producer Code)",
"Relative location referenced to sounding datum, unless otherwise indicated.",
"Identifies the type of visual ground signs for aeronautical aids.",
"Reason data is not collected.",
"Identifies type of missing information.",
"The type of geologic formation created by volcanic activity.",
"Volume/Occupancy Level.  This descriptor has multiple meanings/applications: Size or capacity of industry, amount of activity, or vehicle traffic (i.e., numbers of automobiles/trucks, aircraft, RR cars, ships, etc).",
"Type of wall structure category.",
"The average water depth (in meters).",
"The average seasonal high water depth range (in meters).",
"The average seasonal low water depth range (in meters).",
"Description of the drinking quality of water.",
"Range of water velocity, estimated in meters/second within delineation of feature exclusive of high water due to runoff or low water due to drought.",
"Average normal seasonal high water velocity range estimated in meters/second, within delineation of the feature, exclusive of high water due to runoff or low water due to drought.",
"Average normal seasonal low water velocity range estimated in meters/second, within delineation of the feature, exclusive of high water due to runoff or low water due to drought.",
"The name/type of a named waypoint",
"Weather conditions under which a feature is usable.",
"Type of well.",
"Identifies the type of spring or water-hole.",
"A measurement of the shorter of two linear axes.  For a square feature, measure either axis.  For a round feature, width shall be equal to LEN.  For a bridge, the width is the measurement perpendicular to the axis between the abutments.",
"The width at the top of a feature (in meters).",
"Predominant distance across the crest of the dam, measured perpendicular to the centerline of its length along the crest.",
"Minimum width of a second traveled way implementing the shorter width distance, excluding hard pavements and shoulders (in decimetres).",
"A measurement of the shorter of two linear axes.  For a square feature, measure either axis.  For a round feature, width shall be equal to LEN.  For a bridge, the width is the measurement perpendicular to the axis between the abutments.",
"Coded value indicating percent of winter canopy closure within delineated area of feature.",
"Type of work in progress.",
"Type of wreck as listed in Non Submarine Contacts list.  Reference STANAG 3715.",
"A field that indicates how the Z coordinate value(s) on the feature was determined."
};

