/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
#include "share.h"
int D4_CLASS_NUM=422;

char *D4_class_codes[] = {
"FA005",
"BK010",
"FA001",
"FA000",
"AQ010",
"AQ020",
"GB102",
"GB115",
"GB108",
"GB103",
"GB109",
"GB111",
"GB112",
"GB100",
"GB113",
"GB104",
"GB101",
"GB107",
"GB114",
"GB106",
"GB220",
"GA065",
"GB116",
"GB047",
"GA400",
"GB010",
"GB005",
"GA005",
"GA020",
"AK030",
"AK020",
"BB019",
"BB010",
"AL005",
"GB015",
"BH010",
"AL012",
"GB020",
"ZD003",
"DA005",
"AE010",
"AK040",
"GA010",
"BA022",
"EC010",
"AP041",
"AH010",
"BA050",
"BE050",
"BC010",
"ZB020",
"BB020",
"GB025",
"AC010",
"DB010",
"BH015",
"BB030",
"BF010",
"ZB030",
"BD010",
"BB041",
"AQ056",
"AQ045",
"AQ050",
"AQ055",
"AQ040",
"AL015",
"AL018",
"AL020",
"BC020",
"AT005",
"AL025",
"BB050",
"AI030",
"AK060",
"BH020",
"AP010",
"AC020",
"AQ064",
"DB030",
"AL030",
"BD074",
"AF010",
"BI010",
"EC040",
"BA011",
"BA010",
"AT050",
"AT080",
"AL045",
"GA047",
"AQ058",
"FA041",
"CA010",
"ZB035",
"AQ060",
"AF020",
"AF030",
"SA060",
"AF040",
"DB060",
"BD020",
"EA010",
"AQ062",
"AQ065",
"AQ036",
"BG040",
"BG010",
"DB070",
"BI020",
"GB160",
"AM010",
"DB080",
"BE019",
"BE015",
"BE010",
"ZB040",
"BC102",
"BD030",
"AT010",
"GB090",
"AL050",
"AB000",
"ZB036",
"BH030",
"BB080",
"AL060",
"AF050",
"AK070",
"AK080",
"AQ068",
"BB090",
"AT020",
"BD040",
"DB090",
"AF060",
"AQ090",
"DB100",
"AK090",
"DB110",
"AJ030",
"AL070",
"AQ070",
"AQ080",
"BH040",
"BH171",
"FA015",
"BH050",
"BB100",
"BB110",
"BB105",
"AK190",
"AL073",
"AF070",
"AQ150",
"BI043",
"BH060",
"BC101",
"BH070",
"BA023",
"AH050",
"BD050",
"BH075",
"AL075",
"AL080",
"AP040",
"BI041",
"BI070",
"ZD019",
"ZB060",
"ZD012",
"ZD551",
"ZD550",
"FA090",
"DB115",
"BJ030",
"AK100",
"AK101",
"AM020",
"AM030",
"AK110",
"EB010",
"BB115",
"BB043",
"DA010",
"DB200",
"BB005",
"EA020",
"GB030",
"GB035",
"ZD022",
"AL095",
"AF080",
"EA055",
"FC178",
"BF012",
"FC180",
"BH077",
"AL100",
"BJ040",
"BJ060",
"BJ065",
"BH210",
"BH000",
"CA035",
"GB170",
"AP020",
"FA110",
"BA030",
"ZC050",
"BB140",
"BD060",
"BH190",
"BH080",
"EE020",
"BH090",
"BB150",
"BB151",
"DB211",
"GB040",
"GA031",
"BC100",
"BC040",
"BC060",
"AL110",
"BC070",
"BC050",
"BI030",
"BD071",
"EE010",
"ZC040",
"BK020",
"AQ115",
"FC031",
"FC021",
"BB155",
"BC055",
"ED010",
"FC100",
"SU001",
"AA010",
"BD001",
"AM040",
"GB221",
"DB145",
"BH200",
"BD005",
"EE000",
"AL120",
"BH100",
"AI020",
"BB042",
"AL130",
"AQ110",
"BB160",
"BJ020",
"DB150",
"ZD040",
"AL135",
"GA035",
"BA021",
"GB105",
"EA030",
"EC020",
"GA030",
"BB170",
"AC040",
"AA052",
"EA040",
"BD080",
"AL016",
"AL155",
"AQ152",
"GB045",
"BB180",
"BJ070",
"IA040",
"AK120",
"AK123",
"AL140",
"BH110",
"BC080",
"AK124",
"BB190",
"BD100",
"AL165",
"AQ113",
"AK140",
"BD110",
"AL170",
"ZD015",
"BJ080",
"AD010",
"AT030",
"AT040",
"ZB070",
"AQ111",
"AC000",
"AQ116",
"AA012",
"AA011",
"AK130",
"FC130",
"AT045",
"AN010",
"AN050",
"AN075",
"AN060",
"AL195",
"BB220",
"FC102",
"BH120",
"BD120",
"BH130",
"FC036",
"GB050",
"BH135",
"CA020",
"AA040",
"BB225",
"BH140",
"BH145",
"AP030",
"BD130",
"DB160",
"GA045",
"FC165",
"AQ119",
"AL200",
"GB055",
"GB060",
"FC170",
"BH155",
"BH150",
"DB170",
"EB020",
"GB065",
"GB070",
"BB230",
"BH160",
"AL105",
"AC030",
"AL208",
"AQ118",
"AL019",
"BA024",
"GB057",
"FC179",
"AQ035",
"AK150",
"BB240",
"SA050",
"BI040",
"BD140",
"BJ100",
"AL210",
"AD020",
"BE020",
"AL215",
"GA015",
"BH165",
"CA030",
"BH170",
"AK160",
"AQ125",
"AK141",
"AQ120",
"AM060",
"AQ114",
"AQ161",
"AQ162",
"AD030",
"SU002",
"ED020",
"FC177",
"AK170",
"AM070",
"GB075",
"AT060",
"AT070",
"AK050",
"AL209",
"FA100",
"ZD045",
"FC101",
"BG030",
"BG020",
"AM031",
"AL240",
"BE040",
"BE030",
"AQ160",
"FC041",
"AP050",
"FA165",
"EC030",
"AH020",
"BJ110",
"AQ130",
"AH060",
"AL250",
"BD000",
"AQ135",
"AQ140",
"EA050",
"ZD020",
"DB190",
"DB180",
"AL260",
"BA040",
"BI050",
"AM080",
"BG012",
"BH180",
"GA055",
"AA050",
"GB080",
"AJ050",
"AJ051",
"BD180",
"AB010",
"AK180"
};

char *D4_class_names[] = {
"Access Zone",
"Acoustic Station",
"Administrative Area",
"Administrative Boundary",
"Aerial Cableway Lines/Ski Lift Lines",
"Aerial Cableway Pylon/Ski Pylon",
"Air Facility Aircraft Starting Units",
"Air Facility Available Water Transportation",
"Air Facility Fuel Refueling/Dispensing Unit",
"Air Facility Garbage Disposal",
"Air Facility Location And Remarks",
"Air Facility On-Base Fuel Storage",
"Air Facility On-Base Ordnance Storage",
"Air Facility Point To Point Communications",
"Air Facility Security",
"Air Facility Sewage Disposal",
"Air Facility Special Purpose Vehicless",
"Air Facility Terrain And Drainage",
"Air Facility Vehicles",
"Air Facility Water Supply",
"Air Obstruction",
"Air Warning Light",
"Aircraft Bunker",
"Aircraft Facility Reference Point",
"Airport Associated Strip",
"Airport Lighting",
"Airport/Airfield",
"Airspace",
"Airspace Boundary Segment",
"Amusement Park",
"Amusement Park Attraction",
"Anchor",
"Anchorage",
"Animal Sanctuary",
"Apron/Hardstand",
"Aqueduct",
"Archeological Site",
"Arresting Gear",
"Artifact Location",
"Asphalt Lake",
"Assembly Plant",
"Athletic Field",
"ATS Route Segment/Leg",
"Backshore (Precise IHO)",
"Bamboo/Cane",
"Barrier",
"Bastion/Rampart/Fortification",
"Beach",
"Beach Profile",
"Beacon",
"Benchmark",
"Berth",
"Blast Barrier",
"Blast Furnace",
"Bluff/Cliff/Escarpment",
"Bog",
"Bollard",
"Bottom Characteristics",
"Boundary Monument",
"Breakers",
"Breakwater",
"Bridge Pier",
"Bridge Span",
"Bridge Superstructure",
"Bridge Tower/Bridge Pylon",
"Bridge/Overpass/Viaduct",
"Building",
"Building Superstructure Addition",
"Built-Up Area",
"Buoy",
"Cable",
"Cairn",
"Calling-In Point",
"Camp",
"Campground/Campsite",
"Canal",
"Cart Track",
"Catalytic Cracker",
"Causeway",
"Cave",
"Cemetery",
"Chain/Wire",
"Chimney/Smokestack",
"Cistern",
"Cleared Way/Cut Line/Firebreak",
"Coastline",
"Coastline/Shoreline",
"Communication Building",
"Communication Tower",
"Complex Outline",
"Complex Terminal Route",
"Constriction/Expansion",
"Contact Zone",
"Contour Line (Land)",
"Control Point/Control Station",
"Control Tower",
"Conveyor",
"Cooling Tower",
"Covered Drainage",
"Crane",
"Crevice/Crevasse",
"Crib",
"Cropland",
"Crossing  UK - Crossing/Level Crossing",
"Culvert",
"Curb",
"Current Diagram",
"Current Flow",
"Cut",
"Dam/Weir",
"Decontamination Pad",
"Depot (Storage)",
"Depression",
"Depth Area",
"Depth Contour",
"Depth Curve",
"Diagnostic Point",
"Direction of Lateral Buoyage",
"Discolored Water",
"Disk/Dish",
"Displaced Threshold",
"Display Sign",
"Disposal Site/Waste Pile",
"Distance Mark",
"Ditch",
"Dolphin",
"Dragon Teeth",
"Dredge/Powershovel/Dragline",
"Drive In Theater",
"Drive In Theater Screen",
"Drop Gate/Rolling Block",
"Drydock",
"Early Warning Radar Site",
"Eddies",
"Embankment/Fill",
"Engine Test Cell",
"Entrance/Exit",
"Esker",
"Fairgrounds",
"Fault",
"Feed Lot/Stockyard/Holding Pen",
"Fence",
"Ferry Crossing",
"Ferry Site",
"Filtration Beds/Aeration Beds",
"Fire Hydrant",
"Firing Range/Gunnery Range",
"Fish Hatchery/Fish Farm/Marine Farm",
"Fish Stakes",
"Fish Traps/Fish Weirs",
"Fishing Harbor",
"Fishing Pier/Promenade Pier",
"Flagstaff/Flagpole",
"Flare Pipe",
"Flight of Steps",
"Flood Barrage",
"Flume",
"Fog Signal",
"Ford",
"Foreshore (Precise IHO)",
"Fortification",
"Foul Ground",
"Fountain",
"Gallery",
"Gantry",
"Gate",
"Gate (Nautical)",
"Gauging Station",
"General Miscellaneous Feature",
"Geodetic Point",
"Geographic Information Point",
"Geomorphic Line",
"Geomorphic Location",
"Geophysical Prospecting Grid",
"Geothermal Feature",
"Glacier",
"Golf Course",
"Golf Driving Range",
"Grain Bin/Silo",
"Grain Elevator",
"Grandstand",
"Grassland",
"Gridiron",
"Groin",
"Ground Surface Element",
"Gully/Gorge",
"Harbor",
"Hedgerow",
"Helicopter Landing Pad",
"Heliport",
"Homogeneous Aggregate Feature",
"Homogeneous Radar Significant Area",
"Hopper",
"Hops",
"Hull Integrity Test Area",
"Hull Integrity Test Site",
"Hull Integrity Test Site Bottom Feature",
"Hummock",
"Hut",
"Ice Cliff",
"Ice Peak/Nunatak",
"Ice Shelf",
"Inland Shoreline",
"Inland Water",
"Inland Water Elevation",
"INS Alignment Pad",
"Interchange",
"International Date Line",
"Island",
"Isogonic Lines",
"Jetty",
"Kelp/Seaweed",
"Lagoon/Reef Pool",
"Lake/Pond",
"Land devoid of vegetation",
"Land Subject to Inundation",
"Landing Place",
"Landing Stairs",
"Landslide",
"Launch Pad",
"Lead Radial",
"Leading Line",
"Light",
"Light Sector",
"Light Standard/Light Support",
"Light Vessel/Lightship",
"Lighthouse",
"Lock",
"Log Boom/Booming Ground",
"Logging Area",
"Magnetic Disturbance Area",
"Magnetic Station",
"Manhole Cover",
"Maritime Area",
"Maritime Limit Boundary",
"Maritime Station/Maritime Signal Station",
"Marker",
"Marsh",
"Measured Distance Line",
"Military Base",
"Mine",
"Mine-Naval",
"Mineral Pile",
"Miscellaneous Air Obstruction",
"Miscellaneous Obstacle",
"Miscellaneous Surface Drainage Feature",
"Miscellaneous Underwater Feature",
"Miscellaneous Vegetation",
"Missile Site",
"Moat",
"Mobile Home/Mobile Home Park",
"Mole",
"Monument",
"Mooring Mast",
"Mooring Ring",
"Moraine",
"Mountain Pass",
"Named Location",
"Native Settlement",
"NAVAIDS (Aeronautical)",
"Nearshore (Precise IHO)",
"Non- Site 30 Data Element",
"Nursery",
"Oasis",
"Off Route Radial/Bearing",
"Offshore Loading Facility",
"Oil/Gas Facilities",
"Oil/Gas Field",
"Orchard/Plantation",
"Overfalls/Tide Rips",
"Overhang (Storefront)",
"Overhead Obstruction Location",
"Overhead Walkway",
"Overrun/Stopway",
"Oyster Bed/Mussel Bed",
"Pack Ice",
"Parcel",
"Park",
"Park Bench",
"Particle Accelerator",
"Penstock",
"Perches/Stakes",
"Picnic Table",
"Pier/Wharf/Quay",
"Pile/Piling/Post",
"Pipeline Or Pipe Crossing Point",
"Pipeline/Pipe",
"Planter",
"Platform",
"Plaza/City Square",
"Point of Change",
"Polar Ice",
"Power Plant",
"Power Transmission Line",
"Power Transmission Pylon",
"Precise Radar Significant Location",
"Prepared Raft or Float Bridge Site",
"Processing/Treatment Plant",
"Pumping Station",
"Quarry",
"Quarry/Mine Shear Wall",
"Race Track",
"Radar Reference Line",
"Radar Transmitter",
"Railroad",
"Railroad Siding/Railroad Spur",
"Railroad Turntable",
"Railroad Yard/Marshalling Yard",
"Ramp",
"Ramp (Maritime)",
"Range Centerline",
"Rapids",
"Reef",
"Reservoir",
"Restricted Area",
"Revetment (Airfield/Equipment/Facilities )",
"Rice Field",
"Ridge Line",
"Rig/Superstructure",
"Rip Rap",
"River/Stream",
"River/Stream Vanishing Point",
"Road",
"Rock",
"Rock Strata/Rock Formation",
"Route (Air)",
"Route (Maritime)",
"Route Marker",
"Ruins",
"Runway",
"Runway Radar Reflector",
"Safety Fairway",
"Salt Evaporator",
"Salt Pan",
"Sand Dune/Sand Hills",
"Scrub/Brush/Bush",
"Seaplane Base",
"Seaplane Landing/Seaplane Take-Off Area",
"Seawall",
"Sebkha",
"Settlement",
"Settling Basin/Sludge Pond",
"Shanty Town",
"Sharp Curve(s)",
"Shed",
"Shoreline",
"Shoulder",
"Side Scan Sonar Coverage",
"Sidewalk",
"Ski Jump",
"Slipway/Patent Slip",
"Slope Polygon",
"Sluice Gate",
"Snags/Stumps",
"Snow Field/Ice Field",
"Snow Shed/Rock Shed",
"Solar Panels",
"Sounding",
"Special Area",
"Special Use Airspace",
"Spillway",
"Spot Elevation",
"Spring/Water Hole",
"Stadium/Amphitheater",
"Station (Miscellaneous)",
"Statue Pedestal",
"Steep Grade",
"Storage Bunker/Storage Mound",
"Storm Drain",
"Street Lights",
"Street Sign",
"Substation/Transformer Yard",
"Subway",
"Swamp",
"Swept Area",
"Swimming Pool",
"Tank",
"Taxiway",
"Telephone Line/Telegraph Line",
"Telephone-Telegraph Pylon/Pole",
"Tennis Court(s)",
"Tent Dwellings",
"Test Area",
"Text Description",
"Theodolite Line",
"Tide Data Point",
"Tide Gauge",
"Timber Yard",
"Tower (Non-Communication)",
"Track Line",
"Track Swath",
"Traffic Lights",
"Traffic Separation Scheme (TSS)",
"Trail",
"Training Area",
"Trees",
"Trench",
"Tundra",
"Tunnel",
"Underground Bunker",
"Underground Dwelling",
"Underwater Danger/Hazard",
"Vehicle Stopping Area/Rest Area",
"Vehicle Storage/Parking Area",
"Vineyards",
"Void Collection Area",
"Volcanic Dike",
"Volcano",
"Wall",
"Water (Except Inland)",
"Water Intake Tower",
"Water Tower",
"Water Turbulence",
"Waterfall",
"Waypoint/Reporting-Calling In Point",
"Well",
"Wind Indicator",
"Windmill",
"Windmotor",
"Wreck",
"Wrecking Yard/Scrap Yard",
"Zoo/Safari Park"
};

char *D4_class_defns[] = {
"A zone between a contact zone and the first possible clearing line (road, towing path, passable road bank crest).  (See also FA041 and FA045)",
"A device equipped for the collection of acoustic data.",
"An area controlled by administrative authority.",
"A line of demarcation between controlled areas.",
"Cables which are strung between elevated supports as part of a conveyor system on which cars, buckets, or other carrier units are suspended.  (See also AF020)",
"A tower supporting steel cables which convey cars, buckets, or other suspended carrier units.",
"Information concerning aircraft starting units at the air facility including the type and power output.",
"Information concerning the availability of navigable waterways at the air facility usually accessible via road or railroad.",
"Information Concerning Refueling Units At An Air Facility Including Type, Capacity And Tank Size Or Concerning Dispensing Units Including Types Of Hydrants And Nozzles.",
"Information concerning garbage disposal at the air facility including the capacity per day, method of disposal, and whether treated or untreated.",
"Information concerning location and landmarks at the air facility including the city or town reflected in the airport name and the distance of the city or town from the air facility reference point, measured in nautical miles.",
"Information concerning fuel storage at the air facility including numbers and types of containers, storage capacity, and dispensing rate.",
"Information concerning ordnance storage at the air facility including type,number, and capacity of munitions storage.",
"Information concerning point to point communications at the air facility including type, frequency, maintenance, capacity, operators, and hours of operation.",
"Information concerning security at the air facility including type, height,and location of security walls and fences.",
"Information concerning sewage disposal at the air facility.",
"Information concerning the availability of special equipment at the air facility such as crash, wreck and snow removal equipment.",
"Information concerning the terrain and drainage at the air facility including soil characteristics, acreage, grading, drainage, and maintenance.",
"Information concerning military or commercial vehicles at the air facility.",
"Information concerning water supplies at the air facility, including source, quantity, storage capacity and methods, potability, and method of receipt.",
"An existing object of natural growth, or terrain at a fixed location within prescribed area with a reference to which vertical clearance is or must be provided during flight operations.",
"A light or lights marking an obstacle which constitutes a danger to air navigation.",
"Hardened structure built above or partially above ground which encloses aircraft to provide protection from offensive munitions.",
"The Functional Center Of The Aircraft Facilities Landing Area(s) And/Or Runway(s) As Determined By Reference To ADSOP C8321.1.",
"Drag strips or any other form of a strip in the proximity of the airport and falling within the coverage of the airport sketch.",
"Lights used to: define and outline perimeters, runways, taxiways, etc.; guide aircraft while on the ground, and to provide guidance to aircraft on approach for landing.",
"A defined area of land or water used for landing, take-off, and movement of aircraft including associated buildings and facilities.",
"Designated airspace within which some or all aircraft may be subjected to air traffic control.",
"Single segment of an Airspace (GA005).",
"A predominantly man-made facility equipped with recreational devices.  (See also AK090 and AK120)",
"A large structure located in an Amusement Park.",
"Device normally placed on the sea bottom and attached to a cable or rope used to position a vessel, boat, or any other floating structure.",
"An area of water where vessels anchor or may anchor.",
"A natural area set aside for the preservation and protection of wildlife.",
"A defined paved or hard-packed area at an airport or heliport intended for aircraft parking.",
"A pipe or artificial channel designed to transport water from a remote source, usually by gravity.  (See also BH110)",
"A site or location where remains of ancient civilizations or human activity have been discovered.  (See also AL200)",
"Devices such as cables or barriers that can be used to stop an aircraft immediately upon landing.",
"An indicator which identifies incomplete or illogical data at a specific location (node), used for data processing only.",
"A natural pool of liquid asphalt.",
"A building or group of buildings used for the purpose of combining manufactured parts to make a completed product.",
"An open area where sporting events, exercises, or games occur.",
"A portion of an Air Traffic Service (ATS) Route identified by two electronic NAVAIDS at the extremities and/or reporting points.",
"Area between the normal limit of wave action above either Mean High Water Springs (MHWS) or Mean High High Water (MHHW) as defined by the National Authority and the maximum limit of wave action.  (See also BA020, BA021, and BA023)",
"Woody, treelike grass.",
"A permanent obstruction placed across a route to prevent vehicular traffic.",
"A defensive wall built to defend a fort or other defensive work and sometimes equipped with guns.",
"The shore of the sea or lake, sandy or pebbly, brought up by the waves (including the foreshore area).  (See also BA020, BA021, BA022 and BA023)",
"A representation of the three dimensional relief of the bottom along a line or series of connected lines .",
"A fixed visual or electronic aid to navigation.",
"A reference mark on a permanent object indicating elevation relative to an established datum.",
"The place where a ship lies when secured to a pier, wharf, dolphin(s) or dock.  It may be a designated place away from the coast line.",
"A barrier used to divert or dissipate jet or propeller blast.",
"A heat chamber used for smelting iron ore.",
"A steep, vertical, or overhanging face of rock or earth.  (See also DB110)",
"A poorly drained or periodically flooded area, excluding tidal waters, with soil rich in plant residue.",
"A post on a wharf used for fastening mooring lines.",
"Designations used on surveys and charts to indicate the consistency, color, and classification of the sea floor, as determined by sampling methods.",
"A marker identifying the location of a surveyed boundary line.",
"Waves which break over off-lying shoals or near the shore.  (See also BD080)",
"A structure which protects a shore area, harbor, anchorage, or basin from sea waves or swells by preventing them from reaching the protected area or reducing their magnitude.  (See also BB140 and BB042)",
"The support(s) in the form of pillar(s) or abutment(s) for the spans of a bridge.",
"A section of the bridge deck between successive supports such as pillars, piers, or abutments.",
"Those elements of the bridge structure which are above the lowest deck.  (See also AQ055)",
"A tower or pylon from which a bridge's deck is suspended.",
"A man-made structure spanning and providing passage over a body of water, depression, or other obstacles.",
"A relatively permanent structure, roofed and usually walled and designed for some particular use.  (See also AL100)",
"A supplemental portion of a building which rises from the roof but is not considered to be part of the general roof line.",
"An area containing a concentration of buildings and other structures.",
"A floating object, other than a lightship, moored or anchored to the bottom and serving as an aid to navigation.",
"An insulated wire, or group of wires formed into one continuous strand, located underground or underwater.  (See also AT006, AT030  and AT060)",
"A heap of stones piled up as a memorial or a landmark.  (See also AL090 and AL130)",
"A specified point some distance from the harbor at which a vessel's navigator notifies the harbor authority of his ship's position.  (Note that this is not the same as GA055 which is for aircraft only).",
"A place where tents or buildings serve as temporary residence for members of an organization.",
"A location for camping.  (See also AI020 and AQ140)",
"A man-made or improved natural waterway used for transportation.",
"An unimproved roadway.",
"A unit in which petroleum separation is carried out in the presence of a catalyst.",
"A raised roadway of solid structure built primarily to provide a route across wet ground or intertidal area.",
"A natural subterranean chamber or series of chambers open to the Earth's surface.",
"An area of land for burying the dead.",
"A physical connection between two independent objects, e.g., between: anchor and mooring buoy; anchor and offshore platform; hulk and bollard on land.",
"A vertical structure containing a passage or flue for discharging smoke and gases of combustion.",
"A man-made container used for collection or storage of rain water.",
"A man-made clearing in a cultural area or through a stand of trees, designed to provide access for a road, railroad, pipeline, or power transmission line, or for boundary demarcation, survey line-of-sight, or to impede the progress of forest fires.",
"A line generally following the contact between a land mass and a body of water,  based on the low water line, and used as a reference for measuring international boundaries such as Territorial Limits or Exclusive Economic Zone (EEZ).",
"The line where a land mass is in contact with a body of water.",
"A building in which communication signals are processed or controlled.",
"A relatively tall structure used for transmitting and/or receiving electronic communication signals.  (See also AQ060)",
"An outline delimiting an area in which two or more like features have the same function.",
"Definition of route segments, action points, and various approach minimum altitudes and distances from the end of landing runway as functions of aircraft type and instrument approach procedures.",
"A point where a passage way narrows or expands beyond its normal width.",
"Terrain area 3 metres wide limited on the water side by the contact between land and water (under average level of water condition).  (See also FA005 and FA045)",
"A line connecting points having the same vertical datum value.",
"An object or mark on the ground of known position, elevation, or both.",
"A tower-like structure that houses the persons and equipment used to control the flow of air, rail, or marine traffic.  (See also AL240)",
"An apparatus for moving materials from place to place on a moving belt or series of rollers.",
"A tower used to cool liquids.",
"A natural watercourse or man-made waterway that is covered preventing its observation or further classification.",
"A machine for lifting, shifting, and lowering objects or materials by means of a swinging boom or with the lifting apparatus supported on an overhead track.",
"A narrow fissure, crack, or rift in the Earth's surface, snow or ice.",
"A framework structure submerged or above water used to support pipelines, sewer lines, or outfalls.",
"An area that has been tilled for the planting of crops.  (See also EA040, EA050, and EA055)",
"A point where two or more line features intersect or cross at the same level about which information is required.  (See also BH070)",
"A sewer or drain crossing under a road, track, or embankment, without affecting the construction of the crossed feature.",
"A border of concrete, asphalt or stone forming part of a gutter along the edge of a street or road.",
"A graph or chartlet showing the average speed of the flood and ebb currents at different periods of the current cycle.",
"The flow direction of a current.",
"An excavation of the Earth's surface to provide passage for a road, railroad, canal, etc.",
"A permanent barrier across a watercourse used to impound water or to control its flow.  (See also BI040)",
"A designated area where a Nuclear, Biological, or Chemical (NBC) contaminated aircraft, checked at landing, is sent to be decontaminated by special teams.",
"An area used for the storage of products or supplies.  (See also AB000)",
"A low area surrounded by higher ground.",
"Water area containing soundings within a defined range of values permanently at or below sounding datum.",
"A line connecting points of equal depth at and below the hydrographic datum.",
"A navigational safety line indicating that no sounding of a lesser depth exists seaward of the line, but greater depths may occur on the shallow side of the line.",
"A point used to check system accuracy.",
"A point (symbol) placed in a dataset to indicate the direction defining a lateral buoyage system, such as the International Association of Lighthouse Authorities (IALA) Lateral System where the orientation is not otherwise discernable from the configuration of the shoreline and waterways due to limited geographic extent or other constraints.",
"An area of sea water having a color distinctly different from the surrounding water.",
"A concave object used for transmitting or receiving electronic signals.",
"The designated beginning of the portion of the runway usable for landing.  This is located at a point on the runway other than the designated beginning of the runway.   In addition, the feature typically exists at each end of the runway.",
"An upright panel used to convey visual information.  (See also AL080)",
"A site for the collecting/depositing of refuse or discarded material.  (See also AB010, AM010 and AM040)",
"A mark which indicates the value of distance measured from an origin and consists of either a solid visible structure or a distinct location without special installation.",
"A channel constructed for the purpose of irrigation or drainage.",
"A post or group of posts used for mooring, warping a ship or as an aid to navigation.",
"Regularly spaced concrete or metal barriers laid in single or multiple rows to prevent vehicle movement.",
"An excavating machine for removing earth or materials.",
"A place where motion pictures are shown while viewers remain in their vehicles.",
"A large outdoor screen for showing motion pictures.",
"A massive assemblage of material, usually in the form of concrete logs or blocks, positioned alongside or above a transportation route, ready to be activated as a potential barrier to an advancing enemy ground force, when needed.",
"A structure, providing support for a vessel, which has a means of removing water so that the bottom of the vessel can be exposed.",
"An installation utilizing long range radar to detect approaching aircraft or missiles.",
"Circular movements of water running contrary to the main current.",
"A raised long mound of earth or other material.  (See also BA051)",
"A structure wherein engines are tested.",
"A point of entrance or exit.  (See also AA010 and AQ130)",
"A long, narrow ridge of sand and gravel deposited by a glacial stream.",
"An area where permanent facilities exist to hold outdoor fairs, circuses or exhibitions.  (See also AK030 and AK120)",
"A fracture in the Earth's crust with displacement on one side of the fracture relative to the other.  (See also DB010)",
"An enclosed area in which livestock are temporarily kept.",
"A man-made barrier of relatively light structure used as an enclosure or boundary.  (See also AL260)",
"A route in a body of water where a ferry crosses from one shoreline to another.",
"A point where a ferry takes on or discharges its load.",
"An area containing layers of material used to filter or aerate water.",
"No definition available",
"An open area designated for the purpose of discharging or detonating firearms.",
"An enclosure of water used for the breeding and/or rearing of fish.",
"Poles or stakes placed in shallow water to catch fish.",
"A fence or enclosure set in water to catch fish.",
"A harbor which is primarily used by fishing vessels.",
"A structure extending into the water used as a platform for recreational purposes, not intended as a berthing place for vessels.",
"A staff or pole on which a flag is raised.",
"An open-ended pipe at which waste gases are burned.",
"A series of steps or stairs reaching from one level to another.",
"An artificial obstruction placed in a water course to increase the depth or to divert it.",
"An open, inclined channel which carries water for use in such operations as mining or logging.",
"A warning signal transmitted by a vessel, or aid to navigation, during periods of low visibility.  Also, the device producing such a signal.",
"A shallow place in a body of water used as a crossing.  (See also AQ062)",
"Area between the low water line defined by Mean Low Water Springs (MLWS) or Mean Low Low Water (MLLW) as appropriate and the normal limit of wave action above Mean High Water Springs (MHWS) or Mean High High Water (MHHW) as appropriate.  (See also BA020, BA021, and BA022)",
"A facility constructed for the military defense of a site.  (See also AM060)",
"A region of comparatively shallow water strewn with rocks, boulders, coral, wreckage, or other obstructions, making it unsuitable for anchoring, grounding, or ground fishing.",
"An artificial spring with water.",
"A sunken or cut passageway along a transportation route in mountainous regions constructed to protect vehicles from the elements.  A series of openings on one side may be present for light or ventilation.",
"A frame structure raised on side supports so as to span over or around something.  (See also AL050)",
"A barrier which controls passage to a road, railroad, tunnel, or bridge.",
"A structure that may be swung, drawn, or lowered to block an entrance or passageway.",
"A device which monitors stream flow.",
"Any feature deemed important for a particular mission or user and which is not covered by any other feature coding in this catalog.",
"A physical point on the Earth's surface having a surveyed position (e.g. Trig Points).",
"A location where geographic information or statistics may apply.",
"No definition available",
"No definition available",
"A grid established for the collection of geophysical data within an area.",
"A terrain surface feature controlled by or derived from the heat of the Earth's interior.",
"A large mass of snow and ice moving slowly down a slope or valley from above the snowline.",
"An area of land laid out for the game of golf.",
"A parcel or tract of land used for practicing golf shots.",
"An enclosed container, used for storing grain or fodder.  (See also AM011, AM070, and AM080)",
"A tall structure, equipped for loading, unloading, processing and storing grain.",
"A usually roofed structure for special viewing of events and having tiers of seats or standing room for spectators.",
"An area composed of uncultured plants which have little or no woody tissue.",
"A flat frame, usually of parallel timber baulks, erected on the foreshore so that a vessel may dry out on it for painting or repair at low water.",
"A structure which normally projects outward from a shoreline and which protects a beach from erosion by disrupting  the longshore movement of sand and other sediments, not by preventing waves from reaching the shoreline.  (See also BB140 and BB041)",
"The surface soil characteristics of the earth.",
"A long, narrow, deep erosion with steep banks.",
"A natural or artificial improved body of water providing protection for vessels and anchorage and docking facilities.",
"A continuous growth of shrubbery planted as a fence, a boundary, or a wind break.",
"An improved area used for take-off, and landing, by helicopters and other vertical take-off and landing aircraft.",
"A place designated for the landing and take-off of helicopters, including its buildings and facilities.",
"Two or more like features which are represented as one contiguous aggregate feature: where individual features Included within the aggregate may or may not meet inclusion conditions to be delineated individually.",
"A cluster of structures that combine to form a homogeneous area when grouped according to a common radar reflectance and a common height value.",
"A top-loaded funnel-shaped structure for temporary holding of loose material which will be dispensed from its bottom.",
"An area covered by the systematic planting of hop vines.  (See also EA010, EA040 and EA050)",
"A pre-designated submarine test dive area.",
"Point on the seafloor in a Hull Integrity Test Site where a bottom sample or drill core was taken.",
"Naturally occuring or man-made bottom features associated with Hull Integrity Test Sites and directly impacting the safe operation of the site.",
"An area of higher elevation within a swamp, bog, or marsh.",
"A small simple or crude house or shelter.  (See also AL015)",
"The vertical face of a glacier or ice shelf.",
"A rocky peak projecting above a surrounding ice field that may be perpetually covered with ice.",
"A sheet of thick ice, with level or undulating surface, attached to the land but mostly afloat which is bounded on the seaward side by an Ice Cliff (BJ040).",
"The land-water boundary for all inland hydrographic features having shorelines, Lake/Pond (BH080), or Island (BA030).",
"Any known inland waterway body, such as: lake/pond, reservoir, river/stream, etc. requiring separation into individual features due to status/type grouping that is currently indeterminable.",
"A location with a generalized elevation value relative to a vertical datum associated with an inland, usually confined, water body.",
"A designated area where the automated navigation instruments of aircraft are reset before taking off.",
"A connection designed to provide traffic access from one road to another.",
"A line generally coinciding with the 180th meridian, modified to avoid land, and designated as the place where each calendar day begins.",
"A land mass smaller than a continent and surrounded by water.",
"Lines connecting points of equal magnetic variation.",
"A man-made barrier built out into, or in the water, primarily to restrain or direct currents and waves.  (See also AQ030 and BB040)",
"A large seaweed.",
"Open body of water separated from the sea by a sand bank or coral reef.",
"A body of water surrounded by land.  (See also BH130)",
"Ground or land with little (less than 5 percent) or no vegetation.",
"An area periodically covered by flood water, excluding tidal waters.  (See also BH095, ED010, and ED020)",
"A place on shore where landing from the sea is possible.",
"Steps at the shoreline as the connection between land and water on different levels.",
"The mass of earth or rock which has slipped down from a mountain or cliff.",
"A designated area or structure from which a rocket or missile is launched.",
"A radial or bearing which provides at least 2 miles of lead to assist in turning onto the intermediate portion of an instrument approach when the angle of intercept is greater than 90 degrees.",
"A track which passes through one or more (usually two) clearly defined objects, along which a vessel can safely travel.",
"A specially constructed device which displays a luminous or lighted aid to navigation.  (See also BC050)",
"A sector defined by bearings from seaward within which a light shows a specified character or color, or is obscured.",
"A structure serving as a support for lighting.",
"A distinctively marked manned vessel anchored or moored at a defined point to serve as an aid to navigation.",
"A distinctive structure exhibiting light(s) designed to serve as an aid to navigation.  (See also BC040)",
"An enclosure with a pair or series of gates used for raising or lowering vessels as they pass from one water level to another.  (See also BI005)",
"A line of connected, floating timbers as across a river or enclosing a water area to keep logs ready for the sawmill from floating away; also, the enclosed area.",
"An area of forest or vegetation being exploited for lumber resources.",
"A localized anomaly in the Earth's magnetic field.",
"A device equipped for the collection of magnetic data.",
"A removable cover or plate which provides access to underground utility tunnels, distribution lines, or drainage systems.",
"An area in which certain activities or factors of significance to navigation and/or operation apply.",
"A line where on either side certain activities or factors of significance to navigation and/or operation apply.",
"A facility occupied by a governmental (maritime related) or harbor authority, providing specific services to vessels.  A signal station is a structure (building, tower, mast, etc.), which conveys information visually from station to ship.",
"A colored (usually white) mark on a cliff, rock, wall, etc. which is a conspicuous landmark for marine navigation.",
"An area of wet, often spongy ground that is subject to frequent or tidal inundations, but not considered to be continually under water.  It is characterized by the growth of non woody plants and by the lack of trees.  (Nautical Chart Manual, US National Oceanic and Atmospheric Administration - NOAA, 1992)  (See also BH090, BH095, and ED020)",
"A course whose length has been accurately measured and is used in conjunction with ranges ashore.  It is used by vessels to calibrate logs, engine revolution counters, etc., and determine speed.",
"A center of operations for a military organization.",
"An excavation made in the earth for the purpose of extracting natural deposits.  (See also AQ090)",
"An explosive device used in naval warfare located on or below the sea.",
"A man-made heap of mining or quarrying products excluding waste materials.  (See also AB000)",
"A generic man-made air obstruction.",
"Obstacle feature which is of a minor nature and which is not covered by another feature coding in this specification.",
"Surface drainage feature which is of a minor nature and which is not included in other feature codings in this specification.",
"An object or area on the sea floor or underwater that is not identified by any other code in this specification. (Also see BD000)",
"A mixture of woody and non-woody vegetation types.",
"An area with related facilities for storing and launching missiles.",
"A trench usually filled with water, that surrounds a body of land.",
"A site for the permanent parking of trailer(s) used as dwellings and designed without a permanent foundation.  (See also AK060 and AQ140)",
"A loading and discharge place for vessels.  It is usually a substantial masonry structure, and often serves as a breakwater on its outer side while offering facilities for ships in its inner side.",
"A structure erected or maintained as a memorial to a person or event.  (See also AL025 and AL090)",
"A tower-like structure used to secure an airship.",
"A metal ring attached to a structure and used to secure a vessel.",
"An accumulation of soil and stone debris deposited by a glacier.",
"A natural route through a low place in a mountain range.",
"A geographic place on the earth, not normally appearing as a feature on a map, but having a name that is required to be placed on a map.",
"A concentration of native dwellings, generally of the hut type, which are not usually of substantial construction.",
"Any visual or electronic device which provides point-to-point guidance information or position data.",
"Area between the 10 meter depth curve and the low water line defined by either Mean Low Water Springs (MLWS) or Mean Low Low Water (MLLW) as defined by the National Authority.  (See also BA020, BA022, and BA023)",
"Information concerning non- site 30 data including military activities, defenses, and support facilities.",
"A place where shrubs, flowers, plants and trees are grown for transplanting, seed or grafting.",
"A small, isolated, fertile or green area in a desert region usually having a spring or well.",
"Captures the Off Route Radials/Bearings (directions and distance from a NAVAID to a Waypoint).",
"A facility located offshore for loading and unloading cargo.",
"An area involved in the production or distribution of oil or natural gas.",
"An area where oil and/or gas is pumped or otherwise removed from the ground.",
"An area covered by systematic plantings of trees which yield fruits, nuts or other products.  (See also EA010, EA050 and EA055)",
"Short, breaking waves occurring when a current passes over a shoal or other submarine obstruction or meets a contrary current or wind.  Tide rips occur when one or more of the currents are tidal.  (See also BD010)",
"A canopy or ledge attached to the front of a building and protruding beyond the perimeter wall.",
"An undelineated obstruction location such as underpasses, overhead pipelines, building overhangs, and other covered traveled ways.",
"An elevated or suspended bridge-like structure providing pedestrian passage above the street, floor. Ground, or water level.  (See also AQ151)",
"An area beyond the take-off runway designated as able to support an airplane during an aborted take-off.",
"A place in shallow water where oysters and mussels breed and may be cultivated.",
"An area of ice formed by the drifting and crushing together of floating pieces of ice.",
"Land use and/or land property.",
"An area used for recreational or ornamental purposes.  (See also AK030, AK090 and AL170)",
"A long hard seat for two or more persons, located on land reserved for public use.  Often found backless and attached to or adjacent to a picnic table.",
"An apparatus for imparting high velocities to charged particles.",
"A pipeline or channel generally used by hydroelectric plants or water mills to transport water by gravity and under pressure.  (See also BH010)",
"A small marker used to identify channels or to mark dangers such as rocks, shoals, etc.  (See also BD100 and BD140)",
"A flat horizontal surface supported by one or more vertical legs, often with attached benches for seating.",
"A structure primarily used as berthing places for vessels.",
"A long, heavy timber or section of steel, concrete, etc., forced into the earth to serve as a support, as for a pier.  (See also BC080 and BD140)",
"A traversable site extending across a pipeline or pipe that acts as a passageway for cross country movement of vehicles or troops.",
"A tube for the conveyance of solids, liquids or gases.",
"A container for plants, usually decorative and permanent.",
"A flat surface raised above the sea, as a working stage for conducting offshore operations.",
"An open area which serves as a public square in a city or town.  (See also AK120)",
"The location/position on a linear feature where the characteristics of the feature change significantly.",
"The heaviest, thickest form of ice over land or water.  (See also BJ100)",
"The building(s) and equipment necessary for the generation of electric power.  (See also AD020)",
"A system of above ground wires including their supports, which transmits electricity over distance.  (See also AT005, AT006 and AT060)",
"A pylon or pole used to support a power transmission line.",
"A location selected for high radar reflective potential.",
"Site on a river or canal which has a ramp, piling, and/or pier structures constructed on one or both shores to allow for suitable future crossing operations using float bridge or rafting equipment.",
"A site used for changing or refining a particular material.",
"A facility to move solids, liquids or gases by means of pressure or suction.",
"An excavation created by removal of stone by blasting or cutting.",
"The wall facing of the excavation within a quarry/mine.",
"A course for racing.",
"A line shown on a chart in proximity to a shipping route, along which ships are guided by a traffic control center located in a radar station.  (See also BC032)",
"A device for transmitting and receiving radar emissions.",
"A rail or set of parallel rails on which a train or tram runs.",
"A stretch of railroad tracks connected to the main track by switch(es) - used for temporary storage and loading/unloading.",
"A rotating platform with railroad tracks used for turning locomotives or cars/carriages.",
"A system of tracks within defined limits, and associated features, provided for loading/unloading and assembling trains.",
"An inclined plane usually man-made for moving between two levels.  (See also BB220 and BB240)",
"A partially submerged hard surfaced area on a shoreline for launching and retrieving vessels or vehicles.",
"A surveyed reference track marking the center of a test range. Vessels undergoing testing must maintain position along this track.",
"A place in a stream or river where the current is swift and the surface is usually broken by boulders and rocks.",
"A rocky or coral elevation at or near enough to the surface of the sea to be a danger to surface navigation.",
"A man-made enclosure or area formed for the storage of water.  (See also BH080)",
"An area in which certain aspects of navigation are restricted.",
"A barricade which protects an aircraft, equipment, or facilities from hostile action.",
"An area periodically covered with water used for growing rice.",
"A line representation of a ridge top.",
"A vertical structure fitted for drilling or lifting operations.",
"A loose assemblage of broken stones or similar material erected in water or on soft ground as a foundation or to protect the underlying surface from erosion.",
"A natural flowing watercourse.",
"Point at which a river or stream passes into the ground.",
"An open way maintained for vehicular use.",
"An isolated rocky formation or a single large stone above or below the water surface.",
"A visual topographic outcrop, layers or beds of rock.",
"A specific route designated for channeling the flow or traffic as necessary for the provision of air traffic services.",
"A track or lane established for the safe passage of ships.",
"An emblem used to designate a road's name or identifying number.",
"The deteriorated remains of an unspecified structure.  (See also AL012)",
"A defined area, usually rectangular, used for the conventional landing and take-off of aircraft.  (Excludes GB045)",
"A device, normally placed near the threshold of a runway, used for reflecting radar signals.",
"A route established for the safe passage of vessels through offshore oil and gas fields and minefields.",
"Shallow pools, normally man-made, used for the natural evaporation of water for the collection of salt.",
"A flat area of natural surface salt deposits.",
"Ridges or hills of sand.",
"Low-growing woody plants.  (See also EC030)",
"An installation supporting aircraft capable of taking off and landing on water.",
"A designated portion of water outlined by visual surface markings, used by seaplanes to land and take off.",
"A structure built to protect the shore from erosion.",
"A natural depression in arid or semi-arid regions whose bed is covered with salt encrusted clayey soil.",
"A concentration of small dwellings.",
"A site where solid matter is precipitated from a liquid by evaporating or settling.",
"A dense concentration of crude, improvised dwellings made from salvaged materials, usually located on the outskirts of cities and having few, if any, streets and no public facilities.",
"A curve which may cause transportation restrictions.",
"A storage facility usually characterized by one or more open sides, support pillars and a roof.",
"A line drawn along the normal limit of wave action above either Mean High Water Springs (MHWS) or Mean High High Water (MHHW) as defined by the National Authority.",
"Adjacent area along either side of a road or runway not normally used by vehicles or aircraft, but provided as an allowable margin in case of emergency situations.",
"Area covered by side scan sonar survey.",
"A paved or improved pathway normally alongside streets or roads designed for pedestrian traffic.",
"A ramp used for ski jumping.",
"A prepared slope for launching and recovering vessels.",
"An area enclosing a group of slope values falling within a set range.",
"A gate used to regulate the flow of water.  (See also BI020 and BI039)",
"A stem or a trunk of a tree below the surface of water.  (See also BC080 and BD100)",
"A large area permanently covered by snow or ice over land or water.  (See also BJ080)",
"A shelter build to protect a section of road or railroad from snow/rock slides.",
"Units of solar cells for converting sunlight into electrical energy or heat.  (See also AD010)",
"A measured water depth or spot depth which has been reduced to chart datum.",
"A significant cultural feature area or entity, prominent due to its radar reflecting potential.",
"Airspace of defined dimension identified by area on Earth's surface where activities must be confined because of their nature and/or where limitations may be imposed on aircraft operations not associated with those activities.",
"A passage for surplus water to run over or around a dam.",
"A designated location with an elevation value relative to a vertical datum.",
"A natural outflow of water from below the ground surface.  (See also AA050 and BH075)",
"An arena for holding and viewing events.",
"A stopping place for the transfer of passengers and/or freight.",
"An architectural support or base for a statue.",
"Location along any given traveled way where the percent (%) slope (ratio of change in elevation (vertical distance) to horizontal ground distance multiplied by 100) is high enough to slow, hinder, or even stop movement.",
"A structure which may be covered or surrounded with earth which is resistant to ordnance where materials or products are stored.  (See also AH050)",
"A collector opening into a pipe or channel to allow the removal of excess runoff water or in some cases sewage.  In civil engineering terms, a drop inlet.",
"Light(s) placed along streets for the purpose of illuminating the roadway and adjacent ground.  Usually attached to tall poles.",
"Signs placed along streets for the purpose of regulating the flow of vehicular or pedestrian traffic or providing information.",
"A facility, along a power line route, in which electric current is transformed and/or distributed.",
"An underground, metropolitan electric railway or the tunnel through which it travels.",
"A low lying saturated area covered with water all or most of the year, where accumulating dead vegetation does not rapidly decay.  It can exist on flat-lying areas created by certain geomorphic environments.  The vegetation mainly consists of hydrophytic trees and/or scrubs whose roots are adapted to wet conditions, with an open to very dense canopy closure.  (See also BH090, BH095, and ED010)",
"An area that has been determined to be clear of navigational dangers to a specified depth.",
"A constructed basin used for swimming outdoors.",
"A container used for the storage of liquids or gases.  (See also AM011, AM020, and AM080)",
"A prepared surface providing access to/from runways and the aircraft parking area, terminal area, or service area, etc.",
"A system of above ground wires, including their supports, which transmit electrical signals over distance.  (See also AT005, AT006, and AT030)",
"A pylon or pole used to support a telephone or telegraph line.",
"An area or site used for the sport of tennis.",
"An encampment of people housed in tents.",
"Area for the testing of technical products.",
"An area in which a characteristic or an activity pertaining to the area can be described and possibly labeled on a product if deemed important at the time the product is being produced.",
"Lines of known bearing from fixed geographic locations.  Used to determine accurate positions of a vessel on certain test ranges.",
"Place for which tabulated tidal stream data are given.",
"An instrument for measuring the height of the tide.",
"An open area for the storage of wooden lumber and timbers.",
"A relatively tall structure which may be used for observation, support, or storage, etc.  (See also AF030, AM080, AQ060, and BI050)",
"The path of travel with respect to the earth as drawn on the chart and including the sounding information collected along the line.",
"Area of horizontal depth coverage recorded by SONAR array systems.",
"A set of lights placed along streets for the purpose of automatic regulation of the flow of vehicular or pedestrian traffic, especially at transportation route junctions.  Usually attached to tall poles or suspended from overhead cables.",
"A routing measure aimed at the separation of opposing streams of traffic by appropriate means and by the establishment of traffic lanes.",
"A path worn by the passage of people or animals.",
"An area reserved for training.",
"Woody-perennial plants, having a self-supporting main stem or trunk.  (See also EA040, EB020 and EC015)",
"A linear excavation dug for defensive purposes.",
"A prairie-like region in the Arctic and Subarctic zones which sustains a growth of low vegetation.",
"An underground or underwater passage, open at both ends, and usually containing a road or railroad.  (See also AQ090)",
"An underground facility used by the military either for location of command/control centers or for troop encampment.  (See also AL250)",
"Underground living quarters.  (See also AL040)",
"A known underwater object or area, known to be dangerous to surface navigation.",
"A roadside place usually having facilities for people and/or vehicles.",
"An open land area used for storing or parking vehicles or vessels (including recreational vehicles).  (See also AI020 and AK060)",
"An area covered by the systematic planting of grape vines.  (See also EA010, EA040 and EA055)",
"An area lacking suitable source coverage, or where data is not required.",
"A steep ridge of igneous rock.",
"A mountain or hill, often conical, formed around a vent in the earth's crust through which molten rock, ash, or gases are or have been expelled.",
"A solid man-made barrier of heavy material used as an enclosure or boundary or for protection.  (See also AL070)",
"An area of water which normally has tidal fluctuations.",
"A tower-like structure associated with a dam or water source and used for the intake of water.",
"An elevated container and its supporting structure used to hold water.  (See also AM011, AM020, and AM070)",
"The disturbance of water caused by the interaction of any combination of waves, currents, eddies, tidal streams, wind, shoal patches and obstructions.",
"A vertical or nearly vertical descent of water.",
"A predetermined geographical position, used for route instrument approach definition or progress reporting purposes or to change frequency etc.",
"A hole drilled or dug into the earth or sea bed for the extraction of liquids or gases.  (See also BH170)",
"A visual device used to provide wind information.",
"A wind-driven system of vanes attached to a tower like structure (excluding wind-generated power plants).",
"A modern structure used for wind power.",
"The ruined remains of a vessel.",
"An area or site engaged in the wrecking, dismantling, storage, or resale of discarded products.  (See also AB000)",
"An area with a collection of live animals usually for public display."
};

unsigned char D4DOMAINS[]={
0  /*** Dummy Value ***/,
D_BOUN  /*** Access Zone ***/,
D_OCEN  /*** Acoustic Station ***/,
D_BOUN  /*** Administrative Area ***/,
D_BOUN  /*** Administrative Boundary ***/,
D_POPU  /*** Aerial Cableway Lines/Ski Lift Lines ***/,
D_POPU  /*** Aerial Cableway Pylon/Ski Pylon ***/,
D_AERO  /*** Air Facility Aircraft Starting Units ***/,
D_AERO  /*** Air Facility Available Water Transportation ***/,
D_AERO  /*** Air Facility Fuel Refueling/Dispensing Unit ***/,
D_AERO  /*** Air Facility Garbage Disposal ***/,
D_AERO  /*** Air Facility Location And Remarks ***/,
D_AERO  /*** Air Facility On-Base Fuel Storage ***/,
D_AERO  /*** Air Facility On-Base Ordnance Storage ***/,
D_AERO  /*** Air Facility Point To Point Communications ***/,
D_AERO  /*** Air Facility Security ***/,
D_AERO  /*** Air Facility Sewage Disposal ***/,
D_AERO  /*** Air Facility Special Purpose Vehicless ***/,
D_AERO  /*** Air Facility Terrain And Drainage ***/,
D_AERO  /*** Air Facility Vehicles ***/,
D_AERO  /*** Air Facility Water Supply ***/,
D_AERO  /*** Air Obstruction ***/,
D_AERO  /*** Air Warning Light ***/,
D_AERO  /*** Aircraft Bunker ***/,
D_AERO  /*** Aircraft Facility Reference Point ***/,
D_AERO  /*** Airport Associated Strip ***/,
D_AERO  /*** Airport Lighting ***/,
D_AERO  /*** Airport/Airfield ***/,
D_AERO  /*** Airspace ***/,
D_AERO  /*** Airspace Boundary Segment ***/,
D_POPU  /*** Amusement Park ***/,
D_POPU  /*** Amusement Park Attraction ***/,
D_OCEN  /*** Anchor ***/,
D_OCEN  /*** Anchorage ***/,
D_POPU  /*** Animal Sanctuary ***/,
D_AERO  /*** Apron/Hardstand ***/,
D_INWA  /*** Aqueduct ***/,
D_POPU  /*** Archeological Site ***/,
D_AERO  /*** Arresting Gear ***/,
D_DAQU  /*** Artifact Location ***/,
D_PHYS  /*** Asphalt Lake ***/,
D_UTAN  /*** Assembly Plant ***/,
D_POPU  /*** Athletic Field ***/,
D_AERO  /*** ATS Route Segment/Leg ***/,
D_PHYS  /*** Backshore (Precise IHO) ***/,
D_VEGE  /*** Bamboo/Cane ***/,
D_GRTR  /*** Barrier ***/,
D_DEST  /*** Bastion/Rampart/Fortification ***/,
D_PHYS  /*** Beach ***/,
D_OCEN  /*** Beach Profile ***/,
D_AITO  /*** Beacon ***/,
D_ELEV  /*** Benchmark ***/,
D_POAN  /*** Berth ***/,
D_AERO  /*** Blast Barrier ***/,
D_UTAN  /*** Blast Furnace ***/,
D_PHYS  /*** Bluff/Cliff/Escarpment ***/,
D_VEGE  /*** Bog ***/,
D_POAN  /*** Bollard ***/,
D_PHYS  /*** Bottom Characteristics ***/,
D_BOUN  /*** Boundary Monument ***/,
D_OCEN  /*** Breakers ***/,
D_POAN  /*** Breakwater ***/,
D_GRTR  /*** Bridge Pier ***/,
D_GRTR  /*** Bridge Span ***/,
D_GRTR  /*** Bridge Superstructure ***/,
D_GRTR  /*** Bridge Tower/Bridge Pylon ***/,
D_GRTR  /*** Bridge/Overpass/Viaduct ***/,
D_POPU  /*** Building ***/,
D_GRTR  /*** Building Superstructure Addition ***/,
D_POPU  /*** Built-Up Area ***/,
D_AITO  /*** Buoy ***/,
D_UTAN  /*** Cable ***/,
D_BOUN  /*** Cairn ***/,
D_OCEN  /*** Calling-In Point ***/,
D_POAN  /*** Camp ***/,
D_POPU  /*** Campground/Campsite ***/,
D_INWA  /*** Canal ***/,
D_GRTR  /*** Cart Track ***/,
D_UTAN  /*** Catalytic Cracker ***/,
D_GRTR  /*** Causeway ***/,
D_PHYS  /*** Cave ***/,
D_POPU  /*** Cemetery ***/,
D_POAN  /*** Chain/Wire ***/,
D_UTAN  /*** Chimney/Smokestack ***/,
D_INWA  /*** Cistern ***/,
D_VEGE  /*** Cleared Way/Cut Line/Firebreak ***/,
D_BOUN  /*** Coastline ***/,
D_PHYS  /*** Coastline/Shoreline ***/,
D_UTAN  /*** Communication Building ***/,
D_UTAN  /*** Communication Tower ***/,
D_GENE  /*** Complex Outline ***/,
D_AERO  /*** Complex Terminal Route ***/,
D_GRTR  /*** Constriction/Expansion ***/,
D_BOUN  /*** Contact Zone ***/,
D_ELEV  /*** Contour Line (Land) ***/,
D_ELEV  /*** Control Point/Control Station ***/,
D_POPU  /*** Control Tower ***/,
D_UTAN  /*** Conveyor ***/,
D_UTAN  /*** Cooling Tower ***/,
D_INWA  /*** Covered Drainage ***/,
D_UTAN  /*** Crane ***/,
D_PHYS  /*** Crevice/Crevasse ***/,
D_OCEN  /*** Crib ***/,
D_VEGE  /*** Cropland ***/,
D_GRTR  /*** Crossing  UK - Crossing/Level Crossing ***/,
D_GRTR  /*** Culvert ***/,
D_POPU  /*** Curb ***/,
D_OCEN  /*** Current Diagram ***/,
D_INWA  /*** Current Flow ***/,
D_PHYS  /*** Cut ***/,
D_INWA  /*** Dam/Weir ***/,
D_AERO  /*** Decontamination Pad ***/,
D_UTAN  /*** Depot (Storage) ***/,
D_PHYS  /*** Depression ***/,
D_OCEN  /*** Depth Area ***/,
D_OCEN  /*** Depth Contour ***/,
D_OCEN  /*** Depth Curve ***/,
D_DAQU  /*** Diagnostic Point ***/,
D_AITO  /*** Direction of Lateral Buoyage ***/,
D_OCEN  /*** Discolored Water ***/,
D_UTAN  /*** Disk/Dish ***/,
D_AERO  /*** Displaced Threshold ***/,
D_POPU  /*** Display Sign ***/,
D_UTAN  /*** Disposal Site/Waste Pile ***/,
D_DAQU  /*** Distance Mark ***/,
D_INWA  /*** Ditch ***/,
D_POAN  /*** Dolphin ***/,
D_DEST  /*** Dragon Teeth ***/,
D_UTAN  /*** Dredge/Powershovel/Dragline ***/,
D_POPU  /*** Drive In Theater ***/,
D_POPU  /*** Drive In Theater Screen ***/,
D_GRTR  /*** Drop Gate/Rolling Block ***/,
D_POAN  /*** Drydock ***/,
D_DEST  /*** Early Warning Radar Site ***/,
D_OCEN  /*** Eddies ***/,
D_PHYS  /*** Embankment/Fill ***/,
D_UTAN  /*** Engine Test Cell ***/,
D_GRTR  /*** Entrance/Exit ***/,
D_PHYS  /*** Esker ***/,
D_POPU  /*** Fairgrounds ***/,
D_PHYS  /*** Fault ***/,
D_UTAN  /*** Feed Lot/Stockyard/Holding Pen ***/,
D_POPU  /*** Fence ***/,
D_GRTR  /*** Ferry Crossing ***/,
D_GRTR  /*** Ferry Site ***/,
D_UTAN  /*** Filtration Beds/Aeration Beds ***/,
D_INWA  /*** Fire Hydrant ***/,
D_BOUN  /*** Firing Range/Gunnery Range ***/,
D_INWA  /*** Fish Hatchery/Fish Farm/Marine Farm ***/,
D_OCEN  /*** Fish Stakes ***/,
D_OCEN  /*** Fish Traps/Fish Weirs ***/,
D_POAN  /*** Fishing Harbor ***/,
D_POAN  /*** Fishing Pier/Promenade Pier ***/,
D_POPU  /*** Flagstaff/Flagpole ***/,
D_UTAN  /*** Flare Pipe ***/,
D_POPU  /*** Flight of Steps ***/,
D_POAN  /*** Flood Barrage ***/,
D_UTAN  /*** Flume ***/,
D_AITO  /*** Fog Signal ***/,
D_GRTR  /*** Ford ***/,
D_PHYS  /*** Foreshore (Precise IHO) ***/,
D_DEST  /*** Fortification ***/,
D_OCEN  /*** Foul Ground ***/,
D_POPU  /*** Fountain ***/,
D_GRTR  /*** Gallery ***/,
D_UTAN  /*** Gantry ***/,
D_GRTR  /*** Gate ***/,
D_POAN  /*** Gate (Nautical) ***/,
D_INWA  /*** Gauging Station ***/,
D_GENE  /*** General Miscellaneous Feature ***/,
D_ELEV  /*** Geodetic Point ***/,
D_DAQU  /*** Geographic Information Point ***/,
D_DAQU  /*** Geomorphic Line ***/,
D_DAQU  /*** Geomorphic Location ***/,
D_UTAN  /*** Geophysical Prospecting Grid ***/,
D_PHYS  /*** Geothermal Feature ***/,
D_PHYS  /*** Glacier ***/,
D_POPU  /*** Golf Course ***/,
D_POPU  /*** Golf Driving Range ***/,
D_UTAN  /*** Grain Bin/Silo ***/,
D_UTAN  /*** Grain Elevator ***/,
D_POPU  /*** Grandstand ***/,
D_VEGE  /*** Grassland ***/,
D_POAN  /*** Gridiron ***/,
D_POAN  /*** Groin ***/,
D_SUMA  /*** Ground Surface Element ***/,
D_PHYS  /*** Gully/Gorge ***/,
D_POAN  /*** Harbor ***/,
D_VEGE  /*** Hedgerow ***/,
D_AERO  /*** Helicopter Landing Pad ***/,
D_AERO  /*** Heliport ***/,
D_GENE  /*** Homogeneous Aggregate Feature ***/,
D_POPU  /*** Homogeneous Radar Significant Area ***/,
D_UTAN  /*** Hopper ***/,
D_VEGE  /*** Hops ***/,
D_OCEN  /*** Hull Integrity Test Area ***/,
D_OCEN  /*** Hull Integrity Test Site ***/,
D_OCEN  /*** Hull Integrity Test Site Bottom Feature ***/,
D_VEGE  /*** Hummock ***/,
D_POPU  /*** Hut ***/,
D_PHYS  /*** Ice Cliff ***/,
D_PHYS  /*** Ice Peak/Nunatak ***/,
D_PHYS  /*** Ice Shelf ***/,
D_PHYS  /*** Inland Shoreline ***/,
D_INWA  /*** Inland Water ***/,
D_ELEV  /*** Inland Water Elevation ***/,
D_AERO  /*** INS Alignment Pad ***/,
D_GRTR  /*** Interchange ***/,
D_BOUN  /*** International Date Line ***/,
D_PHYS  /*** Island ***/,
D_PHYS  /*** Isogonic Lines ***/,
D_POAN  /*** Jetty ***/,
D_OCEN  /*** Kelp/Seaweed ***/,
D_OCEN  /*** Lagoon/Reef Pool ***/,
D_INWA  /*** Lake/Pond ***/,
D_VEGE  /*** Land devoid of vegetation ***/,
D_INWA  /*** Land Subject to Inundation ***/,
D_POAN  /*** Landing Place ***/,
D_POAN  /*** Landing Stairs ***/,
D_PHYS  /*** Landslide ***/,
D_AERO  /*** Launch Pad ***/,
D_AITO  /*** Lead Radial ***/,
D_AITO  /*** Leading Line ***/,
D_AITO  /*** Light ***/,
D_AITO  /*** Light Sector ***/,
D_POPU  /*** Light Standard/Light Support ***/,
D_AITO  /*** Light Vessel/Lightship ***/,
D_AITO  /*** Lighthouse ***/,
D_INWA  /*** Lock ***/,
D_UTAN  /*** Log Boom/Booming Ground ***/,
D_VEGE  /*** Logging Area ***/,
D_PHYS  /*** Magnetic Disturbance Area ***/,
D_OCEN  /*** Magnetic Station ***/,
D_UTAN  /*** Manhole Cover ***/,
D_MALI  /*** Maritime Area ***/,
D_MALI  /*** Maritime Limit Boundary ***/,
D_POAN  /*** Maritime Station/Maritime Signal Station ***/,
D_AITO  /*** Marker ***/,
D_VEGE  /*** Marsh ***/,
D_BOUN  /*** Measured Distance Line ***/,
D_DEST  /*** Military Base ***/,
D_UTAN  /*** Mine ***/,
D_OCEN  /*** Mine-Naval ***/,
D_UTAN  /*** Mineral Pile ***/,
D_AERO  /*** Miscellaneous Air Obstruction ***/,
D_DEST  /*** Miscellaneous Obstacle ***/,
D_INWA  /*** Miscellaneous Surface Drainage Feature ***/,
D_OCEN  /*** Miscellaneous Underwater Feature ***/,
D_VEGE  /*** Miscellaneous Vegetation ***/,
D_DEST  /*** Missile Site ***/,
D_DEST  /*** Moat ***/,
D_POPU  /*** Mobile Home/Mobile Home Park ***/,
D_POAN  /*** Mole ***/,
D_POPU  /*** Monument ***/,
D_AERO  /*** Mooring Mast ***/,
D_POAN  /*** Mooring Ring ***/,
D_PHYS  /*** Moraine ***/,
D_PHYS  /*** Mountain Pass ***/,
D_GENE  /*** Named Location ***/,
D_POPU  /*** Native Settlement ***/,
D_AERO  /*** NAVAIDS (Aeronautical) ***/,
D_PHYS  /*** Nearshore (Precise IHO) ***/,
D_AERO  /*** Non- Site 30 Data Element ***/,
D_VEGE  /*** Nursery ***/,
D_VEGE  /*** Oasis ***/,
D_AITO  /*** Off Route Radial/Bearing ***/,
D_POAN  /*** Offshore Loading Facility ***/,
D_UTAN  /*** Oil/Gas Facilities ***/,
D_UTAN  /*** Oil/Gas Field ***/,
D_VEGE  /*** Orchard/Plantation ***/,
D_OCEN  /*** Overfalls/Tide Rips ***/,
D_POPU  /*** Overhang (Storefront) ***/,
D_POPU  /*** Overhead Obstruction Location ***/,
D_POPU  /*** Overhead Walkway ***/,
D_AERO  /*** Overrun/Stopway ***/,
D_OCEN  /*** Oyster Bed/Mussel Bed ***/,
D_PHYS  /*** Pack Ice ***/,
D_BOUN  /*** Parcel ***/,
D_POPU  /*** Park ***/,
D_POPU  /*** Park Bench ***/,
D_UTAN  /*** Particle Accelerator ***/,
D_INWA  /*** Penstock ***/,
D_AITO  /*** Perches/Stakes ***/,
D_POPU  /*** Picnic Table ***/,
D_POAN  /*** Pier/Wharf/Quay ***/,
D_POAN  /*** Pile/Piling/Post ***/,
D_GRTR  /*** Pipeline Or Pipe Crossing Point ***/,
D_UTAN  /*** Pipeline/Pipe ***/,
D_POPU  /*** Planter ***/,
D_UTAN  /*** Platform ***/,
D_POPU  /*** Plaza/City Square ***/,
D_DAQU  /*** Point of Change ***/,
D_PHYS  /*** Polar Ice ***/,
D_UTAN  /*** Power Plant ***/,
D_UTAN  /*** Power Transmission Line ***/,
D_UTAN  /*** Power Transmission Pylon ***/,
D_DAQU  /*** Precise Radar Significant Location ***/,
D_GRTR  /*** Prepared Raft or Float Bridge Site ***/,
D_UTAN  /*** Processing/Treatment Plant ***/,
D_UTAN  /*** Pumping Station ***/,
D_UTAN  /*** Quarry ***/,
D_UTAN  /*** Quarry/Mine Shear Wall ***/,
D_POPU  /*** Race Track ***/,
D_MALI  /*** Radar Reference Line ***/,
D_UTAN  /*** Radar Transmitter ***/,
D_GRTR  /*** Railroad ***/,
D_GRTR  /*** Railroad Siding/Railroad Spur ***/,
D_GRTR  /*** Railroad Turntable ***/,
D_GRTR  /*** Railroad Yard/Marshalling Yard ***/,
D_GRTR  /*** Ramp ***/,
D_POAN  /*** Ramp (Maritime) ***/,
D_OCEN  /*** Range Centerline ***/,
D_INWA  /*** Rapids ***/,
D_OCEN  /*** Reef ***/,
D_INWA  /*** Reservoir ***/,
D_MALI  /*** Restricted Area ***/,
D_AERO  /*** Revetment (Airfield/Equipment/Facilities ) ***/,
D_VEGE  /*** Rice Field ***/,
D_PHYS  /*** Ridge Line ***/,
D_UTAN  /*** Rig/Superstructure ***/,
D_POAN  /*** Rip Rap ***/,
D_INWA  /*** River/Stream ***/,
D_INWA  /*** River/Stream Vanishing Point ***/,
D_GRTR  /*** Road ***/,
D_OCEN  /*** Rock ***/,
D_PHYS  /*** Rock Strata/Rock Formation ***/,
D_AERO  /*** Route (Air) ***/,
D_MALI  /*** Route (Maritime) ***/,
D_GRTR  /*** Route Marker ***/,
D_POPU  /*** Ruins ***/,
D_AERO  /*** Runway ***/,
D_AERO  /*** Runway Radar Reflector ***/,
D_MALI  /*** Safety Fairway ***/,
D_UTAN  /*** Salt Evaporator ***/,
D_UTAN  /*** Salt Pan ***/,
D_PHYS  /*** Sand Dune/Sand Hills ***/,
D_VEGE  /*** Scrub/Brush/Bush ***/,
D_AERO  /*** Seaplane Base ***/,
D_AERO  /*** Seaplane Landing/Seaplane Take-Off Area ***/,
D_POAN  /*** Seawall ***/,
D_PHYS  /*** Sebkha ***/,
D_POPU  /*** Settlement ***/,
D_UTAN  /*** Settling Basin/Sludge Pond ***/,
D_POPU  /*** Shanty Town ***/,
D_GRTR  /*** Sharp Curve(s) ***/,
D_POPU  /*** Shed ***/,
D_BOUN  /*** Shoreline ***/,
D_AERO  /*** Shoulder ***/,
D_OCEN  /*** Side Scan Sonar Coverage ***/,
D_POPU  /*** Sidewalk ***/,
D_POPU  /*** Ski Jump ***/,
D_POAN  /*** Slipway/Patent Slip ***/,
D_SLPO  /*** Slope Polygon ***/,
D_INWA  /*** Sluice Gate ***/,
D_OCEN  /*** Snags/Stumps ***/,
D_PHYS  /*** Snow Field/Ice Field ***/,
D_GRTR  /*** Snow Shed/Rock Shed ***/,
D_UTAN  /*** Solar Panels ***/,
D_OCEN  /*** Sounding ***/,
D_POPU  /*** Special Area ***/,
D_AERO  /*** Special Use Airspace ***/,
D_INWA  /*** Spillway ***/,
D_ELEV  /*** Spot Elevation ***/,
D_INWA  /*** Spring/Water Hole ***/,
D_POPU  /*** Stadium/Amphitheater ***/,
D_GRTR  /*** Station (Miscellaneous) ***/,
D_POPU  /*** Statue Pedestal ***/,
D_GRTR  /*** Steep Grade ***/,
D_UTAN  /*** Storage Bunker/Storage Mound ***/,
D_UTAN  /*** Storm Drain ***/,
D_GRTR  /*** Street Lights ***/,
D_GRTR  /*** Street Sign ***/,
D_UTAN  /*** Substation/Transformer Yard ***/,
D_GRTR  /*** Subway ***/,
D_VEGE  /*** Swamp ***/,
D_MALI  /*** Swept Area ***/,
D_POPU  /*** Swimming Pool ***/,
D_UTAN  /*** Tank ***/,
D_AERO  /*** Taxiway ***/,
D_UTAN  /*** Telephone Line/Telegraph Line ***/,
D_UTAN  /*** Telephone-Telegraph Pylon/Pole ***/,
D_POPU  /*** Tennis Court(s) ***/,
D_POPU  /*** Tent Dwellings ***/,
D_BOUN  /*** Test Area ***/,
D_GENE  /*** Text Description ***/,
D_OCEN  /*** Theodolite Line ***/,
D_OCEN  /*** Tide Data Point ***/,
D_OCEN  /*** Tide Gauge ***/,
D_UTAN  /*** Timber Yard ***/,
D_UTAN  /*** Tower (Non-Communication) ***/,
D_OCEN  /*** Track Line ***/,
D_OCEN  /*** Track Swath ***/,
D_OCEN  /*** Traffic Lights ***/,
D_MALI  /*** Traffic Separation Scheme (TSS) ***/,
D_GRTR  /*** Trail ***/,
D_DEST  /*** Training Area ***/,
D_VEGE  /*** Trees ***/,
D_DEST  /*** Trench ***/,
D_VEGE  /*** Tundra ***/,
D_GRTR  /*** Tunnel ***/,
D_DEST  /*** Underground Bunker ***/,
D_POPU  /*** Underground Dwelling ***/,
D_OCEN  /*** Underwater Danger/Hazard ***/,
D_GRTR  /*** Vehicle Stopping Area/Rest Area ***/,
D_GRTR  /*** Vehicle Storage/Parking Area ***/,
D_VEGE  /*** Vineyards ***/,
D_GENE  /*** Void Collection Area ***/,
D_PHYS  /*** Volcanic Dike ***/,
D_PHYS  /*** Volcano ***/,
D_POPU  /*** Wall ***/,
D_OCEN  /*** Water (Except Inland) ***/,
D_INWA  /*** Water Intake Tower ***/,
D_UTAN  /*** Water Tower ***/,
D_OCEN  /*** Water Turbulence ***/,
D_INWA  /*** Waterfall ***/,
D_AERO  /*** Waypoint/Reporting-Calling In Point ***/,
D_INWA  /*** Well ***/,
D_AERO  /*** Wind Indicator ***/,
D_UTAN  /*** Windmill ***/,
D_UTAN  /*** Windmotor ***/,
D_OCEN  /*** Wreck ***/,
D_UTAN  /*** Wrecking Yard/Scrap Yard ***/,
D_POPU  /*** Zoo/Safari Park ***/
};

int D4DOMAINSLEN = sizeof(D4DOMAINS)/ sizeof(unsigned char);

unsigned char D4STRATS[]={
0  /*** Dummy Value ***/,
S_APPL  /*** Access Zone ***/,
S_APPL  /*** Acoustic Station ***/,
S_APPL  /*** Administrative Area ***/,
S_APPL  /*** Administrative Boundary ***/,
S_APPL  /*** Aerial Cableway Lines/Ski Lift Lines ***/,
S_APPL  /*** Aerial Cableway Pylon/Ski Pylon ***/,
S_APPL  /*** Air Facility Aircraft Starting Units ***/,
S_APPL  /*** Air Facility Available Water Transportation ***/,
S_APPL  /*** Air Facility Fuel Refueling/Dispensing Unit ***/,
S_APPL  /*** Air Facility Garbage Disposal ***/,
S_APPL  /*** Air Facility Location And Remarks ***/,
S_APPL  /*** Air Facility On-Base Fuel Storage ***/,
S_APPL  /*** Air Facility On-Base Ordnance Storage ***/,
S_APPL  /*** Air Facility Point To Point Communications ***/,
S_APPL  /*** Air Facility Security ***/,
S_APPL  /*** Air Facility Sewage Disposal ***/,
S_APPL  /*** Air Facility Special Purpose Vehicless ***/,
S_APPL  /*** Air Facility Terrain And Drainage ***/,
S_APPL  /*** Air Facility Vehicles ***/,
S_APPL  /*** Air Facility Water Supply ***/,
S_APPL  /*** Air Obstruction ***/,
S_APPL  /*** Air Warning Light ***/,
S_APPL  /*** Aircraft Bunker ***/,
S_APPL  /*** Aircraft Facility Reference Point ***/,
S_APPL  /*** Airport Associated Strip ***/,
S_APPL  /*** Airport Lighting ***/,
S_APPL  /*** Airport/Airfield ***/,
S_APPL  /*** Airspace ***/,
S_APPL  /*** Airspace Boundary Segment ***/,
S_APPL  /*** Amusement Park ***/,
S_APPL  /*** Amusement Park Attraction ***/,
S_APPL  /*** Anchor ***/,
S_APPL  /*** Anchorage ***/,
S_APPL  /*** Animal Sanctuary ***/,
S_APPL  /*** Apron/Hardstand ***/,
S_APPL  /*** Aqueduct ***/,
S_APPL  /*** Archeological Site ***/,
S_APPL  /*** Arresting Gear ***/,
S_APPL  /*** Artifact Location ***/,
S_APPL  /*** Asphalt Lake ***/,
S_APPL  /*** Assembly Plant ***/,
S_APPL  /*** Athletic Field ***/,
S_APPL  /*** ATS Route Segment/Leg ***/,
S_APPL  /*** Backshore (Precise IHO) ***/,
S_APPL  /*** Bamboo/Cane ***/,
S_APPL  /*** Barrier ***/,
S_APPL  /*** Bastion/Rampart/Fortification ***/,
S_APPL  /*** Beach ***/,
S_APPL  /*** Beach Profile ***/,
S_APPL  /*** Beacon ***/,
S_APPL  /*** Benchmark ***/,
S_APPL  /*** Berth ***/,
S_APPL  /*** Blast Barrier ***/,
S_APPL  /*** Blast Furnace ***/,
S_APPL  /*** Bluff/Cliff/Escarpment ***/,
S_APPL  /*** Bog ***/,
S_APPL  /*** Bollard ***/,
S_APPL  /*** Bottom Characteristics ***/,
S_APPL  /*** Boundary Monument ***/,
S_APPL  /*** Breakers ***/,
S_APPL  /*** Breakwater ***/,
S_APPL  /*** Bridge Pier ***/,
S_APPL  /*** Bridge Span ***/,
S_APPL  /*** Bridge Superstructure ***/,
S_APPL  /*** Bridge Tower/Bridge Pylon ***/,
S_APPL  /*** Bridge/Overpass/Viaduct ***/,
S_APPL  /*** Building ***/,
S_APPL  /*** Building Superstructure Addition ***/,
S_APPL  /*** Built-Up Area ***/,
S_APPL  /*** Buoy ***/,
S_APPL  /*** Cable ***/,
S_APPL  /*** Cairn ***/,
S_APPL  /*** Calling-In Point ***/,
S_APPL  /*** Camp ***/,
S_APPL  /*** Campground/Campsite ***/,
S_APPL  /*** Canal ***/,
S_APPL  /*** Cart Track ***/,
S_APPL  /*** Catalytic Cracker ***/,
S_APPL  /*** Causeway ***/,
S_APPL  /*** Cave ***/,
S_APPL  /*** Cemetery ***/,
S_APPL  /*** Chain/Wire ***/,
S_APPL  /*** Chimney/Smokestack ***/,
S_APPL  /*** Cistern ***/,
S_APPL  /*** Cleared Way/Cut Line/Firebreak ***/,
S_APPL  /*** Coastline ***/,
S_APPL  /*** Coastline/Shoreline ***/,
S_APPL  /*** Communication Building ***/,
S_APPL  /*** Communication Tower ***/,
S_APPL  /*** Complex Outline ***/,
S_APPL  /*** Complex Terminal Route ***/,
S_APPL  /*** Constriction/Expansion ***/,
S_APPL  /*** Contact Zone ***/,
S_APPL  /*** Contour Line (Land) ***/,
S_APPL  /*** Control Point/Control Station ***/,
S_APPL  /*** Control Tower ***/,
S_APPL  /*** Conveyor ***/,
S_APPL  /*** Cooling Tower ***/,
S_APPL  /*** Covered Drainage ***/,
S_APPL  /*** Crane ***/,
S_APPL  /*** Crevice/Crevasse ***/,
S_APPL  /*** Crib ***/,
S_APPL  /*** Cropland ***/,
S_APPL  /*** Crossing  UK - Crossing/Level Crossing ***/,
S_APPL  /*** Culvert ***/,
S_APPL  /*** Curb ***/,
S_APPL  /*** Current Diagram ***/,
S_APPL  /*** Current Flow ***/,
S_APPL  /*** Cut ***/,
S_APPL  /*** Dam/Weir ***/,
S_APPL  /*** Decontamination Pad ***/,
S_APPL  /*** Depot (Storage) ***/,
S_APPL  /*** Depression ***/,
S_APPL  /*** Depth Area ***/,
S_APPL  /*** Depth Contour ***/,
S_APPL  /*** Depth Curve ***/,
S_APPL  /*** Diagnostic Point ***/,
S_APPL  /*** Direction of Lateral Buoyage ***/,
S_APPL  /*** Discolored Water ***/,
S_APPL  /*** Disk/Dish ***/,
S_APPL  /*** Displaced Threshold ***/,
S_APPL  /*** Display Sign ***/,
S_APPL  /*** Disposal Site/Waste Pile ***/,
S_APPL  /*** Distance Mark ***/,
S_APPL  /*** Ditch ***/,
S_APPL  /*** Dolphin ***/,
S_APPL  /*** Dragon Teeth ***/,
S_APPL  /*** Dredge/Powershovel/Dragline ***/,
S_APPL  /*** Drive In Theater ***/,
S_APPL  /*** Drive In Theater Screen ***/,
S_APPL  /*** Drop Gate/Rolling Block ***/,
S_APPL  /*** Drydock ***/,
S_APPL  /*** Early Warning Radar Site ***/,
S_APPL  /*** Eddies ***/,
S_APPL  /*** Embankment/Fill ***/,
S_APPL  /*** Engine Test Cell ***/,
S_APPL  /*** Entrance/Exit ***/,
S_APPL  /*** Esker ***/,
S_APPL  /*** Fairgrounds ***/,
S_APPL  /*** Fault ***/,
S_APPL  /*** Feed Lot/Stockyard/Holding Pen ***/,
S_APPL  /*** Fence ***/,
S_APPL  /*** Ferry Crossing ***/,
S_APPL  /*** Ferry Site ***/,
S_APPL  /*** Filtration Beds/Aeration Beds ***/,
S_APPL  /*** Fire Hydrant ***/,
S_APPL  /*** Firing Range/Gunnery Range ***/,
S_APPL  /*** Fish Hatchery/Fish Farm/Marine Farm ***/,
S_APPL  /*** Fish Stakes ***/,
S_APPL  /*** Fish Traps/Fish Weirs ***/,
S_APPL  /*** Fishing Harbor ***/,
S_APPL  /*** Fishing Pier/Promenade Pier ***/,
S_APPL  /*** Flagstaff/Flagpole ***/,
S_APPL  /*** Flare Pipe ***/,
S_APPL  /*** Flight of Steps ***/,
S_APPL  /*** Flood Barrage ***/,
S_APPL  /*** Flume ***/,
S_APPL  /*** Fog Signal ***/,
S_APPL  /*** Ford ***/,
S_APPL  /*** Foreshore (Precise IHO) ***/,
S_APPL  /*** Fortification ***/,
S_APPL  /*** Foul Ground ***/,
S_APPL  /*** Fountain ***/,
S_APPL  /*** Gallery ***/,
S_APPL  /*** Gantry ***/,
S_APPL  /*** Gate ***/,
S_APPL  /*** Gate (Nautical) ***/,
S_APPL  /*** Gauging Station ***/,
S_APPL  /*** General Miscellaneous Feature ***/,
S_APPL  /*** Geodetic Point ***/,
S_APPL  /*** Geographic Information Point ***/,
S_APPL  /*** Geomorphic Line ***/,
S_APPL  /*** Geomorphic Location ***/,
S_APPL  /*** Geophysical Prospecting Grid ***/,
S_APPL  /*** Geothermal Feature ***/,
S_APPL  /*** Glacier ***/,
S_APPL  /*** Golf Course ***/,
S_APPL  /*** Golf Driving Range ***/,
S_APPL  /*** Grain Bin/Silo ***/,
S_APPL  /*** Grain Elevator ***/,
S_APPL  /*** Grandstand ***/,
S_APPL  /*** Grassland ***/,
S_APPL  /*** Gridiron ***/,
S_APPL  /*** Groin ***/,
S_APPL  /*** Ground Surface Element ***/,
S_APPL  /*** Gully/Gorge ***/,
S_APPL  /*** Harbor ***/,
S_APPL  /*** Hedgerow ***/,
S_APPL  /*** Helicopter Landing Pad ***/,
S_APPL  /*** Heliport ***/,
S_APPL  /*** Homogeneous Aggregate Feature ***/,
S_APPL  /*** Homogeneous Radar Significant Area ***/,
S_APPL  /*** Hopper ***/,
S_APPL  /*** Hops ***/,
S_APPL  /*** Hull Integrity Test Area ***/,
S_APPL  /*** Hull Integrity Test Site ***/,
S_APPL  /*** Hull Integrity Test Site Bottom Feature ***/,
S_APPL  /*** Hummock ***/,
S_APPL  /*** Hut ***/,
S_APPL  /*** Ice Cliff ***/,
S_APPL  /*** Ice Peak/Nunatak ***/,
S_APPL  /*** Ice Shelf ***/,
S_APPL  /*** Inland Shoreline ***/,
S_APPL  /*** Inland Water ***/,
S_APPL  /*** Inland Water Elevation ***/,
S_APPL  /*** INS Alignment Pad ***/,
S_APPL  /*** Interchange ***/,
S_APPL  /*** International Date Line ***/,
S_APPL  /*** Island ***/,
S_APPL  /*** Isogonic Lines ***/,
S_APPL  /*** Jetty ***/,
S_APPL  /*** Kelp/Seaweed ***/,
S_APPL  /*** Lagoon/Reef Pool ***/,
S_APPL  /*** Lake/Pond ***/,
S_APPL  /*** Land devoid of vegetation ***/,
S_APPL  /*** Land Subject to Inundation ***/,
S_APPL  /*** Landing Place ***/,
S_APPL  /*** Landing Stairs ***/,
S_APPL  /*** Landslide ***/,
S_APPL  /*** Launch Pad ***/,
S_APPL  /*** Lead Radial ***/,
S_APPL  /*** Leading Line ***/,
S_APPL  /*** Light ***/,
S_APPL  /*** Light Sector ***/,
S_APPL  /*** Light Standard/Light Support ***/,
S_APPL  /*** Light Vessel/Lightship ***/,
S_APPL  /*** Lighthouse ***/,
S_APPL  /*** Lock ***/,
S_APPL  /*** Log Boom/Booming Ground ***/,
S_APPL  /*** Logging Area ***/,
S_APPL  /*** Magnetic Disturbance Area ***/,
S_APPL  /*** Magnetic Station ***/,
S_APPL  /*** Manhole Cover ***/,
S_APPL  /*** Maritime Area ***/,
S_APPL  /*** Maritime Limit Boundary ***/,
S_APPL  /*** Maritime Station/Maritime Signal Station ***/,
S_APPL  /*** Marker ***/,
S_APPL  /*** Marsh ***/,
S_APPL  /*** Measured Distance Line ***/,
S_APPL  /*** Military Base ***/,
S_APPL  /*** Mine ***/,
S_APPL  /*** Mine-Naval ***/,
S_APPL  /*** Mineral Pile ***/,
S_APPL  /*** Miscellaneous Air Obstruction ***/,
S_APPL  /*** Miscellaneous Obstacle ***/,
S_APPL  /*** Miscellaneous Surface Drainage Feature ***/,
S_APPL  /*** Miscellaneous Underwater Feature ***/,
S_APPL  /*** Miscellaneous Vegetation ***/,
S_APPL  /*** Missile Site ***/,
S_APPL  /*** Moat ***/,
S_APPL  /*** Mobile Home/Mobile Home Park ***/,
S_APPL  /*** Mole ***/,
S_APPL  /*** Monument ***/,
S_APPL  /*** Mooring Mast ***/,
S_APPL  /*** Mooring Ring ***/,
S_APPL  /*** Moraine ***/,
S_APPL  /*** Mountain Pass ***/,
S_APPL  /*** Named Location ***/,
S_APPL  /*** Native Settlement ***/,
S_APPL  /*** NAVAIDS (Aeronautical) ***/,
S_APPL  /*** Nearshore (Precise IHO) ***/,
S_APPL  /*** Non- Site 30 Data Element ***/,
S_APPL  /*** Nursery ***/,
S_APPL  /*** Oasis ***/,
S_APPL  /*** Off Route Radial/Bearing ***/,
S_APPL  /*** Offshore Loading Facility ***/,
S_APPL  /*** Oil/Gas Facilities ***/,
S_APPL  /*** Oil/Gas Field ***/,
S_APPL  /*** Orchard/Plantation ***/,
S_APPL  /*** Overfalls/Tide Rips ***/,
S_APPL  /*** Overhang (Storefront) ***/,
S_APPL  /*** Overhead Obstruction Location ***/,
S_APPL  /*** Overhead Walkway ***/,
S_APPL  /*** Overrun/Stopway ***/,
S_APPL  /*** Oyster Bed/Mussel Bed ***/,
S_APPL  /*** Pack Ice ***/,
S_APPL  /*** Parcel ***/,
S_APPL  /*** Park ***/,
S_APPL  /*** Park Bench ***/,
S_APPL  /*** Particle Accelerator ***/,
S_APPL  /*** Penstock ***/,
S_APPL  /*** Perches/Stakes ***/,
S_APPL  /*** Picnic Table ***/,
S_APPL  /*** Pier/Wharf/Quay ***/,
S_APPL  /*** Pile/Piling/Post ***/,
S_APPL  /*** Pipeline Or Pipe Crossing Point ***/,
S_APPL  /*** Pipeline/Pipe ***/,
S_APPL  /*** Planter ***/,
S_APPL  /*** Platform ***/,
S_APPL  /*** Plaza/City Square ***/,
S_APPL  /*** Point of Change ***/,
S_APPL  /*** Polar Ice ***/,
S_APPL  /*** Power Plant ***/,
S_APPL  /*** Power Transmission Line ***/,
S_APPL  /*** Power Transmission Pylon ***/,
S_APPL  /*** Precise Radar Significant Location ***/,
S_APPL  /*** Prepared Raft or Float Bridge Site ***/,
S_APPL  /*** Processing/Treatment Plant ***/,
S_APPL  /*** Pumping Station ***/,
S_APPL  /*** Quarry ***/,
S_APPL  /*** Quarry/Mine Shear Wall ***/,
S_APPL  /*** Race Track ***/,
S_APPL  /*** Radar Reference Line ***/,
S_APPL  /*** Radar Transmitter ***/,
S_APPL  /*** Railroad ***/,
S_APPL  /*** Railroad Siding/Railroad Spur ***/,
S_APPL  /*** Railroad Turntable ***/,
S_APPL  /*** Railroad Yard/Marshalling Yard ***/,
S_APPL  /*** Ramp ***/,
S_APPL  /*** Ramp (Maritime) ***/,
S_APPL  /*** Range Centerline ***/,
S_APPL  /*** Rapids ***/,
S_APPL  /*** Reef ***/,
S_APPL  /*** Reservoir ***/,
S_APPL  /*** Restricted Area ***/,
S_APPL  /*** Revetment (Airfield/Equipment/Facilities ) ***/,
S_APPL  /*** Rice Field ***/,
S_APPL  /*** Ridge Line ***/,
S_APPL  /*** Rig/Superstructure ***/,
S_APPL  /*** Rip Rap ***/,
S_APPL  /*** River/Stream ***/,
S_APPL  /*** River/Stream Vanishing Point ***/,
S_APPL  /*** Road ***/,
S_APPL  /*** Rock ***/,
S_APPL  /*** Rock Strata/Rock Formation ***/,
S_APPL  /*** Route (Air) ***/,
S_APPL  /*** Route (Maritime) ***/,
S_APPL  /*** Route Marker ***/,
S_APPL  /*** Ruins ***/,
S_APPL  /*** Runway ***/,
S_APPL  /*** Runway Radar Reflector ***/,
S_APPL  /*** Safety Fairway ***/,
S_APPL  /*** Salt Evaporator ***/,
S_APPL  /*** Salt Pan ***/,
S_APPL  /*** Sand Dune/Sand Hills ***/,
S_APPL  /*** Scrub/Brush/Bush ***/,
S_APPL  /*** Seaplane Base ***/,
S_APPL  /*** Seaplane Landing/Seaplane Take-Off Area ***/,
S_APPL  /*** Seawall ***/,
S_APPL  /*** Sebkha ***/,
S_APPL  /*** Settlement ***/,
S_APPL  /*** Settling Basin/Sludge Pond ***/,
S_APPL  /*** Shanty Town ***/,
S_APPL  /*** Sharp Curve(s) ***/,
S_APPL  /*** Shed ***/,
S_APPL  /*** Shoreline ***/,
S_APPL  /*** Shoulder ***/,
S_APPL  /*** Side Scan Sonar Coverage ***/,
S_APPL  /*** Sidewalk ***/,
S_APPL  /*** Ski Jump ***/,
S_APPL  /*** Slipway/Patent Slip ***/,
S_APPL  /*** Slope Polygon ***/,
S_APPL  /*** Sluice Gate ***/,
S_APPL  /*** Snags/Stumps ***/,
S_APPL  /*** Snow Field/Ice Field ***/,
S_APPL  /*** Snow Shed/Rock Shed ***/,
S_APPL  /*** Solar Panels ***/,
S_APPL  /*** Sounding ***/,
S_APPL  /*** Special Area ***/,
S_APPL  /*** Special Use Airspace ***/,
S_APPL  /*** Spillway ***/,
S_APPL  /*** Spot Elevation ***/,
S_APPL  /*** Spring/Water Hole ***/,
S_APPL  /*** Stadium/Amphitheater ***/,
S_APPL  /*** Station (Miscellaneous) ***/,
S_APPL  /*** Statue Pedestal ***/,
S_APPL  /*** Steep Grade ***/,
S_APPL  /*** Storage Bunker/Storage Mound ***/,
S_APPL  /*** Storm Drain ***/,
S_APPL  /*** Street Lights ***/,
S_APPL  /*** Street Sign ***/,
S_APPL  /*** Substation/Transformer Yard ***/,
S_APPL  /*** Subway ***/,
S_APPL  /*** Swamp ***/,
S_APPL  /*** Swept Area ***/,
S_APPL  /*** Swimming Pool ***/,
S_APPL  /*** Tank ***/,
S_APPL  /*** Taxiway ***/,
S_APPL  /*** Telephone Line/Telegraph Line ***/,
S_APPL  /*** Telephone-Telegraph Pylon/Pole ***/,
S_APPL  /*** Tennis Court(s) ***/,
S_APPL  /*** Tent Dwellings ***/,
S_APPL  /*** Test Area ***/,
S_APPL  /*** Text Description ***/,
S_APPL  /*** Theodolite Line ***/,
S_APPL  /*** Tide Data Point ***/,
S_APPL  /*** Tide Gauge ***/,
S_APPL  /*** Timber Yard ***/,
S_APPL  /*** Tower (Non-Communication) ***/,
S_APPL  /*** Track Line ***/,
S_APPL  /*** Track Swath ***/,
S_APPL  /*** Traffic Lights ***/,
S_APPL  /*** Traffic Separation Scheme (TSS) ***/,
S_APPL  /*** Trail ***/,
S_APPL  /*** Training Area ***/,
S_APPL  /*** Trees ***/,
S_APPL  /*** Trench ***/,
S_APPL  /*** Tundra ***/,
S_APPL  /*** Tunnel ***/,
S_APPL  /*** Underground Bunker ***/,
S_APPL  /*** Underground Dwelling ***/,
S_APPL  /*** Underwater Danger/Hazard ***/,
S_APPL  /*** Vehicle Stopping Area/Rest Area ***/,
S_APPL  /*** Vehicle Storage/Parking Area ***/,
S_APPL  /*** Vineyards ***/,
S_APPL  /*** Void Collection Area ***/,
S_APPL  /*** Volcanic Dike ***/,
S_APPL  /*** Volcano ***/,
S_APPL  /*** Wall ***/,
S_APPL  /*** Water (Except Inland) ***/,
S_APPL  /*** Water Intake Tower ***/,
S_APPL  /*** Water Tower ***/,
S_APPL  /*** Water Turbulence ***/,
S_APPL  /*** Waterfall ***/,
S_APPL  /*** Waypoint/Reporting-Calling In Point ***/,
S_APPL  /*** Well ***/,
S_APPL  /*** Wind Indicator ***/,
S_APPL  /*** Windmill ***/,
S_APPL  /*** Windmotor ***/,
S_APPL  /*** Wreck ***/,
S_APPL  /*** Wrecking Yard/Scrap Yard ***/,
S_APPL  /*** Zoo/Safari Park ***/
};

int D4STRATSLEN = sizeof(D4STRATS)/ sizeof(unsigned char);


