/************
The GAIT Tool was developed at the National Geospatial-Intelligence Agency (NGA) in collaboration with the   
Institute for Defense Analyses (IDA) under a Government contract. The government is releasing this software   
to increase the impact of government investments by providing developers with the opportunity to take things   
in new directions. The software use, modification, and distribution rights are stipulated within the MIT license.
As-is warranty is covered within the MIT license but it's re-stated here for clarity: The GAIT tool contains several   
software components. The software is provided "as is," and no warranty, express or implied, including but not limited   
to the implied warranties of merchantability and fitness for particular purpose or arising by statute or otherwise in   
law or from a course of dealing or usage in trade, is made with respect to the accuracy or functioning of the software.   
Neither NGA or IDA are liable for any claims, losses, or damages arising from or connected with the use of the software.   
The user's sole and exclusive remedy is to stop using the software.
************/
#include "share.h"
int FLDB_CLASS_NUM=348;

char *FLDB_class_codes[] = {
"FA001",
"FA000",
"AQ010",
"AQ020",
"GA065",
"GB047",
"GB005",
"GB010",
"GA005",
"GA020",
"AK030",
"AK020",
"BB010",
"AL005",
"GB015",
"BH010",
"FA020",
"ZD003",
"DA005",
"AK040",
"BA022",
"EC010",
"AH010",
"BA050",
"BC010",
"ZB020",
"BB020",
"AC010",
"DB010",
"BH015",
"BB030",
"BF010",
"ZB030",
"BD010",
"BB041",
"AQ040",
"AQ045",
"AQ050",
"AQ055",
"AL015",
"AL018",
"AL020",
"BC020",
"AT005",
"AL025",
"BB050",
"AI030",
"AK060",
"BH020",
"AP010",
"AC020",
"AQ064",
"DB030",
"FA030",
"AL030",
"AF010",
"BI010",
"FA040",
"EC040",
"BA011",
"BA010",
"AT050",
"AT080",
"AL045",
"AQ058",
"CA010",
"ZB035",
"AQ060",
"AF020",
"AF030",
"SA060",
"AF040",
"DB060",
"BD020",
"EA010",
"AQ065",
"BG040",
"BG010",
"DB070",
"BI020",
"FA060",
"FA070",
"AM010",
"DB080",
"BE019",
"BE015",
"BE010",
"ZB040",
"BD030",
"AT010",
"AL050",
"AB000",
"ZB036",
"BH030",
"BB080",
"AL060",
"AF050",
"AK070",
"AK080",
"AQ068",
"BB090",
"AT020",
"BD040",
"DB090",
"AF060",
"AQ090",
"DB100",
"AK090",
"DB110",
"AJ030",
"AL070",
"AQ070",
"AQ080",
"BH040",
"FA015",
"BH050",
"BB100",
"BB110",
"BB105",
"AK190",
"AL073",
"AF070",
"AQ150",
"AQ111",
"BI043",
"BH060",
"BC101",
"BH070",
"BA023",
"AH050",
"BD050",
"BH075",
"AL075",
"AP040",
"BI041",
"ZB060",
"ZD012",
"ZD551",
"ZD550",
"FA090",
"DB115",
"BJ030",
"AK100",
"AM020",
"AM030",
"AK110",
"EB010",
"BB115",
"BB043",
"DA010",
"DB200",
"EA020",
"GB030",
"GB035",
"ZD022",
"AL095",
"AF080",
"EA055",
"BH077",
"AL100",
"BJ040",
"BJ060",
"BJ065",
"BH210",
"BH000",
"CA035",
"AP020",
"FA110",
"BA030",
"BB140",
"BD060",
"BH190",
"BH080",
"EE020",
"BH090",
"BB150",
"BB151",
"BC100",
"BC040",
"BC060",
"AL110",
"BC070",
"BC050",
"BI030",
"BD071",
"ZC040",
"FA050",
"FC031",
"FC021",
"BB155",
"BC055",
"ED010",
"FC100",
"SU001",
"AA010",
"AM040",
"ZD512",
"AL506",
"DB145",
"BH200",
"BD005",
"EE000",
"AL120",
"BH100",
"AI020",
"AL130",
"AQ110",
"BB160",
"BJ020",
"DB150",
"ZD040",
"AL135",
"GA035",
"BA021",
"EA030",
"EC020",
"BB170",
"AC040",
"AA052",
"EA040",
"BD080",
"AL155",
"GB045",
"BB180",
"BJ070",
"AK120",
"AL140",
"BH110",
"BC080",
"BB190",
"BD100",
"AQ113",
"AL165",
"BD110",
"AL170",
"ZD015",
"BJ080",
"AD010",
"AT030",
"AT040",
"ZB070",
"ZM000",
"AC000",
"AQ116",
"AA012",
"AA011",
"AK130",
"FC130",
"AT045",
"AN010",
"AN050",
"AN075",
"AN060",
"AL195",
"BB220",
"BH120",
"BD120",
"BH130",
"FC036",
"GB050",
"BH135",
"CA020",
"AA040",
"BB225",
"BH140",
"BH145",
"AP030",
"BD130",
"DB160",
"FC165",
"AQ119",
"AL200",
"GB055",
"GB060",
"FC170",
"BH155",
"BH150",
"DB170",
"AB010",
"EB020",
"GB065",
"GB070",
"BB230",
"BH160",
"AL105",
"AC030",
"AL208",
"AL019",
"BA024",
"AK150",
"BB240",
"SA050",
"BI040",
"BD140",
"BJ100",
"AL210",
"AD020",
"BE020",
"AL215",
"BH165",
"CA030",
"BH170",
"AK160",
"AQ125",
"AQ120",
"AM060",
"AQ162",
"AD030",
"SU002",
"ED020",
"FC177",
"AK170",
"AM070",
"GB075",
"AT060",
"AT070",
"AL209",
"ZD045",
"BG030",
"BG020",
"AL240",
"BE040",
"FC041",
"AP050",
"EC030",
"BJ110",
"AQ130",
"AH060",
"AL250",
"BD000",
"AQ118",
"AQ135",
"AQ140",
"EA050",
"ZD020",
"DB190",
"DB180",
"AL260",
"BA040",
"BI050",
"AM080",
"BH180",
"AA050",
"AJ050",
"AJ051",
"BD180",
"FA170",
"AK180"
};

char *FLDB_class_names[] = {
"Administrative Area",
"Administrative Boundary",
"Aerial Cableway Lines/Ski Lift Lines",
"Aerial Cableway Pylon/Ski Pylon",
"Air Warning Light",
"Aircraft Facility Reference Point",
"Airport/Airfield",
"Airport Lighting",
"Airspace",
"Airspace Boundary Segment",
"Amusement Park",
"Amusement Park Attraction",
"Anchorage",
"Animal Sanctuary",
"Apron/Hardstand",
"Aqueduct",
"Armistice Line",
"Artifact Location",
"Asphalt Lake",
"Athletic Field",
"Backshore (Precise IHO)",
"Bamboo/Cane",
"Bastion/Rampart/Fortification",
"Beach",
"Beacon",
"Benchmark",
"Berth",
"Blast Furnace",
"Bluff/Cliff/Escarpment",
"Bog",
"Bollard",
"Bottom Characteristics",
"Boundary Monument",
"Breakers",
"Breakwater",
"Bridge/Overpass/Viaduct",
"Bridge Span",
"Bridge Superstructure",
"Bridge Tower/Bridge Pylon",
"Building",
"Building Superstructure Addition",
"Built-Up Area",
"Buoy",
"Cable",
"Cairn",
"Calling-In Point",
"Camp",
"Campground/Campsite",
"Canal",
"Cart Track",
"Catalytic Cracker",
"Causeway",
"Cave",
"Cease Fire Line",
"Cemetery",
"Chimney/Smokestack",
"Cistern",
"Claim Line",
"Cleared Way/Cut Line/Firebreak",
"Coastline",
"Coastline/Shoreline",
"Communication Building",
"Communication Tower",
"Complex Outline",
"Constriction/Expansion",
"Contour Line (Land)",
"Control Point/Control Station",
"Control Tower",
"Conveyor",
"Cooling Tower",
"Covered Drainage",
"Crane",
"Crevice/Crevasse",
"Crib",
"Cropland",
"Culvert",
"Current Diagram",
"Current Flow",
"Cut",
"Dam/Weir",
"Defact Boundary",
"Demilitarized Zone",
"Depot (Storage)",
"Depression",
"Depth Area",
"Depth Contour",
"Depth Curve",
"Diagnostic Point",
"Discolored Water",
"Disk/Dish",
"Display Sign",
"Disposal Site/Waste Pile",
"Distance Mark",
"Ditch",
"Dolphin",
"Dragon Teeth",
"Dredge/Powershovel/Dragline",
"Drive In Theater",
"Drive In Theater Screen",
"Drop Gate/Rolling Block",
"Drydock",
"Early Warning Radar Site",
"Eddies",
"Embankment/Fill",
"Engine Test Cell",
"Entrance/Exit",
"Esker",
"Fairgrounds",
"Fault",
"Feed Lot/Stockyard/Holding Pen",
"Fence",
"Ferry Crossing",
"Ferry Site",
"Filtration Beds/Aeration Beds",
"Firing Range/Gunnery Range",
"Fish Hatchery/Fish Farm/Marine Farm",
"Fish Stakes",
"Fish Traps/Fish Weirs",
"Fishing Harbor",
"Fishing Pier/Promenade Pier",
"Flagstaff/Flagpole",
"Flare Pipe",
"Flight of Steps",
"Prepared Raft or Float Bridge Site",
"Flood Barrage",
"Flume",
"Fog Signal",
"Ford",
"Foreshore (Precise IHO)",
"Fortification",
"Foul Ground",
"Fountain",
"Gallery",
"Gate",
"Gate (Nautical)",
"Geodetic Point",
"Geographic Information Point",
"Geomorphic Line",
"Geomorphic Location",
"Geophysical Prospecting Grid",
"Geothermal Feature",
"Glacier",
"Golf Course",
"Grain Bin/Silo",
"Grain Elevator",
"Grandstand",
"Grassland",
"Gridiron",
"Groin",
"Ground Surface Element",
"Gully/Gorge",
"Hedgerow",
"Helicopter Landing Pad",
"Heliport",
"Homogeneous Aggregate Feature",
"Homogeneous Radar Significant Area",
"Hopper",
"Hops",
"Hummock",
"Hut",
"Ice Cliff",
"Ice Peak/Nunatak",
"Ice Shelf",
"Inland Shoreline",
"Inland Water",
"Inland Water Elevation",
"Interchange",
"International Date Line",
"Island",
"Jetty",
"Kelp/Seaweed",
"Lagoon/Reef Pool",
"Lake/Pond",
"Land devoid of vegetation",
"Land Subject to Inundation",
"Landing Place",
"Landing Stairs",
"Leading Line",
"Light",
"Light Sector",
"Light Standard/Light Support",
"Light Vessel/Lightship",
"Lighthouse",
"Lock",
"Log Boom/Booming Ground",
"Magnetic Disturbance Area",
"Mandate Line / Convention Line",
"Maritime Area",
"Maritime Limit Boundary",
"Maritime Station/Maritime Signal Station",
"Marker",
"Marsh",
"Measured Distance Line",
"Military Base",
"Mine",
"Mineral Pile",
"Miscellaneous Cultural Feature",
"Miscellaneous Feature",
"Miscellaneous Obstacle",
"Miscellaneous Surface Drainage Feature",
"Miscellaneous Underwater Feature",
"Miscellaneous Vegetation",
"Missile Site",
"Moat",
"Mobile Home/Mobile Home Park",
"Monument",
"Mooring Mast",
"Mooring Ring",
"Moraine",
"Mountain Pass",
"Named Location",
"Native Settlement",
"NAVAIDS (Aeronautical)",
"Nearshore (Precise IHO)",
"Nursery",
"Oasis",
"Offshore Loading Facility",
"Oil/Gas Facilities",
"Oil/Gas Field",
"Orchard/Plantation",
"Overfalls/Tide Rips",
"Overhead Obstruction Location",
"Overrun/Stopway",
"Oyster Bed/Mussel Bed",
"Pack Ice",
"Park",
"Particle Accelerator",
"Penstock",
"Perches/Stakes",
"Pier/Wharf/Quay",
"Pile/Piling/Post",
"Pipeline/Pipe",
"Pipeline Or Pipe Crossing Point",
"Platform",
"Plaza/City Square",
"Point of Change",
"Polar Ice",
"Power Plant",
"Power Transmission Line",
"Power Transmission Pylon",
"Precise Radar Significant Location",
"Process MBR Feature",
"Processing/Treatment Plant",
"Pumping Station",
"Quarry",
"Quarry/Mine Shear Wall",
"Race Track",
"Radar Reference Line",
"Radar Transmitter",
"Railroad",
"Railroad Siding/Railroad Spur",
"Railroad Turntable",
"Railroad Yard/Marshalling Yard",
"Ramp",
"Ramp (Maritime)",
"Rapids",
"Reef",
"Reservoir",
"Restricted Area",
"Revetment (Airfield/Equipment/Facilities )",
"Rice Field",
"Ridge Line",
"Rig/Superstructure",
"Rip Rap",
"River/Stream",
"River/Stream Vanishing Point",
"Road",
"Rock",
"Rock Strata/Rock Formation",
"Route (Maritime)",
"Route Marker",
"Ruins",
"Runway",
"Runway Radar Reflector",
"Safety Fairway",
"Salt Evaporator",
"Salt Pan",
"Sand Dune/Sand Hills",
"Wrecking Yard/Scrap Yard",
"Scrub/Brush/Bush",
"Seaplane Base",
"Seaplane Landing/Seaplane Take-Off Area",
"Seawall",
"Sebkha",
"Settlement",
"Settling Basin/Sludge Pond",
"Shanty Town",
"Shed",
"Shoreline",
"Ski Jump",
"Slipway/Patent Slip",
"Slope Polygon",
"Sluice Gate",
"Snags/Stumps",
"Snow Field/Ice Field",
"Snow Shed/Rock Shed",
"Solar Panels",
"Sounding",
"Special Area",
"Spillway",
"Spot Elevation",
"Spring/Water Hole",
"Stadium/Amphitheater",
"Station (Miscellaneous)",
"Steep Grade",
"Storage Bunker/Storage Mound",
"Street Sign",
"Substation/Transformer Yard",
"Subway",
"Swamp",
"Swept Area",
"Swimming Pool",
"Tank",
"Taxiway",
"Telephone Line/Telegraph Line",
"Telephone-Telegraph Pylon/Pole",
"Tent Dwellings",
"Text Description",
"Tide Data Point",
"Tide Gauge",
"Tower (Non-Communication)",
"Track Line",
"Traffic Separation Scheme (TSS)",
"Trail",
"Trees",
"Tundra",
"Tunnel",
"Underground Bunker",
"Underground Dwelling",
"Underwater Danger/Hazard",
"Sharp Curve(s)",
"Vehicle Stopping Area/Rest Area",
"Vehicle Storage/Parking Area",
"Vineyards",
"Void Collection Area",
"Volcanic Dike",
"Volcano",
"Wall",
"Water (Except Inland)",
"Water Intake Tower",
"Water Tower",
"Waterfall",
"Well",
"Windmill",
"Windmotor",
"Wreck",
"Zone Of Occupation",
"Zoo/Safari Park"
};

char *FLDB_class_defns[] = {
"An area controlled by administrative authority.",
"A line of demarcation between controlled areas.",
"Cables which are strung between elevated supports as part of a conveyor system on which cars, buckets, or other carrier units are suspended.  (See also AF020)",
"A tower supporting steel cables which convey cars, buckets, or other suspended carrier units.",
"A light or lights marking an obstacle which constitutes a danger to air navigation.",
"The Functional Center Of The Aircraft Facilities Landing Area(s) And/Or Runway(s) As Determined By Reference To ADSOP C8321.1.",
"A defined area of land or water used for landing, take-off, and movement of aircraft including associated buildings and facilities.",
"Lights used to: define and outline perimeters, runways, taxiways, etc.; guide aircraft while on the ground, and to provide guidance to aircraft on approach for landing.",
"Designated airspace within which some or all aircraft may be subjected to air traffic control.",
"Single segment of an Airspace (GA005).",
"A predominantly man-made facility equipped with recreational devices.  (See also AK090 and AK120)",
"A large structure located in an Amusement Park.",
"An area of water where vessels anchor or may anchor.",
"A natural area set aside for the preservation and protection of wildlife.",
"A defined paved or hard-packed area at an airport or heliport intended for aircraft parking.",
"A pipe or artificial channel designed to transport water from a remote source, usually by gravity.  (See also BH110)",
"A line established by opposing political groups as a result of cessation of hostilities.",
"An indicator which identifies incomplete or illogical data at a specific location (node), used for data processing only.",
"A natural pool of liquid asphalt.",
"An open area where sporting events, exercises, or games occur.",
"Area between the normal limit of wave action above either Mean High Water Springs (MHWS) or Mean High High Water (MHHW) as defined by the National Authority and the maximum limit of wave action.  (See also BA020, BA021, and BA023)",
"Woody, treelike grass.",
"A defensive wall built to defend a fort or other defensive work and sometimes equipped with guns.",
"The shore of the sea or lake, sandy or pebbly, brought up by the waves (including the foreshore area).  (See also BA020, BA021, BA022 and BA023)",
"A fixed visual or electronic aid to navigation.",
"A reference mark on a permanent object indicating elevation relative to an established datum.",
"The place where a ship lies when secured to a pier, wharf, dolphin(s) or dock.  It may be a designated place away from the coast line.",
"A heat chamber used for smelting iron ore.",
"A steep, vertical, or overhanging face of rock or earth.  (See also DB110)",
"A poorly drained or periodically flooded area, excluding tidal waters, with soil rich in plant residue.",
"A post on a wharf used for fastening mooring lines.",
"Designations used on surveys and charts to indicate the consistency, color, and classification of the sea floor, as determined by sampling methods.",
"A marker identifying the location of a surveyed boundary line.",
"Waves which break over off-lying shoals or near the shore.  (See also BD080)",
"A structure which protects a shore area, harbor, anchorage, or basin from sea waves or swells by preventing them from reaching the protected area or reducing their magnitude.  (See also BB140 and BB042)",
"A man-made structure spanning and providing passage over a body of water, depression, or other obstacles.",
"A section of the bridge deck between successive supports such as pillars, piers, or abutments.",
"Those elements of the bridge structure which are above the lowest deck.  (See also AQ055)",
"A tower or pylon from which a bridge's deck is suspended.",
"A relatively permanent structure, roofed and usually walled and designed for some particular use.  (See also AL100)",
"A supplemental portion of a building which rises from the roof but is not considered to be part of the general roof line.",
"An area containing a concentration of buildings and other structures.",
"A floating object, other than a lightship, moored or anchored to the bottom and serving as an aid to navigation.",
"An insulated wire, or group of wires formed into one continuous strand, located underground or underwater.  (See also AT006, AT030  and AT060)",
"A heap of stones piled up as a memorial or a landmark.  (See also AL090 and AL130)",
"A specified point some distance from the harbor at which a vessel's navigator notifies the harbor authority of his ship's position.  (Note that this is not the same as GA055 which is for aircraft only).",
"A place where tents or buildings serve as temporary residence for members of an organization.",
"A location for camping.  (See also AI020 and AQ140)",
"A man-made or improved natural waterway used for transportation.",
"An unimproved roadway.",
"A unit in which petroleum separation is carried out in the presence of a catalyst.",
"A raised roadway of solid structure built primarily to provide a route across wet ground or intertidal area.",
"A natural subterranean chamber or series of chambers open to the Earth's surface.",
"A line along which active hostilities are suspended.",
"An area of land for burying the dead.",
"A vertical structure containing a passage or flue for discharging smoke and gases of combustion.",
"A man-made container used for collection or storage of rain water.",
"A limit of an area which is unilaterally claimed by one political group without consent or negotiation with another.",
"A man-made clearing in a cultural area or through a stand of trees, designed to provide access for a road, railroad, pipeline, or power transmission line, or for boundary demarcation, survey line-of-sight, or to impede the progress of forest fires.",
"A line generally following the contact between a land mass and a body of water,  based on the low water line, and used as a reference for measuring international boundaries such as Territorial Limits or Exclusive Economic Zone (EEZ).",
"The line where a land mass is in contact with a body of water.",
"A building in which communication signals are processed or controlled.",
"A relatively tall structure used for transmitting and/or receiving electronic communication signals.  (See also AQ060)",
"An outline delimiting an area in which two or more like features have the same function.",
"A point where a passage way narrows or expands beyond its normal width.",
"A line connecting points having the same vertical datum value.",
"An object or mark on the ground of known position, elevation, or both.",
"A tower-like structure that houses the persons and equipment used to control the flow of air, rail, or marine traffic.  (See also AL240)",
"An apparatus for moving materials from place to place on a moving belt or series of rollers.",
"A tower used to cool liquids.",
"A natural watercourse or man-made waterway that is covered preventing its observation or further classification.",
"A machine for lifting, shifting, and lowering objects or materials by means of a swinging boom or with the lifting apparatus supported on an overhead track.",
"A narrow fissure, crack, or rift in the Earth's surface, snow or ice.",
"A framework structure submerged or above water used to support pipelines, sewer lines, or outfalls.",
"An area that has been tilled for the planting of crops.  (See also EA040, EA050, and EA055)",
"A sewer or drain crossing under a road, track, or embankment, without affecting the construction of the crossed feature.",
"A graph or chartlet showing the average speed of the flood and ebb currents at different periods of the current cycle.",
"The flow direction of a current.",
"An excavation of the Earth's surface to provide passage for a road, railroad, canal, etc.",
"A permanent barrier across a watercourse used to impound water or to control its flow.  (See also BI040)",
"An existing line of separation not officially recognized by various governments.",
"An area where military activity is prohibited.",
"An area used for the storage of products or supplies.  (See also AB000)",
"A low area surrounded by higher ground.",
"Water area containing soundings within a defined range of values permanently at or below sounding datum.",
"A line connecting points of equal depth at and below the hydrographic datum.",
"A navigational safety line indicating that no sounding of a lesser depth exists seaward of the line, but greater depths may occur on the shallow side of the line.",
"A point used to check system accuracy.",
"An area of sea water having a color distinctly different from the surrounding water.",
"A concave object used for transmitting or receiving electronic signals.",
"An upright panel used to convey visual information.  (See also AL080)",
"A site for the collecting/depositing of refuse or discarded material.  (See also AB010, AM010 and AM040)",
"A mark which indicates the value of distance measured from an origin and consists of either a solid visible structure or a distinct location without special installation.",
"A channel constructed for the purpose of irrigation or drainage.",
"A post or group of posts used for mooring, warping a ship or as an aid to navigation.",
"Regularly spaced concrete or metal barriers laid in single or multiple rows to prevent vehicle movement.",
"An excavating machine for removing earth or materials.",
"A place where motion pictures are shown while viewers remain in their vehicles.",
"A large outdoor screen for showing motion pictures.",
"A massive assemblage of material, usually in the form of concrete logs or blocks, positioned alongside or above a transportation route, ready to be activated as a potential barrier to an advancing enemy ground force, when needed.",
"A structure, providing support for a vessel, which has a means of removing water so that the bottom of the vessel can be exposed.",
"An installation utilizing long range radar to detect approaching aircraft or missiles.",
"Circular movements of water running contrary to the main current.",
"A raised long mound of earth or other material.  (See also BA051)",
"A structure wherein engines are tested.",
"A point of entrance or exit.  (See also AA010 and AQ130)",
"A long, narrow ridge of sand and gravel deposited by a glacial stream.",
"An area where permanent facilities exist to hold outdoor fairs, circuses or exhibitions.  (See also AK030 and AK120)",
"A fracture in the Earth's crust with displacement on one side of the fracture relative to the other.  (See also DB010)",
"An enclosed area in which livestock are temporarily kept.",
"A man-made barrier of relatively light structure used as an enclosure or boundary.  (See also AL260)",
"A route in a body of water where a ferry crosses from one shoreline to another.",
"A point where a ferry takes on or discharges its load.",
"An area containing layers of material used to filter or aerate water.",
"An open area designated for the purpose of discharging or detonating firearms.",
"An enclosure of water used for the breeding and/or rearing of fish.",
"Poles or stakes placed in shallow water to catch fish.",
"A fence or enclosure set in water to catch fish.",
"A harbor which is primarily used by fishing vessels.",
"A structure extending into the water used as a platform for recreational purposes, not intended as a berthing place for vessels.",
"A staff or pole on which a flag is raised.",
"An open-ended pipe at which waste gases are burned.",
"A series of steps or stairs reaching from one level to another.",
"Site on a river or canal which has a ramp, piling, and/or pier structures constructed on one or both shores to allow for suitable future crossing operations using float bridge or rafting equipment.",
"An artificial obstruction placed in a water course to increase the depth or to divert it.",
"An open, inclined channel which carries water for use in such operations as mining or logging.",
"A warning signal transmitted by a vessel, or aid to navigation, during periods of low visibility.  Also, the device producing such a signal.",
"A shallow place in a body of water used as a crossing.  (See also AQ062)",
"Area between the low water line defined by Mean Low Water Springs (MLWS) or Mean Low Low Water (MLLW) as appropriate and the normal limit of wave action above Mean High Water Springs (MHWS) or Mean High High Water (MHHW) as appropriate.  (See also BA020, BA021, and BA022)",
"A facility constructed for the military defense of a site.  (See also AM060)",
"A region of comparatively shallow water strewn with rocks, boulders, coral, wreckage, or other obstructions, making it unsuitable for anchoring, grounding, or ground fishing.",
"An artificial spring with water.",
"A sunken or cut passageway along a transportation route in mountainous regions constructed to protect vehicles from the elements.  A series of openings on one side may be present for light or ventilation.",
"A barrier which controls passage to a road, railroad, tunnel, or bridge.",
"A structure that may be swung, drawn, or lowered to block an entrance or passageway.",
"A physical point on the Earth's surface having a surveyed position (e.g. Trig Points).",
"A location where geographic information or statistics may apply.",
"No definition available",
"No definition available",
"A grid established for the collection of geophysical data within an area.",
"A terrain surface feature controlled by or derived from the heat of the Earth's interior.",
"A large mass of snow and ice moving slowly down a slope or valley from above the snowline.",
"An area of land laid out for the game of golf.",
"An enclosed container, used for storing grain or fodder.  (See also AM011, AM070, and AM080)",
"A tall structure, equipped for loading, unloading, processing and storing grain.",
"A usually roofed structure for special viewing of events and having tiers of seats or standing room for spectators.",
"An area composed of uncultured plants which have little or no woody tissue.",
"A flat frame, usually of parallel timber baulks, erected on the foreshore so that a vessel may dry out on it for painting or repair at low water.",
"A structure which normally projects outward from a shoreline and which protects a beach from erosion by disrupting  the longshore movement of sand and other sediments, not by preventing waves from reaching the shoreline.  (See also BB140 and BB041)",
"The surface soil characteristics of the earth.",
"A long, narrow, deep erosion with steep banks.",
"A continuous growth of shrubbery planted as a fence, a boundary, or a wind break.",
"An improved area used for take-off, and landing, by helicopters and other vertical take-off and landing aircraft.",
"A place designated for the landing and take-off of helicopters, including its buildings and facilities.",
"Two or more like features which are represented as one contiguous aggregate feature: where individual features Included within the aggregate may or may not meet inclusion conditions to be delineated individually.",
"A cluster of structures that combine to form a homogeneous area when grouped according to a common radar reflectance and a common height value.",
"A top-loaded funnel-shaped structure for temporary holding of loose material which will be dispensed from its bottom.",
"An area covered by the systematic planting of hop vines.  (See also EA010, EA040 and EA050)",
"An area of higher elevation within a swamp, bog, or marsh.",
"A small simple or crude house or shelter.  (See also AL015)",
"The vertical face of a glacier or ice shelf.",
"A rocky peak projecting above a surrounding ice field that may be perpetually covered with ice.",
"A sheet of thick ice, with level or undulating surface, attached to the land but mostly afloat which is bounded on the seaward side by an Ice Cliff (BJ040).",
"The land-water boundary for all inland hydrographic features having shorelines, Lake/Pond (BH080), or Island (BA030).",
"Any known inland waterway body, such as: lake/pond, reservoir, river/stream, etc. requiring separation into individual features due to status/type grouping that is currently indeterminable.",
"A location with a generalized elevation value relative to a vertical datum associated with an inland, usually confined, water body.",
"A connection designed to provide traffic access from one road to another.",
"A line generally coinciding with the 180th meridian, modified to avoid land, and designated as the place where each calendar day begins.",
"A land mass smaller than a continent and surrounded by water.",
"A man-made barrier built out into, or in the water, primarily to restrain or direct currents and waves.  (See also AQ030 and BB040)",
"A large seaweed.",
"Open body of water separated from the sea by a sand bank or coral reef.",
"A body of water surrounded by land.  (See also BH130)",
"Ground or land with little (less than 5 percent) or no vegetation.",
"An area periodically covered by flood water, excluding tidal waters.  (See also BH095, ED010, and ED020)",
"A place on shore where landing from the sea is possible.",
"Steps at the shoreline as the connection between land and water on different levels.",
"A track which passes through one or more (usually two) clearly defined objects, along which a vessel can safely travel.",
"A specially constructed device which displays a luminous or lighted aid to navigation.  (See also BC050)",
"A sector defined by bearings from seaward within which a light shows a specified character or color, or is obscured.",
"A structure serving as a support for lighting.",
"A distinctively marked manned vessel anchored or moored at a defined point to serve as an aid to navigation.",
"A distinctive structure exhibiting light(s) designed to serve as an aid to navigation.  (See also BC040)",
"An enclosure with a pair or series of gates used for raising or lowering vessels as they pass from one water level to another.  (See also BI005)",
"A line of connected, floating timbers as across a river or enclosing a water area to keep logs ready for the sawmill from floating away; also, the enclosed area.",
"A localized anomaly in the Earth's magnetic field.",
"A line established to regulate matters between nations or groups over a specific area or territory.",
"An area in which certain activities or factors of significance to navigation and/or operation apply.",
"A line where on either side certain activities or factors of significance to navigation and/or operation apply.",
"A facility occupied by a governmental (maritime related) or harbor authority, providing specific services to vessels.  A signal station is a structure (building, tower, mast, etc.), which conveys information visually from station to ship.",
"A colored (usually white) mark on a cliff, rock, wall, etc. which is a conspicuous landmark for marine navigation.",
"An area of wet, often spongy ground that is subject to frequent or tidal inundations, but not considered to be continually under water.  It is characterized by the growth of non woody plants and by the lack of trees.  (Nautical Chart Manual, US National Oceanic and Atmospheric Administration - NOAA, 1992)  (See also BH090, BH095, and ED020)",
"A course whose length has been accurately measured and is used in conjunction with ranges ashore.  It is used by vessels to calibrate logs, engine revolution counters, etc., and determine speed.",
"A center of operations for a military organization.",
"An excavation made in the earth for the purpose of extracting natural deposits.  (See also AQ090)",
"A man-made heap of mining or quarrying products excluding waste materials.  (See also AB000)",
"No definition available",
"No definition available",
"Obstacle feature which is of a minor nature and which is not covered by another feature coding in this specification.",
"Surface drainage feature which is of a minor nature and which is not included in other feature codings in this specification.",
"An object or area on the sea floor or underwater that is not identified by any other code in this specification. (Also see BD000)",
"A mixture of woody and non-woody vegetation types.",
"An area with related facilities for storing and launching missiles.",
"A trench usually filled with water, that surrounds a body of land.",
"A site for the permanent parking of trailer(s) used as dwellings and designed without a permanent foundation.  (See also AK060 and AQ140)",
"A structure erected or maintained as a memorial to a person or event.  (See also AL025 and AL090)",
"A tower-like structure used to secure an airship.",
"A metal ring attached to a structure and used to secure a vessel.",
"An accumulation of soil and stone debris deposited by a glacier.",
"A natural route through a low place in a mountain range.",
"A geographic place on the earth, not normally appearing as a feature on a map, but having a name that is required to be placed on a map.",
"A concentration of native dwellings, generally of the hut type, which are not usually of substantial construction.",
"Any visual or electronic device which provides point-to-point guidance information or position data.",
"Area between the 10 meter depth curve and the low water line defined by either Mean Low Water Springs (MLWS) or Mean Low Low Water (MLLW) as defined by the National Authority.  (See also BA020, BA022, and BA023)",
"A place where shrubs, flowers, plants and trees are grown for transplanting, seed or grafting.",
"A small, isolated, fertile or green area in a desert region usually having a spring or well.",
"A facility located offshore for loading and unloading cargo.",
"An area involved in the production or distribution of oil or natural gas.",
"An area where oil and/or gas is pumped or otherwise removed from the ground.",
"An area covered by systematic plantings of trees which yield fruits, nuts or other products.  (See also EA010, EA050 and EA055)",
"Short, breaking waves occurring when a current passes over a shoal or other submarine obstruction or meets a contrary current or wind.  Tide rips occur when one or more of the currents are tidal.  (See also BD010)",
"An undelineated obstruction location such as underpasses, overhead pipelines, building overhangs, and other covered traveled ways.",
"An area beyond the take-off runway designated as able to support an airplane during an aborted take-off.",
"A place in shallow water where oysters and mussels breed and may be cultivated.",
"An area of ice formed by the drifting and crushing together of floating pieces of ice.",
"An area used for recreational or ornamental purposes.  (See also AK030, AK090 and AL170)",
"An apparatus for imparting high velocities to charged particles.",
"A pipeline or channel generally used by hydroelectric plants or water mills to transport water by gravity and under pressure.  (See also BH010)",
"A small marker used to identify channels or to mark dangers such as rocks, shoals, etc.  (See also BD100 and BD140)",
"A structure primarily used as berthing places for vessels.",
"A long, heavy timber or section of steel, concrete, etc., forced into the earth to serve as a support, as for a pier.  (See also BC080 and BD140)",
"A tube for the conveyance of solids, liquids or gases.",
"A traversable site extending across a pipeline or pipe that acts as a passageway for cross country movement of vehicles or troops.",
"A flat surface raised above the sea, as a working stage for conducting offshore operations.",
"An open area which serves as a public square in a city or town.  (See also AK120)",
"The location/position on a linear feature where the characteristics of the feature change significantly.",
"The heaviest, thickest form of ice over land or water.  (See also BJ100)",
"The building(s) and equipment necessary for the generation of electric power.  (See also AD020)",
"A system of above ground wires including their supports, which transmits electricity over distance.  (See also AT005, AT006 and AT060)",
"A pylon or pole used to support a power transmission line.",
"A location selected for high radar reflective potential.",
"No definition available",
"A site used for changing or refining a particular material.",
"A facility to move solids, liquids or gases by means of pressure or suction.",
"An excavation created by removal of stone by blasting or cutting.",
"The wall facing of the excavation within a quarry/mine.",
"A course for racing.",
"A line shown on a chart in proximity to a shipping route, along which ships are guided by a traffic control center located in a radar station.  (See also BC032)",
"A device for transmitting and receiving radar emissions.",
"A rail or set of parallel rails on which a train or tram runs.",
"A stretch of railroad tracks connected to the main track by switch(es) - used for temporary storage and loading/unloading.",
"A rotating platform with railroad tracks used for turning locomotives or cars/carriages.",
"A system of tracks within defined limits, and associated features, provided for loading/unloading and assembling trains.",
"An inclined plane usually man-made for moving between two levels.  (See also BB220 and BB240)",
"A partially submerged hard surfaced area on a shoreline for launching and retrieving vessels or vehicles.",
"A place in a stream or river where the current is swift and the surface is usually broken by boulders and rocks.",
"A rocky or coral elevation at or near enough to the surface of the sea to be a danger to surface navigation.",
"A man-made enclosure or area formed for the storage of water.  (See also BH080)",
"An area in which certain aspects of navigation are restricted.",
"A barricade which protects an aircraft, equipment, or facilities from hostile action.",
"An area periodically covered with water used for growing rice.",
"A line representation of a ridge top.",
"A vertical structure fitted for drilling or lifting operations.",
"A loose assemblage of broken stones or similar material erected in water or on soft ground as a foundation or to protect the underlying surface from erosion.",
"A natural flowing watercourse.",
"Point at which a river or stream passes into the ground.",
"An open way maintained for vehicular use.",
"An isolated rocky formation or a single large stone above or below the water surface.",
"A visual topographic outcrop, layers or beds of rock.",
"A track or lane established for the safe passage of ships.",
"An emblem used to designate a road's name or identifying number.",
"The deteriorated remains of an unspecified structure.  (See also AL012)",
"A defined area, usually rectangular, used for the conventional landing and take-off of aircraft.  (Excludes GB045)",
"A device, normally placed near the threshold of a runway, used for reflecting radar signals.",
"A route established for the safe passage of vessels through offshore oil and gas fields and minefields.",
"Shallow pools, normally man-made, used for the natural evaporation of water for the collection of salt.",
"A flat area of natural surface salt deposits.",
"Ridges or hills of sand.",
"An area or site engaged in the wrecking, dismantling, storage, or resale of discarded products.  (See also AB000)",
"Low-growing woody plants.  (See also EC030)",
"An installation supporting aircraft capable of taking off and landing on water.",
"A designated portion of water outlined by visual surface markings, used by seaplanes to land and take off.",
"A structure built to protect the shore from erosion.",
"A natural depression in arid or semi-arid regions whose bed is covered with salt encrusted clayey soil.",
"A concentration of small dwellings.",
"A site where solid matter is precipitated from a liquid by evaporating or settling.",
"A dense concentration of crude, improvised dwellings made from salvaged materials, usually located on the outskirts of cities and having few, if any, streets and no public facilities.",
"A storage facility usually characterized by one or more open sides, support pillars and a roof.",
"A line drawn along the normal limit of wave action above either Mean High Water Springs (MHWS) or Mean High High Water (MHHW) as defined by the National Authority.",
"A ramp used for ski jumping.",
"A prepared slope for launching and recovering vessels.",
"An area enclosing a group of slope values falling within a set range.",
"A gate used to regulate the flow of water.  (See also BI020 and BI039)",
"A stem or a trunk of a tree below the surface of water.  (See also BC080 and BD100)",
"A large area permanently covered by snow or ice over land or water.  (See also BJ080)",
"A shelter build to protect a section of road or railroad from snow/rock slides.",
"Units of solar cells for converting sunlight into electrical energy or heat.  (See also AD010)",
"A measured water depth or spot depth which has been reduced to chart datum.",
"A significant cultural feature area or entity, prominent due to its radar reflecting potential.",
"A passage for surplus water to run over or around a dam.",
"A designated location with an elevation value relative to a vertical datum.",
"A natural outflow of water from below the ground surface.  (See also AA050 and BH075)",
"An arena for holding and viewing events.",
"A stopping place for the transfer of passengers and/or freight.",
"Location along any given traveled way where the percent (%) slope (ratio of change in elevation (vertical distance) to horizontal ground distance multiplied by 100) is high enough to slow, hinder, or even stop movement.",
"A structure which may be covered or surrounded with earth which is resistant to ordnance where materials or products are stored.  (See also AH050)",
"Signs placed along streets for the purpose of regulating the flow of vehicular or pedestrian traffic or providing information.",
"A facility, along a power line route, in which electric current is transformed and/or distributed.",
"An underground, metropolitan electric railway or the tunnel through which it travels.",
"A low lying saturated area covered with water all or most of the year, where accumulating dead vegetation does not rapidly decay.  It can exist on flat-lying areas created by certain geomorphic environments.  The vegetation mainly consists of hydrophytic trees and/or scrubs whose roots are adapted to wet conditions, with an open to very dense canopy closure.  (See also BH090, BH095, and ED010)",
"An area that has been determined to be clear of navigational dangers to a specified depth.",
"A constructed basin used for swimming outdoors.",
"A container used for the storage of liquids or gases.  (See also AM011, AM020, and AM080)",
"A prepared surface providing access to/from runways and the aircraft parking area, terminal area, or service area, etc.",
"A system of above ground wires, including their supports, which transmit electrical signals over distance.  (See also AT005, AT006, and AT030)",
"A pylon or pole used to support a telephone or telegraph line.",
"An encampment of people housed in tents.",
"An area in which a characteristic or an activity pertaining to the area can be described and possibly labeled on a product if deemed important at the time the product is being produced.",
"Place for which tabulated tidal stream data are given.",
"An instrument for measuring the height of the tide.",
"A relatively tall structure which may be used for observation, support, or storage, etc.  (See also AF030, AM080, AQ060, and BI050)",
"The path of travel with respect to the earth as drawn on the chart and including the sounding information collected along the line.",
"A routing measure aimed at the separation of opposing streams of traffic by appropriate means and by the establishment of traffic lanes.",
"A path worn by the passage of people or animals.",
"Woody-perennial plants, having a self-supporting main stem or trunk.  (See also EA040, EB020 and EC015)",
"A prairie-like region in the Arctic and Subarctic zones which sustains a growth of low vegetation.",
"An underground or underwater passage, open at both ends, and usually containing a road or railroad.  (See also AQ090)",
"An underground facility used by the military either for location of command/control centers or for troop encampment.  (See also AL250)",
"Underground living quarters.  (See also AL040)",
"A known underwater object or area, known to be dangerous to surface navigation.",
"A curve which may cause transportation restrictions.",
"A roadside place usually having facilities for people and/or vehicles.",
"An open land area used for storing or parking vehicles or vessels (including recreational vehicles).  (See also AI020 and AK060)",
"An area covered by the systematic planting of grape vines.  (See also EA010, EA040 and EA055)",
"An area lacking suitable source coverage, or where data is not required.",
"A steep ridge of igneous rock.",
"A mountain or hill, often conical, formed around a vent in the earth's crust through which molten rock, ash, or gases are or have been expelled.",
"A solid man-made barrier of heavy material used as an enclosure or boundary or for protection.  (See also AL070)",
"An area of water which normally has tidal fluctuations.",
"A tower-like structure associated with a dam or water source and used for the intake of water.",
"An elevated container and its supporting structure used to hold water.  (See also AM011, AM020, and AM070)",
"A vertical or nearly vertical descent of water.",
"A hole drilled or dug into the earth or sea bed for the extraction of liquids or gases.  (See also BH170)",
"A wind-driven system of vanes attached to a tower like structure (excluding wind-generated power plants).",
"A modern structure used for wind power.",
"The ruined remains of a vessel.",
"An area temporarily held and controlled by a foreign military force.",
"An area with a collection of live animals usually for public display."
};

unsigned char FLDBDOMAINS[]={
0  /*** Dummy Value ***/,
D_BOUN  /*** Administrative Area ***/,
D_BOUN  /*** Administrative Boundary ***/,
D_POPU  /*** Aerial Cableway Lines/Ski Lift Lines ***/,
D_POPU  /*** Aerial Cableway Pylon/Ski Pylon ***/,
D_AERO  /*** Air Warning Light ***/,
D_AERO  /*** Aircraft Facility Reference Point ***/,
D_AERO  /*** Airport/Airfield ***/,
D_AERO  /*** Airport Lighting ***/,
D_AERO  /*** Airspace ***/,
D_AERO  /*** Airspace Boundary Segment ***/,
D_POPU  /*** Amusement Park ***/,
D_POPU  /*** Amusement Park Attraction ***/,
D_OCEN  /*** Anchorage ***/,
D_POPU  /*** Animal Sanctuary ***/,
D_AERO  /*** Apron/Hardstand ***/,
D_INWA  /*** Aqueduct ***/,
D_BOUN  /*** Armistice Line ***/,
D_DAQU  /*** Artifact Location ***/,
D_PHYS  /*** Asphalt Lake ***/,
D_POPU  /*** Athletic Field ***/,
D_PHYS  /*** Backshore (Precise IHO) ***/,
D_VEGE  /*** Bamboo/Cane ***/,
D_DEST  /*** Bastion/Rampart/Fortification ***/,
D_PHYS  /*** Beach ***/,
D_AITO  /*** Beacon ***/,
D_ELEV  /*** Benchmark ***/,
D_POAN  /*** Berth ***/,
D_UTAN  /*** Blast Furnace ***/,
D_PHYS  /*** Bluff/Cliff/Escarpment ***/,
D_VEGE  /*** Bog ***/,
D_POAN  /*** Bollard ***/,
D_PHYS  /*** Bottom Characteristics ***/,
D_BOUN  /*** Boundary Monument ***/,
D_OCEN  /*** Breakers ***/,
D_POAN  /*** Breakwater ***/,
D_GRTR  /*** Bridge/Overpass/Viaduct ***/,
D_GRTR  /*** Bridge Span ***/,
D_GRTR  /*** Bridge Superstructure ***/,
D_GRTR  /*** Bridge Tower/Bridge Pylon ***/,
D_POPU  /*** Building ***/,
D_GRTR  /*** Building Superstructure Addition ***/,
D_POPU  /*** Built-Up Area ***/,
D_AITO  /*** Buoy ***/,
D_UTAN  /*** Cable ***/,
D_BOUN  /*** Cairn ***/,
D_OCEN  /*** Calling-In Point ***/,
D_POAN  /*** Camp ***/,
D_POPU  /*** Campground/Campsite ***/,
D_INWA  /*** Canal ***/,
D_GRTR  /*** Cart Track ***/,
D_UTAN  /*** Catalytic Cracker ***/,
D_GRTR  /*** Causeway ***/,
D_PHYS  /*** Cave ***/,
D_BOUN  /*** Cease Fire Line ***/,
D_POPU  /*** Cemetery ***/,
D_UTAN  /*** Chimney/Smokestack ***/,
D_INWA  /*** Cistern ***/,
D_BOUN  /*** Claim Line ***/,
D_VEGE  /*** Cleared Way/Cut Line/Firebreak ***/,
D_BOUN  /*** Coastline ***/,
D_PHYS  /*** Coastline/Shoreline ***/,
D_UTAN  /*** Communication Building ***/,
D_UTAN  /*** Communication Tower ***/,
D_GENE  /*** Complex Outline ***/,
D_GRTR  /*** Constriction/Expansion ***/,
D_ELEV  /*** Contour Line (Land) ***/,
D_ELEV  /*** Control Point/Control Station ***/,
D_POPU  /*** Control Tower ***/,
D_UTAN  /*** Conveyor ***/,
D_UTAN  /*** Cooling Tower ***/,
D_INWA  /*** Covered Drainage ***/,
D_UTAN  /*** Crane ***/,
D_PHYS  /*** Crevice/Crevasse ***/,
D_OCEN  /*** Crib ***/,
D_VEGE  /*** Cropland ***/,
D_GRTR  /*** Culvert ***/,
D_OCEN  /*** Current Diagram ***/,
D_INWA  /*** Current Flow ***/,
D_PHYS  /*** Cut ***/,
D_INWA  /*** Dam/Weir ***/,
D_BOUN  /*** Defact Boundary ***/,
D_BOUN  /*** Demilitarized Zone ***/,
D_UTAN  /*** Depot (Storage) ***/,
D_PHYS  /*** Depression ***/,
D_OCEN  /*** Depth Area ***/,
D_OCEN  /*** Depth Contour ***/,
D_OCEN  /*** Depth Curve ***/,
D_DAQU  /*** Diagnostic Point ***/,
D_OCEN  /*** Discolored Water ***/,
D_UTAN  /*** Disk/Dish ***/,
D_POPU  /*** Display Sign ***/,
D_UTAN  /*** Disposal Site/Waste Pile ***/,
D_DAQU  /*** Distance Mark ***/,
D_INWA  /*** Ditch ***/,
D_POAN  /*** Dolphin ***/,
D_DEST  /*** Dragon Teeth ***/,
D_UTAN  /*** Dredge/Powershovel/Dragline ***/,
D_POPU  /*** Drive In Theater ***/,
D_POPU  /*** Drive In Theater Screen ***/,
D_GRTR  /*** Drop Gate/Rolling Block ***/,
D_POAN  /*** Drydock ***/,
D_DEST  /*** Early Warning Radar Site ***/,
D_OCEN  /*** Eddies ***/,
D_PHYS  /*** Embankment/Fill ***/,
D_UTAN  /*** Engine Test Cell ***/,
D_GRTR  /*** Entrance/Exit ***/,
D_PHYS  /*** Esker ***/,
D_POPU  /*** Fairgrounds ***/,
D_PHYS  /*** Fault ***/,
D_UTAN  /*** Feed Lot/Stockyard/Holding Pen ***/,
D_POPU  /*** Fence ***/,
D_GRTR  /*** Ferry Crossing ***/,
D_GRTR  /*** Ferry Site ***/,
D_UTAN  /*** Filtration Beds/Aeration Beds ***/,
D_BOUN  /*** Firing Range/Gunnery Range ***/,
D_INWA  /*** Fish Hatchery/Fish Farm/Marine Farm ***/,
D_OCEN  /*** Fish Stakes ***/,
D_OCEN  /*** Fish Traps/Fish Weirs ***/,
D_POAN  /*** Fishing Harbor ***/,
D_POAN  /*** Fishing Pier/Promenade Pier ***/,
D_POPU  /*** Flagstaff/Flagpole ***/,
D_UTAN  /*** Flare Pipe ***/,
D_POPU  /*** Flight of Steps ***/,
D_GRTR  /*** Prepared Raft or Float Bridge Site ***/,
D_POAN  /*** Flood Barrage ***/,
D_UTAN  /*** Flume ***/,
D_AITO  /*** Fog Signal ***/,
D_GRTR  /*** Ford ***/,
D_PHYS  /*** Foreshore (Precise IHO) ***/,
D_DEST  /*** Fortification ***/,
D_OCEN  /*** Foul Ground ***/,
D_POPU  /*** Fountain ***/,
D_GRTR  /*** Gallery ***/,
D_GRTR  /*** Gate ***/,
D_POAN  /*** Gate (Nautical) ***/,
D_ELEV  /*** Geodetic Point ***/,
D_DAQU  /*** Geographic Information Point ***/,
D_DAQU  /*** Geomorphic Line ***/,
D_DAQU  /*** Geomorphic Location ***/,
D_UTAN  /*** Geophysical Prospecting Grid ***/,
D_PHYS  /*** Geothermal Feature ***/,
D_PHYS  /*** Glacier ***/,
D_POPU  /*** Golf Course ***/,
D_UTAN  /*** Grain Bin/Silo ***/,
D_UTAN  /*** Grain Elevator ***/,
D_POPU  /*** Grandstand ***/,
D_VEGE  /*** Grassland ***/,
D_POAN  /*** Gridiron ***/,
D_POAN  /*** Groin ***/,
D_SUMA  /*** Ground Surface Element ***/,
D_PHYS  /*** Gully/Gorge ***/,
D_VEGE  /*** Hedgerow ***/,
D_AERO  /*** Helicopter Landing Pad ***/,
D_AERO  /*** Heliport ***/,
D_GENE  /*** Homogeneous Aggregate Feature ***/,
D_POPU  /*** Homogeneous Radar Significant Area ***/,
D_UTAN  /*** Hopper ***/,
D_VEGE  /*** Hops ***/,
D_VEGE  /*** Hummock ***/,
D_POPU  /*** Hut ***/,
D_PHYS  /*** Ice Cliff ***/,
D_PHYS  /*** Ice Peak/Nunatak ***/,
D_PHYS  /*** Ice Shelf ***/,
D_PHYS  /*** Inland Shoreline ***/,
D_INWA  /*** Inland Water ***/,
D_ELEV  /*** Inland Water Elevation ***/,
D_GRTR  /*** Interchange ***/,
D_BOUN  /*** International Date Line ***/,
D_PHYS  /*** Island ***/,
D_POAN  /*** Jetty ***/,
D_OCEN  /*** Kelp/Seaweed ***/,
D_OCEN  /*** Lagoon/Reef Pool ***/,
D_INWA  /*** Lake/Pond ***/,
D_VEGE  /*** Land devoid of vegetation ***/,
D_INWA  /*** Land Subject to Inundation ***/,
D_POAN  /*** Landing Place ***/,
D_POAN  /*** Landing Stairs ***/,
D_AITO  /*** Leading Line ***/,
D_AITO  /*** Light ***/,
D_AITO  /*** Light Sector ***/,
D_POPU  /*** Light Standard/Light Support ***/,
D_AITO  /*** Light Vessel/Lightship ***/,
D_AITO  /*** Lighthouse ***/,
D_INWA  /*** Lock ***/,
D_UTAN  /*** Log Boom/Booming Ground ***/,
D_PHYS  /*** Magnetic Disturbance Area ***/,
D_BOUN  /*** Mandate Line / Convention Line ***/,
D_MALI  /*** Maritime Area ***/,
D_MALI  /*** Maritime Limit Boundary ***/,
D_POAN  /*** Maritime Station/Maritime Signal Station ***/,
D_AITO  /*** Marker ***/,
D_VEGE  /*** Marsh ***/,
D_BOUN  /*** Measured Distance Line ***/,
D_DEST  /*** Military Base ***/,
D_UTAN  /*** Mine ***/,
D_UTAN  /*** Mineral Pile ***/,
D_POPU  /*** Miscellaneous Cultural Feature ***/,
D_GENE  /*** Miscellaneous Feature ***/,
D_DEST  /*** Miscellaneous Obstacle ***/,
D_INWA  /*** Miscellaneous Surface Drainage Feature ***/,
D_OCEN  /*** Miscellaneous Underwater Feature ***/,
D_VEGE  /*** Miscellaneous Vegetation ***/,
D_DEST  /*** Missile Site ***/,
D_DEST  /*** Moat ***/,
D_POPU  /*** Mobile Home/Mobile Home Park ***/,
D_POPU  /*** Monument ***/,
D_AERO  /*** Mooring Mast ***/,
D_POAN  /*** Mooring Ring ***/,
D_PHYS  /*** Moraine ***/,
D_PHYS  /*** Mountain Pass ***/,
D_GENE  /*** Named Location ***/,
D_POPU  /*** Native Settlement ***/,
D_AERO  /*** NAVAIDS (Aeronautical) ***/,
D_PHYS  /*** Nearshore (Precise IHO) ***/,
D_VEGE  /*** Nursery ***/,
D_VEGE  /*** Oasis ***/,
D_POAN  /*** Offshore Loading Facility ***/,
D_UTAN  /*** Oil/Gas Facilities ***/,
D_UTAN  /*** Oil/Gas Field ***/,
D_VEGE  /*** Orchard/Plantation ***/,
D_OCEN  /*** Overfalls/Tide Rips ***/,
D_POPU  /*** Overhead Obstruction Location ***/,
D_AERO  /*** Overrun/Stopway ***/,
D_OCEN  /*** Oyster Bed/Mussel Bed ***/,
D_PHYS  /*** Pack Ice ***/,
D_POPU  /*** Park ***/,
D_UTAN  /*** Particle Accelerator ***/,
D_INWA  /*** Penstock ***/,
D_AITO  /*** Perches/Stakes ***/,
D_POAN  /*** Pier/Wharf/Quay ***/,
D_POAN  /*** Pile/Piling/Post ***/,
D_UTAN  /*** Pipeline/Pipe ***/,
D_GRTR  /*** Pipeline Or Pipe Crossing Point ***/,
D_UTAN  /*** Platform ***/,
D_POPU  /*** Plaza/City Square ***/,
D_DAQU  /*** Point of Change ***/,
D_PHYS  /*** Polar Ice ***/,
D_UTAN  /*** Power Plant ***/,
D_UTAN  /*** Power Transmission Line ***/,
D_UTAN  /*** Power Transmission Pylon ***/,
D_DAQU  /*** Precise Radar Significant Location ***/,
D_GENE  /*** Process MBR Feature ***/,
D_UTAN  /*** Processing/Treatment Plant ***/,
D_UTAN  /*** Pumping Station ***/,
D_UTAN  /*** Quarry ***/,
D_UTAN  /*** Quarry/Mine Shear Wall ***/,
D_POPU  /*** Race Track ***/,
D_MALI  /*** Radar Reference Line ***/,
D_UTAN  /*** Radar Transmitter ***/,
D_GRTR  /*** Railroad ***/,
D_GRTR  /*** Railroad Siding/Railroad Spur ***/,
D_GRTR  /*** Railroad Turntable ***/,
D_GRTR  /*** Railroad Yard/Marshalling Yard ***/,
D_GRTR  /*** Ramp ***/,
D_POAN  /*** Ramp (Maritime) ***/,
D_INWA  /*** Rapids ***/,
D_OCEN  /*** Reef ***/,
D_INWA  /*** Reservoir ***/,
D_MALI  /*** Restricted Area ***/,
D_AERO  /*** Revetment (Airfield/Equipment/Facilities ) ***/,
D_VEGE  /*** Rice Field ***/,
D_PHYS  /*** Ridge Line ***/,
D_UTAN  /*** Rig/Superstructure ***/,
D_POAN  /*** Rip Rap ***/,
D_INWA  /*** River/Stream ***/,
D_INWA  /*** River/Stream Vanishing Point ***/,
D_GRTR  /*** Road ***/,
D_OCEN  /*** Rock ***/,
D_PHYS  /*** Rock Strata/Rock Formation ***/,
D_MALI  /*** Route (Maritime) ***/,
D_GRTR  /*** Route Marker ***/,
D_POPU  /*** Ruins ***/,
D_AERO  /*** Runway ***/,
D_AERO  /*** Runway Radar Reflector ***/,
D_MALI  /*** Safety Fairway ***/,
D_UTAN  /*** Salt Evaporator ***/,
D_UTAN  /*** Salt Pan ***/,
D_PHYS  /*** Sand Dune/Sand Hills ***/,
D_UTAN  /*** Wrecking Yard/Scrap Yard ***/,
D_VEGE  /*** Scrub/Brush/Bush ***/,
D_AERO  /*** Seaplane Base ***/,
D_AERO  /*** Seaplane Landing/Seaplane Take-Off Area ***/,
D_POAN  /*** Seawall ***/,
D_PHYS  /*** Sebkha ***/,
D_POPU  /*** Settlement ***/,
D_UTAN  /*** Settling Basin/Sludge Pond ***/,
D_POPU  /*** Shanty Town ***/,
D_POPU  /*** Shed ***/,
D_BOUN  /*** Shoreline ***/,
D_POPU  /*** Ski Jump ***/,
D_POAN  /*** Slipway/Patent Slip ***/,
D_SLPO  /*** Slope Polygon ***/,
D_INWA  /*** Sluice Gate ***/,
D_OCEN  /*** Snags/Stumps ***/,
D_PHYS  /*** Snow Field/Ice Field ***/,
D_GRTR  /*** Snow Shed/Rock Shed ***/,
D_UTAN  /*** Solar Panels ***/,
D_OCEN  /*** Sounding ***/,
D_POPU  /*** Special Area ***/,
D_INWA  /*** Spillway ***/,
D_ELEV  /*** Spot Elevation ***/,
D_INWA  /*** Spring/Water Hole ***/,
D_POPU  /*** Stadium/Amphitheater ***/,
D_GRTR  /*** Station (Miscellaneous) ***/,
D_GRTR  /*** Steep Grade ***/,
D_UTAN  /*** Storage Bunker/Storage Mound ***/,
D_GRTR  /*** Street Sign ***/,
D_UTAN  /*** Substation/Transformer Yard ***/,
D_GRTR  /*** Subway ***/,
D_VEGE  /*** Swamp ***/,
D_MALI  /*** Swept Area ***/,
D_POPU  /*** Swimming Pool ***/,
D_UTAN  /*** Tank ***/,
D_AERO  /*** Taxiway ***/,
D_UTAN  /*** Telephone Line/Telegraph Line ***/,
D_UTAN  /*** Telephone-Telegraph Pylon/Pole ***/,
D_POPU  /*** Tent Dwellings ***/,
D_GENE  /*** Text Description ***/,
D_OCEN  /*** Tide Data Point ***/,
D_OCEN  /*** Tide Gauge ***/,
D_UTAN  /*** Tower (Non-Communication) ***/,
D_OCEN  /*** Track Line ***/,
D_MALI  /*** Traffic Separation Scheme (TSS) ***/,
D_GRTR  /*** Trail ***/,
D_VEGE  /*** Trees ***/,
D_VEGE  /*** Tundra ***/,
D_GRTR  /*** Tunnel ***/,
D_DEST  /*** Underground Bunker ***/,
D_POPU  /*** Underground Dwelling ***/,
D_OCEN  /*** Underwater Danger/Hazard ***/,
D_GRTR  /*** Sharp Curve(s) ***/,
D_GRTR  /*** Vehicle Stopping Area/Rest Area ***/,
D_GRTR  /*** Vehicle Storage/Parking Area ***/,
D_VEGE  /*** Vineyards ***/,
D_GENE  /*** Void Collection Area ***/,
D_PHYS  /*** Volcanic Dike ***/,
D_PHYS  /*** Volcano ***/,
D_POPU  /*** Wall ***/,
D_OCEN  /*** Water (Except Inland) ***/,
D_INWA  /*** Water Intake Tower ***/,
D_UTAN  /*** Water Tower ***/,
D_INWA  /*** Waterfall ***/,
D_INWA  /*** Well ***/,
D_UTAN  /*** Windmill ***/,
D_UTAN  /*** Windmotor ***/,
D_OCEN  /*** Wreck ***/,
D_BOUN  /*** Zone Of Occupation ***/,
D_POPU  /*** Zoo/Safari Park ***/
};

int FLDBDOMAINSLEN = sizeof(FLDBDOMAINS)/ sizeof(unsigned char);

unsigned char FLDBSTRATS[]={
0  /*** Dummy Value ***/,
S_APPL  /*** Administrative Area ***/,
S_APPL  /*** Administrative Boundary ***/,
S_APPL  /*** Aerial Cableway Lines/Ski Lift Lines ***/,
S_APPL  /*** Aerial Cableway Pylon/Ski Pylon ***/,
S_APPL  /*** Air Warning Light ***/,
S_APPL  /*** Aircraft Facility Reference Point ***/,
S_APPL  /*** Airport/Airfield ***/,
S_APPL  /*** Airport Lighting ***/,
S_APPL  /*** Airspace ***/,
S_APPL  /*** Airspace Boundary Segment ***/,
S_APPL  /*** Amusement Park ***/,
S_APPL  /*** Amusement Park Attraction ***/,
S_APPL  /*** Anchorage ***/,
S_APPL  /*** Animal Sanctuary ***/,
S_APPL  /*** Apron/Hardstand ***/,
S_APPL  /*** Aqueduct ***/,
S_APPL  /*** Armistice Line ***/,
S_APPL  /*** Artifact Location ***/,
S_APPL  /*** Asphalt Lake ***/,
S_APPL  /*** Athletic Field ***/,
S_APPL  /*** Backshore (Precise IHO) ***/,
S_APPL  /*** Bamboo/Cane ***/,
S_APPL  /*** Bastion/Rampart/Fortification ***/,
S_APPL  /*** Beach ***/,
S_APPL  /*** Beacon ***/,
S_APPL  /*** Benchmark ***/,
S_APPL  /*** Berth ***/,
S_APPL  /*** Blast Furnace ***/,
S_APPL  /*** Bluff/Cliff/Escarpment ***/,
S_APPL  /*** Bog ***/,
S_APPL  /*** Bollard ***/,
S_APPL  /*** Bottom Characteristics ***/,
S_APPL  /*** Boundary Monument ***/,
S_APPL  /*** Breakers ***/,
S_APPL  /*** Breakwater ***/,
S_APPL  /*** Bridge/Overpass/Viaduct ***/,
S_APPL  /*** Bridge Span ***/,
S_APPL  /*** Bridge Superstructure ***/,
S_APPL  /*** Bridge Tower/Bridge Pylon ***/,
S_APPL  /*** Building ***/,
S_APPL  /*** Building Superstructure Addition ***/,
S_APPL  /*** Built-Up Area ***/,
S_APPL  /*** Buoy ***/,
S_APPL  /*** Cable ***/,
S_APPL  /*** Cairn ***/,
S_APPL  /*** Calling-In Point ***/,
S_APPL  /*** Camp ***/,
S_APPL  /*** Campground/Campsite ***/,
S_APPL  /*** Canal ***/,
S_APPL  /*** Cart Track ***/,
S_APPL  /*** Catalytic Cracker ***/,
S_APPL  /*** Causeway ***/,
S_APPL  /*** Cave ***/,
S_APPL  /*** Cease Fire Line ***/,
S_APPL  /*** Cemetery ***/,
S_APPL  /*** Chimney/Smokestack ***/,
S_APPL  /*** Cistern ***/,
S_APPL  /*** Claim Line ***/,
S_APPL  /*** Cleared Way/Cut Line/Firebreak ***/,
S_APPL  /*** Coastline ***/,
S_APPL  /*** Coastline/Shoreline ***/,
S_APPL  /*** Communication Building ***/,
S_APPL  /*** Communication Tower ***/,
S_APPL  /*** Complex Outline ***/,
S_APPL  /*** Constriction/Expansion ***/,
S_APPL  /*** Contour Line (Land) ***/,
S_APPL  /*** Control Point/Control Station ***/,
S_APPL  /*** Control Tower ***/,
S_APPL  /*** Conveyor ***/,
S_APPL  /*** Cooling Tower ***/,
S_APPL  /*** Covered Drainage ***/,
S_APPL  /*** Crane ***/,
S_APPL  /*** Crevice/Crevasse ***/,
S_APPL  /*** Crib ***/,
S_APPL  /*** Cropland ***/,
S_APPL  /*** Culvert ***/,
S_APPL  /*** Current Diagram ***/,
S_APPL  /*** Current Flow ***/,
S_APPL  /*** Cut ***/,
S_APPL  /*** Dam/Weir ***/,
S_APPL  /*** Defact Boundary ***/,
S_APPL  /*** Demilitarized Zone ***/,
S_APPL  /*** Depot (Storage) ***/,
S_APPL  /*** Depression ***/,
S_APPL  /*** Depth Area ***/,
S_APPL  /*** Depth Contour ***/,
S_APPL  /*** Depth Curve ***/,
S_APPL  /*** Diagnostic Point ***/,
S_APPL  /*** Discolored Water ***/,
S_APPL  /*** Disk/Dish ***/,
S_APPL  /*** Display Sign ***/,
S_APPL  /*** Disposal Site/Waste Pile ***/,
S_APPL  /*** Distance Mark ***/,
S_APPL  /*** Ditch ***/,
S_APPL  /*** Dolphin ***/,
S_APPL  /*** Dragon Teeth ***/,
S_APPL  /*** Dredge/Powershovel/Dragline ***/,
S_APPL  /*** Drive In Theater ***/,
S_APPL  /*** Drive In Theater Screen ***/,
S_APPL  /*** Drop Gate/Rolling Block ***/,
S_APPL  /*** Drydock ***/,
S_APPL  /*** Early Warning Radar Site ***/,
S_APPL  /*** Eddies ***/,
S_APPL  /*** Embankment/Fill ***/,
S_APPL  /*** Engine Test Cell ***/,
S_APPL  /*** Entrance/Exit ***/,
S_APPL  /*** Esker ***/,
S_APPL  /*** Fairgrounds ***/,
S_APPL  /*** Fault ***/,
S_APPL  /*** Feed Lot/Stockyard/Holding Pen ***/,
S_APPL  /*** Fence ***/,
S_APPL  /*** Ferry Crossing ***/,
S_APPL  /*** Ferry Site ***/,
S_APPL  /*** Filtration Beds/Aeration Beds ***/,
S_APPL  /*** Firing Range/Gunnery Range ***/,
S_APPL  /*** Fish Hatchery/Fish Farm/Marine Farm ***/,
S_APPL  /*** Fish Stakes ***/,
S_APPL  /*** Fish Traps/Fish Weirs ***/,
S_APPL  /*** Fishing Harbor ***/,
S_APPL  /*** Fishing Pier/Promenade Pier ***/,
S_APPL  /*** Flagstaff/Flagpole ***/,
S_APPL  /*** Flare Pipe ***/,
S_APPL  /*** Flight of Steps ***/,
S_APPL  /*** Prepared Raft or Float Bridge Site ***/,
S_APPL  /*** Flood Barrage ***/,
S_APPL  /*** Flume ***/,
S_APPL  /*** Fog Signal ***/,
S_APPL  /*** Ford ***/,
S_APPL  /*** Foreshore (Precise IHO) ***/,
S_APPL  /*** Fortification ***/,
S_APPL  /*** Foul Ground ***/,
S_APPL  /*** Fountain ***/,
S_APPL  /*** Gallery ***/,
S_APPL  /*** Gate ***/,
S_APPL  /*** Gate (Nautical) ***/,
S_APPL  /*** Geodetic Point ***/,
S_APPL  /*** Geographic Information Point ***/,
S_APPL  /*** Geomorphic Line ***/,
S_APPL  /*** Geomorphic Location ***/,
S_APPL  /*** Geophysical Prospecting Grid ***/,
S_APPL  /*** Geothermal Feature ***/,
S_APPL  /*** Glacier ***/,
S_APPL  /*** Golf Course ***/,
S_APPL  /*** Grain Bin/Silo ***/,
S_APPL  /*** Grain Elevator ***/,
S_APPL  /*** Grandstand ***/,
S_APPL  /*** Grassland ***/,
S_APPL  /*** Gridiron ***/,
S_APPL  /*** Groin ***/,
S_APPL  /*** Ground Surface Element ***/,
S_APPL  /*** Gully/Gorge ***/,
S_APPL  /*** Hedgerow ***/,
S_APPL  /*** Helicopter Landing Pad ***/,
S_APPL  /*** Heliport ***/,
S_APPL  /*** Homogeneous Aggregate Feature ***/,
S_APPL  /*** Homogeneous Radar Significant Area ***/,
S_APPL  /*** Hopper ***/,
S_APPL  /*** Hops ***/,
S_APPL  /*** Hummock ***/,
S_APPL  /*** Hut ***/,
S_APPL  /*** Ice Cliff ***/,
S_APPL  /*** Ice Peak/Nunatak ***/,
S_APPL  /*** Ice Shelf ***/,
S_APPL  /*** Inland Shoreline ***/,
S_APPL  /*** Inland Water ***/,
S_APPL  /*** Inland Water Elevation ***/,
S_APPL  /*** Interchange ***/,
S_APPL  /*** International Date Line ***/,
S_APPL  /*** Island ***/,
S_APPL  /*** Jetty ***/,
S_APPL  /*** Kelp/Seaweed ***/,
S_APPL  /*** Lagoon/Reef Pool ***/,
S_APPL  /*** Lake/Pond ***/,
S_APPL  /*** Land devoid of vegetation ***/,
S_APPL  /*** Land Subject to Inundation ***/,
S_APPL  /*** Landing Place ***/,
S_APPL  /*** Landing Stairs ***/,
S_APPL  /*** Leading Line ***/,
S_APPL  /*** Light ***/,
S_APPL  /*** Light Sector ***/,
S_APPL  /*** Light Standard/Light Support ***/,
S_APPL  /*** Light Vessel/Lightship ***/,
S_APPL  /*** Lighthouse ***/,
S_APPL  /*** Lock ***/,
S_APPL  /*** Log Boom/Booming Ground ***/,
S_APPL  /*** Magnetic Disturbance Area ***/,
S_APPL  /*** Mandate Line / Convention Line ***/,
S_APPL  /*** Maritime Area ***/,
S_APPL  /*** Maritime Limit Boundary ***/,
S_APPL  /*** Maritime Station/Maritime Signal Station ***/,
S_APPL  /*** Marker ***/,
S_APPL  /*** Marsh ***/,
S_APPL  /*** Measured Distance Line ***/,
S_APPL  /*** Military Base ***/,
S_APPL  /*** Mine ***/,
S_APPL  /*** Mineral Pile ***/,
S_APPL  /*** Miscellaneous Cultural Feature ***/,
S_APPL  /*** Miscellaneous Feature ***/,
S_APPL  /*** Miscellaneous Obstacle ***/,
S_APPL  /*** Miscellaneous Surface Drainage Feature ***/,
S_APPL  /*** Miscellaneous Underwater Feature ***/,
S_APPL  /*** Miscellaneous Vegetation ***/,
S_APPL  /*** Missile Site ***/,
S_APPL  /*** Moat ***/,
S_APPL  /*** Mobile Home/Mobile Home Park ***/,
S_APPL  /*** Monument ***/,
S_APPL  /*** Mooring Mast ***/,
S_APPL  /*** Mooring Ring ***/,
S_APPL  /*** Moraine ***/,
S_APPL  /*** Mountain Pass ***/,
S_APPL  /*** Named Location ***/,
S_APPL  /*** Native Settlement ***/,
S_APPL  /*** NAVAIDS (Aeronautical) ***/,
S_APPL  /*** Nearshore (Precise IHO) ***/,
S_APPL  /*** Nursery ***/,
S_APPL  /*** Oasis ***/,
S_APPL  /*** Offshore Loading Facility ***/,
S_APPL  /*** Oil/Gas Facilities ***/,
S_APPL  /*** Oil/Gas Field ***/,
S_APPL  /*** Orchard/Plantation ***/,
S_APPL  /*** Overfalls/Tide Rips ***/,
S_APPL  /*** Overhead Obstruction Location ***/,
S_APPL  /*** Overrun/Stopway ***/,
S_APPL  /*** Oyster Bed/Mussel Bed ***/,
S_APPL  /*** Pack Ice ***/,
S_APPL  /*** Park ***/,
S_APPL  /*** Particle Accelerator ***/,
S_APPL  /*** Penstock ***/,
S_APPL  /*** Perches/Stakes ***/,
S_APPL  /*** Pier/Wharf/Quay ***/,
S_APPL  /*** Pile/Piling/Post ***/,
S_APPL  /*** Pipeline/Pipe ***/,
S_APPL  /*** Pipeline Or Pipe Crossing Point ***/,
S_APPL  /*** Platform ***/,
S_APPL  /*** Plaza/City Square ***/,
S_APPL  /*** Point of Change ***/,
S_APPL  /*** Polar Ice ***/,
S_APPL  /*** Power Plant ***/,
S_APPL  /*** Power Transmission Line ***/,
S_APPL  /*** Power Transmission Pylon ***/,
S_APPL  /*** Precise Radar Significant Location ***/,
S_APPL  /*** Process MBR Feature ***/,
S_APPL  /*** Processing/Treatment Plant ***/,
S_APPL  /*** Pumping Station ***/,
S_APPL  /*** Quarry ***/,
S_APPL  /*** Quarry/Mine Shear Wall ***/,
S_APPL  /*** Race Track ***/,
S_APPL  /*** Radar Reference Line ***/,
S_APPL  /*** Radar Transmitter ***/,
S_APPL  /*** Railroad ***/,
S_APPL  /*** Railroad Siding/Railroad Spur ***/,
S_APPL  /*** Railroad Turntable ***/,
S_APPL  /*** Railroad Yard/Marshalling Yard ***/,
S_APPL  /*** Ramp ***/,
S_APPL  /*** Ramp (Maritime) ***/,
S_APPL  /*** Rapids ***/,
S_APPL  /*** Reef ***/,
S_APPL  /*** Reservoir ***/,
S_APPL  /*** Restricted Area ***/,
S_APPL  /*** Revetment (Airfield/Equipment/Facilities ) ***/,
S_APPL  /*** Rice Field ***/,
S_APPL  /*** Ridge Line ***/,
S_APPL  /*** Rig/Superstructure ***/,
S_APPL  /*** Rip Rap ***/,
S_APPL  /*** River/Stream ***/,
S_APPL  /*** River/Stream Vanishing Point ***/,
S_APPL  /*** Road ***/,
S_APPL  /*** Rock ***/,
S_APPL  /*** Rock Strata/Rock Formation ***/,
S_APPL  /*** Route (Maritime) ***/,
S_APPL  /*** Route Marker ***/,
S_APPL  /*** Ruins ***/,
S_APPL  /*** Runway ***/,
S_APPL  /*** Runway Radar Reflector ***/,
S_APPL  /*** Safety Fairway ***/,
S_APPL  /*** Salt Evaporator ***/,
S_APPL  /*** Salt Pan ***/,
S_APPL  /*** Sand Dune/Sand Hills ***/,
S_APPL  /*** Wrecking Yard/Scrap Yard ***/,
S_APPL  /*** Scrub/Brush/Bush ***/,
S_APPL  /*** Seaplane Base ***/,
S_APPL  /*** Seaplane Landing/Seaplane Take-Off Area ***/,
S_APPL  /*** Seawall ***/,
S_APPL  /*** Sebkha ***/,
S_APPL  /*** Settlement ***/,
S_APPL  /*** Settling Basin/Sludge Pond ***/,
S_APPL  /*** Shanty Town ***/,
S_APPL  /*** Shed ***/,
S_APPL  /*** Shoreline ***/,
S_APPL  /*** Ski Jump ***/,
S_APPL  /*** Slipway/Patent Slip ***/,
S_APPL  /*** Slope Polygon ***/,
S_APPL  /*** Sluice Gate ***/,
S_APPL  /*** Snags/Stumps ***/,
S_APPL  /*** Snow Field/Ice Field ***/,
S_APPL  /*** Snow Shed/Rock Shed ***/,
S_APPL  /*** Solar Panels ***/,
S_APPL  /*** Sounding ***/,
S_APPL  /*** Special Area ***/,
S_APPL  /*** Spillway ***/,
S_APPL  /*** Spot Elevation ***/,
S_APPL  /*** Spring/Water Hole ***/,
S_APPL  /*** Stadium/Amphitheater ***/,
S_APPL  /*** Station (Miscellaneous) ***/,
S_APPL  /*** Steep Grade ***/,
S_APPL  /*** Storage Bunker/Storage Mound ***/,
S_APPL  /*** Street Sign ***/,
S_APPL  /*** Substation/Transformer Yard ***/,
S_APPL  /*** Subway ***/,
S_APPL  /*** Swamp ***/,
S_APPL  /*** Swept Area ***/,
S_APPL  /*** Swimming Pool ***/,
S_APPL  /*** Tank ***/,
S_APPL  /*** Taxiway ***/,
S_APPL  /*** Telephone Line/Telegraph Line ***/,
S_APPL  /*** Telephone-Telegraph Pylon/Pole ***/,
S_APPL  /*** Tent Dwellings ***/,
S_APPL  /*** Text Description ***/,
S_APPL  /*** Tide Data Point ***/,
S_APPL  /*** Tide Gauge ***/,
S_APPL  /*** Tower (Non-Communication) ***/,
S_APPL  /*** Track Line ***/,
S_APPL  /*** Traffic Separation Scheme (TSS) ***/,
S_APPL  /*** Trail ***/,
S_APPL  /*** Trees ***/,
S_APPL  /*** Tundra ***/,
S_APPL  /*** Tunnel ***/,
S_APPL  /*** Underground Bunker ***/,
S_APPL  /*** Underground Dwelling ***/,
S_APPL  /*** Underwater Danger/Hazard ***/,
S_APPL  /*** Sharp Curve(s) ***/,
S_APPL  /*** Vehicle Stopping Area/Rest Area ***/,
S_APPL  /*** Vehicle Storage/Parking Area ***/,
S_APPL  /*** Vineyards ***/,
S_APPL  /*** Void Collection Area ***/,
S_APPL  /*** Volcanic Dike ***/,
S_APPL  /*** Volcano ***/,
S_APPL  /*** Wall ***/,
S_APPL  /*** Water (Except Inland) ***/,
S_APPL  /*** Water Intake Tower ***/,
S_APPL  /*** Water Tower ***/,
S_APPL  /*** Waterfall ***/,
S_APPL  /*** Well ***/,
S_APPL  /*** Windmill ***/,
S_APPL  /*** Windmotor ***/,
S_APPL  /*** Wreck ***/,
S_APPL  /*** Zone Of Occupation ***/,
S_APPL  /*** Zoo/Safari Park ***/
};

int FLDBSTRATSLEN = sizeof(FLDBSTRATS)/ sizeof(unsigned char);


