/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
int MGCP4_ATTR_NUM=109;

char *MGCP4_attr_codes[] = {
"ZVA",
"SFS",
"LFA",
"FPT",
"AOO",
"ATC",
"TXT",
"AFA",
"BOC",
"RSA",
"BOT",
"BSC",
"BAC",
"PBY",
"CAB",
"CAT",
"DMT",
"CCN",
"FUN",
"CNS",
"CAA",
"CCT",
"CDA",
"CRM",
"CRA",
"CSP",
"COD",
"SEP",
"FIC",
"EET",
"MZN",
"FMM",
"FFP",
"FFN",
"TRE",
"FUC",
"FHC",
"HGT",
"HAF",
"ACC",
"HWT",
"HYP",
"IKO",
"LEN",
"RTA",
"RST",
"UID",
"AZC",
"STA",
"MES",
"NAM",
"NFN",
"NFI",
"SWT",
"NST",
"OPC",
"OHB",
"PRM",
"PPC",
"PPO",
"RAY",
"RAC",
"RWC",
"GAW",
"RGC",
"RRA",
"RRC",
"RIR",
"ORD",
"REL",
"WTC",
"RKF",
"WD1",
"CON",
"SDO",
"SDT",
"SUC",
"PWC",
"SLT",
"FAC",
"SDV",
"SDP",
"SRT",
"NOS",
"MCC",
"SSC",
"SMC",
"HCT",
"TID",
"NA2",
"TOS",
"TTC",
"LTN",
"TRS",
"TUC",
"DMB",
"VEG",
"VSP",
"VOI",
"LOC",
"VGT",
"GNC",
"WLE",
"SCC",
"WCC",
"WST",
"FRT",
"WFT",
"WID"
};

char *MGCP4_attr_names[] = {
"Aerodrome Elevation",
"Aerodrome Pavement Functional Status",
"Aeronautical Light Function",
"Airfield Type",
"Angle of Orientation",
"Aqueduct Type",
"Associated Text",
"Available Vessel Service",
"Bog Type",
"Branch Railway Type",
"Bridge Opening Type",
"Bridge Structure Type",
"Built-up Area Density Category",
"By-product",
"Cable Type",
"Cableway Type",
"Canopy Cover",
"Commercial Copyright Notice",
"Condition of Facility",
"Controlled",
"Controlling Authority",
"Cover Closure Type",
"Covered Drain",
"Crane Mobility Type",
"Crane Type",
"Crop Species",
"Delineation Known",
"Divided",
"Embankment Type",
"Engineered Earthwork Type",
"Extraction Mine Type",
"Farming Method",
"Farming Pattern",
"Feature Function",
"Foliage Type",
"Functional Use",
"Harbour Facility Function",
"Height Above Surface Level",
"Helipad Associated Facility",
"Horizontal Accuracy Category",
"House of Worship Type",
"Hydrologic Persistence",
"ICAO Location Indicator",
"Length",
"Linear Feature Arrangement",
"Load-bearing Surface Type",
"MGCP Feature universally unique identifier",
"Man-made",
"Maritime Station Type",
"Median Present",
"Name",
"Name Identifier",
"Named Feature Identifier",
"Natural Pool Type",
"Navigation System Type",
"Offshore Platform Type",
"Overall Bridge Height",
"Permanent",
"Power Station Type",
"Product",
"Racing Type",
"Radar Antenna Configuration",
"Railway Class",
"Railway Gauge",
"Railway Gauge Classification",
"Railway Power Method",
"Railway Use",
"Railway in Road",
"Relative Importance",
"Religious Designation",
"Road Weather Restriction",
"Rock Formation Structure",
"Route Minimum Travelled Way Width",
"Route Width Constriction Type",
"Sand Dune Orientation",
"Sand Dune Type",
"Shed Type",
"Shoreline Construction Type",
"Shoreline Type",
"Solid Maritime Construction",
"Source Date and Time",
"Source Description",
"Source Type",
"Span Count",
"Structural Material Type",
"Structure Shape",
"Surface Material Type",
"Thoroughfare Class",
"Tide Influenced",
"Touristic Name",
"Tower Shape",
"Tower Type",
"Track or Lane Count",
"Transportation System Type",
"Transportation Use",
"Undergrowth Density",
"Vegetation Characteristic",
"Vegetation Species",
"Vertical Obstruction Identifier",
"Vertical Relative Location",
"Volcano Shape",
"Water Gate Type",
"Water Level Effect",
"Water Type",
"Watercourse Channel Type",
"Watercourse Sink Type",
"Weapons Range Type",
"Well Type",
"Width"
};

char *MGCP4_attr_types[] = {
"Real",
"Short Integer",
"Short Integer",
"Short Integer",
"Real",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Real",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Real",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Real",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Real",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Real",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Real",
"Short Integer",
"Real",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Real",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Real"
};

char *MGCP4_attr_defns[] = {
"The vertical distance above Mean Sea Level (MSL) of the highest point of the landing area.",
"The functional status of the pavement of an aerodrome movement area. ( An aerodrome movement area is that part of an aerodrome to be used for aircraft movement operations, consisting of the manoeuvring area and the apron(s). )",
"The type of lighting or lighting system that is used to support aeronautical navigation.",
"The type of an airfield based on the size and/or paving of its runways.",
"The angular distance in the horizontal plane measured from true north (0 degrees) clockwise to the major axis of the feature. ( If the feature is square, the axis 0 up to 90 degrees is recorded. If the feature is circular, 360 degrees is recorded. )",
"The type of an aqueduct based on its structure.",
"A narrative or other textual description associated with a feature or data set.",
"The type(s) of vessel service available at, or in the near vicinity of, a facility.",
"The type of a bog or fen based on its morphology and/or dominant vegetation. ( A fen is similar to a bog but may have alkaline, neutral, or only slightly acid peaty soil whereas a bog is generally very acidic. In both cases the vegetation is usually dominated by peat mosses, ericaceous shrubs, and sedges. )",
"The function or configuration of a branch railway.",
"The type of structure or mechanism by which a bridge or bridge span is moved to allow passage of a vessel.",
"The type(s) of structural design of a bridge, bridge span, or bridge superstructure.",
"A general evaluation of the density of a built-up area, as a category.",
"The principal by-product(s) of a production, mining, or agricultural activity. ( If multiple by-products are specified then they are usually listed in descending order of importance. )",
"The type of a cable based on its use.",
"The type of a cableway based on structure and/or function.",
"The fraction of canopy cover within a defined area during the season of maximum foliage. ( The canopy is formed by the upper branches of the trees in a forest forming a more or less continuous layer. )",
"A description of any commercial (or similar) copyright notice applicable to information regarding the feature or data set. ( For example, '2000 Space Imaging, Inc.', in which case the copyright information for use of such imagery needs to be stated; this generally includes restrictions on use and distribution. For non copyright data, for example 'Copyright 2004 by the National Geospatial-Intelligence Agency, U.S. Government. No domestic copyright claimed under Title 17 U.S.C. All rights reserved.' )",
"The state of planning, construction, repair, and/or maintenance of the structures and/or equipment comprising a facility and/or located at a site, as a whole.",
"An indication that a facility is controlled. ( For example, maritime traffic control. )",
"The controlling authority responsible for a facility or site. ( Controlling authorities may be distinguished by organizational level (for example: national, sub-national, or military district) and/or type (for example: private or public). )",
"The extent and/or nature of the cover (for example: a roof) of a structure.",
"An indication that a watercourse section is completely covered over and connects to uncovered watercourses at each end.",
"The type of mobility of a crane.",
"The type of a crane based on its design and/or method of operation.",
"The predominant species of a crop land.",
"An indication that the delineation (for example: limits and information) of a feature is known.",
"An indication that the lanes or tracks in a land transportation route (for example: a road or a railway), are horizontally separated (for example: by a median strip) and not adjoining. ( May be used to indicate the separation of opposing flows of traffic in order to improve safety or to meet route engineering restrictions by some means. For example, the two travelled ways of a divided highway may pass at different elevations along the side of a mountain or may diverge when passing around significant engineering obstacles (for example: rocky outcrops). )",
"The type of an embankment based on its use and/or relationship to the surrounding terrain.",
"The type of an excavation and/or embankment created for the purpose of enhancing the defense of a site from armed attack.",
"The type of an extraction mine.",
"The agricultural practice(s) in use within an agro-ecosystem.",
"The general arrangement(s) and/or pattern(s) of farming fields.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The predominant foliage type of the vegetation.",
"The general categories of function or use that a facility, site, or region serves or may serve. ( May be so designated by legal means (for example: statute, zoning, or treaty) or be the unplanned consequence of economic forces. )",
"The primary function(s) of harbour facilities that are associated with a service or commercial operation of public interest.",
"The vertical distance measured from the lowest point of the base of the feature at ground or water level (downhill/downstream side) to the tallest point of the feature. ( For non-inland water bodies, the water level is usually understood to be Mean Sea Level (MSL). Note that the feature may be supported above the surface by another feature (for example: a tower supported by a building) and as a consequence the value of the Height Above Surface Level is different (larger) than the base-to-top height of the feature (for example: supported tower) itself. )",
"The type of facility or building that is associated with a freestanding helipad.",
"A general evaluation of the horizontal accuracy of the geographic position of a feature, as a category.",
"The type of a house of worship based on its use, structure and/or religious denomination served.",
"The degree of persistence of water in an inland water body (for example: a spring, a flowing stream, a lake or a pond). ( Inland water bodies may also include, for example, crevices, ditches, fountains, and water troughs. )",
"The identifier that is assigned to a location in accordance with rules prescribed by the International Civil Aviation Organization (ICAO) in Document 7910. ( If available this indicator shall be used as primary for identification. )",
"The dimension of a feature taken along its primary alignment of use and generally in the horizontal plane. ( The primary alignment of a feature is its established direction of flow or use (for example: a road, a power line, a river, a rapid, and/or a bridge). A feature-specific rule may apply. In the case of a bridge, the length is the distance between the bridge abutments along the bridge centreline. In the case of a dam, the length is the distance along the dam crest. If no established direction of flow or use exists then (1) if the feature is irregular in shape its length is its greatest horizontal dimension (see Attribute: 'Greatest Horizontal Extent'), else (2) if the feature is regular in shape then a shape-specific rule may apply: for a rectangular feature, the length of the longer axis; for a round feature, the diameter. )",
"The arrangement of parallel linear features on a single support structure including both directions (if applicable). ( For example, two railways sharing a single roadbed. )",
"The physical surface composition of a terrain surface that is intended to bear loads. ( For example, the surface of a road, a runway, a hard standing, or a vehicle storage lot. )",
"A unique identifier for each instance of MGCP Feature assigned by national system in accordance with ISO /IEC 9834-8 standard.The UUID shall be represented by a string of hexadecimal digits, using two hexadecimal digits for each octet of the binary form",
"An indication that a feature is man-made.",
"The type(s) of activities of significance to navigation and/or operation that takes place at a maritime station.",
"An indication that the lanes or tracks of a divided land transportation route (for example: a road or a railway) are separated by a vertical median barrier. ( Often used to separate opposing flows of traffic in order to improve safety. For example, may be a substantial concrete barrier of approximately 1 metre height. )",
"A textual identifier or code that is used to denote a feature.",
"The unique name identifier element in the NGA Geographic Names Data Base (GNDB). ( Typically used together with Attribute: 'Named Feature Identifier' to provide a unique index into the NGA Geographic Names Data Base (GNDB) from which NGA draws all of its feature name information. )",
"The unique named feature identifier element in the NGA Geographic Names Data Base (GNDB). ( Typically used together with Attribute: 'Name Identifier' to provide a unique index into the NGA Geographic Names Data Base (GNDB) from which NGA draws all of its feature name information. )",
"The type of a natural pool, generally based on its origin.",
"The type(s) of equipment or system used in electronic navigation.",
"The type of an offshore platform based on its structure and/or use(s).",
"The vertical distance measured from the lowest point at ground or water level to the highest portion of the bridge (including superstructure).",
"An indication that a feature is permanent. ( Temporary features last, or are meant to last, for a limited time only. )",
"The type of an electric power station based on its energy source.",
"The principal product(s) resulting from a production, mining, or agricultural activity. ( If multiple products are specified then they are usually listed in descending order of importance. )",
"The type(s) of racing held at a site or facility.",
"The physical mounting and/or configuration of a radar antenna.",
"The class of a railway based on its importance in the general transportation network.",
"The distance between a single pair of rails of a railway, measured along the shortest distance from inside rail to inside rail.",
"The classification of a railway based on the distance between a single pair of rails, measured along the shortest distance from inside rail to inside rail.",
"The method by which electrical power is distributed on a railway, if any.",
"The use(s) to which a railway is put as part of a transportation system.",
"An indication that a railway track is located within the bounds of a roadbed. ( For example, an infrequently used railway spur in a roadway or a carline running (regularly) in a roadway. )",
"The relative importance of an object. ( For example, as an ordinal rank. )",
"A designation denoting a religion or system of belief.",
"The type of weather conditions under which a road is usable.",
"The structure of a signficiant outcropping of exposed rock.",
"The minimum width of the travelled way of a route. ( Excludes pavements and shoulders. )",
"The type of a route width constriction based on the nature of the surrounding area. ( For example, reduction in road width to less than 4 metres is considered to be a constriction. Width restrictions cause vehicles and people to travel through narrow passages creating choke points. )",
"The characteristic alignment of a sand dune imposed by prevailing winds. ( Normally, the angular distance measured from true north (0 degrees) clockwise to the direction of the dune crests. )",
"The type of a sand dune based on its shape and/or structure.",
"The type of use of a shed.",
"The type of a shoreline construction (for example: a pier, a wharf, or a quay). ( May be used as a means of subtyping Feature: 'Shoreline Construction'. )",
"The physical characteristics of a shoreline.",
"An indication that a marine construction (for example: a pier, wharf, or quay) is solid, thereby blocking the free circulation of water underneath the construction. ( The construction may be of concrete, masonry, wood, and/or other building materials. Open pile construction is used where the benefits of protection from currents and waves is not required. )",
"The date and, optionally, time of collection of the data set that was used to define the digital representation of the feature or data set. ( Midnight is understood to be 00:00:00 (the beginning of a day); when the time is not specified then midnight in the local time zone is typically implied. )",
"A description of the data set that was used to define the digital representation of the feature or data set. ( No restriction is placed on the length of the description. )",
"The type(s) of the data set(s) that were used to define the digital representation of the feature or data set. ( For example, based on a data product specification. )",
"The number of spans in a bridge.",
"The primary type(s) of material composing a feature, exclusive of the surface. ( The basis for 'primary' may be, for example, compositional dominance or structural organization. )",
"The geometric form, appearance, and/or configuration of the feature as a whole.",
"The surface material composition of a feature, excluding its internal (structural) composition. ( Usually determined by remotely sensed characteristics, for example radar return. Generally, the very thin layer that interacts with electro-optical wavelengths. )",
"The class of a thoroughfare based on its importance in the general transportation network.",
"An indication that a waterbody is affected by the tide.",
"A touristic identifier or code that is used to denote a feature. ( Used in addition to a geographic name. )",
"The general shape and/or structure of a tower.",
"The type of a tower based on its intended use(s).",
"The total number of independent, parallel paths (for example: a railway track and/or a road lane) in both directions within a route.",
"The type of a transportation system based on the type(s) of vehicles employed and/or the nature(s) of the objects transported.",
"The primary use(s) of a transportation system.",
"The fraction of land within a defined area that is covered by undergrowth (for example: scrub, brush, and/or bush).",
"The type of a vegetated area based on species, biome, physiography and/or structural organization.",
"The predominant species of a tract of vegetation.",
"Identification code that uniquely identifies a feature that is a vertical obstruction to low-level flight. ( Although parts of the identifier include digits it can also consist of non-numeric characters. )",
"The relationship between the feature and the underlying ground (terrain) or waterbody bottom.",
"The classification by shape of a volcano.",
"The type of barrier that may be swung, drawn, or lowered to block an entrance or passageway on a watercourse.",
"The relationship between the feature and surrounding (including covering and/or underlying) water.",
"The type of available water based on its composition and/or fitness for human consumption.",
"The type of trough-like depression that is normally occupied by a watercourse.",
"The type of the sink of a watercourse.",
"The type of a weapons range based on its intended use(s).",
"The type of a well, generally based on method of construction.",
"The dimension of a feature taken perpendicular to its primary alignment of use and generally in the horizontal plane. ( The primary alignment of a feature is its established direction of flow or use (for example: a road, a power line right-of-way, a river, rapid, and/or a bridge). A feature-specific rule may apply. In the case of a bridge, the width is the distance perpendicular to the bridge centre-line and generally in the horizontal plane. In the case of a dam, the width is the distance perpendicular to (across the) the dam crest. If no such direction of flow or use exists then (1) if the feature is irregular in shape its width is taken perpendicular to the direction of its greatest horizontal dimension (see Attribute: 'Greatest Horizontal Extent'), else (2) if the feature is regular in shape then a shape-specific rule may apply: for a rectangular feature, the length of the shorter axis; for a round feature, the diameter. )"
};

int MGCP4_attr_lens[] = {
19,
6,
6,
6,
19,
6,
255,
6,
6,
6,
6,
6,
6,
6,
6,
6,
19,
255,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
6,
19,
6,
6,
6,
6,
255,
19,
6,
6,
36,
6,
6,
6,
80,
18,
18,
6,
6,
6,
19,
6,
6,
6,
6,
6,
6,
19,
6,
6,
6,
6,
6,
6,
6,
6,
19,
6,
19,
6,
6,
6,
6,
6,
20,
255,
6,
6,
6,
6,
6,
6,
6,
80,
6,
6,
6,
6,
6,
19,
6,
6,
36,
6,
6,
6,
6,
6,
6,
6,
6,
6,
19
};

