/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
#include "share.h"
int MGCP3_CLASS_NUM=185;

char *MGCP3_class_codes[] = {
"GB005",
"GA035",
"GB220",
"GB050",
"GB010",
"AK030",
"GB015",
"BH010",
"AL012",
"BA050",
"BB190",
"BH015",
"BB041",
"AQ040",
"AQ045",
"AL015",
"AL020",
"AT041",
"AL025",
"AK060",
"BH020",
"EC010",
"AP010",
"AC020",
"AQ064",
"DB030",
"AL030",
"AH070",
"AJ010",
"BI010",
"EC040",
"AT060",
"AT050",
"AT080",
"AQ060",
"AF020",
"AF030",
"AF040",
"BJ031",
"DB061",
"EA010",
"AQ065",
"DB070",
"DB071",
"BI020",
"AT010",
"AB000",
"BH030",
"BB090",
"DB090",
"AQ090",
"DB100",
"AA010",
"AK090",
"AL070",
"AQ070",
"FA015",
"AF070",
"BH060",
"BH070",
"EC060",
"AH050",
"AL080",
"DB110",
"FA090",
"DB115",
"BJ030",
"AK100",
"AM030",
"AM020",
"EB010",
"BB043",
"DB200",
"BB005",
"BB008",
"BD130",
"AD050",
"EA020",
"GB030",
"GB035",
"AJ030",
"AL100",
"AA052",
"BJ040",
"BJ060",
"AQ075",
"BA030",
"BH080",
"BH090",
"BA010",
"GB040",
"BC050",
"BI030",
"BH050",
"BB155",
"ED010",
"AL130",
"SU001",
"AM040",
"AQ110",
"BJ020",
"DB150",
"ZD040",
"BH170",
"AL240",
"EC020",
"BD110",
"AK120",
"AL140",
"BH110",
"AQ113",
"AT030",
"AD010",
"AD030",
"AC000",
"AL210",
"AL170",
"AQ116",
"AT042",
"AA012",
"AK130",
"AT045",
"AN010",
"AN050",
"AN075",
"AN060",
"BH120",
"AK190",
"AB010",
"BH130",
"BH135",
"AA040",
"BH140",
"AP030",
"AP020",
"AQ135",
"DB160",
"AL200",
"GB055",
"BH160",
"BH155",
"DB170",
"GB065",
"BB230",
"AL105",
"AC030",
"BB240",
"BI040",
"AF010",
"BJ100",
"DA010",
"AD020",
"AK040",
"AK160",
"DB010",
"GB045",
"AM010",
"AM070",
"BD100",
"AM060",
"ED020",
"GB075",
"FA100",
"EB020",
"BA040",
"AP050",
"BB140",
"AQ125",
"BJ110",
"AQ130",
"BH145",
"AQ140",
"ZD020",
"DB180",
"AL260",
"BI041",
"BI050",
"AM080",
"BH040",
"BH180",
"AA050",
"AJ050",
"AJ051",
"EC030",
"AK180"
};

char *MGCP3_class_names[] = {
"Aerodrome",
"Aeronautical NAVAID",
"Air Obstruction",
"Aircraft Revetment",
"Airport Navigation Lights",
"Amusement Park",
"Apron",
"Aqueduct",
"Archeological Site",
"Beach",
"Berthing Structure",
"Bog",
"Breakwater",
"Bridge",
"Bridge Span",
"Building",
"Built-Up Area",
"Cableway",
"Cairn",
"Camp-site",
"Canal",
"Cane",
"Cart Track",
"Catalytic Cracker",
"Causeway",
"Cave",
"Cemetery",
"Checkpoint",
"Circular Irrigation System",
"Cistern",
"Cleared Way",
"Communication Line",
"Communication Station",
"Communication Tower",
"Control Tower",
"Conveyor",
"Cooling Tower",
"Crane",
"Crevasse",
"Crevice",
"Crop Land",
"Culvert",
"Cut",
"Cut Line",
"Dam",
"Dish Aerial",
"Disposal Site",
"Ditch",
"Dry Dock",
"Embankment",
"Entrance and/or Exit",
"Esker",
"Extraction Mine",
"Fairground",
"Fence",
"Ferry Crossing",
"Firing Range",
"Flare Pipe",
"Flume",
"Ford",
"Forest Clearing",
"Fortification",
"Gantry",
"Geologic Fault",
"Geophysical Prospecting Grid",
"Geothermal Outlet",
"Glacier",
"Golf Course",
"Grain Elevator",
"Grain Storage Structure",
"Grassland",
"Groin",
"Gully",
"Harbour",
"Harbour Waters",
"Hazardous Rock",
"Heating Facility",
"Hedgerow",
"Helipad",
"Heliport",
"Holding Pen",
"Hut",
"Hydrocarbons Field",
"Ice Cliff",
"Ice Peak",
"Ice Route",
"Island",
"Lake",
"Land Subject to Inundation",
"Land Water Boundary",
"Launch Pad",
"Lighthouse",
"Lock",
"Marine Farm",
"Maritime Signal Station",
"Marsh",
"Memorial Monument",
"Military Installation",
"Mineral Pile",
"Mooring Mast",
"Moraine",
"Mountain Pass",
"Named Location",
"Natural Pool",
"Non-communication Tower",
"Oasis",
"Offshore Platform",
"Park",
"Particle Accelerator",
"Penstock",
"Pipeline",
"Power Line",
"Power Station",
"Power Substation",
"Processing Facility",
"Protection Shed",
"Public Square",
"Pumping Station",
"Pylon",
"Quarry",
"Racetrack",
"Radar Station",
"Railway",
"Railway Sidetrack",
"Railway Turntable",
"Railway Yard",
"Rapids",
"Recreational Pier",
"Recycling Site",
"Reservoir",
"Rice Field",
"Rig",
"River",
"Road",
"Road Interchange",
"Roadside Rest Area",
"Rock Formation",
"Ruins",
"Runway",
"Sabkha",
"Salt Evaporator",
"Sand Dunes",
"Seaplane Base",
"Seawall",
"Settlement",
"Settling Pond",
"Slipway",
"Sluice Gate",
"Smokestack",
"Snow Field and/or Ice-field",
"Soil Surface Region",
"Solar Panel",
"Sports Ground",
"Stadium",
"Steep Terrain Face",
"Stopway",
"Storage Depot",
"Storage Tank",
"Structural Pile",
"Surface Bunker",
"Swamp",
"Taxiway",
"Test Site",
"Thicket",
"Tidal Water",
"Trail",
"Training Wall",
"Transportation Station",
"Tundra",
"Tunnel",
"Vanishing Point",
"Vehicle Lot",
"Void Collection Area",
"Volcano",
"Wall",
"Water Gate",
"Water Intake Tower",
"Water Tower",
"Water Treatment Bed",
"Waterfall",
"Well",
"Windmill",
"Windmotor",
"Wood",
"Zoo"
};

char *MGCP3_class_defns[] = {
"An area of land set aside for the take-off, landing and/or accommodation of aircraft.",
"Any visual or electronic device that provides aeronautical guidance information or position data.",
"An object at a fixed location with reference to which vertical clearance is or must be provided during flight operations.",
"A barricade that protects an aircraft, equipment, and/or facility from hostile action.",
"Lights used to: define and outline airport components (for example: perimeters, runways, and taxiways); guide aircraft while on the ground; and provide guidance to aircraft on approach for landing.",
"A predominantly man-made facility equipped with recreational devices.",
"A defined area at an aerodrome or heliport intended for aircraft parking.",
"A pipe or artificial channel, often supported by a bridge, designed to transport water from a remote source, usually by gravity.",
"A site where remains of ancient civilizations or human activity have been discovered.",
"On a shore, the area on which the waves break and over which shore debris (for example: sand, shingle, and/or pebbles) accumulate.",
"A structure primarily used as a berthing place for vessels.",
"A poorly drained wetland that consists of decaying vegetation, retains stagnant water, and is too soft to bear the weight of any heavy body.",
"A structure that protects a waterbody region (for example: a shore, a harbour, and/or an anchorage) from water waves by preventing them from reaching the protected region or reducing their magnitude.",
"A structure that connects two locations and provides for the passage of a transportation route (for example: a road or a railway) over a terrain obstacle (for example: a waterbody, a gully, and/or a road).",
"A component of the deck of a bridge spanning successive bridge piers.",
"A relatively permanent structure, roofed and usually walled and designed for some particular use.",
"A tract containing a concentration of buildings and/or other structures.",
"A transportation system consisting of load cables strung between pylons on which carrier units (for example: cars or buckets intended to transport people, material, and/or equipment) are suspended.",
"A heap of stones piled up as a memorial or a landmark.",
"A place for camping.",
"An artificial waterway with no flow, or a controlled flow, used for navigation.",
"A tract covered mainly by large treelike grasses.",
"An unimproved road.",
"A device in which the separation of petroleum is carried out in the presence of a catalyst.",
"A raised road supported by a solid structure and/or raised land providing a route across wet and/or intertidal terrain.",
"An interconnected series of subterranean chambers.",
"A site and associated structures devoted to the burial of the dead.",
"An official place to register, declare and/or inspect goods and/or people.",
"An elevated irrigation system revolving around a central pivot point.",
"A man-made container used for the collection and/or storage of water.",
"A man-made cleared strip through a vegetated region.",
"A cable that transmits communication signals.",
"A facility in which communication signals are processed and/or controlled.",
"A tower used to support an aerial for transmitting and/or receiving electronic communication signals.",
"A tower that houses personnel and equipment used to control the flow of traffic on a transportation route (for example: an air, rail, or maritime route).",
"Mechanical device for conveying articles or materials during manufacture or processing using an endless moving belt or series of rollers.",
"A tall tower for cooling hot water from an industrial process before reuse.",
"Equipment for lifting, shifting, and lowering objects or materials by means of a swinging boom or with the lifting apparatus supported on an overhead track.",
"A deep crack or fissure in a glacier that results from differential movement of ice. (May also describe a deep vertical opening in the terrain that appears after an earthquake.)",
"A narrow opening or fissure produced by a crack in the land, especially in rock.",
"An area that has been tilled for the planting of crops.",
"An enclosed channel for carrying a watercourse (for example: a stream, a sewer, or a drain) under a route (for example: a road, a railway, or an embankment).(Usually the construction of the route is unaffected.)",
"An excavation in the terrain to provide passage for a land or water transportation route (for example: a road, a railway, and/or a canal).",
"The demarcation line between a cut and the surrounding land surface.",
"A barrier constructed to hold back water and raise its level to form a reservoir or to prevent flooding.",
"A concave-shaped aerial that is used for transmitting and/or receiving electronic signals.",
"A site for the collection and/or deposition of refuse or discarded material.",
"An artificial waterway with no flow, or a controlled flow, used for draining or irrigating land.",
"An artificial basin fitted with a gate or caisson into which vessels can be floated and the water pumped out to expose the bottom of the vessel.",
"A man-made raised long mound of earth or other material.",
"A location of entrance and/or exit.",
"A long, narrow ridge of sand and gravel deposited by a glacial stream.",
"An excavation made in the terrain for the purpose of extracting and/or exploiting natural resources.",
"An area where permanent facilities exist to hold outdoor fairs, circuses or exhibitions.",
"A man-made barrier of relatively light structure used as an enclosure or boundary.",
"A route where a ferry crosses from one shore to another.",
"A site designated for the purpose of discharging firearms or detonating munitions.",
"An open-ended pipe at which waste gases are burned.",
"An inclined channel for conveying water from a distance. (For example, carries water to be utilized for power, transportation, and/or irrigation.)",
"A shallow place in a body of water used as a crossing.",
"A site in a forest or wood(s) that has been cleared, often for slash and burn agriculture and/or as a result of clear-cutting logging.",
"A structure constructed for the military defence of a site.",
"A permanent raised structure used to support equipment (for example: cranes, signal lights, or signs) while spanning over or around an object (for example: over a road or railroad, or around a ship hull or rocket).",
"A fracture in a rock formation, marked by the relative displacement on either side of the plane of the fracture.",
"A grid established for the collection of geophysical data within an area.(The grid is typically composed of one or more series of observation points where each series is obtained along a single track and the grid is then assembled from multiple tracks assembled from multiple tracks.)",
"A terrain surface feature controlled by or derived from the heat of the Earth's interior.",
"A large mass or river of ice formed by accumulation and compaction of snow on higher ground that is moving slowly down a slope or valley from above the snowline.",
"A tract of land on which golf is played.",
"A tall structure, equipped for loading, unloading, processing, and/or storing grain.",
"An enclosed container, used for storing grain or fodder.",
"A tract covered mainly by grasses that have little or no woody tissue.",
"A low artificial wall-like structure of durable material extending from the land to seaward for a particular purpose, such as to prevent coast erosion.",
"A deep ditch or channel cut into the terrain that results from erosion due to surface water runoff.",
"A natural or artificial improved body of water providing protection for vessels and generally anchorage and docking facilities.",
"A natural or artificial improved body of water providing protection for vessels and usually associated with a port.",
"An isolated rocky formation or a single large stone or coral, usually one constituting a danger to navigation.",
"A facility for the generation of thermal energy for heating purposes.",
"A continuous growth of shrubs planted as a fence, a boundary, and/or a windbreak.",
"An improved area used for take-off and landing of helicopters.",
"An aerodrome or a defined place on a structure intended to be used wholly or in part for the arrival, departure, and/or surface movement of helicopters.",
"An enclosed tract on which livestock are temporarily kept.",
"A small, simple, or crude house or shelter.(See also Feature: 'Building'.)",
"An area where petroleum, oil and/or natural gas is pumped or otherwise removed from the ground.",
"The vertical face of a glacier or ice shelf.",
"A rocky peak projecting above a surrounding ice field that may be perpetually covered with ice.",
"A route over a frozen watercourse.",
"A land mass, other than a continent, surrounded by water.",
"A large body of water entirely surrounded by land.",
"A tract periodically covered by flood water, excluding tidal waters.",
"The line where a land mass is in contact with a body of water.",
"A designated site or structure from which a rocket or missile is launched.",
"A distinctive structure on or off a coast exhibiting a major light designed to serve as an aid to navigation.",
"An enclosure with a pair or series of gates used for raising or lowering vessels as they pass from one water level to another.",
"An assemblage of cages, nets, rafts and floats or posts where fish, including shellfish, are artificially cultivated.",
"A place on shore from which signals are made to vessels at sea.",
"A soft, poorly drained wetland that is characterized by the growth of only non-woody plants (for example: grasses) and often forms a transition region between a waterbody and land.",
"A marker erected and/or maintained as a memorial to a person and/or event.",
"An installation designed for military use.",
"A man-made heap of mining or quarrying products that does not contain waste materials.",
"A mast used to secure an airship.",
"An accumulation of soil and stone debris deposited by a glacier.",
"A narrow route through a mountainous region or over a mountain range.",
"A location that normally does not appear as a specific, characterized object but that has a name that is required to be displayed in association with that location.",
"A naturally formed pool of water.",
"A tower that is used for purposes other than communication.",
"A small, isolated, fertile or green area in a desert region usually having a spring or well.",
"An offshore structure with a flat surface raised above the sea, used as a working stage for conducting offshore operations.",
"An area used for recreational or ornamental purposes.",
"An apparatus for imparting high velocities to charged particles.",
"A pipeline or channel generally used by hydroelectric plants or water mills to transport water by gravity and under pressure.",
"A connected set of pipes for conveying liquids, slurries, or gases.",
"A cable that transmits or distributes electrical power.",
"A facility including one or more buildings and equipment used for power generation.",
"A facility, along a power transmission line, in which electric current is switched, transformed, and/or converted.",
"A facility including one or more buildings used for processing materials.",
"A shelter built to protect a section of road or railway from slides of snow and/or rock. (For example, a snow shed or a rock shed.)",
"An open site that serves as a public meeting location in a built-up area.",
"A facility to move solids, liquids or gases by means of pressure or suction.",
"A pylon or pole used to support one or more cables.",
"An open-air excavation created by removal of stone by blasting or cutting.",
"A ground or tract marked out for racing.",
"A facility utilizing radar to detect and analyze objects (for example: aircraft, artificial satellites, asteroids, and/or missiles) and/or envionmental phenomena (for example: tornados).",
"One or more railway tracks comprising a network that is operated for the conveyance of passengers and/or goods.",
"A stretch of railway track connected to a main railway and used for temporary storage, passing, loading, and/or unloading.",
"A rotating platform with railway tracks used for turning locomotives and/or railway carriages.",
"A system of railway tracks and associated structures that are located within defined limits and that provide for loading, unloading, and/or assembling trains.",
"Portions of a stream with accelerated current where it descends rapidly but without a break in the slope of the bed sufficient to form a waterfall.",
"A structure extending into the water used as a platform for recreational purposes, not intended as a berthing place for vessels.",
"A site engaged in the wrecking, dismantling, storage, recycling, and/or disposal of discarded or scrap products.",
"A substantial lake-like body of water impounded by a dam.",
"A tract that is periodically covered with water and is used for growing rice.",
"A superstructure fitted for drilling or lifting operations for extraction and/or exploitation of natural resources.",
"A natural flowing watercourse.",
"A route with a specially prepared surface that is maintained for use by motor vehicles.",
"A connection designed to provide traffic access from one road to another.",
"A roadside place usually having facilities for people and/or vehicles.",
"A signficiant outcropping of exposed bedrock.",
"The deteriorated remains of an unspecified structure.",
"A defined, usually rectangular, area on an aerodrome prepared for the landing and take-off of aircraft.",
"A natural depression in arid or semi-arid regions whose bed is covered with salt encrusted clayey soil.",
"Shallow pools, normally man-made, used for the natural evaporation of water for the collection of salt.",
"One or more mounds or ridges of sand usually formed by the wind.",
"An installation supporting aircraft capable of taking off and landing on water.",
"An embankment or wall for protection against waves or tidal action along a shore or water front.",
"A continuously occupied concentration of tents or lightweight fixed structures (for example: huts) serving as residences.",
"A small reservoir where solid matter is precipitated from a liquid by evaporating or settling.",
"The prepared and usually reinforced inclined surface on which keel- and bilge-blocks are laid for supporting a vessel under construction.",
"The gate used to regulate the flow of water in a sluice.",
"A vertical structure containing a passage or flue for discharging smoke and gases of combustion.",
"A large area permanently covered by snow and/or ice.",
"A region of the land that is homogeneous with respect to a soil characteristic.",
"A panel designed to absorb the sun's rays for the purpose of generating electricity or heat.",
"An open area where sporting events, exercises, and/or games occur.(For example, an athletic field, a playing field, and/or a sports field.)",
"An arena for holding and viewing events.",
"A steep, vertical, or overhanging face of rock and/or soil.",
"A tract beyond the take-off runway endpoint that is designated as able to support an aircraft during an aborted take-off.",
"A tract used for the storage of products and/or supplies.",
"A container used for the storage of liquids and/or gases that is not supported by a tower.",
"A long pile (for example: a heavy timber or section of steel, wood, or concrete) forced into the earth that may serve as a support (for example: for a pier) or as a free standing pole within a marine environment.",
"A surface structure that may be covered and/or surrounded with earth and is resistant to ordnance.",
"A seasonally flooded, poorly drained wetland with more woody plants than a marsh and better drainage than a bog.",
"A defined path on an aerodrome established for the taxiing of aircraft and intended to provide a link between one part of the aerodrome and another.",
"A site for the testing of technical products and equipment.",
"A tract covered mainly by low-growing, uncultured, woody plants that are thickly tangled together.",
"Any water the level of which changes periodically due to tidal action.",
"A path worn by the passage of people or animals.",
"A wall, bank or jetty often submerged, built to direct or confine the flow of a river or tidal current or to promote scour actions.",
"A station that serves as a stopping place along a transportation route.",
"A vast, nearly level, treeless arctic region usually with a marshy surface and underlying permafrost.",
"An underground passage that is open at both ends and usually contains a land transportation route (for example: a road and/or a railway).",
"The location at which a watercourse disappears into the terrain.",
"A tract used for storing and/or parking vehicles (for example: recreational vehicles) and/or vessels.",
"A data collection region lacking suitable source coverage and/or where data is not required.",
"A hill or mountain situated over an opening or openings in the Earth's crust through which lava, cinders, steam, and/or gases, are or have been expelled.",
"A solid man-made barrier of generally heavy material used as an enclosure, boundary, or for protection.",
"A barrier that may be swung, drawn, or lowered to block an entrance or passageway on a watercourse.",
"A tower-like structure associated with a dam or water source and used for the intake of water.",
"A tower supporting an elevated storage tank of water.",
"A tract for the treatment of water that consists of a bed of material where water is aerated or filtered.",
"A vertically decending part of a watercourse where it falls from a height (for example: over a rock or a precipice).",
"An excavation drilled or dug into the ground (for example: the sea bed) for the extraction of liquids and/or gases.",
"A system of vanes attached to a tower and driven by wind (excluding windmotors).",
"Equipment attached to a tower that generates electrical power from wind.",
"A tract of trees whose canopy is not closed (allows sunlight to reach the ground) and often includes undergrowth.",
"A site where wild animals are kept for exhibition to the public, that may also support breeding and/or study."
};

unsigned char MGCP3DOMAINS[]={
0  /*** Dummy Value ***/,
D_AERO  /*** Aerodrome ***/,
D_AITO  /*** Aeronautical NAVAID ***/,
D_AERO  /*** Air Obstruction ***/,
D_AERO  /*** Aircraft Revetment ***/,
D_AERO  /*** Airport Navigation Lights ***/,
D_POPU  /*** Amusement Park ***/,
D_AERO  /*** Apron ***/,
D_INWA  /*** Aqueduct ***/,
D_POPU  /*** Archeological Site ***/,
D_PHYS  /*** Beach ***/,
D_POAN  /*** Berthing Structure ***/,
D_VEGE  /*** Bog ***/,
D_POAN  /*** Breakwater ***/,
D_GRTR  /*** Bridge ***/,
D_GRTR  /*** Bridge Span ***/,
D_POPU  /*** Building ***/,
D_POPU  /*** Built-Up Area ***/,
D_POPU  /*** Cableway ***/,
D_BOUN  /*** Cairn ***/,
D_POPU  /*** Camp-site ***/,
D_INWA  /*** Canal ***/,
D_VEGE  /*** Cane ***/,
D_GRTR  /*** Cart Track ***/,
D_UTAN  /*** Catalytic Cracker ***/,
D_GRTR  /*** Causeway ***/,
D_PHYS  /*** Cave ***/,
D_POPU  /*** Cemetery ***/,
D_DEST  /*** Checkpoint ***/,
D_UTAN  /*** Circular Irrigation System ***/,
D_INWA  /*** Cistern ***/,
D_VEGE  /*** Cleared Way ***/,
D_UTAN  /*** Communication Line ***/,
D_UTAN  /*** Communication Station ***/,
D_UTAN  /*** Communication Tower ***/,
D_POPU  /*** Control Tower ***/,
D_UTAN  /*** Conveyor ***/,
D_UTAN  /*** Cooling Tower ***/,
D_UTAN  /*** Crane ***/,
D_PHYS  /*** Crevasse ***/,
D_PHYS  /*** Crevice ***/,
D_VEGE  /*** Crop Land ***/,
D_INWA  /*** Culvert ***/,
D_PHYS  /*** Cut ***/,
D_PHYS  /*** Cut Line ***/,
D_INWA  /*** Dam ***/,
D_UTAN  /*** Dish Aerial ***/,
D_UTAN  /*** Disposal Site ***/,
D_INWA  /*** Ditch ***/,
D_POAN  /*** Dry Dock ***/,
D_PHYS  /*** Embankment ***/,
D_GRTR  /*** Entrance and/or Exit ***/,
D_PHYS  /*** Esker ***/,
D_UTAN  /*** Extraction Mine ***/,
D_POPU  /*** Fairground ***/,
D_POPU  /*** Fence ***/,
D_GRTR  /*** Ferry Crossing ***/,
D_DEST  /*** Firing Range ***/,
D_UTAN  /*** Flare Pipe ***/,
D_UTAN  /*** Flume ***/,
D_GRTR  /*** Ford ***/,
D_VEGE  /*** Forest Clearing ***/,
D_DEST  /*** Fortification ***/,
D_UTAN  /*** Gantry ***/,
D_PHYS  /*** Geologic Fault ***/,
D_UTAN  /*** Geophysical Prospecting Grid ***/,
D_PHYS  /*** Geothermal Outlet ***/,
D_PHYS  /*** Glacier ***/,
D_POPU  /*** Golf Course ***/,
D_UTAN  /*** Grain Elevator ***/,
D_UTAN  /*** Grain Storage Structure ***/,
D_VEGE  /*** Grassland ***/,
D_POAN  /*** Groin ***/,
D_PHYS  /*** Gully ***/,
D_POAN  /*** Harbour ***/,
D_POAN  /*** Harbour Waters ***/,
D_OCEN  /*** Hazardous Rock ***/,
D_UTAN  /*** Heating Facility ***/,
D_VEGE  /*** Hedgerow ***/,
D_AERO  /*** Helipad ***/,
D_AERO  /*** Heliport ***/,
D_UTAN  /*** Holding Pen ***/,
D_POPU  /*** Hut ***/,
D_UTAN  /*** Hydrocarbons Field ***/,
D_PHYS  /*** Ice Cliff ***/,
D_PHYS  /*** Ice Peak ***/,
D_GRTR  /*** Ice Route ***/,
D_PHYS  /*** Island ***/,
D_INWA  /*** Lake ***/,
D_INWA  /*** Land Subject to Inundation ***/,
D_BOUN  /*** Land Water Boundary ***/,
D_AERO  /*** Launch Pad ***/,
D_AITO  /*** Lighthouse ***/,
D_INWA  /*** Lock ***/,
D_INWA  /*** Marine Farm ***/,
D_POAN  /*** Maritime Signal Station ***/,
D_VEGE  /*** Marsh ***/,
D_POPU  /*** Memorial Monument ***/,
D_DEST  /*** Military Installation ***/,
D_UTAN  /*** Mineral Pile ***/,
D_AERO  /*** Mooring Mast ***/,
D_PHYS  /*** Moraine ***/,
D_GRTR  /*** Mountain Pass ***/,
D_GENE  /*** Named Location ***/,
D_INWA  /*** Natural Pool ***/,
D_UTAN  /*** Non-communication Tower ***/,
D_VEGE  /*** Oasis ***/,
D_UTAN  /*** Offshore Platform ***/,
D_POPU  /*** Park ***/,
D_UTAN  /*** Particle Accelerator ***/,
D_INWA  /*** Penstock ***/,
D_UTAN  /*** Pipeline ***/,
D_UTAN  /*** Power Line ***/,
D_UTAN  /*** Power Station ***/,
D_UTAN  /*** Power Substation ***/,
D_UTAN  /*** Processing Facility ***/,
D_POPU  /*** Protection Shed ***/,
D_POPU  /*** Public Square ***/,
D_UTAN  /*** Pumping Station ***/,
D_UTAN  /*** Pylon ***/,
D_UTAN  /*** Quarry ***/,
D_POPU  /*** Racetrack ***/,
D_UTAN  /*** Radar Station ***/,
D_GRTR  /*** Railway ***/,
D_GRTR  /*** Railway Sidetrack ***/,
D_GRTR  /*** Railway Turntable ***/,
D_GRTR  /*** Railway Yard ***/,
D_INWA  /*** Rapids ***/,
D_POAN  /*** Recreational Pier ***/,
D_UTAN  /*** Recycling Site ***/,
D_INWA  /*** Reservoir ***/,
D_VEGE  /*** Rice Field ***/,
D_UTAN  /*** Rig ***/,
D_INWA  /*** River ***/,
D_GRTR  /*** Road ***/,
D_GRTR  /*** Road Interchange ***/,
D_GRTR  /*** Roadside Rest Area ***/,
D_PHYS  /*** Rock Formation ***/,
D_POPU  /*** Ruins ***/,
D_AERO  /*** Runway ***/,
D_PHYS  /*** Sabkha ***/,
D_UTAN  /*** Salt Evaporator ***/,
D_PHYS  /*** Sand Dunes ***/,
D_AERO  /*** Seaplane Base ***/,
D_POAN  /*** Seawall ***/,
D_POPU  /*** Settlement ***/,
D_UTAN  /*** Settling Pond ***/,
D_POAN  /*** Slipway ***/,
D_INWA  /*** Sluice Gate ***/,
D_UTAN  /*** Smokestack ***/,
D_PHYS  /*** Snow Field and/or Ice-field ***/,
D_PHYS  /*** Soil Surface Region ***/,
D_UTAN  /*** Solar Panel ***/,
D_POPU  /*** Sports Ground ***/,
D_POPU  /*** Stadium ***/,
D_PHYS  /*** Steep Terrain Face ***/,
D_AERO  /*** Stopway ***/,
D_UTAN  /*** Storage Depot ***/,
D_UTAN  /*** Storage Tank ***/,
D_POAN  /*** Structural Pile ***/,
D_UTAN  /*** Surface Bunker ***/,
D_VEGE  /*** Swamp ***/,
D_AERO  /*** Taxiway ***/,
D_UTAN  /*** Test Site ***/,
D_VEGE  /*** Thicket ***/,
D_OCEN  /*** Tidal Water ***/,
D_GRTR  /*** Trail ***/,
D_POAN  /*** Training Wall ***/,
D_GRTR  /*** Transportation Station ***/,
D_VEGE  /*** Tundra ***/,
D_GRTR  /*** Tunnel ***/,
D_INWA  /*** Vanishing Point ***/,
D_GRTR  /*** Vehicle Lot ***/,
D_GENE  /*** Void Collection Area ***/,
D_PHYS  /*** Volcano ***/,
D_POPU  /*** Wall ***/,
D_INWA  /*** Water Gate ***/,
D_INWA  /*** Water Intake Tower ***/,
D_UTAN  /*** Water Tower ***/,
D_UTAN  /*** Water Treatment Bed ***/,
D_INWA  /*** Waterfall ***/,
D_UTAN  /*** Well ***/,
D_UTAN  /*** Windmill ***/,
D_UTAN  /*** Windmotor ***/,
D_VEGE  /*** Wood ***/,
D_POPU  /*** Zoo ***/
};

int MGCP3DOMAINSLEN = sizeof(MGCP3DOMAINS)/ sizeof(unsigned char);

unsigned char MGCP3STRATS[]={
0  /*** Dummy Value ***/,
S_APPL  /*** Aerodrome ***/,
S_APPL  /*** Aeronautical NAVAID ***/,
S_APPL  /*** Air Obstruction ***/,
S_APPL  /*** Aircraft Revetment ***/,
S_APPL  /*** Airport Navigation Lights ***/,
S_APPL  /*** Amusement Park ***/,
S_APPL  /*** Apron ***/,
S_APPL  /*** Aqueduct ***/,
S_APPL  /*** Archeological Site ***/,
S_APPL  /*** Beach ***/,
S_APPL  /*** Berthing Structure ***/,
S_APPL  /*** Bog ***/,
S_APPL  /*** Breakwater ***/,
S_APPL  /*** Bridge ***/,
S_APPL  /*** Bridge Span ***/,
S_APPL  /*** Building ***/,
S_APPL  /*** Built-Up Area ***/,
S_APPL  /*** Cableway ***/,
S_APPL  /*** Cairn ***/,
S_APPL  /*** Camp-site ***/,
S_APPL  /*** Canal ***/,
S_APPL  /*** Cane ***/,
S_APPL  /*** Cart Track ***/,
S_APPL  /*** Catalytic Cracker ***/,
S_APPL  /*** Causeway ***/,
S_APPL  /*** Cave ***/,
S_APPL  /*** Cemetery ***/,
S_APPL  /*** Checkpoint ***/,
S_APPL  /*** Circular Irrigation System ***/,
S_APPL  /*** Cistern ***/,
S_APPL  /*** Cleared Way ***/,
S_APPL  /*** Communication Line ***/,
S_APPL  /*** Communication Station ***/,
S_APPL  /*** Communication Tower ***/,
S_APPL  /*** Control Tower ***/,
S_APPL  /*** Conveyor ***/,
S_APPL  /*** Cooling Tower ***/,
S_APPL  /*** Crane ***/,
S_APPL  /*** Crevasse ***/,
S_APPL  /*** Crevice ***/,
S_APPL  /*** Crop Land ***/,
S_APPL  /*** Culvert ***/,
S_APPL  /*** Cut ***/,
S_APPL  /*** Cut Line ***/,
S_APPL  /*** Dam ***/,
S_APPL  /*** Dish Aerial ***/,
S_APPL  /*** Disposal Site ***/,
S_APPL  /*** Ditch ***/,
S_APPL  /*** Dry Dock ***/,
S_APPL  /*** Embankment ***/,
S_APPL  /*** Entrance and/or Exit ***/,
S_APPL  /*** Esker ***/,
S_APPL  /*** Extraction Mine ***/,
S_APPL  /*** Fairground ***/,
S_APPL  /*** Fence ***/,
S_APPL  /*** Ferry Crossing ***/,
S_APPL  /*** Firing Range ***/,
S_APPL  /*** Flare Pipe ***/,
S_APPL  /*** Flume ***/,
S_APPL  /*** Ford ***/,
S_APPL  /*** Forest Clearing ***/,
S_APPL  /*** Fortification ***/,
S_APPL  /*** Gantry ***/,
S_APPL  /*** Geologic Fault ***/,
S_APPL  /*** Geophysical Prospecting Grid ***/,
S_APPL  /*** Geothermal Outlet ***/,
S_APPL  /*** Glacier ***/,
S_APPL  /*** Golf Course ***/,
S_APPL  /*** Grain Elevator ***/,
S_APPL  /*** Grain Storage Structure ***/,
S_APPL  /*** Grassland ***/,
S_APPL  /*** Groin ***/,
S_APPL  /*** Gully ***/,
S_APPL  /*** Harbour ***/,
S_APPL  /*** Harbour Waters ***/,
S_APPL  /*** Hazardous Rock ***/,
S_APPL  /*** Heating Facility ***/,
S_APPL  /*** Hedgerow ***/,
S_APPL  /*** Helipad ***/,
S_APPL  /*** Heliport ***/,
S_APPL  /*** Holding Pen ***/,
S_APPL  /*** Hut ***/,
S_APPL  /*** Hydrocarbons Field ***/,
S_APPL  /*** Ice Cliff ***/,
S_APPL  /*** Ice Peak ***/,
S_APPL  /*** Ice Route ***/,
S_APPL  /*** Island ***/,
S_APPL  /*** Lake ***/,
S_APPL  /*** Land Subject to Inundation ***/,
S_APPL  /*** Land Water Boundary ***/,
S_APPL  /*** Launch Pad ***/,
S_APPL  /*** Lighthouse ***/,
S_APPL  /*** Lock ***/,
S_APPL  /*** Marine Farm ***/,
S_APPL  /*** Maritime Signal Station ***/,
S_APPL  /*** Marsh ***/,
S_APPL  /*** Memorial Monument ***/,
S_APPL  /*** Military Installation ***/,
S_APPL  /*** Mineral Pile ***/,
S_APPL  /*** Mooring Mast ***/,
S_APPL  /*** Moraine ***/,
S_APPL  /*** Mountain Pass ***/,
S_APPL  /*** Named Location ***/,
S_APPL  /*** Natural Pool ***/,
S_APPL  /*** Non-communication Tower ***/,
S_APPL  /*** Oasis ***/,
S_APPL  /*** Offshore Platform ***/,
S_APPL  /*** Park ***/,
S_APPL  /*** Particle Accelerator ***/,
S_APPL  /*** Penstock ***/,
S_APPL  /*** Pipeline ***/,
S_APPL  /*** Power Line ***/,
S_APPL  /*** Power Station ***/,
S_APPL  /*** Power Substation ***/,
S_APPL  /*** Processing Facility ***/,
S_APPL  /*** Protection Shed ***/,
S_APPL  /*** Public Square ***/,
S_APPL  /*** Pumping Station ***/,
S_APPL  /*** Pylon ***/,
S_APPL  /*** Quarry ***/,
S_APPL  /*** Racetrack ***/,
S_APPL  /*** Radar Station ***/,
S_APPL  /*** Railway ***/,
S_APPL  /*** Railway Sidetrack ***/,
S_APPL  /*** Railway Turntable ***/,
S_APPL  /*** Railway Yard ***/,
S_APPL  /*** Rapids ***/,
S_APPL  /*** Recreational Pier ***/,
S_APPL  /*** Recycling Site ***/,
S_APPL  /*** Reservoir ***/,
S_APPL  /*** Rice Field ***/,
S_APPL  /*** Rig ***/,
S_APPL  /*** River ***/,
S_APPL  /*** Road ***/,
S_APPL  /*** Road Interchange ***/,
S_APPL  /*** Roadside Rest Area ***/,
S_APPL  /*** Rock Formation ***/,
S_APPL  /*** Ruins ***/,
S_APPL  /*** Runway ***/,
S_APPL  /*** Sabkha ***/,
S_APPL  /*** Salt Evaporator ***/,
S_APPL  /*** Sand Dunes ***/,
S_APPL  /*** Seaplane Base ***/,
S_APPL  /*** Seawall ***/,
S_APPL  /*** Settlement ***/,
S_APPL  /*** Settling Pond ***/,
S_APPL  /*** Slipway ***/,
S_APPL  /*** Sluice Gate ***/,
S_APPL  /*** Smokestack ***/,
S_APPL  /*** Snow Field and/or Ice-field ***/,
S_APPL  /*** Soil Surface Region ***/,
S_APPL  /*** Solar Panel ***/,
S_APPL  /*** Sports Ground ***/,
S_APPL  /*** Stadium ***/,
S_APPL  /*** Steep Terrain Face ***/,
S_APPL  /*** Stopway ***/,
S_APPL  /*** Storage Depot ***/,
S_APPL  /*** Storage Tank ***/,
S_APPL  /*** Structural Pile ***/,
S_APPL  /*** Surface Bunker ***/,
S_APPL  /*** Swamp ***/,
S_APPL  /*** Taxiway ***/,
S_APPL  /*** Test Site ***/,
S_APPL  /*** Thicket ***/,
S_APPL  /*** Tidal Water ***/,
S_APPL  /*** Trail ***/,
S_APPL  /*** Training Wall ***/,
S_APPL  /*** Transportation Station ***/,
S_APPL  /*** Tundra ***/,
S_APPL  /*** Tunnel ***/,
S_APPL  /*** Vanishing Point ***/,
S_APPL  /*** Vehicle Lot ***/,
S_APPL  /*** Void Collection Area ***/,
S_APPL  /*** Volcano ***/,
S_APPL  /*** Wall ***/,
S_APPL  /*** Water Gate ***/,
S_APPL  /*** Water Intake Tower ***/,
S_APPL  /*** Water Tower ***/,
S_APPL  /*** Water Treatment Bed ***/,
S_APPL  /*** Waterfall ***/,
S_APPL  /*** Well ***/,
S_APPL  /*** Windmill ***/,
S_APPL  /*** Windmotor ***/,
S_APPL  /*** Wood ***/,
S_APPL  /*** Zoo ***/
};

int MGCP3STRATSLEN = sizeof(MGCP3STRATS)/ sizeof(unsigned char);


char *MGCP3_p_optional[] = {
"EC030 PFH",
"EC030 NFN",
"EC030 NFI",
"EC030 NAM",
"EC030 ISS",
"EC030 DMT",
"EC030 DMB",
"AJ051 VOI",
"AJ051 SMC",
"AJ051 HGT",
"AJ050 VOI",
"AJ050 TOS",
"AJ050 SMC",
"AJ050 NFN",
"AJ050 NFI",
"AJ050 NAM",
"AJ050 HGT",
"AA050 WFT",
"AA050 NFN",
"AA050 NFI",
"AA050 NAM",
"BH180 NFN",
"BH180 NFI",
"BH180 NAM",
"AM080 WID",
"AM080 VOI",
"AM080 SMC",
"AM080 LEN",
"AM080 HGT",
"AM080 AWP",
"BI050 VOI",
"BI050 SMC",
"BI050 NFN",
"BI050 NFI",
"BI050 NAM",
"BI050 LEN",
"BI050 HGT",
"BI041 WID",
"BI041 LEN",
"BI041 GNC",
"DB180 VGT",
"DB180 NFN",
"DB180 NFI",
"DB180 NAM",
"DB180 HGT",
"AQ125 NFN",
"AQ125 NFI",
"AQ125 NAM",
"AQ125 FUN",
"AM060 WID",
"AM060 PPO",
"AM060 NFN",
"AM060 NFI",
"AM060 NAM",
"AM060 LEN",
"BD100 WLE",
"BD100 ARA",
"AM070 WID",
"AM070 VOI",
"AM070 SMC",
"AM070 NFN",
"AM070 NFI",
"AM070 NAM",
"AM070 LEN",
"AM070 HGT",
"AM070 AWP",
"AM070 ARA",
"AK160 WID",
"AK160 VOI",
"AK160 SSR",
"AK160 NFN",
"AK160 NFI",
"AK160 NAM",
"AK160 LEN",
"AK160 HGT",
"AK040 WID",
"AK040 SMC",
"AK040 NFN",
"AK040 NFI",
"AK040 NAM",
"AK040 LEN",
"AK040 ARA",
"AD020 WID",
"AD020 SMC",
"AD020 PPO",
"AD020 LEN",
"AD020 HGT",
"AD020 FUN",
"AF010 WID",
"AF010 VOI",
"AF010 SMC",
"AF010 NFN",
"AF010 NFI",
"AF010 NAM",
"AF010 LEN",
"AF010 HGT",
"AF010 FUN",
"AF010 AWP",
"BI040 LEN",
"AL105 PFH",
"AL105 NFN",
"AL105 NFI",
"AL105 NAM",
"GB065 ZVA",
"GB065 SMC",
"GB065 NAM",
"GB065 COD",
"GB065 CAA",
"DB160 RKF",
"DB160 NFN",
"DB160 NFI",
"DB160 NAM",
"DB160 HGT",
"AP020 RTN",
"AP020 RIT",
"AP020 NFN",
"AP020 NFI",
"AP020 NAM",
"AP020 NA3",
"AA040 VOI",
"AA040 SMC",
"AA040 PPO",
"AA040 NFN",
"AA040 NFI",
"AA040 NAM",
"AA040 LEN",
"AA040 HGT",
"BH120 NFN",
"BH120 NFI",
"BH120 NAM",
"BH120 LMC",
"BH120 LEN",
"AT045 SMC",
"AT045 NFN",
"AT045 NFI",
"AT045 NAM",
"AT045 LEN",
"AT045 HGT",
"AA012 PPO",
"AA012 NFN",
"AA012 NFI",
"AA012 NAM",
"AA012 ARA",
"AT042 VOI",
"AT042 TOS",
"AT042 HGT",
"AT042 CAT",
"AT042 CAB",
"AQ116 WID",
"AQ116 SMC",
"AQ116 PPO",
"AQ116 LEN",
"AQ116 HGT",
"AL210 LEN",
"AC000 VOI",
"AC000 PPO",
"AC000 PFH",
"AC000 NFN",
"AC000 NFI",
"AC000 NAM",
"AC000 LEN",
"AC000 HGT",
"AC000 ARA",
"AD030 WID",
"AD030 VOI",
"AD030 SMC",
"AD030 NFN",
"AD030 NFI",
"AD030 NAM",
"AD030 LEN",
"AD030 HGT",
"AD030 ARA",
"AD010 WID",
"AD010 VOI",
"AD010 SMC",
"AD010 PFH",
"AD010 NFN",
"AD010 NFI",
"AD010 NAM",
"AD010 LEN",
"AD010 HGT",
"AD010 ARA",
"BD110 VOI",
"BD110 SMC",
"BD110 NFN",
"BD110 NFI",
"BD110 NAM",
"BD110 HGT",
"BD110 AWP",
"BD110 AOO",
"AL240 VOI",
"AL240 TTC",
"AL240 SMC",
"AL240 NFN",
"AL240 NFI",
"AL240 NAM",
"AL240 LEN",
"AL240 HGT",
"AL240 AWP",
"BH170 SCC",
"BH170 NFN",
"BH170 NFI",
"BH170 NAM",
"ZD040 NFN",
"ZD040 NFI",
"ZD040 NAM",
"DB150 NFN",
"DB150 NFI",
"DB150 NAM",
"AQ110 VOI",
"AQ110 SMC",
"AQ110 NFN",
"AQ110 NFI",
"AQ110 NAM",
"AQ110 HGT",
"AQ110 AWP",
"AM040 PPO",
"AM040 LEN",
"AM040 HGT",
"SU001 NFN",
"SU001 NFI",
"SU001 NAM",
"AL130 WID",
"AL130 VOI",
"AL130 NFN",
"AL130 NFI",
"AL130 NAM",
"AL130 LEN",
"AL130 HGT",
"BB155 STA",
"BB155 NFN",
"BB155 NFI",
"BB155 NAM",
"BB155 COS",
"BI030 NFN",
"BI030 NFI",
"BI030 NAM",
"BI030 LEN",
"BC050 VOI",
"BC050 VDC",
"BC050 SMC",
"BC050 NFN",
"BC050 NFI",
"BC050 NAM",
"BC050 HGT",
"BC050 COS",
"GB040 ZVA",
"GB040 NFN",
"GB040 NFI",
"GB040 NAM",
"GB040 HGT",
"GB040 FUN",
"GB040 AWP",
"BJ060 NFN",
"BJ060 NFI",
"BJ060 NAM",
"BJ060 HGT",
"AL100 None",
"GB030 ZVA",
"GB030 WID",
"GB030 SMC",
"GB030 NAM",
"GB030 HGT",
"GB030 CAA",
"AD050 SMC",
"AD050 NFN",
"AD050 NFI",
"AD050 NAM",
"BD130 WLE",
"BD130 UHS",
"BD130 SMC",
"BD130 NFN",
"BD130 NFI",
"BD130 NAM",
"BD130 LEN",
"AM020 WID",
"AM020 VOI",
"AM020 SMC",
"AM020 PFH",
"AM020 NFN",
"AM020 NFI",
"AM020 NAM",
"AM020 LEN",
"AM020 HGT",
"AM020 AWP",
"AM030 WID",
"AM030 VOI",
"AM030 SMC",
"AM030 LEN",
"AM030 HGT",
"DB115 NFN",
"DB115 NFI",
"DB115 NAM",
"AL080 WID",
"AL080 TRS",
"AL080 SMC",
"AL080 LEN",
"AL080 HGT",
"AH050 WID",
"AH050 SMC",
"AH050 NFN",
"AH050 NFI",
"AH050 NAM",
"AH050 LEN",
"AH050 HGT",
"AH050 FUN",
"BH070 TRS",
"BH070 RST",
"BH070 NFN",
"BH070 NFI",
"BH070 NAM",
"AF070 VOI",
"AF070 SRL",
"AF070 SMC",
"AF070 LEN",
"AF070 HGT",
"AF070 FUN",
"AF070 DMF",
"AF070 AWP",
"AQ070 NFN",
"AQ070 NFI",
"AQ070 NAM",
"AQ070 FUN",
"AQ070 FCL",
"AA010 SSO",
"AA010 PPO",
"AA010 NFN",
"AA010 NFI",
"AA010 NAM",
"AA010 ARA",
"AQ090 NFN",
"AQ090 NFI",
"AQ090 NAM",
"AT010 VOI",
"AT010 SMC",
"AT010 LEN",
"AT010 HGT",
"BI020 VOI",
"BI020 SMC",
"BI020 NFN",
"BI020 NFI",
"BI020 NAM",
"BI020 LEN",
"BI020 HGT",
"BI020 DFT",
"BI020 AOO",
"AQ065 WID",
"AF040 VOI",
"AF040 TRS",
"AF040 SMC",
"AF040 NFN",
"AF040 NFI",
"AF040 NAM",
"AF040 HGT",
"AF040 FUN",
"AF030 VOI",
"AF030 SMC",
"AF030 NFN",
"AF030 NFI",
"AF030 NAM",
"AF030 LEN",
"AF030 HGT",
"AF030 AWP",
"AQ060 VOI",
"AQ060 TRS",
"AQ060 SMC",
"AQ060 NFN",
"AQ060 NFI",
"AQ060 NAM",
"AQ060 HGT",
"AQ060 AWP",
"AT080 VOI",
"AT080 TOS",
"AT080 SMC",
"AT080 NST",
"AT080 NFN",
"AT080 NFI",
"AT080 NAM",
"AT080 LOC",
"AT080 HGT",
"AT080 AWP",
"BI010 SMC",
"AH070 NFN",
"AH070 NFI",
"AH070 NAM",
"AL030 REL",
"AL030 NFN",
"AL030 NFI",
"AL030 NAM",
"DB030 NFN",
"DB030 NFI",
"DB030 NAM",
"AC020 VOI",
"AC020 SMC",
"AC020 NFN",
"AC020 NFI",
"AC020 NAM",
"AC020 HGT",
"AC020 FUN",
"AL025 NFN",
"AL025 NFI",
"AL025 NAM",
"AL020 ORD",
"AL020 NFN",
"AL020 NFI",
"AL020 NAM",
"AL020 HGT",
"AL015 WID",
"AL015 VOI",
"AL015 UUC",
"AL015 SUC",
"AL015 SMC",
"AL015 SFY",
"AL015 RES",
"AL015 PPO",
"AL015 PAF",
"AL015 NFN",
"AL015 NFI",
"AL015 NAM",
"AL015 MFC",
"AL015 LEN",
"AL015 ICF",
"AL015 HGT",
"AL015 EBT",
"AL015 DDC",
"AL015 CUS",
"AL015 CIT",
"AL015 CFC",
"AL015 CEF",
"AL015 CAA",
"AL015 ARA",
"AL015 AOO",
"AL015 AFC",
"BA050 SMC",
"BA050 NFN",
"BA050 NFI",
"BA050 NAM",
"AL012 NFN",
"AL012 NFI",
"AL012 NAM",
"GB010 NAM",
"GB010 LFA",
"GB220 VOI",
"GB220 SMC",
"GB220 PRM",
"GB220 NFN",
"GB220 NFI",
"GB220 NAM",
"GB220 HGT",
"GB220 AWP",
"GA035 NST",
"GA035 NAM",
"GA035 BRF",
"GA035 AWP",
"GA035 ART"
};

int MGCP3_P_OPTCOUNT = 455;


char *MGCP3_l_optional[] = {
"EC030 PFH",
"EC030 NFN",
"EC030 NFI",
"EC030 NAM",
"EC030 ISS",
"EC030 DMT",
"EC030 DMB",
"BH180 NFN",
"BH180 NFI",
"BH180 NAM",
"BI041 WID",
"BI041 GNC",
"AL260 WID",
"AL260 PFH",
"AL260 NFN",
"AL260 NFI",
"AL260 NAM",
"AL260 MOH",
"AQ130 WID",
"AQ130 NFN",
"AQ130 NFI",
"AQ130 NAM",
"AQ130 LEN",
"BB140 WID",
"BB140 LEN",
"AP050 NFN",
"AP050 NFI",
"AP050 NAM",
"DB010 PFH",
"DB010 NFN",
"DB010 NFI",
"DB010 NAM",
"BI040 None",
"BB230 WLE",
"BB230 WID",
"AP030 NFN",
"AP030 NFI",
"AP030 NAM",
"AP030 HCT",
"BH140 WST",
"BH140 TID",
"BH140 SHR",
"BH140 SHL",
"BH140 RBV",
"BH140 NFN",
"BH140 NFI",
"BH140 NAM",
"BH140 LBV",
"BH140 CDA",
"AK190 SMC",
"AK190 NFN",
"AK190 NFI",
"AK190 NAM",
"BH120 NFN",
"BH120 NFI",
"BH120 NAM",
"BH120 LMC",
"BH120 LEN",
"AN050 NFN",
"AN050 NFI",
"AN050 NAM",
"AN050 GAW",
"AN050 CTL",
"AN010 RTA",
"AN010 RRC",
"AN010 NFN",
"AN010 NFI",
"AN010 NAM",
"AN010 GAW",
"AK130 NFN",
"AK130 NFI",
"AK130 NAM",
"AL210 WID",
"AT030 VOI",
"AT030 TST",
"AT030 PFH",
"AT030 OWO",
"AT030 NPL",
"AT030 NFN",
"AT030 NFI",
"AT030 NAM",
"AT030 KVA",
"AT030 HGT",
"AQ113 OWO",
"AQ113 HGT",
"BI030 NFN",
"BI030 NFI",
"BI030 NAM",
"BA010 SLT",
"BA010 NFN",
"BA010 NFI",
"BA010 NAM",
"AQ075 NFN",
"AQ075 NFI",
"AQ075 NAM",
"BJ040 NFN",
"BJ040 NFI",
"BJ040 NAM",
"EA020 None",
"DB200 NFN",
"DB200 NFI",
"DB200 NAM",
"BB043 WLE",
"BB043 WID",
"BB043 LEN",
"FA090 WID",
"FA090 NFN",
"FA090 NFI",
"FA090 NAM",
"DB110 NFN",
"DB110 NFI",
"DB110 NAM",
"BH070 TRS",
"BH070 RST",
"BH070 NFN",
"BH070 NFI",
"BH070 NAM",
"BH060 LOC",
"AQ070 NFN",
"AQ070 NFI",
"AQ070 NAM",
"AQ070 FUN",
"AQ070 FCL",
"AL070 PFH",
"AL070 MOH",
"AL070 FTI",
"DB100 None",
"DB090 WID",
"DB090 PFH",
"DB090 NFN",
"DB090 NFI",
"DB090 NAM",
"BH030 WID",
"BH030 RBV",
"BH030 LBV",
"BH030 HYP",
"BH030 CDA",
"BI020 VOI",
"BI020 SMC",
"BI020 NFN",
"BI020 NFI",
"BI020 NAM",
"BI020 HGT",
"BI020 DFT",
"BI020 AOO",
"DB071 PFH",
"DB071 NFN",
"DB071 NFI",
"DB071 NAM",
"DB070 WID",
"DB070 PFH",
"DB070 NFN",
"DB070 NFI",
"DB070 NAM",
"DB061 WID",
"BJ031 WID",
"AF020 VOI",
"AF020 SMC",
"AF020 HGT",
"AF020 FUN",
"AF020 AWP",
"AT060 VOI",
"AT060 OWO",
"AT060 HGT",
"AT060 CLI",
"AT060 CAB",
"AQ064 WLE",
"AQ064 NFN",
"AQ064 NFI",
"AQ064 NAM",
"AQ064 HGT",
"AP010 WD1",
"AP010 NFN",
"AP010 NFI",
"AP010 NAM",
"BH020 RBV",
"BH020 NVS",
"BH020 NFN",
"BH020 NFI",
"BH020 NAM",
"BH020 LOC",
"BH020 LBV",
"AT041 NFN",
"AT041 NFI",
"AT041 NAM",
"AT041 HGT",
"AQ045 SMC",
"AQ045 FUN",
"AQ045 BSM",
"AQ040 WID",
"AQ040 WD1",
"AQ040 VOI",
"AQ040 SMC",
"AQ040 OHB",
"AQ040 NOS",
"AQ040 NFN",
"AQ040 NFI",
"AQ040 NAM",
"AQ040 MVC",
"AQ040 LC4",
"AQ040 LC3",
"AQ040 LC2",
"AQ040 LC1",
"AQ040 HCA",
"AQ040 BSC",
"AQ040 BOT",
"BB041 WLE",
"BB041 WID",
"BB041 LEN",
"BB190 WLE",
"BB190 WID",
"BB190 PWC",
"BB190 NFN",
"BB190 NFI",
"BB190 NAM",
"BB190 LEN",
"BB190 FAC",
"GB050 WID",
"GB050 SCB",
"GB050 PFH",
"GB050 NFN",
"GB050 NFI",
"GB050 NAM",
"GB050 LNU",
"GB050 HGT"
};

int MGCP3_L_OPTCOUNT = 225;


char *MGCP3_a_optional[] = {
"AK180 NFN",
"AK180 NFI",
"AK180 NAM",
"EC030 PFH",
"EC030 NFN",
"EC030 NFI",
"EC030 NAM",
"EC030 ISS",
"EC030 DMT",
"EC030 DMB",
"BH040 WID",
"BH040 NFN",
"BH040 NFI",
"BH040 NAM",
"DB180 VGT",
"DB180 NFN",
"DB180 NFI",
"DB180 NAM",
"DB180 HGT",
"ZD020 None",
"AQ140 RST",
"BJ110 SMC",
"BJ110 NFN",
"BJ110 NFI",
"BJ110 NAM",
"AQ125 NFN",
"AQ125 NFI",
"AQ125 NAM",
"AQ125 FUN",
"BB140 WID",
"BB140 LEN",
"BA040 NFN",
"BA040 NFI",
"BA040 NAM",
"BA040 NA2",
"EB020 PFH",
"EB020 NFN",
"EB020 NFI",
"EB020 NAM",
"EB020 DMB",
"FA100 NFN",
"FA100 NFI",
"FA100 NAM",
"GB075 WID",
"GB075 TXP",
"GB075 SCB",
"GB075 RST",
"GB075 NAM",
"GB075 LEN",
"GB075 ACS",
"ED020 VSP",
"ED020 VEG",
"ED020 TID",
"ED020 PFH",
"ED020 NFN",
"ED020 NFI",
"ED020 NAM",
"ED020 DMT",
"AM060 WID",
"AM060 PPO",
"AM060 NFN",
"AM060 NFI",
"AM060 NAM",
"AM060 LEN",
"BD100 WLE",
"AM070 WID",
"AM070 VOI",
"AM070 SMC",
"AM070 NFN",
"AM070 NFI",
"AM070 NAM",
"AM070 LEN",
"AM070 HGT",
"AM070 AWP",
"AM010 WID",
"AM010 VOI",
"AM010 PPO",
"AM010 NFN",
"AM010 NFI",
"AM010 NAM",
"AM010 LEN",
"AM010 HGT",
"GB045 WID",
"GB045 SCB",
"GB045 RST",
"GB045 NFN",
"GB045 NFI",
"GB045 NAM",
"GB045 LEN",
"GB045 ACS",
"AK160 VOI",
"AK160 SSR",
"AK160 NFN",
"AK160 NFI",
"AK160 NAM",
"AK160 HGT",
"AK040 SMC",
"AK040 NFN",
"AK040 NFI",
"AK040 NAM",
"DA010 NFN",
"DA010 NFI",
"DA010 NAM",
"BJ100 NFN",
"BJ100 NFI",
"BJ100 NAM",
"BB240 WLE",
"BB240 WID",
"BB240 SMC",
"BB240 NFN",
"BB240 NFI",
"BB240 NAM",
"BB240 LEN",
"AC030 WID",
"AC030 LEN",
"AL105 PFH",
"AL105 NFN",
"AL105 NFI",
"AL105 NAM",
"DB170 NFN",
"DB170 NFI",
"DB170 NAM",
"BH155 NFN",
"BH155 NFI",
"BH155 NAM",
"BH155 ASC",
"BH160 WID",
"BH160 NFN",
"BH160 NFI",
"BH160 NAM",
"GB055 ZVA",
"GB055 SCB",
"GB055 PRM",
"GB055 NAM",
"GB055 CAA",
"GB055 ACS",
"AL200 NFN",
"AL200 NFI",
"AL200 NAM",
"AL200 HGT",
"DB160 RKF",
"DB160 NFN",
"DB160 NFI",
"DB160 NAM",
"DB160 HGT",
"AQ135 NFN",
"AQ135 NFI",
"AQ135 NAM",
"BH140 WST",
"BH140 WID",
"BH140 TID",
"BH140 SHR",
"BH140 SHL",
"BH140 RBV",
"BH140 NFN",
"BH140 NFI",
"BH140 NAM",
"BH140 LBV",
"BH140 CDA",
"BH135 NFN",
"BH135 NFI",
"BH135 NAM",
"BH130 NFN",
"BH130 NFI",
"BH130 NAM",
"BH130 HYP",
"AB010 NFN",
"AB010 NFI",
"AB010 NAM",
"AB010 HGT",
"AK190 SMC",
"AK190 NFN",
"AK190 NFI",
"AK190 NAM",
"BH120 NFN",
"BH120 NFI",
"BH120 NAM",
"BH120 LMC",
"AN060 NFN",
"AN060 NFI",
"AN060 NAM",
"AN060 CTL",
"AA012 PPO",
"AA012 NFN",
"AA012 NFI",
"AA012 NAM",
"AQ116 WID",
"AQ116 SMC",
"AQ116 PPO",
"AQ116 LEN",
"AQ116 HGT",
"AL170 NFN",
"AL170 NFI",
"AL170 NAM",
"AC000 VOI",
"AC000 PPO",
"AC000 PFH",
"AC000 NFN",
"AC000 NFI",
"AC000 NAM",
"AC000 LEN",
"AC000 HGT",
"AD030 WID",
"AD030 VOI",
"AD030 SMC",
"AD030 NFN",
"AD030 NFI",
"AD030 NAM",
"AD030 LEN",
"AD030 HGT",
"AD010 WID",
"AD010 VOI",
"AD010 SMC",
"AD010 PFH",
"AD010 NFN",
"AD010 NFI",
"AD010 NAM",
"AD010 LEN",
"AD010 HGT",
"AL140 NFN",
"AL140 NFI",
"AL140 NAM",
"AL140 LEN",
"AK120 NFN",
"AK120 NFI",
"AK120 NAM",
"EC020 VSP",
"EC020 NFN",
"EC020 NFI",
"EC020 NAM",
"BJ020 NFN",
"BJ020 NFI",
"BJ020 NAM",
"BJ020 LEN",
"AM040 VOI",
"AM040 PPO",
"AM040 LEN",
"AM040 HGT",
"SU001 NFN",
"SU001 NFI",
"SU001 NAM",
"ED010 WLE",
"ED010 TID",
"ED010 NFN",
"ED010 NFI",
"ED010 NAM",
"BH050 NFN",
"BH050 NFI",
"BH050 NAM",
"BI030 WID",
"BI030 NFN",
"BI030 NFI",
"BI030 NAM",
"BI030 LEN",
"BH090 CNS",
"BH090 ASC",
"BH080 SCC",
"BH080 NFN",
"BH080 NFI",
"BH080 NAM",
"BA030 NFN",
"BA030 NFI",
"BA030 NAM",
"AA052 NFN",
"AA052 NFI",
"AA052 NAM",
"AJ030 NFN",
"AJ030 NFI",
"AJ030 NAM",
"GB035 ZVA",
"GB035 NAM",
"GB035 CAA",
"AD050 SMC",
"AD050 NFN",
"AD050 NFI",
"AD050 NAM",
"BB008 NFN",
"BB008 NFI",
"BB008 NAM",
"BB005 NFN",
"BB005 NFI",
"BB005 NAM",
"BB005 FHC",
"DB200 NFN",
"DB200 NFI",
"DB200 NAM",
"BB043 WLE",
"BB043 WID",
"BB043 LEN",
"EB010 VEG",
"EB010 NFN",
"EB010 NFI",
"EB010 NAM",
"AM020 WID",
"AM020 VOI",
"AM020 SMC",
"AM020 PFH",
"AM020 NFN",
"AM020 NFI",
"AM020 NAM",
"AM020 LEN",
"AM020 HGT",
"AM020 AWP",
"AM030 WID",
"AM030 VOI",
"AM030 SMC",
"AM030 LEN",
"AM030 HGT",
"AK100 NFN",
"AK100 NFI",
"AK100 NAM",
"BJ030 NFN",
"BJ030 NFI",
"BJ030 NAM",
"DB115 NFN",
"DB115 NFI",
"DB115 NAM",
"AH050 WID",
"AH050 SMC",
"AH050 NFN",
"AH050 NFI",
"AH050 NAM",
"AH050 HGT",
"AH050 FUN",
"EC060 None",
"FA015 NFN",
"FA015 NFI",
"FA015 NAM",
"FA015 FUN",
"AK090 NFN",
"AK090 NFI",
"AK090 NAM",
"AA010 SSO",
"AA010 PPO",
"AA010 NFN",
"AA010 NFI",
"AA010 NAM",
"DB090 PFH",
"DB090 NFN",
"DB090 NFI",
"DB090 NAM",
"DB090 LEN",
"BB090 WID",
"BB090 NFN",
"BB090 NFI",
"BB090 NAM",
"BB090 LEN",
"BH030 WID",
"BH030 RBV",
"BH030 LBV",
"BH030 HYP",
"BH030 CDA",
"AB000 VOI",
"AB000 PBY",
"AB000 NFN",
"AB000 NFI",
"AB000 NAM",
"AB000 HGT",
"BI020 WID",
"BI020 VOI",
"BI020 SMC",
"BI020 NFN",
"BI020 NFI",
"BI020 NAM",
"BI020 LEN",
"BI020 HGT",
"BI020 DFT",
"BI020 AOO",
"EA010 TRE",
"EA010 PPO",
"EA010 PFH",
"EA010 NFN",
"EA010 NFI",
"EA010 NAM",
"EA010 IRG",
"EA010 FMM",
"EA010 DMT",
"EA010 CSP",
"DB061 None",
"BJ031 None",
"AT050 VOI",
"AT050 SMC",
"AT050 NFN",
"AT050 NFI",
"AT050 NAM",
"AT050 LEN",
"AT050 HGT",
"AT050 FUN",
"EC040 WID",
"EC040 NFN",
"EC040 NFI",
"EC040 NAM",
"EC040 LEN",
"AJ010 NFN",
"AJ010 NFI",
"AJ010 NAM",
"AJ010 LEN",
"AL030 REL",
"AL030 NFN",
"AL030 NFI",
"AL030 NAM",
"EC010 NFN",
"EC010 NFI",
"EC010 NAM",
"BH020 WID",
"BH020 RBV",
"BH020 NVS",
"BH020 NFN",
"BH020 NFI",
"BH020 NAM",
"BH020 LOC",
"BH020 LBV",
"AK060 NFN",
"AK060 NFI",
"AK060 NAM",
"AL020 ORD",
"AL020 NFN",
"AL020 NFI",
"AL020 NAM",
"AL020 HGT",
"AL015 WID",
"AL015 VOI",
"AL015 UUC",
"AL015 SUC",
"AL015 SMC",
"AL015 SFY",
"AL015 RES",
"AL015 PPO",
"AL015 PAF",
"AL015 NFN",
"AL015 NFI",
"AL015 NAM",
"AL015 MFC",
"AL015 ICF",
"AL015 HGT",
"AL015 EBT",
"AL015 DDC",
"AL015 CUS",
"AL015 CIT",
"AL015 CFC",
"AL015 CEF",
"AL015 CAA",
"AL015 AOO",
"AL015 AFC",
"BB041 WLE",
"BB041 WID",
"BB041 LEN",
"BH015 NFN",
"BH015 NFI",
"BH015 NAM",
"BB190 WLE",
"BB190 WID",
"BB190 PWC",
"BB190 NFN",
"BB190 NFI",
"BB190 NAM",
"BB190 LEN",
"BB190 FAC",
"BA050 SMC",
"BA050 NFN",
"BA050 NFI",
"BA050 NAM",
"AL012 NFN",
"AL012 NFI",
"AL012 NAM",
"GB015 WID",
"GB015 SCB",
"GB015 NAM",
"GB015 ACS",
"AK030 NFN",
"AK030 NFI",
"AK030 NAM",
"AK030 HGT",
"GB005 NAM"
};

int MGCP3_A_OPTCOUNT = 474;


