/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
#include "share.h"
int MGCP4_CLASS_NUM=196;

char *MGCP4_class_codes[] = {
"GB220",
"GA034",
"GB230",
"GB050",
"AK030",
"GB485",
"GB015",
"BH010",
"AL012",
"BA050",
"BB190",
"BH015",
"BB041",
"AQ040",
"AL020",
"AT041",
"AL025",
"AI030",
"AK060",
"BH020",
"EC010",
"AP010",
"AC020",
"AQ063",
"DB029",
"AL030",
"AH070",
"AJ010",
"BI010",
"EC040",
"AT060",
"AT050",
"AF020",
"AF040",
"BJ031",
"DB061",
"EA010",
"AQ065",
"DB070",
"DB071",
"BI020",
"AT010",
"AB000",
"BH030",
"AL060",
"BB090",
"AD010",
"DB090",
"AH025",
"AQ090",
"DB100",
"AA010",
"AL010",
"AK090",
"AL070",
"AQ070",
"FA015",
"BH051",
"AF070",
"BH060",
"BH070",
"EC060",
"AH050",
"AL015",
"DB110",
"FA090",
"DB115",
"BJ030",
"AK100",
"AM030",
"AM020",
"EB010",
"AJ110",
"BB043",
"DB200",
"BB005",
"BD130",
"AD050",
"EA020",
"GB030",
"GB035",
"AJ030",
"EA055",
"AL099",
"AA052",
"BJ040",
"BJ060",
"AQ075",
"BA030",
"BH080",
"GB005",
"BH090",
"BA010",
"GB040",
"BI030",
"ED030",
"BH050",
"BB155",
"ED010",
"AL130",
"SU001",
"AM040",
"AQ110",
"BJ020",
"DB150",
"ZD040",
"BH170",
"EC020",
"BD110",
"EA040",
"AK120",
"AL140",
"BH110",
"AQ113",
"AT030",
"AD030",
"AC000",
"AL210",
"AL170",
"AQ116",
"AT042",
"AA012",
"AK130",
"AT045",
"AN010",
"AN050",
"AN075",
"AN060",
"BH120",
"AK190",
"AB010",
"BD120",
"BH130",
"BH135",
"AA040",
"BH140",
"AP030",
"AQ135",
"DB160",
"AN076",
"AL200",
"GB055",
"BH160",
"BH155",
"BH150",
"DB170",
"BB230",
"AL105",
"AC030",
"AL208",
"AL019",
"AK150",
"BB240",
"BI040",
"AF010",
"BJ100",
"DA010",
"AD020",
"BH165",
"AK040",
"AK160",
"DB010",
"GB045",
"AM010",
"AM070",
"BD100",
"AM060",
"ED020",
"AK170",
"GB075",
"FA100",
"EB020",
"BA040",
"AL241",
"AP050",
"BB140",
"AQ125",
"BJ110",
"AQ130",
"BH145",
"AQ140",
"EA050",
"ZD020",
"DB180",
"AL260",
"GB065",
"BI041",
"BI050",
"BH040",
"BH180",
"AA050",
"AJ051",
"AJ050",
"EC030",
"BD180",
"AK180"
};

char *MGCP4_class_names[] = {
"Aeronautical Obstacle",
"Aeronautical Radio Navigation Service",
"Aircraft Hangar",
"Aircraft Revetment",
"Amusement Park",
"Approach Lighting System",
"Apron",
"Aqueduct",
"Archeological Site",
"Beach",
"Berthing Structure",
"Bog",
"Breakwater",
"Bridge",
"Built-Up Area",
"Cableway",
"Cairn",
"Camp",
"Camp-site",
"Canal",
"Cane",
"Cart Track",
"Catalytic Cracker",
"Causeway Structure",
"Cave Mouth",
"Cemetery",
"Checkpoint",
"Circular Irrigation System",
"Cistern",
"Cleared Way",
"Communication Line",
"Communication Station",
"Conveyor",
"Crane",
"Crevasse",
"Crevice",
"Crop Land",
"Culvert",
"Cut",
"Cut Line",
"Dam",
"Dish Aerial",
"Disposal Site",
"Ditch",
"Dragon's Teeth",
"Dry Dock",
"Electric Power Station",
"Embankment",
"Engineered Earthwork",
"Entrance and/or Exit",
"Esker",
"Extraction Mine",
"Facility",
"Fairground",
"Fence",
"Ferry Crossing",
"Firing Range",
"Fish Farm Facility",
"Flare Pipe",
"Flume",
"Ford",
"Forest Clearing",
"Fortification",
"General Building",
"Geologic Fault",
"Geophysical Prospecting Grid",
"Geothermal Outlet",
"Glacier",
"Golf Course",
"Grain Elevator",
"Grain Storage Structure",
"Grassland",
"Greenhouse",
"Groin",
"Gully",
"Harbour",
"Hazardous Rock",
"Heating Facility",
"Hedgerow",
"Helipad",
"Heliport",
"Holding Pen",
"Hop Field",
"Hut",
"Hydrocarbons Field",
"Ice Cliff",
"Ice Peak",
"Ice Route",
"Island",
"Lake",
"Land Aerodrome",
"Land Subject to Inundation",
"Land Water Boundary",
"Launch Pad",
"Lock",
"Mangrove Swamp",
"Mariculture Site",
"Maritime Signal Station",
"Marsh",
"Memorial Monument",
"Military Installation",
"Mineral Pile",
"Mooring Mast",
"Moraine",
"Mountain Pass",
"Named Location",
"Natural Pool",
"Oasis",
"Offshore Platform",
"Orchard",
"Park",
"Particle Accelerator",
"Penstock",
"Pipeline",
"Power Line",
"Power Substation",
"Processing Facility",
"Protection Shed",
"Public Square",
"Pumping Station",
"Pylon",
"Quarry",
"Racetrack",
"Radar Station",
"Railway",
"Railway Sidetrack",
"Railway Turntable",
"Railway Yard",
"Rapids",
"Recreational Pier",
"Recycling Site",
"Reef",
"Reservoir",
"Rice Field",
"Rig",
"River",
"Road",
"Roadside Rest Area",
"Rock Formation",
"Roundhouse",
"Ruins",
"Runway",
"Sabkha",
"Salt Evaporator",
"Salt Flat",
"Sand Dunes",
"Seawall",
"Settlement",
"Settling Pond",
"Shanty Town",
"Shed",
"Ski-jump",
"Slipway",
"Sluice Gate",
"Smokestack",
"Snow Field and/or Ice-field",
"Soil Surface Region",
"Solar Panel",
"Spillway",
"Sports Ground",
"Stadium",
"Steep Terrain Face",
"Stopway",
"Storage Depot",
"Storage Tank",
"Structural Pile",
"Surface Bunker",
"Swamp",
"Swimming Pool",
"Taxiway",
"Test Site",
"Thicket",
"Tidal Water",
"Tower",
"Trail",
"Training Wall",
"Transportation Station",
"Tundra",
"Tunnel",
"Vanishing Point",
"Vehicle Lot",
"Vineyard",
"Void Collection Area",
"Volcano",
"Wall",
"Water Aerodrome",
"Water Gate",
"Water Intake Tower",
"Water Treatment Bed",
"Waterfall",
"Well",
"Wind Turbine",
"Windmill",
"Wood",
"Wreck",
"Zoo"
};

char *MGCP4_class_defns[] = {
"Any object, or part thereof, or terrain which rises far enough above the surrounding surface or above a specified height to create a hazard to aircraft operations. ( Obstacle objects may be fixed (whether temporary or permanent) or mobile. )",
"A service providing aeronautical navigation guidance information or position data, intended for the benefit and safe operation of aircraft.",
"A building for housing aircraft.",
"A barricade that protects an aircraft, equipment, and/or facility from hostile action.",
"A predominantly man-made facility equipped with recreational devices.",
"An airport lighting facility which provides visual guidance to landing aircraft by radiating light beams in a directional pattern by which the pilot aligns the aircraft with the final approach path for landing.",
"A defined area, on a land aerodrome/heliport, intended to accommodate aircraft/helicopters for purposes of loading and unloading passengers, mail or cargo, and for fuelling, parking or maintenance.",
"A pipe or artificial channel that is designed to transport water from a remote source, usually by gravity, for freshwater supply, agricultural, and/or industrial use. ( It may be supported by a bridge. )",
"A site where remains of past civilizations or human activity have been discovered.",
"On a shore, the area on which the waves break and over which shore debris (for example: sand, shingle, and/or pebbles) accumulate. ( A beach includes backshore and foreshore. )",
"A structure primarily used as a berthing place for vessels. ( For example, a pier, a wharf, and a quay. Consideration should be given to using the more general Feature: 'Shoreline Construction' and a type-discriminating attribute. )",
"A permanently wet area of land consisting of incompletely decayed organic material and mainly stagnant fresh water. ( It is generally too soft to bear the weight of any heavy body. A subtype of the more generalized Feature: 'Wetland'. )",
"A structure that protects a waterbody region (for example: a shore, a harbour, and/or an anchorage) from water waves by preventing them from reaching the protected region or reducing their magnitude.",
"A structure that connects two locations and provides for the passage of a transportation route (for example: a road or a railway) over a terrain obstacle (for example: a waterbody, a gully, and/or a road). ( A bridge consists of a set of two abutments and/or zero or more bridge piers joined by bridge spans. A bridge may serve, for example, as an overpass or a viaduct. In the context of a bridge, the scope of the term 'transportation route' includes the transportation of liquids or gases by means of either pipelines or aqueducts. )",
"A tract containing a concentration of buildings and/or other structures.",
"A transportation system consisting of load cables strung between pylons on which carrier units (for example: cars or buckets intended to transport people, material, and/or equipment) are suspended. ( For example, a ski-lift. )",
"A heap of stones piled up as a memorial or a landmark.",
"An encampment where tents and/or other easily moveable structures (for example: yurts) serve as full-time, temporary, or seasonal residences.",
"A designated place for recreational camping.",
"An artificial waterway with no flow, or a controlled flow, usable or built for navigation.",
"A tract covered mainly by large treelike grasses. ( For example, bamboo and sugarcane. )",
"An unimproved road. ( The surface is usually rough (for example: rutted) and minimally prepared (for example: packed earth or thinly covered with gravel). )",
"A device in which the separation of petroleum is carried out in the presence of a catalyst.",
"A solid raised way across a terrain obstacle (for example: a wetland or a body of shallow water) that is intended to support a transportation route (for example: a road or a railway). (The causeway structure is often constructed from local fill supplemented by other materials (for example: rocks, boulders or gravel) and consists of a solid linear structure in the configuration of an embankment. Causeway structures are built just high enough to insure that the transportation route will remain passable during periods of flooding, tides and seasonal rainfall. Culverts may occur along the length of the causeway structure and individual sections of the causeway structure may be interrupted by bridges. )",
"The entrance to an interconnected series of subterranean chambers. ( Typically located in limestone, and often open to the Earth's surface either vertically or horizontally. )",
"A site and associated structures devoted to the burial of the dead.",
"A location to control passage and/or to register, declare and/or inspect goods, vehicles and/or people.",
"An elevated irrigation system revolving around a central pivot point.",
"A man-made container used for the collection and/or storage of water.",
"A man-made cleared strip through a vegetated region. ( May be designed to: provide access for a road, railroad, pipeline, power transmission line, or electrical signal line; demarcate a boundary; obtain survey line-of-sight; or to impede the progress of forest fires (a firebreak). )",
"A cable that transmits communication signals. ( For example, a telephone line, a telegraph line, or a fibreoptic cable. )",
"A facility in which communication signals are processed and/or controlled. ( For example, a telephone switching station, a microwave repeater station, a satellite ground station, cellular telephone equipment, and a land-line telephone repeater station. )",
"A mechanical device for conveying articles or materials during manufacture or processing using an endless moving belt or series of rollers.",
"Equipment for lifting, shifting, and lowering objects or materials by means of a swinging boom or with the lifting apparatus supported on an overhead track.",
"A deep crack or fissure in a glacier that results from differential movement of ice.",
"A narrow opening or fissure produced by a crack in the land, especially in rock. ( May also describe a deep vertical opening in the terrain that appears after an earthquake. )",
"An area that has been tilled for the planting of crops.",
"An enclosed channel for carrying a watercourse (for example: a stream, a sewer, or a drain) under a route (for example: a road, a railway, or an embankment). ( Usually the construction of the route is unaffected. )",
"An excavation in the terrain to provide passage for a land or water transportation route (for example: a road, a railway, and/or a canal).",
"The demarcation line between a cut and the surrounding land surface.",
"A barrier constructed to hold back water and raise its level to form a reservoir or to prevent flooding.",
"A concave-shaped aerial that is used for emitting and/or sensing electromagnetic energy. ( For example, used to transmit and/or receive electronic signals as at a satellite station or to capture electromagnetic energy as in radio astronomy. )",
"A site for the collection and/or deposition of refuse or discarded material.",
"An artificial waterway with no flow, or a controlled flow, usually unlined, used for draining or irrigating land.",
"Upward-pointing obstacles laid in the ground to slow or stop the movement of vehicles. ( Typically constructed of regularly spaced concrete or metal shapes laid in single or multiple rows. )",
"An artificial basin fitted with a gate or caisson into which vessels can be floated and the water pumped out to expose the bottom of the vessel.",
"A facility including one or more buildings and equipment used for electric power generation. ( An electric power station consists of one or more power generating units, each consisting of the full set of equipment required to generate power and capable of independent operation. The power generating units are located on one or more contiguous or adjacent properties, are under the common control of the same entity and supply power through a common connection to the electric grid. Electric power stations most commonly are used to generate electricity for long distance transmission. )",
"A man-made raised long mound of earth or other material.",
"An excavation and/or embankment created by remolding the natural configuration of the terrain for the purpose of enhancing the defense of a site from armed attack. ( The earthwork may include ancillary elements (for example: a palisade) or reinforcements (for example: a concrete facing). )",
"A location of entrance and/or exit. ( For example, a cave mouth or a doorway. )",
"A long, narrow ridge of sand and gravel deposited by a glacial stream.",
"An excavation made in the terrain for the purpose of extracting and/or exploiting natural resources.",
"An area that has been developed to perform a specific principal function, consisting of one or more vertical constructions (for example: structures or buildings), horizontal constructions (for example: pavements, roads, rail tracks, or bridges), and/or supporting utilities (for example: power lines, water supply, or sewerage), plus the underlying land. ( For example, an industrial plant consisting of building(s), shipping dock(s), storage area(s), power transformer(s), heating and/or cooling equipment, vehicle parking, roads, railroad tracks, and perimeter fences and gates. )",
"An area where permanent facilities exist to hold outdoor fairs, circuses or exhibitions.",
"A man-made barrier of relatively light structure used as an enclosure or boundary. ( Similar structures that are constructed of heavy materials (for example: stone, rock or masonry) are classified as walls. )",
"A route where a ferry crosses from one shore to another.",
"A site designated for the purpose of discharging firearms or detonating munitions.",
"A facility involved in the breeding (hatching and associated activities) and cultivation (raising for release or harvesting) of fish in tanks or landlocked enclosures. ( Fish species raised on fish farms include, for example, salmon, catfish, tilapia, cod, carp, and trout. )",
"An open-ended pipe at which waste gases are burned.",
"An inclined channel for conveying water from a distance. ( For example, carries water to be utilized for power, transportation, and/or irrigation. )",
"A shallow place in a body of water used as a crossing.",
"A site in a forest or wood(s) that has been cleared, often for slash and burn agriculture and/or as a result of clear-cutting logging. ( May also occur from natural causes such as a forest fire. )",
"A structure constructed for the military defence of a site. ( For example, a bastion and a rampart. )",
"A relatively permanent structure, roofed and usually walled and designed for some particular use.",
"A fracture or zone of fractures in a rock formation, marked by the relative displacement on either side of the plane of the fracture. ( The intersection of a geologic fault with the ground surface is termed the 'fault trace' and is commonly plotted on maps to represent a fault. Since geologic faults do not usually consist of a single, clean fracture, the term 'fault zone' (or 'distributed fault') is often used when referring to the zone of complex deformation and numerous small fractures that is associated with the fault plane. )",
"A grid established for the collection of geophysical data within an area. ( The grid is typically composed of one or more series of observation points where each series is obtained along a single track and the grid is then assembled from multiple tracks. )",
"A terrain surface feature controlled by or derived from the heat of the Earth's interior. ( For example, a hot spring. )",
"A large mass or river of ice formed by accumulation and compaction of snow on higher ground that is moving slowly down a slope or valley from above the snowline.",
"A tract of land on which golf is played.",
"A tall structure, equipped for loading, unloading, processing, and/or storing grain.",
"An enclosed container, used for storing grain or fodder.",
"A tract covered mainly by grasses that have little or no woody tissue. ( For example, pasture, meadow, and steppe. )",
"A building constructed primarily of transparent material (for example: glass or plastic), in which temperature and humidity can be controlled for the cultivation and/or protection of plants.",
"A low artificial wall-like structure of durable material extending from the land to seaward for a particular purpose, such as to prevent coast erosion.",
"A deep ditch or channel cut into the terrain that results from erosion due to surface water runoff.",
"A natural or artificial improved body of water providing protection for vessels and generally anchorage and docking facilities. ( A harbour consists of both its port (see Feature: 'Port') and its waters (see Feature: 'Harbour Waters'). )",
"An isolated rocky formation or a single large stone or coral, usually one constituting a danger to navigation. ( May be either dry, awash, or below the water surface. )",
"A facility for the generation of thermal energy for heating purposes.",
"A continuous growth of shrubs planted as a fence, a boundary, and/or a windbreak.",
"A designated area, usually with a prepared surface, used for the take-off, landing, or parking of helicopters. ( This prepared surface could either be located on land or on a platform over water. It may or may not be associated with an aerodrome. For example: a hospital helipad, and an offshore rig helipad. )",
"An aerodrome intended to be used for the arrival, landing, takeoff or departure of vertical takeoff and landing aircraft/helicopters.",
"An enclosed tract on which livestock are temporarily kept. ( For example, a sheepfold, a holding paddock, a livestock pen, a feedlot, and/or a stock yard. The enclosure may be by, for example, a fence or a wall. )",
"A tract covered by the systematic planting of hop vines.",
"A small, simple free-standing (detached) self-contained residence usually having only a single multi-function room. ( May be intended only as temporary (for example: by displaced persons) or seasonal (for example: during seasonal livestock movement) residence. May be crude (for example: quickly built from locally-available natural materials) or relatively modern in construction and austerely furnished (for example: a Norwegian 'hytte'). )",
"An area where the presence of recoverable petroleum, oil, and/or natural gas has been identified. ( The field can exist regardless of current exploitation activities. )",
"The vertical face of a glacier or ice shelf.",
"A rocky peak projecting above a surrounding ice field that may be perpetually covered with ice.",
"A route over a frozen watercourse. ( Usually marked and intended to support substantial vehicle traffic. Often designed as an alternate to a seasonally-closed ferry crossing (see Feature: 'Ferry Crossing'). )",
"A land mass, other than a continent, surrounded by water.",
"A large body of water entirely surrounded by land.",
"An aerodrome on land intended to be used either wholly or in part for the arrival, departure and surface movement of aircraft.",
"A tract periodically covered by flood water, excluding tidal waters.",
"The line where a land mass is in contact with a body of water and the tide state or river stage are unspecified. ( It may be in either the littoral or inland waters. In the littoral, consideration should be given to using the more specific high water or low water lines based on the nature of the source data collection. )",
"A designated site or structure from which a rocket or missile is launched.",
"An enclosure with a pair or series of gates used for raising or lowering vessels as they pass from one water level to another.",
"A dense thicket of mangrove that is subject to tidal inundation and forming a muddy swamp.",
"A site where marine organisms are cultivated for food and other products in either the open ocean, in an enclosed section of the ocean, or in tanks, ponds or raceways that are filled with seawater (for example: the farming of marine fish, prawns, or oysters in saltwater ponds).",
"A place on shore from which signals are made to vessels at sea.",
"A soft, poorly drained wetland that is characterized by the growth of only non-woody plants (for example: grasses) and often forms a transition region between a waterbody and land. ( It is subject to frequent or tidal inundations, but not considered to be continually under water. It lacks trees. A subtype of the more generalized Feature: 'Wetland'. )",
"A marker erected and/or maintained as a memorial to a person and/or event.",
"An installation designed for military use. ( For example, used to perform military operations, initiate forward movements, and/or furnish supplies. Often protected by fortifications or natural advantages. )",
"A man-made heap of mining or quarrying products that does not contain waste materials. ( For example, a pile of coal or quarried stones. )",
"A mast used to secure an airship.",
"An accumulation of soil and stone debris deposited by a glacier.",
"A narrow route through a mountainous region or over a mountain range.",
"A location that normally does not appear as a specific, characterized object but that has a name that is required to be displayed in association with that location. ( For example, the name of the Alps or the Sahara. )",
"A naturally formed pool of water. ( It is usually fed by surface drainage from the surrounding region and/or water arising from an underground source (for example: a spring or a resurgence). )",
"A small, isolated, fertile or green area in a desert region usually having a spring or well.",
"An offshore structure with a flat surface raised above the sea, used as a working stage for conducting offshore operations. ( May be fixed or floating. )",
"A tract covered by systematic plantings of trees that yield fruits (including nuts).",
"An area used for recreational or ornamental purposes.",
"An apparatus for imparting high velocities to charged particles.",
"A pipeline that is used by hydroelectric plants to transport water by gravity from a reservoir to the turbine(s).",
"A connected set of pipes for conveying liquids, slurries, or gases. ( Usually for long distances and often located underground. )",
"A cable that transmits or distributes electrical power. ( Long distance power transmission lines are typically operated at high voltages (for example, 500 kilovolts) whereas local power distribution lines are typically operated at much lower voltages (usually less than one kilovolt). )",
"A facility, along a power transmission line, in which electric current is switched, transformed, and/or converted.",
"A facility including one or more buildings used for processing materials. ( For example, a treatment plant. )",
"A shelter built to protect a section of road or railway from slides of snow and/or rock. ( For example, a snow shed or a rock shed. )",
"An open site that serves as a public meeting location in a built-up area.",
"A facility to move solids, liquids or gases by means of pressure or suction.",
"A pylon or pole used to support one or more cables.",
"An open-air excavation created by removal of stone by blasting or cutting.",
"A ground or tract marked out for racing. ( The track may be banked to facilitate high-speed racing, either by grading of the terrain or the use of structures. The bank angle may exceed 30 arc degrees and such structures can reach significant heights. )",
"A facility utilizing radar to detect and analyze objects (for example: aircraft, artificial satellites, asteroids, and/or missiles) and/or environmental phenomena (for example: tornadoes). ( May include both a radar aerial as well as a structure housing radar equipment. )",
"One or more railway tracks comprising a network that is operated for the conveyance of passengers and/or goods.",
"A stretch of railway track connected to a main railway and used for temporary storage, passing, loading, and/or unloading.",
"A rotating platform with railway tracks used for turning locomotives and/or railway carriages. ( May be enclosed within a structure. )",
"A system of railway tracks and associated structures that are located within defined limits and that provide for loading, unloading, and/or assembling trains.",
"Portions of a stream with accelerated current where it descends rapidly but without a break in the slope of the bed sufficient to form a waterfall. ( The surface is usually broken by boulders and rocks. )",
"A structure extending into the water used as a platform for recreational purposes, not intended as a berthing place for vessels. ( For example, a fishing pier or a promenade pier. )",
"A site engaged in the wrecking, dismantling, storage, recycling, and/or disposal of discarded or scrap products. ( For example, a wrecking yard or a scrap yard. )",
"A mass of rock or coral which either reaches close to the sea surface or is exposed at low tide, posing a hazard to navigation.",
"A substantial lake-like body of water impounded by a dam. ( May be used for flood control and/or as a source of water for irrigation, industrial processes, and/or human consumption. )",
"A tract that is periodically covered with water and is used for growing rice.",
"A superstructure fitted for drilling or lifting operations for extraction and/or exploitation of natural resources.",
"A natural flowing watercourse.",
"A route with a specially prepared surface that is intended for use by wheeled vehicles.",
"A roadside place usually having facilities for people and/or vehicles.",
"A significant outcropping of exposed bedrock.",
"A circular or semicircular building, with a railway turntable in the centre, used for storing and/or repairing railway locomotives. ( The railway turntable may be either completely covered, partially covered or not covered, and partially or completely surrounded by the building. )",
"The deteriorated remains of an unspecified structure.",
"A defined rectangular area on a land aerodrome prepared for the landing and take-off of aircraft.",
"A natural depression in arid or semi-arid regions whose bed is covered with salt encrusted clayey soil. ( Found especially in North Africa and Arabia. )",
"Shallow pools, normally man-made, used for the natural evaporation of water for the collection of salt.",
"A flat area of natural surface salt deposits. ( May also be used to describe smaller areas; these are commonly termed salt pans. )",
"One or more mounds or ridges of sand usually formed by the wind.",
"An embankment or wall for protection against waves or tidal action along a shore or water front.",
"A continuously occupied concentration of tents or lightweight fixed structures (for example: huts) serving as residences. ( May also include supporting non-residential (for example: commercial) structures. )",
"A small reservoir where solid matter is precipitated from a liquid by evaporating or settling.",
"A section of a built-up area consisting chiefly of densely packed shacks and having few, if any, streets and no public facilities. ( Usually located on the outskirts of the built-up area. The shacks are generally crude, improvised, and made from salvaged materials. )",
"A small building, generally of light construction, that usually has one or more open sides. ( Typically used for storage. )",
"A man-made structure consisting of a steep ramp levelling off at the end and built on a natural slope, used in ski-jumping.",
"The prepared and usually reinforced inclined surface on which keel- and bilge-blocks are laid for supporting a vessel under construction. ( Rails associated with a slipway are usually represented separately, for example as a marine railway. )",
"A gate used to regulate the flow or level of water in a watercourse (for example: stream, irrigation ditch, or sluice). ( Sluice gates are normally installed in a superstructure and/or frame and most commonly slide vertically to open but on occasion may instead slide horizontally. When opened they allow water to flow under or beside the gate. Commonly sluice gates will be installed perpendicular to the orientation of the flow of water within a watercourse and will be constructed as wide as the watercourse they regulate. Sluice gates may also be installed along the margins of watercourses for the purpose of controlling or permitting the flow of water to or from that watercourse into adjacent watercourses. Sluice gates may be used to regulate both tidal or non-tidal waters. )",
"A vertical structure containing a passage or flue for discharging smoke and gases of combustion.",
"A large area permanently covered by snow and/or ice. ( May cover land and/or water. )",
"A region of the land that is homogeneous with respect to a soil characteristic.",
"A panel designed to absorb the sun's rays for the purpose of generating electricity or heat.",
"A passage for surplus water to run over or around a dam.",
"An open area where sporting events, exercises, and/or games occur. ( For example, an athletic field, a playing field, and/or a sports field. )",
"An arena for holding and viewing events.",
"A steep, vertical, or overhanging face of rock and/or soil. ( For example, an escarpment, a bluff, or a cliff. )",
"A defined rectangular area on the ground at the end of the take-off run available that has been prepared as a suitable area in which an aircraft can be stopped in the case of an abandoned take-off.",
"A tract used for the storage of products and/or supplies.",
"A container used for the storage of liquids and/or gases that is not supported by a tower.",
"A long pile (for example: a heavy timber or section of steel, wood, or concrete) forced into the earth that may serve as a support (for example: for a pier) or as a free standing pole within a marine environment.",
"A surface structure that may be covered and/or surrounded with earth and is resistant to ordnance. ( Used, for example, for storage and/or aircraft protection. )",
"A seasonally flooded, poorly drained wetland with more woody plants than a marsh and better drainage than a bog. ( It is covered with water all or most of the year, and accumulating dead vegetation does not rapidly decay. It can exist on flat-lying areas created by certain geomorphic environments. The vegetation mainly consists of hydrophytic trees and/or scrubs whose roots are adapted to wet conditions, with an open to very dense canopy closure. A subtype of the more generalized Feature: 'Wetland'. )",
"A man-made pool used for swimming outdoors.",
"A defined path at an aerodrome established for the taxiing of aircraft and intended to provide a ground movement link between one part of the aerodrome and another.",
"A site for the testing of technical products and equipment.",
"A tract covered mainly by low-growing, uncultured, woody plants that are thickly tangled together. ( For example, covered by brushwood and/or stunted trees. The predominant height may be up to 6-8 metres. )",
"Any water the level of which changes periodically due to tidal action.",
"A relatively tall, narrow structure that may either stand alone or may form part of another structure. ( Usually of a square, circular, or rectangular cross-section. )",
"A path worn by the passage of people or animals.",
"A wall, bank or jetty often submerged, built to direct or confine the flow of a river or tidal current or to promote scour actions.",
"A station that serves as a stopping place along a transportation route. ( For example, used for the transfer of passengers and/or freight. )",
"A vast, nearly level, treeless arctic region usually with a marshy surface and underlying permafrost.",
"An underground passage that is open at both ends and usually contains a land transportation route (for example: a road and/or a railway). ( Commonly used to pass through a hill or mountain, or under a river or road. May also provide underground passage in a mine. )",
"The location at which a watercourse disappears into the terrain.",
"A tract used for storing and/or parking vehicles (for example: recreational vehicles) and/or vessels.",
"A tract covered by the systematic planting of grape vines.",
"A data collection region lacking suitable source coverage and/or where data is not required.",
"A hill or mountain situated over an opening or openings in the Earth's crust through which lava, cinders, steam, and/or gases, are or have been expelled.",
"A solid man-made barrier of generally heavy material used as an enclosure, boundary, or for protection.",
"An aerodrome intended to be used either wholly or in part for the arrival, departure and surface movement of aircraft on water.",
"A barrier that may be swung, drawn, or lowered to block an entrance or passageway on a watercourse.",
"A tower-like structure associated with a dam or water source and used for the intake of water.",
"A tract for the treatment of water that consists of a bed of material where water is aerated or filtered.",
"A vertically descending part of a watercourse where it falls from a height (for example: over a rock or a precipice). ( In place names, commonly shortened to 'fall' or 'falls', for example, 'Niagara Falls'. )",
"An excavation drilled or dug into the ground (for example: the sea bed) for the extraction of liquids and/or gases.",
"A tower and associated equipment that generates electrical power from wind.",
"A system of vanes attached to a tower and driven by wind (excluding wind turbines).",
"A tract of trees whose canopy is not closed (allows sunlight to reach the ground) and often includes undergrowth.",
"The ruined remains of a stranded or sunken vessel that has been rendered useless.",
"A site where wild animals are kept for exhibition to the public, that may also support breeding and/or study."
};

unsigned char MGCP4DOMAINS[]={
0  /*** Dummy Value ***/,
D_AERO  /*** Aeronautical Obstacle ***/,
D_AERO  /*** Aeronautical Radio Navigation Service ***/,
D_AERO  /*** Aircraft Hangar ***/,
D_AERO  /*** Aircraft Revetment ***/,
D_POPU  /*** Amusement Park ***/,
D_AERO  /*** Approach Lighting System ***/,
D_AERO  /*** Apron ***/,
D_INWA  /*** Aqueduct ***/,
D_POPU  /*** Archeological Site ***/,
D_PHYS  /*** Beach ***/,
D_POAN  /*** Berthing Structure ***/,
D_VEGE  /*** Bog ***/,
D_POAN  /*** Breakwater ***/,
D_GRTR  /*** Bridge ***/,
D_POPU  /*** Built-Up Area ***/,
D_POPU  /*** Cableway ***/,
D_BOUN  /*** Cairn ***/,
D_POPU  /*** Camp ***/,
D_POPU  /*** Camp-site ***/,
D_INWA  /*** Canal ***/,
D_VEGE  /*** Cane ***/,
D_GRTR  /*** Cart Track ***/,
D_UTAN  /*** Catalytic Cracker ***/,
D_GRTR  /*** Causeway Structure ***/,
D_PHYS  /*** Cave Mouth ***/,
D_POPU  /*** Cemetery ***/,
D_DEST  /*** Checkpoint ***/,
D_UTAN  /*** Circular Irrigation System ***/,
D_INWA  /*** Cistern ***/,
D_VEGE  /*** Cleared Way ***/,
D_UTAN  /*** Communication Line ***/,
D_UTAN  /*** Communication Station ***/,
D_UTAN  /*** Conveyor ***/,
D_UTAN  /*** Crane ***/,
D_PHYS  /*** Crevasse ***/,
D_PHYS  /*** Crevice ***/,
D_VEGE  /*** Crop Land ***/,
D_INWA  /*** Culvert ***/,
D_PHYS  /*** Cut ***/,
D_PHYS  /*** Cut Line ***/,
D_INWA  /*** Dam ***/,
D_UTAN  /*** Dish Aerial ***/,
D_UTAN  /*** Disposal Site ***/,
D_INWA  /*** Ditch ***/,
D_DEST  /*** Dragon's Teeth ***/,
D_POAN  /*** Dry Dock ***/,
D_UTAN  /*** Electric Power Station ***/,
D_PHYS  /*** Embankment ***/,
D_DEST  /*** Engineered Earthwork ***/,
D_GRTR  /*** Entrance and/or Exit ***/,
D_PHYS  /*** Esker ***/,
D_UTAN  /*** Extraction Mine ***/,
D_POPU  /*** Facility ***/,
D_POPU  /*** Fairground ***/,
D_POPU  /*** Fence ***/,
D_GRTR  /*** Ferry Crossing ***/,
D_DEST  /*** Firing Range ***/,
D_INWA  /*** Fish Farm Facility ***/,
D_UTAN  /*** Flare Pipe ***/,
D_UTAN  /*** Flume ***/,
D_GRTR  /*** Ford ***/,
D_VEGE  /*** Forest Clearing ***/,
D_DEST  /*** Fortification ***/,
D_POPU  /*** General Building ***/,
D_PHYS  /*** Geologic Fault ***/,
D_UTAN  /*** Geophysical Prospecting Grid ***/,
D_PHYS  /*** Geothermal Outlet ***/,
D_PHYS  /*** Glacier ***/,
D_POPU  /*** Golf Course ***/,
D_UTAN  /*** Grain Elevator ***/,
D_UTAN  /*** Grain Storage Structure ***/,
D_VEGE  /*** Grassland ***/,
D_POPU  /*** Greenhouse ***/,
D_POAN  /*** Groin ***/,
D_PHYS  /*** Gully ***/,
D_POAN  /*** Harbour ***/,
D_OCEN  /*** Hazardous Rock ***/,
D_UTAN  /*** Heating Facility ***/,
D_VEGE  /*** Hedgerow ***/,
D_AERO  /*** Helipad ***/,
D_AERO  /*** Heliport ***/,
D_UTAN  /*** Holding Pen ***/,
D_VEGE  /*** Hop Field ***/,
D_POPU  /*** Hut ***/,
D_UTAN  /*** Hydrocarbons Field ***/,
D_PHYS  /*** Ice Cliff ***/,
D_PHYS  /*** Ice Peak ***/,
D_GRTR  /*** Ice Route ***/,
D_PHYS  /*** Island ***/,
D_INWA  /*** Lake ***/,
D_AERO  /*** Land Aerodrome ***/,
D_INWA  /*** Land Subject to Inundation ***/,
D_BOUN  /*** Land Water Boundary ***/,
D_AERO  /*** Launch Pad ***/,
D_INWA  /*** Lock ***/,
D_VEGE  /*** Mangrove Swamp ***/,
D_INWA  /*** Mariculture Site ***/,
D_POAN  /*** Maritime Signal Station ***/,
D_VEGE  /*** Marsh ***/,
D_POPU  /*** Memorial Monument ***/,
D_DEST  /*** Military Installation ***/,
D_UTAN  /*** Mineral Pile ***/,
D_AERO  /*** Mooring Mast ***/,
D_PHYS  /*** Moraine ***/,
D_GRTR  /*** Mountain Pass ***/,
D_GENE  /*** Named Location ***/,
D_INWA  /*** Natural Pool ***/,
D_VEGE  /*** Oasis ***/,
D_UTAN  /*** Offshore Platform ***/,
D_VEGE  /*** Orchard ***/,
D_POPU  /*** Park ***/,
D_UTAN  /*** Particle Accelerator ***/,
D_INWA  /*** Penstock ***/,
D_UTAN  /*** Pipeline ***/,
D_UTAN  /*** Power Line ***/,
D_UTAN  /*** Power Substation ***/,
D_UTAN  /*** Processing Facility ***/,
D_POPU  /*** Protection Shed ***/,
D_POPU  /*** Public Square ***/,
D_UTAN  /*** Pumping Station ***/,
D_UTAN  /*** Pylon ***/,
D_UTAN  /*** Quarry ***/,
D_POPU  /*** Racetrack ***/,
D_UTAN  /*** Radar Station ***/,
D_GRTR  /*** Railway ***/,
D_GRTR  /*** Railway Sidetrack ***/,
D_GRTR  /*** Railway Turntable ***/,
D_GRTR  /*** Railway Yard ***/,
D_INWA  /*** Rapids ***/,
D_POAN  /*** Recreational Pier ***/,
D_UTAN  /*** Recycling Site ***/,
D_OCEN  /*** Reef ***/,
D_INWA  /*** Reservoir ***/,
D_VEGE  /*** Rice Field ***/,
D_UTAN  /*** Rig ***/,
D_INWA  /*** River ***/,
D_GRTR  /*** Road ***/,
D_GRTR  /*** Roadside Rest Area ***/,
D_PHYS  /*** Rock Formation ***/,
D_GRTR  /*** Roundhouse ***/,
D_POPU  /*** Ruins ***/,
D_AERO  /*** Runway ***/,
D_PHYS  /*** Sabkha ***/,
D_UTAN  /*** Salt Evaporator ***/,
D_PHYS  /*** Salt Flat ***/,
D_PHYS  /*** Sand Dunes ***/,
D_POAN  /*** Seawall ***/,
D_POPU  /*** Settlement ***/,
D_UTAN  /*** Settling Pond ***/,
D_POPU  /*** Shanty Town ***/,
D_POPU  /*** Shed ***/,
D_POPU  /*** Ski-jump ***/,
D_POAN  /*** Slipway ***/,
D_INWA  /*** Sluice Gate ***/,
D_UTAN  /*** Smokestack ***/,
D_PHYS  /*** Snow Field and/or Ice-field ***/,
D_PHYS  /*** Soil Surface Region ***/,
D_UTAN  /*** Solar Panel ***/,
D_INWA  /*** Spillway ***/,
D_POPU  /*** Sports Ground ***/,
D_POPU  /*** Stadium ***/,
D_PHYS  /*** Steep Terrain Face ***/,
D_AERO  /*** Stopway ***/,
D_UTAN  /*** Storage Depot ***/,
D_UTAN  /*** Storage Tank ***/,
D_POAN  /*** Structural Pile ***/,
D_UTAN  /*** Surface Bunker ***/,
D_VEGE  /*** Swamp ***/,
D_POPU  /*** Swimming Pool ***/,
D_AERO  /*** Taxiway ***/,
D_UTAN  /*** Test Site ***/,
D_VEGE  /*** Thicket ***/,
D_OCEN  /*** Tidal Water ***/,
D_POPU  /*** Tower ***/,
D_GRTR  /*** Trail ***/,
D_POAN  /*** Training Wall ***/,
D_GRTR  /*** Transportation Station ***/,
D_VEGE  /*** Tundra ***/,
D_GRTR  /*** Tunnel ***/,
D_INWA  /*** Vanishing Point ***/,
D_GRTR  /*** Vehicle Lot ***/,
D_VEGE  /*** Vineyard ***/,
D_GENE  /*** Void Collection Area ***/,
D_PHYS  /*** Volcano ***/,
D_POPU  /*** Wall ***/,
D_AERO  /*** Water Aerodrome ***/,
D_INWA  /*** Water Gate ***/,
D_INWA  /*** Water Intake Tower ***/,
D_UTAN  /*** Water Treatment Bed ***/,
D_INWA  /*** Waterfall ***/,
D_UTAN  /*** Well ***/,
D_UTAN  /*** Wind Turbine ***/,
D_UTAN  /*** Windmill ***/,
D_VEGE  /*** Wood ***/,
D_OCEN  /*** Wreck ***/,
D_POPU  /*** Zoo ***/
};

int MGCP4DOMAINSLEN = sizeof(MGCP4DOMAINS)/ sizeof(unsigned char);

unsigned char MGCP4STRATS[]={
0  /*** Dummy Value ***/,
S_APPL  /*** Aeronautical Obstacle ***/,
S_APPL  /*** Aeronautical Radio Navigation Service ***/,
S_APPL  /*** Aircraft Hangar ***/,
S_APPL  /*** Aircraft Revetment ***/,
S_APPL  /*** Amusement Park ***/,
S_APPL  /*** Approach Lighting System ***/,
S_APPL  /*** Apron ***/,
S_APPL  /*** Aqueduct ***/,
S_APPL  /*** Archeological Site ***/,
S_APPL  /*** Beach ***/,
S_APPL  /*** Berthing Structure ***/,
S_APPL  /*** Bog ***/,
S_APPL  /*** Breakwater ***/,
S_APPL  /*** Bridge ***/,
S_APPL  /*** Built-Up Area ***/,
S_APPL  /*** Cableway ***/,
S_APPL  /*** Cairn ***/,
S_APPL  /*** Camp ***/,
S_APPL  /*** Camp-site ***/,
S_APPL  /*** Canal ***/,
S_APPL  /*** Cane ***/,
S_APPL  /*** Cart Track ***/,
S_APPL  /*** Catalytic Cracker ***/,
S_APPL  /*** Causeway Structure ***/,
S_APPL  /*** Cave Mouth ***/,
S_APPL  /*** Cemetery ***/,
S_APPL  /*** Checkpoint ***/,
S_APPL  /*** Circular Irrigation System ***/,
S_APPL  /*** Cistern ***/,
S_APPL  /*** Cleared Way ***/,
S_APPL  /*** Communication Line ***/,
S_APPL  /*** Communication Station ***/,
S_APPL  /*** Conveyor ***/,
S_APPL  /*** Crane ***/,
S_APPL  /*** Crevasse ***/,
S_APPL  /*** Crevice ***/,
S_APPL  /*** Crop Land ***/,
S_APPL  /*** Culvert ***/,
S_APPL  /*** Cut ***/,
S_APPL  /*** Cut Line ***/,
S_APPL  /*** Dam ***/,
S_APPL  /*** Dish Aerial ***/,
S_APPL  /*** Disposal Site ***/,
S_APPL  /*** Ditch ***/,
S_APPL  /*** Dragon's Teeth ***/,
S_APPL  /*** Dry Dock ***/,
S_APPL  /*** Electric Power Station ***/,
S_APPL  /*** Embankment ***/,
S_APPL  /*** Engineered Earthwork ***/,
S_APPL  /*** Entrance and/or Exit ***/,
S_APPL  /*** Esker ***/,
S_APPL  /*** Extraction Mine ***/,
S_APPL  /*** Facility ***/,
S_APPL  /*** Fairground ***/,
S_APPL  /*** Fence ***/,
S_APPL  /*** Ferry Crossing ***/,
S_APPL  /*** Firing Range ***/,
S_APPL  /*** Fish Farm Facility ***/,
S_APPL  /*** Flare Pipe ***/,
S_APPL  /*** Flume ***/,
S_APPL  /*** Ford ***/,
S_APPL  /*** Forest Clearing ***/,
S_APPL  /*** Fortification ***/,
S_APPL  /*** General Building ***/,
S_APPL  /*** Geologic Fault ***/,
S_APPL  /*** Geophysical Prospecting Grid ***/,
S_APPL  /*** Geothermal Outlet ***/,
S_APPL  /*** Glacier ***/,
S_APPL  /*** Golf Course ***/,
S_APPL  /*** Grain Elevator ***/,
S_APPL  /*** Grain Storage Structure ***/,
S_APPL  /*** Grassland ***/,
S_APPL  /*** Greenhouse ***/,
S_APPL  /*** Groin ***/,
S_APPL  /*** Gully ***/,
S_APPL  /*** Harbour ***/,
S_APPL  /*** Hazardous Rock ***/,
S_APPL  /*** Heating Facility ***/,
S_APPL  /*** Hedgerow ***/,
S_APPL  /*** Helipad ***/,
S_APPL  /*** Heliport ***/,
S_APPL  /*** Holding Pen ***/,
S_APPL  /*** Hop Field ***/,
S_APPL  /*** Hut ***/,
S_APPL  /*** Hydrocarbons Field ***/,
S_APPL  /*** Ice Cliff ***/,
S_APPL  /*** Ice Peak ***/,
S_APPL  /*** Ice Route ***/,
S_APPL  /*** Island ***/,
S_APPL  /*** Lake ***/,
S_APPL  /*** Land Aerodrome ***/,
S_APPL  /*** Land Subject to Inundation ***/,
S_APPL  /*** Land Water Boundary ***/,
S_APPL  /*** Launch Pad ***/,
S_APPL  /*** Lock ***/,
S_APPL  /*** Mangrove Swamp ***/,
S_APPL  /*** Mariculture Site ***/,
S_APPL  /*** Maritime Signal Station ***/,
S_APPL  /*** Marsh ***/,
S_APPL  /*** Memorial Monument ***/,
S_APPL  /*** Military Installation ***/,
S_APPL  /*** Mineral Pile ***/,
S_APPL  /*** Mooring Mast ***/,
S_APPL  /*** Moraine ***/,
S_APPL  /*** Mountain Pass ***/,
S_APPL  /*** Named Location ***/,
S_APPL  /*** Natural Pool ***/,
S_APPL  /*** Oasis ***/,
S_APPL  /*** Offshore Platform ***/,
S_APPL  /*** Orchard ***/,
S_APPL  /*** Park ***/,
S_APPL  /*** Particle Accelerator ***/,
S_APPL  /*** Penstock ***/,
S_APPL  /*** Pipeline ***/,
S_APPL  /*** Power Line ***/,
S_APPL  /*** Power Substation ***/,
S_APPL  /*** Processing Facility ***/,
S_APPL  /*** Protection Shed ***/,
S_APPL  /*** Public Square ***/,
S_APPL  /*** Pumping Station ***/,
S_APPL  /*** Pylon ***/,
S_APPL  /*** Quarry ***/,
S_APPL  /*** Racetrack ***/,
S_APPL  /*** Radar Station ***/,
S_APPL  /*** Railway ***/,
S_APPL  /*** Railway Sidetrack ***/,
S_APPL  /*** Railway Turntable ***/,
S_APPL  /*** Railway Yard ***/,
S_APPL  /*** Rapids ***/,
S_APPL  /*** Recreational Pier ***/,
S_APPL  /*** Recycling Site ***/,
S_APPL  /*** Reef ***/,
S_APPL  /*** Reservoir ***/,
S_APPL  /*** Rice Field ***/,
S_APPL  /*** Rig ***/,
S_APPL  /*** River ***/,
S_APPL  /*** Road ***/,
S_APPL  /*** Roadside Rest Area ***/,
S_APPL  /*** Rock Formation ***/,
S_APPL  /*** Roundhouse ***/,
S_APPL  /*** Ruins ***/,
S_APPL  /*** Runway ***/,
S_APPL  /*** Sabkha ***/,
S_APPL  /*** Salt Evaporator ***/,
S_APPL  /*** Salt Flat ***/,
S_APPL  /*** Sand Dunes ***/,
S_APPL  /*** Seawall ***/,
S_APPL  /*** Settlement ***/,
S_APPL  /*** Settling Pond ***/,
S_APPL  /*** Shanty Town ***/,
S_APPL  /*** Shed ***/,
S_APPL  /*** Ski-jump ***/,
S_APPL  /*** Slipway ***/,
S_APPL  /*** Sluice Gate ***/,
S_APPL  /*** Smokestack ***/,
S_APPL  /*** Snow Field and/or Ice-field ***/,
S_APPL  /*** Soil Surface Region ***/,
S_APPL  /*** Solar Panel ***/,
S_APPL  /*** Spillway ***/,
S_APPL  /*** Sports Ground ***/,
S_APPL  /*** Stadium ***/,
S_APPL  /*** Steep Terrain Face ***/,
S_APPL  /*** Stopway ***/,
S_APPL  /*** Storage Depot ***/,
S_APPL  /*** Storage Tank ***/,
S_APPL  /*** Structural Pile ***/,
S_APPL  /*** Surface Bunker ***/,
S_APPL  /*** Swamp ***/,
S_APPL  /*** Swimming Pool ***/,
S_APPL  /*** Taxiway ***/,
S_APPL  /*** Test Site ***/,
S_APPL  /*** Thicket ***/,
S_APPL  /*** Tidal Water ***/,
S_APPL  /*** Tower ***/,
S_APPL  /*** Trail ***/,
S_APPL  /*** Training Wall ***/,
S_APPL  /*** Transportation Station ***/,
S_APPL  /*** Tundra ***/,
S_APPL  /*** Tunnel ***/,
S_APPL  /*** Vanishing Point ***/,
S_APPL  /*** Vehicle Lot ***/,
S_APPL  /*** Vineyard ***/,
S_APPL  /*** Void Collection Area ***/,
S_APPL  /*** Volcano ***/,
S_APPL  /*** Wall ***/,
S_APPL  /*** Water Aerodrome ***/,
S_APPL  /*** Water Gate ***/,
S_APPL  /*** Water Intake Tower ***/,
S_APPL  /*** Water Treatment Bed ***/,
S_APPL  /*** Waterfall ***/,
S_APPL  /*** Well ***/,
S_APPL  /*** Wind Turbine ***/,
S_APPL  /*** Windmill ***/,
S_APPL  /*** Wood ***/,
S_APPL  /*** Wreck ***/,
S_APPL  /*** Zoo ***/
};

int MGCP4STRATSLEN = sizeof(MGCP4STRATS)/ sizeof(unsigned char);


char *MGCP4_p_optional[] = {
"BD180 None",
"AK170 None",
"BD100 None",
"AL019 None",
"AN076 None",
"AL099 None",
"AJ030 None",
"BI010 None",
"GB050 None"
};

int MGCP4_P_OPTCOUNT = 9;


char *MGCP4_l_optional[] = {
"BH165 None",
"EA020 None",
"FA090 None",
"AL070 None",
"DB100 None",
"DB071 None",
"GB050 None"
};

int MGCP4_L_OPTCOUNT = 7;


char *MGCP4_a_optional[] = {
"ZD020 None",
"BJ110 None",
"AK170 None",
"BD100 None",
"BH165 None",
"AL019 None",
"AN076 None",
"BJ020 None",
"EA055 None",
"AJ030 None",
"EC060 None",
"DB061 None",
"BJ031 None",
"EC040 None",
"AJ010 None",
"EC010 None"
};

int MGCP4_A_OPTCOUNT = 16;


