/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
#include "share.h"
int SAC_CLASS_NUM=41;

char *SAC_class_codes[] = {
"GB230",
"GB015",
"GB020",
"GB025",
"AQ040",
"AL015",
"AQ060",
"DB185",
"AQ065",
"GB090",
"BH030",
"AQ090",
"AL070",
"AM075",
"GB250",
"GB030",
"GA048",
"BA010",
"AL110",
"AM065",
"GA035",
"AQ113",
"AN010",
"AN050",
"GB050",
"AP030",
"GB055",
"GB056",
"AF010",
"GB045",
"AM010",
"AM070",
"AM060",
"GB075",
"AL241",
"EC031",
"AQ095",
"AH060",
"AP041",
"AL260",
"AM080"
};

char *SAC_class_names[] = {
"Aircraft Hangar",
"Apron_or_hardstand",
"Arresting Gear",
"Blast Barrier",
"Bridge",
"Building",
"Control Tower",
"Crater",
"Culvert",
"Displaced Threshold",
"Ditch",
"Entrance/Exit",
"Fence",
"Fuel Storage Depot",
"Hardened Aircraft Shelter",
"Helipad",
"ILS Component",
"Land Water Boundary",
"Light Support Structure",
"Munition Storage Depot",
"NAVAIDS (Aeronautical) - excluding ILS",
"Pipeline",
"Railway",
"Railway_Sidetrack_or_spur",
"Revetment",
"Road",
"Runway",
"Runway Endpoint",
"Smokestack",
"Stopway",
"Storage Depot",
"Storage Tank",
"Surface Bunker",
"Taxiway",
"Tower",
"Tree",
"Tunnel Mouth",
"Underground Bunker",
"Vehicle Barrier",
"Wall",
"Water Tower"
};

char *SAC_class_defns[] = {
"No definition available.",
"A defined paved or hard-packed area at an airport or heliport intended for aircraft parking.",
"Devices such as cables or barriers that can be used to stop an aircraft immediately upon landing.",
"A barrier used to divert or dissipate jet or propeller blast.",
"A man-made structure spanning and providing passage over a body of water, depression, or other obstacles.",
"A relatively permanent structure, roofed and usually walled and designed for some particular use.  (See also AL100)",
"A tower-like structure that houses the persons and equipment used to control the flow of air, rail, or marine traffic.  (See also AL240)",
"No definition available.",
"A sewer or drain crossing under a road, track, or embankment, without affecting the construction of the crossed feature.",
"The designated beginning of the portion of the runway usable for landing.  This is located at a point on the runway other than the designated beginning of the runway.   In addition, the feature typically exists at each end of the runway.",
"A channel constructed for the purpose of irrigation or drainage.",
"A point of entrance or exit.  (See also AA010 and AQ130)",
"A man-made barrier of relatively light structure used as an enclosure or boundary.  (See also AL260)",
"No definition available.",
"No definition available.",
"An improved area used for take-off, and landing, by helicopters and other vertical take-off and landing aircraft.",
"No definition available.",
"The line where a land mass is in contact with a body of water.",
"A structure serving as a support for lighting.",
"No definition available.",
"Any visual or electronic device which provides point-to-point guidance information or position data.",
"A tube for the conveyance of solids, liquids or gases.",
"A rail or set of parallel rails on which a train or tram runs.",
"A stretch of railroad tracks connected to the main track by switch(es) - used for temporary storage and loading/unloading.",
"A barricade which protects an aircraft, equipment, or facilities from hostile action.",
"An open way maintained for vehicular use.",
"A defined area, usually rectangular, used for the conventional landing and take-off of aircraft.  (Excludes GB045)",
"No definition available.",
"A vertical structure containing a passage or flue for discharging smoke and gases of combustion.",
"An area beyond the take-off runway designated as able to support an airplane during an aborted take-off.",
"An area used for the storage of products or supplies.  (See also AB000)",
"A container used for the storage of liquids or gases.  (See also AM011, AM020, and AM080)",
"A structure which may be covered or surrounded with earth which is resistant to ordnance where materials or products are stored.  (See also AH050)",
"A prepared surface providing access to/from runways and the aircraft parking area, terminal area, or service area, etc.",
"No definition available.",
"No definition available",
"No definition available.",
"An underground facility used by the military either for location of command/control centers or for troop encampment.  (See also AL250)",
"A permanent obstruction placed across a route to prevent vehicular traffic.",
"A solid man-made barrier of heavy material used as an enclosure or boundary or for protection.  (See also AL070)",
"An elevated container and its supporting structure used to hold water.  (See also AM011, AM020, and AM070)"
};

unsigned char SACDOMAINS[]={
0  /*** Dummy Value ***/,
D_AERO  /*** Aircraft Hangar ***/,
D_AERO  /*** Apron_or_hardstand ***/,
D_AERO  /*** Arresting Gear ***/,
D_AERO  /*** Blast Barrier ***/,
D_GRTR  /*** Bridge ***/,
D_POPU  /*** Building ***/,
D_POPU  /*** Control Tower ***/,
D_DEST  /*** Crater ***/,
D_GRTR  /*** Culvert ***/,
D_AERO  /*** Displaced Threshold ***/,
D_INWA  /*** Ditch ***/,
D_GRTR  /*** Entrance/Exit ***/,
D_POPU  /*** Fence ***/,
D_UTAN  /*** Fuel Storage Depot ***/,
D_AERO  /*** Hardened Aircraft Shelter ***/,
D_AERO  /*** Helipad ***/,
D_AERO  /*** ILS Component ***/,
D_PHYS  /*** Land Water Boundary ***/,
D_POPU  /*** Light Support Structure ***/,
D_UTAN  /*** Munition Storage Depot ***/,
D_AERO  /*** NAVAIDS (Aeronautical) - excluding ILS ***/,
D_UTAN  /*** Pipeline ***/,
D_GRTR  /*** Railway ***/,
D_GRTR  /*** Railway_Sidetrack_or_spur ***/,
D_AERO  /*** Revetment ***/,
D_GRTR  /*** Road ***/,
D_AERO  /*** Runway ***/,
D_AERO  /*** Runway Endpoint ***/,
D_UTAN  /*** Smokestack ***/,
D_AERO  /*** Stopway ***/,
D_UTAN  /*** Storage Depot ***/,
D_UTAN  /*** Storage Tank ***/,
D_UTAN  /*** Surface Bunker ***/,
D_AERO  /*** Taxiway ***/,
D_AERO  /*** Tower ***/,
D_VEGE  /*** Tree ***/,
D_PHYS  /*** Tunnel Mouth ***/,
D_DEST  /*** Underground Bunker ***/,
D_GRTR  /*** Vehicle Barrier ***/,
D_POPU  /*** Wall ***/,
D_UTAN  /*** Water Tower ***/
};

int SACDOMAINSLEN = sizeof(SACDOMAINS)/ sizeof(unsigned char);

unsigned char SACSTRATS[]={
0  /*** Dummy Value ***/,
S_APPL  /*** Aircraft Hangar ***/,
S_APPL  /*** Apron_or_hardstand ***/,
S_APPL  /*** Arresting Gear ***/,
S_APPL  /*** Blast Barrier ***/,
S_APPL  /*** Bridge ***/,
S_APPL  /*** Building ***/,
S_APPL  /*** Control Tower ***/,
S_APPL  /*** Crater ***/,
S_APPL  /*** Culvert ***/,
S_APPL  /*** Displaced Threshold ***/,
S_APPL  /*** Ditch ***/,
S_APPL  /*** Entrance/Exit ***/,
S_APPL  /*** Fence ***/,
S_APPL  /*** Fuel Storage Depot ***/,
S_APPL  /*** Hardened Aircraft Shelter ***/,
S_APPL  /*** Helipad ***/,
S_APPL  /*** ILS Component ***/,
S_APPL  /*** Land Water Boundary ***/,
S_APPL  /*** Light Support Structure ***/,
S_APPL  /*** Munition Storage Depot ***/,
S_APPL  /*** NAVAIDS (Aeronautical) - excluding ILS ***/,
S_APPL  /*** Pipeline ***/,
S_APPL  /*** Railway ***/,
S_APPL  /*** Railway_Sidetrack_or_spur ***/,
S_APPL  /*** Revetment ***/,
S_APPL  /*** Road ***/,
S_APPL  /*** Runway ***/,
S_APPL  /*** Runway Endpoint ***/,
S_APPL  /*** Smokestack ***/,
S_APPL  /*** Stopway ***/,
S_APPL  /*** Storage Depot ***/,
S_APPL  /*** Storage Tank ***/,
S_APPL  /*** Surface Bunker ***/,
S_APPL  /*** Taxiway ***/,
S_APPL  /*** Tower ***/,
S_APPL  /*** Tree ***/,
S_APPL  /*** Tunnel Mouth ***/,
S_APPL  /*** Underground Bunker ***/,
S_APPL  /*** Vehicle Barrier ***/,
S_APPL  /*** Wall ***/,
S_APPL  /*** Water Tower ***/
};

int SACSTRATSLEN = sizeof(SACSTRATS)/ sizeof(unsigned char);


