/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
int SAC_ATTR_NUM=60;

char *SAC_attr_codes[] = {
"AEH",
"ALA",
"ALO",
"AOH",
"ACS",
"HAC",
"ARA",
"AGC",
"AGD",
"CLASS",
"FUN",
"NA4",
"NA4_2",
"DSG",
"DTF",
"DTM",
"Z5F",
"Z5M",
"EHI",
"ELI",
"FFN",
"Z7F",
"ZV7",
"HNG",
"HTP",
"HDW",
"HGF",
"HGT",
"IKO",
"LEF",
"LEN",
"LCX",
"LCR",
"LCV",
"RST",
"PC3",
"MVC",
"NST",
"PCN",
"PC4",
"PC1",
"REL",
"REMARKS",
"WD2",
"RID",
"STC",
"PC2",
"SMC",
"LTN",
"TRS",
"UUID_1",
"UUID_2",
"UUID_3",
"UUID_4",
"UUID_5",
"UUID_6",
"LOC",
"WGP",
"WGF",
"WAC_INNR"
};

char *SAC_attr_names[] = {
"Absolute Ellipsoid Height Accuracy in Meters",
"Absolute Latitude Accuracy in Meters (WGS84)",
"Absolute Longitude Accuracy in Meters (WGS84)",
"Absolute Orthometric Height Accuracy in Meters",
"Accessibility Status",
"Aeronautical Apron/Hardstand Category",
"Area in Square Meters",
"Arresting Gear Category",
"Arresting Gear Engagement Direction",
"Classification",
"Condition of Facility",
"Country Code (FIPS)",
"Country Code (GENC)",
"Designator",
"Displaced Threshold Distance in Feet",
"Displaced Threshold Distance in Meters",
"Ellipsoid Height (Feet)",
"Ellipsoid Height (Meters)",
"Extracted Runway High Identifier",
"Extracted Runway Low Identifier",
"Feature Function(s)",
"Geoid Elevation (Feet)",
"Geoid Elevation (Meters)",
"Hangar Door Height in Feet",
"Hangar Type Category",
"Hanger Door Width in Feet",
"Height Above Surface Level in Feet",
"Height Above Surface Level in Meters",
"ICAO Designator",
"Length/Diameter in Feet",
"Length/Diameter in Meters",
"Load Classification Number (LCN)",
"Load Classification Number (LCN) Remark",
"Load Classification Number (LCN) Validity (or Basis)",
"Load-bearing Surface Type",
"Maximum Tire Pressure",
"Maximum Vertical Clearance in Meters",
"Navigation System Types",
"Pavement Classification Number (PCN)",
"Pavement Evaluation Method",
"Pavement Type",
"Releasability",
"Remarks",
"Route Total Usable Width [Meters}",
"Runway End Identifier [Tens of Degrees]",
"Source Type Code",
"Sub-Grade Category",
"Surface Material Category",
"Track/Lane Number",
"Transportation System Type",
"Universally Unique Identifier",
"Universally Unique Identifier 2",
"Universally Unique Identifier 3",
"Universally Unique Identifier 4",
"Universally Unique Identifier 5",
"Universally Unique Identifier 6",
"Vertical Relative Location",
"Width (Meters)",
"Width in Feet",
"World Aeronautical Chart-Installation Number"
};

char *SAC_attr_types[] = {
"Real",
"Real",
"Real",
"Real",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"Real",
"Real",
"Real",
"Real",
"String",
"String",
"Short Integer",
"Real",
"Real",
"Real",
"Short Integer",
"Real",
"Real",
"Real",
"String",
"Real",
"Real",
"Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Real",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Real",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"Real",
"Real",
"String"
};

char *SAC_attr_defns[] = {
"No definition available.",
"No definition available.",
"No definition available.",
"No definition available.",
"No definition available.",
"No definition available.",
"No definition available.",
"Device used to stop an uncontrolled aircraft at the end of a runway.",
"The direction the aircraft must be moving in order to utilize this feature.",
"No definition available.",
"No definition available.",
"A four character country identification code as designated in Federal Information Processing Standard (FIPS)  Pub 10-4, Countries, Dependencies, Areas of Special Sovereignty, and their Principal Administrative Divisions, identifying the country and the principal administrative division in which the feature is located.  The last two characters will be blank filled if principal administrative division information is not required.",
"No definition available.",
"No definition available.",
"No definition available.",
"No definition available.",
"No definition available.",
"No definition available.",
"Runway High Identifier.",
"Runway Low Identifier.",
"No definition available.",
"No definition available.",
"No definition available.",
"The measurement of the vertical extent of the hangar door.",
"Hangar design code.",
"The measurement of the horizontal extent of the hangar door.",
"No definition available.",
"Distance measured from the lowest point of the base at ground or water level (downhill side/downstream side) to the tallest point of the feature.",
"International Civil Aviation Organization location identifier as designated in ICAO document 7910.",
"No definition available.",
"No definition available.",
"No definition available.",
"No definition available.",
"No definition available.",
"The physical surface composition of a road or runway.",
"No definition available.",
"The greatest distance between the traveled way and any obstruction vertically above it.",
"Type of equipment or system used in electronic navigation (primary system).",
"No definition available.",
"No definition available.",
"No definition available.",
"Name of religious order at site.",
"No definition available.",
"Total usable width including pavements and hard shoulders (in decimetres).",
"The  degree identification of the runway in a two-digit identifier ranging from 01-36, derived from the runway heading, rounded to the nearest ten degrees and divided by ten.  For parallel runways a third character is added to differentiate between left (L), right (R), center (C), or STOL (S) runway positions.",
"The source from which features are captured or upgraded.",
"No definition available.",
"Surface material composition excluding internal structural material.",
"The number of track(s) or lanes of the feature, including both directions.",
"No definition available.",
"A unique identifier for each instance of every feature.",
"A unique identifier for each instance of every feature.",
"A unique identifier for each instance of every feature.",
"A unique identifier for each instance of every feature.",
"A unique identifier for each instance of every feature.",
"A unique identifier for each instance of every feature.",
"Status of  feature relative to surrounding area or water.",
"A measurement of the shorter of two linear axes.  For a square feature, measure either axis.  For a round feature, width shall be equal to LEN.  For a bridge, the width is the measurement perpendicular to the axis between the abutments.",
"No definition available.",
"No definition available."
};

