/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
#include "share.h"
int TDS4_CLASS_NUM=317;

char *TDS4_class_codes[] = {
"AB040",
"AT011",
"AT012",
"GB230",
"GB050",
"AK164",
"AK030",
"AK020",
"ZD045",
"GB015",
"BH010",
"BH116",
"AQ151",
"AL012",
"DA005",
"AL142",
"AJ085",
"BI045",
"AG050",
"AC010",
"BH015",
"AA045",
"EA031",
"ZB030",
"AQ040",
"AQ056",
"AQ045",
"AQ050",
"AQ055",
"EB070",
"AF021",
"AL013",
"AL018",
"AL020",
"AT005",
"AT041",
"AL025",
"AI030",
"AK060",
"BH020",
"EC010",
"SU004",
"AI020",
"AP010",
"AL375",
"AL376",
"AC020",
"AQ063",
"DB029",
"AL030",
"AH070",
"BI010",
"EC040",
"FA210",
"FA012",
"ZB035",
"AQ060",
"AF020",
"AD055",
"AF030",
"AL175",
"AF040",
"BJ031",
"DB061",
"EA010",
"AQ062",
"ZD030",
"AQ065",
"DB070",
"DB071",
"BI020",
"ZI031",
"DB080",
"EE030",
"AT010",
"AB000",
"BH030",
"AL060",
"AK070",
"BB090",
"AD010",
"CA010",
"DB090",
"AF060",
"AH025",
"DB100",
"AF050",
"AA010",
"AL010",
"AK090",
"AL070",
"AQ070",
"AQ080",
"AL017",
"FA015",
"BH051",
"BI060",
"BB110",
"AL073",
"AF070",
"BB199",
"BI044",
"BH070",
"EC015",
"EC060",
"AH055",
"BH075",
"AM075",
"AL080",
"AP040",
"BI070",
"DB110",
"DB115",
"BJ030",
"AK100",
"AK101",
"AM030",
"AM020",
"AK110",
"EB010",
"AJ110",
"BB005",
"GB250",
"AD050",
"EA020",
"GB030",
"GB035",
"AJ030",
"EA055",
"AF080",
"BD181",
"BH077",
"AL099",
"AC040",
"AA052",
"BJ040",
"BJ060",
"AQ075",
"BJ065",
"BJ099",
"AL270",
"AC060",
"BH082",
"AL011",
"AL201",
"FA110",
"BA030",
"GB005",
"BH090",
"BA010",
"DB211",
"GB040",
"AL110",
"BC070",
"BC050",
"AB021",
"BI030",
"EE010",
"AK121",
"ED010",
"AL130",
"SU001",
"AA020",
"AL065",
"AM040",
"AL120",
"BH100",
"AI021",
"AQ110",
"BJ020",
"AQ170",
"DB150",
"AM065",
"ZD040",
"BH170",
"AL014",
"ZI041",
"AA054",
"AD041",
"EC020",
"AG040",
"BD115",
"EA040",
"AK080",
"AL155",
"AK120",
"AQ141",
"AL140",
"BH110",
"AK061",
"AQ113",
"AL165",
"EA030",
"BJ080",
"BB009",
"AD030",
"AQ111",
"AL170",
"AQ116",
"AT042",
"BH012",
"AK130",
"AT045",
"AN010",
"AN050",
"AN085",
"AN075",
"AN060",
"AL195",
"BH120",
"AB010",
"AL180",
"BH135",
"AA040",
"BH140",
"AP030",
"AP020",
"AQ135",
"DB160",
"AN076",
"AL200",
"GB055",
"BH160",
"BH155",
"BH150",
"DB170",
"AK161",
"GB070",
"AL105",
"AC030",
"AC507",
"AL208",
"AQ118",
"AA011",
"AL019",
"BI006",
"AM011",
"BB241",
"AG030",
"BB081",
"BB082",
"AQ035",
"AK150",
"AK155",
"BI040",
"BB201",
"AF010",
"BD140",
"BJ100",
"DA010",
"AD025",
"AD020",
"AL351",
"ZI040",
"BH165",
"AK040",
"CA030",
"AJ080",
"AK160",
"AQ150",
"AQ120",
"DB010",
"GB045",
"AM010",
"AM070",
"AQ114",
"AQ161",
"AQ162",
"BD100",
"AM060",
"ED020",
"AK170",
"AM071",
"GB075",
"FA100",
"AL510",
"EB020",
"BA040",
"AL036",
"AL241",
"AQ160",
"AP050",
"FA165",
"AQ068",
"AQ059",
"AL211",
"AQ125",
"EC005",
"BJ110",
"AQ130",
"AQ095",
"AH060",
"AL250",
"AQ115",
"BH145",
"AP041",
"AQ140",
"BI005",
"EA050",
"ZD020",
"DB190",
"DB180",
"AL260",
"GB065",
"BI050",
"AJ055",
"BH065",
"AM080",
"BH040",
"BH230",
"BH180",
"BH220",
"AQ180",
"AD060",
"AJ051",
"AJ050",
"AK180"
};

char *TDS4_class_names[] = {
"Aeration Basin",
"Aerial",
"Aerial Farm",
"Aircraft Hangar",
"Aircraft Revetment",
"Amphitheatre",
"Amusement Park",
"Amusement Park Attraction",
"Annotated Location",
"Apron",
"Aqueduct",
"Aquifer",
"Arcade",
"Archeological Site",
"Asphalt Lake",
"Astronomical Observatory",
"Barn",
"Basin Gate",
"Billboard",
"Blast-furnace",
"Bog",
"Borehole",
"Botanic Garden",
"Boundary Monument",
"Bridge",
"Bridge Pier",
"Bridge Span",
"Bridge Superstructure",
"Bridge Tower",
"Brush",
"Bucket Elevator",
"Building",
"Building Superstructure",
"Built-up Area",
"Cable",
"Cableway",
"Cairn",
"Camp",
"Camp-site",
"Canal",
"Cane",
"Cantonment Area",
"Caravan Park",
"Cart Track",
"Castle",
"Castle Complex",
"Catalytic Cracker",
"Causeway Structure",
"Cave Mouth",
"Cemetery",
"Checkpoint",
"Cistern",
"Cleared Way",
"Conservation Area",
"Contaminated Region",
"Control Point",
"Control Tower",
"Conveyor",
"Cooling Facility",
"Cooling Tower",
"Courtyard",
"Crane",
"Crevasse",
"Crevice",
"Crop Land",
"Crossing",
"Cultural Context Location",
"Culvert",
"Cut",
"Cut Line",
"Dam",
"Dataset",
"Depression",
"Desert",
"Dish Aerial",
"Disposal Site",
"Ditch",
"Dragon's Teeth",
"Drive-in Theatre",
"Dry Dock",
"Electric Power Station",
"Elevation Contour",
"Embankment",
"Engine Test Cell",
"Engineered Earthwork",
"Esker",
"Excavating Machine",
"Extraction Mine",
"Facility",
"Fairground",
"Fence",
"Ferry Crossing",
"Ferry Station",
"Fire Hydrant",
"Firing Range",
"Fish Farm Facility",
"Fish Ladder",
"Fish Weir",
"Flagpole",
"Flare Pipe",
"Floating Dry Dock",
"Flood Control Structure",
"Ford",
"Forest",
"Forest Clearing",
"Fortified Building",
"Fountain",
"Fuel Storage Facility",
"Gantry",
"Gate",
"Gauging Station",
"Geologic Fault",
"Geothermal Outlet",
"Glacier",
"Golf Course",
"Golf Driving Range",
"Grain Elevator",
"Grain Storage Structure",
"Grandstand",
"Grassland",
"Greenhouse",
"Harbour",
"Hardened Aircraft Shelter",
"Heating Facility",
"Hedgerow",
"Helipad",
"Heliport",
"Holding Pen",
"Hop Field",
"Hopper",
"Hulk",
"Hummock",
"Hut",
"Hydrocarbon Products Facility",
"Hydrocarbons Field",
"Ice Cliff",
"Ice Peak",
"Ice Route",
"Ice Shelf",
"Ice-cap",
"Industrial Farm",
"Industrial Furnace",
"Inland Waterbody",
"Installation",
"Interest Site",
"International Date Line",
"Island",
"Land Aerodrome",
"Land Subject to Inundation",
"Land Water Boundary",
"Landslide Mass",
"Launch Pad",
"Light Support Structure",
"Light Vessel",
"Lighthouse",
"Liquid Diffuser",
"Lock",
"Logging Site",
"Lookout",
"Marsh",
"Memorial Monument",
"Military Installation",
"Mine Shaft Superstructure",
"Minefield",
"Mineral Pile",
"Missile Site",
"Moat",
"Mobile Home Park",
"Mooring Mast",
"Moraine",
"Motor Vehicle Station",
"Mountain Pass",
"Munition Storage Facility",
"Named Location",
"Natural Pool",
"Non-building Structure",
"Non-spatial Metadata Entity Collection",
"Non-water Well",
"Nuclear Reactor Containment",
"Oasis",
"Office Park",
"Offshore Construction",
"Orchard",
"Outdoor Theatre Screen",
"Overhead Obstruction",
"Park",
"Parking Garage",
"Particle Accelerator",
"Penstock",
"Picnic Site",
"Pipeline",
"Pipeline Crossing Point",
"Plant Nursery",
"Polar Ice",
"Port",
"Power Substation",
"Prepared Watercourse Crossing",
"Public Square",
"Pumping Station",
"Pylon",
"Qanat Shaft",
"Racetrack",
"Radar Station",
"Railway",
"Railway Sidetrack",
"Railway Signal",
"Railway Turntable",
"Railway Yard",
"Ramp",
"Rapids",
"Recycling Site",
"Retail Stand",
"Rice Field",
"Rig",
"River",
"Road",
"Road Interchange",
"Roadside Rest Area",
"Rock Formation",
"Roundhouse",
"Ruins",
"Runway",
"Sabkha",
"Salt Evaporator",
"Salt Flat",
"Sand Dunes",
"Scoreboard",
"Seaplane Run",
"Settlement",
"Settling Pond",
"Sewage Treatment Plant",
"Shanty Town",
"Sharp Curve",
"Shear Wall",
"Shed",
"Ship Elevator",
"Shipping Container",
"Shipyard",
"Shopping Complex",
"Shoreline Construction",
"Shoreline Ramp",
"Sidewalk",
"Ski-jump",
"Ski-run",
"Sluice Gate",
"Small Craft Facility",
"Smokestack",
"Snag",
"Snow Field and/or Ice-field",
"Soil Surface Region",
"Solar Farm",
"Solar Panel",
"Space Facility",
"Spatial Metadata Entity Collection",
"Spillway",
"Sports Ground",
"Spot Elevation",
"Stable",
"Stadium",
"Stair",
"Steep Grade",
"Steep Terrain Face",
"Stopway",
"Storage Depot",
"Storage Tank",
"Storm Drain",
"Street Lamp",
"Street Sign",
"Structural Pile",
"Surface Bunker",
"Swamp",
"Swimming Pool",
"Tank Farm",
"Taxiway",
"Test Site",
"Tethered Balloon",
"Thicket",
"Tidal Water",
"Tomb",
"Tower",
"Traffic Light",
"Trail",
"Training Site",
"Transportation Block",
"Transportation Route Characteristic Change",
"Transportation Route Protection Structure",
"Transportation Station",
"Tree",
"Tundra",
"Tunnel",
"Tunnel Mouth",
"Underground Bunker",
"Underground Dwelling",
"Utility Cover",
"Vanishing Point",
"Vehicle Barrier",
"Vehicle Lot",
"Vessel Lift",
"Vineyard",
"Void Collection Area",
"Volcanic Dyke",
"Volcano",
"Wall",
"Water Aerodrome",
"Water Intake Tower",
"Water Mill",
"Water Race",
"Water Tower",
"Water Treatment Bed",
"Water Well",
"Waterfall",
"Waterwork",
"Weigh Station",
"Wind Farm",
"Wind Turbine",
"Windmill",
"Zoo"
};

char *TDS4_class_defns[] = {
"A basin, usually artificial, in which air is mixed with partially treated wastewater. Amplifying Description: The water is treated with microorganisms to consume organic materials and convert suspended solids to settleable solids that are later collected by a settling pond and removed as sludge.",
"A device that is used for emitting and/or sensing electromagnetic energy. Amplifying Description: For example, used to transmit and/or receive electronic signals as on a radio tower or to capture electromagnetic energy as in radio astronomy.",
"A collection of aerials that are collocated and serve a common purpose. Amplifying Description: They may be organized either to function as a single larger virtual device (for example: a phased array) or function relatively independently of each other (for example: pointed in different directions and operating at different frequencies as at a satellite communication ground station).",
"A building for housing aircraft.",
"A barricade that protects an aircraft, equipment, and/or facility from hostile action.",
"A small tract of level ground serving as a stage that is surrounded by rising slopes (either naturally occurring or artificially constructed) supporting tiered seating (for example: benches). Amplifying Description: Generally oval or circular in overall shape and typically used for live theatrical presentations, concerts, opera or dance productions, cinema, and/or other stage productions.",
"A predominantly man-made facility equipped with recreational devices.",
"A large structure located in an amusement park.",
"A location at which text pertaining to that location is annotated. Amplifying Description: For example, a characteristic or activity pertaining to the location may be described.",
"A defined area, on a land aerodrome/heliport, intended to accommodate aircraft/helicopters for purposes of loading and unloading passengers, mail or cargo, and for fuelling, parking or maintenance.",
"A pipe or artificial channel that is designed to transport water from a remote source, usually by gravity, for freshwater supply, agricultural, and/or industrial use. Amplifying Description: It may be supported by a bridge.",
"An underground layer of water-bearing permeable rock or unconsolidated materials (for example: gravel, sand, silt, or clay). Amplifying Description: It may yield economically significant quantities of groundwater to wells and springs.",
"A covered pedestrian route composed of arches and pillars, usually open along one or both sides.",
"A site where remains of past civilizations or human activity have been discovered.",
"A natural accumulation of liquid asphalt.",
"A building designed and equipped (for example: with a telescope) for making observations of celestial objects (including the earth in relation to them), of space, and of the universe as a whole. Amplifying Description: Typically incorporates a dome-shaped covering that may be opened in order to expose instruments to the sky or closed to protect them from the weather.",
"A roofed farm building designed for sheltering harvested crops (for example: hay), livestock (for example: cattle), and/or farm machinery (for example: tractors and plows).",
"A gate that impounds water within a basin or chamber that is used by watercraft. Amplifying Description: For example, gates used at locks or dry docks.",
"A large outdoor board for advertisements. Amplifying Description: May be attached to another structure or self-supporting. Usually elevated so as to be seen for a significant distance.",
"A smelting furnace in which a blast of air is used, especially one for iron-smelting using a compressed hot air blast.",
"A permanently wet area of land consisting of incompletely decayed organic material and mainly stagnant fresh water. Amplifying Description: It is generally too soft to bear the weight of any heavy body. A subtype of the more generalized wetland.",
"An excavation drilled into the ground for purposes other than the extraction of potable water, oil, gas or brine. Amplifying Description: For example, drilled to support the underground testing of munitions, for coring or sampling of bedrock or ice for scientific purposes, or drilled for the injection of waste material.",
"A culturally designated tract where plants are displayed.",
"A marker identifying the location of a surveyed boundary line.",
"A structure that connects two locations and provides for the passage of a transportation route (for example: a road or a railway) over a terrain obstacle (for example: a waterbody, a gully, and/or a road). Amplifying Description: A bridge consists of a set of two abutments and/or zero or more bridge piers joined by bridge spans. A bridge may serve, for example, as an overpass or a viaduct. In the context of a bridge, the scope of the term 'transportation route' includes the transportation of liquids or gases by means of either pipelines or aqueducts.",
"A pillar or abutment that supports a bridge span.",
"A component of the deck of a bridge spanning successive bridge piers.",
"A superstructure of a bridge, above the lowest deck, not including pylons or towers.",
"A tower and/or pylon from which the deck of a bridge is suspended.",
"A tract covered mainly by short, uncultured, woody plants. Amplifying Description: For example, covered by brush, scrub and/or shrubs. The predominant height is usually less than 2-3 metres.",
"Equipment, usually a series of buckets, for raising materials or liquids to a higher level.",
"A free-standing self-supporting construction that is roofed, usually walled, and is intended for human occupancy (for example: a place of work or recreation) and/or habitation. Amplifying Description: For example, a dormitory, a bank, and a restaurant.",
"A supplemental portion of a building which rises from the roof but is not considered to be a portion of the roof.",
"A tract containing a concentration of buildings and/or other structures.",
"A single continuous rope-like bundle consisting of multiple strands. Amplifying Description: The strands may be individually insulated and/or protected and the cable as a whole sheathed. Cables may be used for load bearing (for example, supporting or suspending equipment and/or structures), transmitting electrical power, and/or communicating signals (for example, by electrical or optical means).",
"A suspended transportation system consisting of one or more load cables, supporting pylons, carrier units (for example: cars or buckets intended to transport people, material, and/or equipment) and usually stations. Amplifying Description: A cableway consists of carrier units attached to load cables which are strung between pylons and/or stations. For example, a ski-lift.",
"A heap of stones piled up as a memorial or a landmark.",
"An encampment where tents and/or other easily moveable structures (for example: yurts) serve as full-time, temporary, or seasonal residences.",
"A designated place for recreational camping.",
"An artificial waterway with no flow, or a controlled flow, usable or built for navigation.",
"A tract covered mainly by large treelike grasses. Amplifying Description: For example, bamboo and sugarcane.",
"An area containing military quarters. Amplifying Description: Typically consisting of the residential sections of a military installation, where tactical training may be limited due to other activities that would endanger and disrupt personnel and their dependents.",
"A prepared site, typically including facilities, used for holiday accommodations where caravans and/or motor homes are parked. Amplifying Description: Caravans are travel trailers towed behind vehicles while motor homes are self-contained vehicles used for both travel and accommodations. Facilities may include utility connections (for example: water, power, or gas), convenience store(s), showers, laundry facilities, and swimming pools.",
"An unimproved road. Amplifying Description: The surface is usually rough (for example: rutted) and minimally prepared (for example: packed earth or thinly covered with gravel).",
"A single large fortified building that has thick walls, battlements, and often the presence of a moat, and is commonly of some historical significance. Amplifying Description: Historically castles were designed and constructed as defensive structures situated so as to dominate the surrounding countryside. With advancing technology, especially artillery, they have become obsolete for military defensive purposes and are now valued primarily for their historical significance. In more recent times elaborate country houses were built incorporating many design elements of a castle but which were not fully capable of being used as defensive structures. Examples of castles of both types include Doue-la-Fontaine and Neuschwanstein.",
"A fortified complex of buildings and related structures that consists principally of a central keep with surrounding thick walls, battlements, and often the presence of a moat, and is commonly of some historical significance. Amplifying Description: A castle complex may be quite extensive, including multiple distinct buildings of diverse function. Historically castle complexes were designed and constructed as defensive structures situated so as to dominate the surrounding countryside. With advancing technology, especially artillery, they have become obsolete for military defensive purposes and are now valued primarily for their historical significance. Examples of castle complexes include Prague and Windsor Castles.",
"A device in which the separation of petroleum is carried out in the presence of a catalyst.",
"A solid raised way across a terrain obstacle (for example: a wetland or a body of shallow water) that is intended to support a transportation route (for example: a road or a railway). Amplifying Description: The causeway structure is often constructed from local fill supplemented by other materials (for example: rocks, boulders or gravel) and consists of a solid linear structure in the configuration of an embankment.Causeway structures are built just high enough to insure that the transportation route will remain passable during periods of flooding, tides and seasonal rainfall.Culverts may occur along the length of the causeway structure and individual sections of the causeway structure may be interrupted by bridges.",
"The entrance to an interconnected series of naturally occurring subterranean chambers. Amplifying Description: Typically located in limestone, and often open to the Earth's surface either vertically or horizontally. Alterations may have been made to the cave mouth.",
"A site and associated structures devoted to the burial of the dead.",
"A location to control passage and/or to register, declare and/or inspect goods, vehicles and/or people.",
"A man-made container used for the collection and/or storage of water.",
"A man-made cleared strip through a vegetated region. Amplifying Description: May be designed to: provide access for a road, railroad, pipeline, power transmission line, or electrical signal line; demarcate a boundary; obtain survey line-of-sight; or to impede the progress of forest fires (a firebreak).",
"An area of land and/or sea especially dedicated to the protection and maintenance of biological diversity, and of natural and associated cultural resources, and managed through legal or other effective means. Amplifying Description: As determined, for example, by the International Union for Conservation of Nature and Natural Resources (IUCN).",
"A region whose prevailing natural conditions have been degraded through contamination by harmful or objectionable substances. Amplifying Description: The contamination may be either naturally occurring or the result of human activity. For example, polluted by sewage or toxic chemicals, obscured by smoke or ash from volcanic eruptions, or contaminated by exposure to Chemical, Biological, Radiological, and/or Nuclear (CBRN) agents.",
"A terrain object (for example: a marker) with a known location (for example: horizontal position, elevation, or both) intended to serve as a survey control. Amplifying Description: Usually of a lower order of positional accuracy than a Geodetic Point but of sufficient accuracy for local surveying.",
"A structure that houses personnel and equipment used to control the flow of traffic within a specified range of an installation. Amplifying Description: Examples of installations that use control towers are aerodromes, railways, and maritime routes.",
"A mechanical device for conveying articles or materials during manufacture or processing using an endless moving belt or series of rollers.",
"A facility for the removal of thermal energy (for example: by generating and circulating chilled water) for cooling purposes.",
"A tall tower for cooling hot water from an industrial process before reuse.",
"An open area that is open to the sky and surrounded by walls or buildings forming the precincts of a larger facility (for example: an extended house, a castle, or a homestead), often in the form of an area that is enclosed by a single building. Amplifying Description: Historically, these areas in inns and public buildings were often the primary meeting places for some purposes, leading to the other meanings of the term 'court'.",
"Equipment for lifting, shifting, and lowering objects or materials by means of a swinging boom or with the lifting apparatus supported on an overhead track.",
"A deep crack or fissure in a glacier that results from differential movement of ice.",
"A narrow opening or fissure produced by a crack in the land, especially in rock. Amplifying Description: May also describe a deep vertical opening in the terrain that appears after an earthquake.",
"An area that has been tilled for the planting of crops.",
"A location where land transportation routes intersect or cross at the same vertical level. Amplifying Description: For example, a railway crossing, a road intersection, and a ford.",
"A location that normally does not appear as a specific, characterized object but that represents an area where a specific cultural factor (for example: religion, ethnicity, language, or tribal/clan affiliation) predominates.",
"An enclosed channel for carrying a watercourse (for example: a stream, a sewer, or a drain) under a route (for example: a road, a railway, or an embankment). Amplifying Description: Usually the construction of the route is unaffected.",
"An excavation in the terrain to provide passage for a land or water transportation route (for example: a road, a railway, and/or a canal).",
"The demarcation line between a cut and the surrounding land surface.",
"A barrier constructed to hold back water and raise its level to form a reservoir or to prevent flooding.",
"A resource that is a set of instances of one or more modeling entities selected according to a single rationale (for example: a common production or publication process). Amplifying Description: For example, a set of modeling entities whose instances together constitute a 'water resources map'.",
"A sunken place in the terrain that is completely surrounded by higher terrain.",
"An arid and treeless uncultivated sparsely populated tract of land.",
"A concave-shaped aerial that is used for emitting and/or sensing electromagnetic energy. Amplifying Description: For example, used to transmit and/or receive electronic signals as at a satellite station or to capture electromagnetic energy as in radio astronomy.",
"A site on land for the collection and/or deposition of refuse or discarded material.",
"An artificial waterway with no flow, or a controlled flow, usually unlined, used for draining or irrigating land.",
"Upward-pointing obstacles laid in the ground to slow or stop the movement of vehicles. Amplifying Description: Typically constructed of regularly spaced concrete or metal shapes laid in single or multiple rows.",
"A place where motion pictures are shown while viewers remain in their vehicles.",
"An artificial basin fitted with a gate or caisson into which vessels can be floated and the water pumped out to expose the bottom of the vessel.",
"A facility including one or more buildings and equipment used for electric power generation. Amplifying Description: An electric power station consists of one or more power generating units, each consisting of the full set of equipment required to generate power and capable of independent operation. The power generating units are located on one or more contiguous or adjacent properties, are under the common control of the same entity and supply power through a common connection to the electric grid. Electric power stations most commonly are used to generate electricity for long distance transmission.",
"A line connecting points having the same elevation value relative to a vertical datum.",
"A man-made raised long mound of earth or other material.",
"A structure wherein aircraft or rocket engines are tested. Amplifying Description: The most common test cells are used for testing the performance characteristics of jet engines and are typically located at military aerodromes or aerospace research and development facilities. Test cells for liquid-fueled rocket booster engines are unique, massive structures (for example: the test cell located at Stennis Space Flight Center in the U.S.).",
"An excavation and/or embankment created by remolding the natural configuration of the terrain for the purpose of enhancing the defense of a site from armed attack. Amplifying Description: The earthwork may include ancillary elements (for example: a palisade) or reinforcements (for example: a concrete facing).",
"A long, narrow ridge of sand and gravel deposited by a glacial stream.",
"A mechanical device for removing materials from the ground. Amplifying Description: For example, a dredger, a power shovel, and a dragline.",
"An excavation made in the terrain for the purpose of extracting and/or exploiting natural resources.",
"An area that has been developed to perform a specific principal function, consisting of one or more vertical constructions (for example: structures or buildings), horizontal constructions (for example: pavements, roads, rail tracks, or bridges), and/or supporting utilities (for example: power lines, water supply, or sewerage), plus the underlying land. Amplifying Description: For example, an industrial plant consisting of building(s), shipping dock(s), storage area(s), power transformer(s), heating and/or cooling equipment, vehicle parking, roads, railroad tracks, and perimeter fences and gates.",
"An area where permanent facilities exist to hold outdoor fairs, circuses or exhibitions.",
"A man-made barrier of relatively light structure used as an enclosure or boundary. Amplifying Description: Similar structures that are constructed of heavy materials (for example: stone, rock or masonry) are classified as walls.",
"A route where a ferry crosses from one shore to another.",
"A location where a ferry takes on or discharges its load.",
"An apparatus for drawing water directly from a main, especially alongside a street or road, consisting of a pipe with one or more nozzles or spouts, to which a hose of a fire-engine may be attached.",
"A site designated for the purpose of discharging firearms or detonating munitions.",
"A facility involved in the breeding (hatching and associated activities) and cultivation (raising for release or harvesting) of fish in tanks or landlocked enclosures. Amplifying Description: Fish species raised on fish farms include, for example, salmon, catfish, tilapia, cod, carp, and trout.",
"A series of ascending pools constructed to enable fish to swim upstream over (or around) a dam.",
"A fence of stakes or wall of stones set in a river or along the shore to direct fish towards fish traps or nets. Amplifying Description: The weir is shaped so as to encourage fish to naturally congregate, usually based on river or tidal flow. Although generally consisting of linear segments on rivers, in shore areas one or more components may be curved so as to form an enclosure with a narrow entrance. When constructed of stones the thickness of the wall constitutes a permanent hazard to maritime navigation.",
"A staff or pole on which a flag is raised.",
"An open-ended pipe at which waste gases are burned.",
"A form of dry dock consisting of a floating structure of one or more sections which can be partly submerged by controlled flooding to receive a vessel, then raised by pumping out the water so that the vessel's bottom can be exposed.",
"An artificial structure or gate that is utilized as a defense against flooding or storm surges. Amplifying Description: Consideration should be given to using the more specific Dam or Embankment features where appropriate in lieu of Flood Control Structure.",
"A shallow place in a body of water used as a crossing.",
"A tract of land primarily covered by trees and undergrowth. Amplifying Description: The area is sometimes mixed with pasture.",
"A site in a forest or wood(s) that has been cleared, often for slash and burn agriculture and/or as a result of clear-cutting logging. Amplifying Description: May also occur from natural causes such as a forest fire.",
"A building that is specifically designed or reinforced to provide for defense from armed attack.",
"A monumental and/or ornamental structure containing moving water, often including jets, falls, or other decorative features. Amplifying Description: The structure is often of a civic nature; the water is typically recirculated.",
"A facility for the storage of fuel (for example: jet fuel, gasoline, or diesel oil). Amplifying Description: The fuel is typically stored in large tanks that may be partially or wholly buried and is accompanied by metering and dispensing equipment. Facilities may range in size from a small stockpile of drums (sometimes termed a 'fuel dump') to a large perimeter-controlled site with multiple permanent surface tanks, in-ground pipelines and associated equipment (sometimes termed a 'fuel depot').",
"A permanent raised structure used to support equipment (for example: cranes, signal lights, or signs) while spanning over or around an object (for example: over a road or railroad, or around a ship hull or rocket). Amplifying Description: A gantry may be moveable (for example: a rocket gantry may be repositioned away from the launch pad when pre-launch preparations are complete). A 'scaffold' is a structure that may be similar in appearance but is assembled only for temporary use (for example: during external repair of a building).",
"A barrier on a transportation route (for example: a road, a railway, a tunnel, or a bridge) that controls passage (may be opened and closed).",
"A device that monitors river flow and/or depth, and any associated support structures.",
"A fracture or zone of fractures in a rock formation, marked by the relative displacement on either side of the plane of the fracture. Amplifying Description: The intersection of a geologic fault with the ground surface is termed the 'fault trace' and is commonly plotted on maps to represent a fault. Since geologic faults do not usually consist of a single, clean fracture, the term 'fault zone' (or 'distributed fault') is often used when referring to the zone of complex deformation and numerous small fractures that is associated with the fault plane.",
"A terrain surface feature controlled by or derived from the heat of the Earth's interior. Amplifying Description: For example, a hot spring.",
"A large mass or river of ice formed by accumulation and compaction of snow on higher ground that is moving slowly down a slope or valley from above the snowline.",
"A tract of land on which golf is played.",
"A parcel of land used for practicing golf shots.",
"A tall structure, equipped for loading, unloading, processing, and/or storing grain.",
"An enclosed container, used for storing grain or fodder.",
"A structure for special viewing of outdoor events, usually roofed, that has tiers of seats or standing room for spectators.",
"A tract covered mainly by grasses that have little or no woody tissue. Amplifying Description: For example, pasture, meadow, and steppe.",
"A building or structure constructed primarily of transparent material (for example: glass or plastic), in which temperature and humidity can be controlled for the cultivation and/or protection of plants. Amplifying Description: Greenhouses can range in size from very large conservatories such as the Palm House at Kew Gardens in England to row covers. Many of the large public greenhouse conservatories are used for growing tender and rare plants. Commercial greenhouses are often state-of-the-art production facilities for vegetables or flowers. Row covers and similar structures are usually made of a lightweight transparent material placed directly above rows of crops on a supporting framework to form a low tunnel. The transparent materials on these structures may be temporary being removed once the crop is well-established. At times, the entire structure may be removed.",
"A natural or artificial improved body of water providing protection for vessels and generally anchorage and docking facilities. Amplifying Description: A harbour consists of both its port and its waters.",
"A hardened structure built above or partially above ground that encloses aircraft to provide protection from enemy attack. Amplifying Description: The shelter is closed by blast resistant doors and is generally limited in size, only accommodating one or two relatively smaller (for example: fighter) aircraft. Those built to NATO specifications are designed to withstand a direct hit by a 226 kilogram bomb.",
"A facility for the generation of thermal energy for heating purposes.",
"A continuous growth of shrubs planted as a fence, a boundary, and/or a windbreak.",
"A designated area, usually with a prepared surface, used for the take-off, landing, or parking of helicopters. Amplifying Description: This prepared surface could either be located on land or on a platform over water. It may or may not be associated with an aerodrome. For example: a hospital helipad, and an offshore rig helipad.",
"An aerodrome intended to be used for the arrival, landing, takeoff or departure of vertical takeoff and landing aircraft/helicopters.",
"An enclosed tract on which livestock are temporarily kept. Amplifying Description: For example, a sheepfold, a holding paddock, a livestock pen, a feedlot, and/or a stock yard. The enclosure may be by, for example, a fence or a wall.",
"A tract covered by the systematic planting of hop vines.",
"A top-loaded funnel-shaped structure for temporary holding of loose material which will be dispensed from its bottom.",
"A vessel, either stranded aground or permanently moored, that is no longer seaworthy due to an inoperable propulsion plant or compromised vessel integrity.",
"A place of higher elevation within a wetland (for example: a swamp, a bog, or a marsh).",
"A small, simple free-standing (detached) self-contained residence usually having only a single multi-function room. Amplifying Description: May be intended only as temporary (for example: by displaced persons) or seasonal (for example: during seasonal livestock movement) residence. May be crude (for example: quickly built from locally-available natural materials) or relatively modern in construction and austerely furnished (for example: a Norwegian 'hytte').",
"A facility involved in the production or distribution of petroleum, oil and/or natural gas products.",
"An area where the presence of recoverable petroleum, oil, and/or natural gas has been identified. Amplifying Description: The field can exist regardless of current exploitation activities.",
"The vertical face of a glacier or ice shelf.",
"A rocky peak projecting above a surrounding ice field that may be perpetually covered with ice.",
"A route over a frozen watercourse. Amplifying Description: Usually marked and intended to support substantial vehicle traffic. Often designed as an alternate to a seasonally-closed ferry crossing.",
"A floating ice sheet of considerable thickness that is normally attached to the land along its landward edge. Amplifying Description: Ice shelves are the seaward extension of land glaciers. Limited areas of the ice shelf may be aground where the glacier first enters the water and possibly in other places offshore. Ice shelves are usually of great horizontal extent and have a level or gently undulating surface. The seaward edge of an ice shelf is termed an 'ice cliff'.",
"A permanent layer of ice covering a tract of land (especially a polar region) or the top of a mountain. Amplifying Description: Usually includes a surface layer of snow.",
"An estate or large farm operating on the plantation economy model in which the farm operates as a single economic unit whose operations are based on agricultural mass production of a few staple crops (for example: cotton, tobacco, sugar cane, bananas, and/or rubber) that are typically not indigenous to the region. Amplifying Description: Plantation economies are often dependent on distant (for example: export) markets as the crops are harvested in large quantities. Historically, industrial farms were often found in former European colonies and termed 'plantations'.",
"A structure used in material processing that employs heating to harden (for example: to fire brick or ceramic), pyrolyse (for example: convert coal to coke, or limestone to lime), burn (for example: to incinerate waste), or dry (for example: lumber). Amplifying Description: May assume many forms, for example a domed 'beehive' kiln or a long linear coke oven battery.",
"A body of water that is entirely surrounded by land. Amplifying Description: It may occur in a natural terrain depression in which water collects, or may be impounded by a dam, or formed by its bed being hollowed out of the soil, or formed by embanking and/or damming up a natural hollow (for example: by a beaver dam).Inland waterbodies have many uses such as: a source of water for irrigation, industrial processes, human consumption, and recreation. Impounded inland waterbodies may also be used for flood control.",
"A grouping of facilities, located in the same vicinity, which support particular functions.",
"A site maintained for the public and declared to be of national or provincial historical significance and/or interest.",
"A line designated as the place on the Earth where each calendar day begins. Amplifying Description: This line generally coincides with the 180th meridian but is modified to avoid land.",
"A land mass, other than a continent, surrounded by water.",
"An aerodrome on land intended to be used either wholly or in part for the arrival, departure and surface movement of aircraft.",
"A tract periodically covered by flood water, excluding tidal waters.",
"The line where a land mass is in contact with a body of water and the tide state or river stage are unspecified. Amplifying Description: It may be in either the littoral or inland waters. In the littoral, consideration should be given to using the more specific high water or low water lines based on the nature of the source data collection.",
"The mass of earth or rock which has slipped down from a mountain or cliff.",
"A designated site or structure from which a rocket or missile is launched.",
"A structure serving as a support for one or more lights. Amplifying Description: For example, a light standard or a lamp post.",
"A distinctively marked vessel anchored or moored at a charted point, to serve as an aid to navigation. Amplifying Description: By night, it displays a characteristic light(s) and is usually equipped with other devices (for example: a fog signal, a submarine sound signal, and/or a radio-beacon) to assist navigation.",
"A distinctive structure on or off a coast exhibiting a major light designed to serve as an aid to navigation.",
"Equipment located at or below water level where liquids (for example: cooling water) are spread out.",
"An enclosure with a pair or series of gates used for raising or lowering vessels as they pass from one water level to another.",
"A tract of vegetation that is being exploited for lumber resources.",
"A location, which is generally elevated, from which the surrounding area may be observed. Amplifying Description: For example, it is easily accessible by vehicle, is free of obscuring vegetation, and the local topography allows for unobstructed viewing of distant features.",
"A soft, poorly drained wetland that is characterized by the growth of only non-woody plants (for example: grasses) and often forms a transition region between a waterbody and land. Amplifying Description: It is subject to frequent or tidal inundations, but not considered to be continually under water. It lacks trees. A subtype of the more generalized wetland.",
"A marker erected and/or maintained as a memorial to a person and/or event.",
"An installation designed for military use. Amplifying Description: For example, used to perform military operations, initiate forward movements, and/or furnish supplies. Often protected by fortifications or natural advantages.",
"A structure over a vertical mine shaft containing machinery (for example: a winding head or hoist) used to transport minerals, equipment, and/or workers between the surface and various levels within the mine. Amplifying Description: It is usually the most prominent structure at a shaft mining facility.",
"A site laid with explosive mines.",
"A man-made heap of mining or quarrying products that does not contain waste materials. Amplifying Description: For example, a pile of coal or quarried stones.",
"A site and related facilities for storing and launching missiles.",
"A trench surrounding a tract of land and serving as a barrier. Amplifying Description: It is usually filled with water.",
"A site for the permanent parking of mobile homes used as dwellings and designed without a permanent foundation. Amplifying Description: Mobile homes are prefabricated homes built in factories, rather than on-site, and then taken to the place where they will be occupied. They are usually transported by tractor-trailers over public roads to sites which are often in rural areas or high-density developments. While these houses are usually placed in one location and left there permanently, they do retain the ability to be moved as this is a requirement in many areas. Behind the cosmetic work fitted at installation to hide the base, there are strong trailer frames, axles, wheels and tow-hitches.",
"A mast used to secure an airship.",
"An accumulation of soil and stone debris deposited by a glacier.",
"A building at, or in which, motor vehicles are refuelled, serviced, and sometimes repaired. Amplifying Description: Usually accompanied by several prominently placed petrol pumps.",
"A narrow route through a mountainous region or over a mountain range.",
"A facility for the storage of munitions (for example: bombs, missiles, warheads, mines or ammunition). Amplifying Description: Specifically, storage of weapons charged with: explosives; propellant; pyrotechnics; initiating composition; or nuclear, chemical, or biological material for use in military operations. Facilities may range in size from a small stockpile of munitions (sometimes termed an 'ammo dump') that may be revetted to a large perimeter-controlled site with multiple dispersed bunkers laid out to minimize the effect of accidental detonation (sometimes termed a 'munitions depot').",
"A location that normally does not appear as a specific, characterized object but that has a name that is required to be displayed in association with that location. Amplifying Description: For example, the name of the Alps or the Sahara.",
"A naturally formed pool of water. Amplifying Description: It is usually fed by surface drainage from the surrounding region and/or water arising from an underground source (for example: a spring or a resurgence).",
"A free-standing self-supporting construction (for example: a large piece of equipment) designed to support human activities (for example: agriculture, manufacturing, or mining) but not intended for human occupancy and/or habitation (for example: a house, a bank, an office, or a stadium). Amplifying Description: May have only limited protection from the weather (for example: a hayrick) and often composed of components specialized for a particular activity (for example: animal feeding, material storage, or traffic control) or process (for example: chemical reaction, heating, mixing, or physical shaping). For example, a cane press, a cement mill, a cotton gin, a distillation tower, and a rock crusher.",
"A resource that collects instances of one or more modeling entities that share common source(s) and processing step(s) as the basis for their digital non-spatial representation. Amplifying Description: The modeling entity specifies metadata regarding the type(s) of data that were used to define the digital representation of the non-spatial component(s) of the entity collection. For example, an existing vertical obstruction dataset may be used to populate accurate height or material type attributes, or a land navigation dataset may be used to populate accurate road width, clearance, and/or surface composition attributes.",
"A shaft sunk into the ground to reach and tap a supply of liquids and/or gases other than water intended for use in agriculture or domestic consumption. Amplifying Description: Typically drilled to tap underground reservoirs of hydrocarbons (for example: petroleum or natural gas). May also, for example, yield geothermally heated liquids for use in power generation or heating, or brine for use in the extraction of salt.",
"A building-like structure intended to create a barrier against the release of radioactivity generated during nuclear power operations. Amplifying Description: The structure is usually heavily reinforced. It houses equipment used to manage a self-sustaining nuclear reaction of fissile material. The consequent release of energy may be used to generate electricity, as in a power plant.",
"A small, isolated, fertile or green area in a desert region usually having a spring or well.",
"A commercial facility consisting of multiple office buildings tenanted by one or more non-retail businesses (for example: corporate management, consulting services, or research and development) and supportive businesses (for example: a restaurant serving mid-day meals or a post office) that share a common park-like setting consisting of landscaping (for example: lawns, ornamental plantings, or ponds), parking facilities, and common entrances from adjacent roads. Amplifying Description: May also include commercial tenants involved in light industry (for example: gem cutting or specialized electronics manufacture).",
"An artificial structure that is located offshore. Amplifying Description: It usually has a surface that is raised above the sea and may be used as a working stage for conducting offshore operations (for example: drilling for petroleum and/or natural gas, loading and/or unloading vessels, or navigation support).",
"A tract covered by systematic plantings of trees that yield fruits (including nuts).",
"A large outdoor screen for showing motion pictures.",
"An overhead obstruction (for example: an underpass, an overhead pipeline, and/or the overhang of a building) on a transportation route.",
"An area of defined limits which is set aside for human recreation and enjoyment and/or for historic preservation purposes, and is usually maintained in a natural, semi-natural, or ornamentally planted state. Amplifying Description: Parks may be in urban areas such as Central Park in New York City or in less developed areas such as Poplar Forest in Forest, Virginia, where Thomas Jefferson's plantation and plantation house are located.",
"A designated, multi-level, structure used for parking and/or storing vehicles. Amplifying Description: May be present as part of a building or as a separate structure.",
"An apparatus for imparting high velocities to charged particles.",
"A pipeline that is used by hydroelectric plants to transport water by gravity from a reservoir to the turbine(s).",
"A site that has been set aside for picnics. Amplifying Description: It may have picnic tables for public use.",
"A connected set of pipes for conveying liquids, slurries, or gases. Amplifying Description: Usually for long distances and often located underground.",
"A traversable site extending across a pipeline that acts as a passageway for cross-country movement of vehicles or troops.",
"A tract where plants (for example: shrubs, flowers, and/or trees) are grown for transplanting, seed, and/or grafting.",
"Sea ice that is more than one year old and more than 3 metres thick. Amplifying Description: Sea ice is any form of ice which has originated from sea water.",
"A place provided with terminal and transfer facilities for loading and/or discharging cargo or passengers, usually located in a harbour. Amplifying Description: A port and its related waters together comprise a harbour.",
"A facility, along a power transmission line, in which electric current is switched, transformed, and/or converted.",
"A location on a watercourse that has ramps, structural piles, and/or piers constructed on one or both shores to allow for suitable future crossing operations using floating bridges or rafting equipment. Amplifying Description: For example, a prepared float bridge site or a prepared raft site.",
"An open site that serves as a public meeting location in a built-up area.",
"A facility to move solids, liquids or gases by means of pressure or suction.",
"A pylon or pole used to support one or more cables.",
"A vertical shaft that provides access to an underground aqueduct and which is part of a qanat system. Amplifying Description: A qanat system consists a system of deep underground tunnels especially constructed to channel water from an uphill region to a dryer lower region for use (for example: a village, a garden, a crop land), and qanat shafts to provide access from the surface to the underground tunnels.",
"A ground or tract marked out for racing. Amplifying Description: The track may be banked to facilitate high-speed racing, either by grading of the terrain or the use of structures. The bank angle may exceed 30 arc degrees and such structures can reach significant heights.",
"A facility utilizing radar to detect and analyze objects (for example: aircraft, artificial satellites, asteroids, and/or missiles) and/or environmental phenomena (for example: tornadoes). Amplifying Description: May include both a radar aerial as well as a structure housing radar equipment.",
"One or more railway tracks comprising a network that is operated for the conveyance of passengers and/or goods.",
"A stretch of railway track connected to a main railway and used for temporary storage, passing, loading, and/or unloading.",
"A signal used to control traffic on a railway.",
"A rotating platform with railway tracks used for turning locomotives and/or railway carriages. Amplifying Description: May be enclosed within a structure.",
"A system of railway tracks and associated structures that are located within defined limits and that provide for loading, unloading, and/or assembling trains.",
"An inclined plane, usually man-made, for moving between two levels.",
"Portions of a stream with accelerated current where it descends rapidly but without a break in the slope of the bed sufficient to form a waterfall. Amplifying Description: The surface is usually broken by boulders and rocks.",
"A site engaged in the wrecking, dismantling, storage, recycling, and/or disposal of discarded or scrap products. Amplifying Description: For example, a wrecking yard or a scrap yard.",
"A small structure that stands alone, and is designated for the purpose of supplying a product (for example: souvenirs, magazines, snacks or refreshments) or service (for example: a shoe shine) to passers-by. Amplifying Description: It may be roofed (for example: a newspaper stand along the side of a city street or the attendant's booth in a parking lot or at a taxi cab stand), covered by an awning (for example: a cellular phone booth in the center of the promenade of a shopping mall or a hot dog stand on a city sidewalk), or unroofed. Although often semi-permanent in nature it may be wheeled and portable on a seasonal basis or more frequently as business conditions warrant.",
"A tract that is periodically covered with water and is used for growing rice.",
"A superstructure fitted for drilling or lifting operations for extraction and/or exploitation of natural resources.",
"A natural flowing watercourse.",
"A route with a specially prepared surface that is intended for use by wheeled vehicles.",
"A connection designed to provide traffic access from one road to another.",
"A roadside place usually having facilities for people and/or vehicles.",
"A significant outcropping of exposed bedrock.",
"A circular or semicircular building, with a railway turntable in the centre, used for storing and/or repairing railway locomotives. Amplifying Description: The railway turntable may be either completely covered, partially covered or not covered, and partially or completely surrounded by the building.",
"The deteriorated remains of an unspecified structure.",
"A defined rectangular area on a land aerodrome prepared for the landing and take-off of aircraft.",
"A natural depression in arid or semi-arid regions whose bed is covered with salt encrusted clayey soil. Amplifying Description: Found especially in North Africa and Arabia.",
"Shallow pools, normally man-made, used for the natural evaporation of water for the collection of salt.",
"A flat area of natural surface salt deposits. Amplifying Description: May also be used to describe smaller areas; these are commonly termed salt pans.",
"One or more mounds or ridges of sand usually formed by the wind.",
"A large outdoor board for publicly displaying the score in an athletic event. Amplifying Description: Usually associated with a sports stadium or major playing field.",
"A designated portion of water that is outlined by visual surface markings and used by seaplanes to land and take-off.",
"A continuously occupied concentration of tents or lightweight fixed structures (for example: huts) serving as residences. Amplifying Description: May also include supporting non-residential (for example: commercial) structures.",
"A small reservoir where solid matter is precipitated from a liquid by evaporating or settling.",
"An operational area with buildings and other facilities for the purification of wastewater.",
"A section of a built-up area consisting chiefly of densely packed shacks and having few, if any, streets and no public facilities. Amplifying Description: Usually located on the outskirts of the built-up area. The shacks are generally crude, improvised, and made from salvaged materials.",
"A curve along a land transportation route that may restrict vehicle traffic.",
"The wall of the excavation within a quarry or extraction mine.",
"A small building, generally of light construction, that usually has one or more open sides. Amplifying Description: Typically used for storage.",
"A device used to raise ships vertically between water bodies with different elevations. Amplifying Description: Normally ship elevators consist of water filled chambers which can be raised or lowered by means of mechanical devices. Commonly used to move ships between canals where locks would be impractical.",
"A moveable container used for the shipping of solid, liquid, or gaseous materials. Amplifying Description: The container may be either closed on all sides or open on the top or along a side. With minor modifications, if needed, shipping containers may be used for non-traditional purposes including, for example: emergency shelter, housing, retail activities, warehousing and secure space.",
"A large enclosed area adjoining the sea or a major river, including facilities in which ships are built or repaired.",
"A commercial facility tenanted by multiple retail stores (for example: household goods, clothing, or books), restaurants (for example: a food court), entertainment venues (for example: a movie theatre or electronic games arcade), and/or other businesses (for example: professional services), that is completely enclosed, climate controlled, has a common public arcade (for example: furnished with decorative plantings, benches, and/or fountains) and a common vehicle parking area (for example: a parking lot or parking garage). Amplifying Description: When the commercial entrances open onto the interior of the complex (public access being by means of central entries and broad corridors) it may consist of multiple levels connected by escalators and is often termed a 'shopping mall'. When the commercial entrances open towards the exterior of the complex and access to individual commercial entrances is directly from an adjacent vehicle parking area it consists of a single level and is often termed a 'shopping centre' or 'shopping plaza'.",
"An artificial structure attached to land bordering a body of water and fixed in position. Amplifying Description: It is usually fixed to the waterbody bottom (for example: a mole) but may occasionally be fixed in position (for example: attached to the shore at one end and held between pilings at the other), but floating. Shoreline constructions are normally used for berthing and/or protection.",
"A ramp-like structure on a shoreline that is intended to facilitate the movement of vessels and/or materials (for example: logs) into or out of the water.",
"A paved or improved pedestrian path, typically located adjacent and parallel to a street or road.",
"A man-made structure consisting of a steep ramp levelling off at the end and built on a natural slope, used in ski-jumping.",
"A slope or trail prepared for skiing.",
"A gate used to regulate the flow or level of water in a watercourse (for example: stream, irrigation ditch, or sluice). Amplifying Description: Sluice gates are normally installed in a superstructure and/or frame and most commonly slide vertically to open but on occasion may instead slide horizontally. When opened they allow water to flow under or beside the gate. Commonly sluice gates will be installed perpendicular to the orientation of the flow of water within a watercourse and will be constructed as wide as the watercourse they regulate. Sluice gates may also be installed along the margins of watercourses for the purpose of controlling or permitting the flow of water to or from that watercourse into adjacent watercourses. Sluice gates may be used to regulate both tidal or non-tidal waters.",
"A place at which a service generally of interest to small craft or pleasure boats is available.",
"A vertical structure containing a passage or flue for discharging smoke and gases of combustion.",
"A tree, branch or broken pile embedded in the ocean floor, river or lake bottom and may not be visible on the surface, forming thereby a hazard to vessels.",
"A large area permanently covered by snow and/or ice. Amplifying Description: May cover land and/or water.",
"A region of the land that is homogeneous with respect to a soil characteristic.",
"An extensive collection of solar panels that are collocated and serve a common purpose (for example: the generation of electricity or the generation of heating steam and/or water). Amplifying Description: The collection is often organized as an array covering many hundreds of square metres in area and it may be controlled so as to track the direction of the sun throughout the day.",
"A panel designed to absorb the sun's rays for the purpose of generating electricity or heat.",
"A facility that is used to support space related activities (for example: services such as assembly, launching or recovery of spacecraft or managing flight operations).",
"A resource that collects instances of one or more modeling entities that share common source(s) and processing step(s) as the basis for their digital spatial representation. Amplifying Description: The modeling entity specifies metadata regarding the type(s) of data that were used to define the digital representation of the spatial component(s) of the entity collection. In a 2-dimensional representation the spatial component(s) are expressed as the horizontal coordinate values of the entity geometry. In a 3-dimensional representation the vertical coordinate values may be determined using a separate source and process (for example: stereoscopic imagery), in which case the 'vertical source' attributes may be additionally used for greater specificity.",
"A passage for surplus water to run over or around a dam.",
"An open area where sporting events, exercises, and/or games occur. Amplifying Description: For example, an athletic field, a playing field, and/or a sports field.",
"A designated location with an elevation value relative to a vertical datum.",
"A building similar to a barn and adapted for the shelter and feeding of domestic animals, being divided into individual stalls. Amplifying Description: Although commonly used to house horses, it may be used to house other animals (for example: prize cattle, sheep or goats) and often includes a storage loft (for example: for hay).",
"A field and/or stage partly or completely surrounded by a structure designed to allow spectators to stand or sit while viewing an event. Amplifying Description: The field and/or stage may be enclosed in a building or be outdoors. Stadiums are surrounded on most or all sides by tiered seating for spectators. Often designed in size and shape to accommodate specific sports (for example: baseball, football, basketball or ice hockey), theater or musical performances.",
"A series of fixed steps leading from one level to another, especially such a series leading from one floor level to another inside a structure. Amplifying Description: The steps may also be on the outside of the structure, for example, on a gasometer.",
"A stretch along a land transportation route where the slope is high enough to slow, hinder, or even stop traffic. Amplifying Description: The percent (%) slope is the ratio of change in elevation (vertical distance) to horizontal ground distance multiplied by 100.",
"A steep, vertical, or overhanging face of rock and/or soil. Amplifying Description: For example, an escarpment, a bluff, or a cliff.",
"A defined rectangular area on the ground at the end of the take-off run available that has been prepared as a suitable area in which an aircraft can be stopped in the case of an abandoned take-off.",
"A tract used for the storage of products and/or supplies.",
"A container used for the storage of liquids and/or gases that is not supported by a tower.",
"A collector opening into a pipe or channel to allow the removal of excess runoff water or in some cases sewage. Amplifying Description: In civil engineering terms, a drop inlet.",
"A lamp intended to illuminate a road. Amplifying Description: May also illuminate the ground adjacent to the road. Usually attached to a tall pole.",
"A sign placed along a road for the purpose of regulating the flow of traffic (for example: vehicles and/or pedestrians) and/or providing information.",
"A long pile (for example: a heavy timber or section of steel, wood, or concrete) forced into the earth that may serve as a support (for example: for a pier) or as a free standing pole within a marine environment.",
"A surface structure that may be covered and/or surrounded with earth and is resistant to ordnance. Amplifying Description: Used, for example, for storage and/or aircraft protection.",
"A seasonally flooded, poorly drained wetland with more woody plants than a marsh and better drainage than a bog. Amplifying Description: It is covered with water all or most of the year, and accumulating dead vegetation does not rapidly decay. It can exist on flat-lying areas created by certain geomorphic environments. The vegetation mainly consists of hydrophytic trees and/or scrubs whose roots are adapted to wet conditions, with an open to very dense canopy closure. A subtype of the more generalized wetland.",
"A man-made pool used for swimming outdoors.",
"A tract of land occupied by large-capacity tanks in which petroleum, natural gas, or liquid petrochemicals are stored. Amplifying Description: The tanks are usually round, constructed from metal plates, and separated from each other by berms intended to contain any leakage.",
"A defined path at an aerodrome established for the taxiing of aircraft and intended to provide a ground movement link between one part of the aerodrome and another.",
"A site for the testing of technical products and equipment.",
"A balloon that is tethered to the ground at an anchoring device (for example: a ring and pad) or substantial structure (for example: a mooring tower). Amplifying Description: It is usually deployed for extended periods of time and may be used, for example, for weather sensing and/or observation of the surrounding terrain.",
"A tract covered mainly by low-growing, uncultured, woody plants that are thickly tangled together. Amplifying Description: For example, covered by brushwood and/or stunted trees. The predominant height may be up to 6-8 metres.",
"Any water the level of which changes periodically due to tidal action.",
"A structure within which a corpse is entombed. Amplifying Description: It is often a building-like structure that may be partly or wholly underground (except for its entrance), but may be a simple enclosure cut into solid rock (for example: into a cliff face or inside of a cave). It may contain a single corpse or a related group (for example: a family) may be entombed together.",
"A relatively tall, narrow structure that may either stand alone or may form part of another structure. Amplifying Description: Usually of a square, circular, or rectangular cross-section.",
"A set of automatic lights (usually red, amber, and green) for controlling road traffic, especially at a road intersection. Amplifying Description: Usually attached to tall poles or suspended from overhead cables.",
"A path worn by the passage of people or animals.",
"A site reserved for training.",
"A substantial semi-permanent assemblage of material, usually in the form of concrete blocks and/or cylinders, positioned alongside or above a land transportation route, ready to be activated as a potential barrier. Amplifying Description: For example, a rolling block is positioned alongside the route and a drop gate is positioned above the route.",
"A section of a transportation route where its size (for example: narrowing or expansion in width) and/or operating speed is significantly different than in the adjacent sections of the route. Amplifying Description: For example, an increase or decrease in the number of lanes in a road. Constrictions along or beside a transportation route may impede the flow of vehicles or people thus resulting in 'choke points'.",
"A structure built over and/or along a transportation route designed to prevent damage to, or blockage of, the route from rock slides, snow slides and/or weather phenomena. Amplifying Description: For example, a snow shed, a rock shed or a gallery. These structures are usually located in rugged mountainous regions.",
"A station that serves as a stopping place along a transportation route. Amplifying Description: For example, used for the transfer of passengers and/or freight.",
"An individual woody perennial plant, typically having a single stem or trunk growing to a considerable height and bearing lateral branches at some distance from the ground. Amplifying Description: May be distinguished by its relative isolation from other features, thus serving as a landmark.",
"A vast, nearly level, treeless arctic region usually with a marshy surface and underlying permafrost.",
"An underground passage that is open at both ends and usually contains a land transportation route (for example: a road and/or a railway). Amplifying Description: Commonly used to pass through a hill or mountain, or under a river or road. May also provide underground passage in a mine.",
"The opening of a tunnel into a larger space (for example: onto the terrain surface). Amplifying Description: A tunnel is usually open to the terrain surface at both ends, but may sometimes lead to an enclosed space, for example: leading to an underground bunker, into an underground mine (termed an 'adit') or into an underground railway station.",
"A reinforced underground shelter. Amplifying Description: May be located within a mountain or buried below the terrain. Often used as an underground facility for military command, control, and/or troop billeting.",
"Underground living quarters.",
"A removable cover or plate which provides access to underground utility tunnels, distribution lines, or drainage systems. Amplifying Description: For example, a manhole cover.",
"The location at which a watercourse disappears into the terrain.",
"A obstruction placed across a transportation route (for example: a road, a railway, a tunnel, or a bridge) to prevent the passage of vehicles.",
"A tract used for storing and/or parking vehicles (for example: recreational vehicles) and/or vessels.",
"A mechanical device for lifting vessels from the water. Amplifying Description: The device may be, for example, a stationary crane or a wheeled vehicle. After removal from the water the vessel may be maintained (for example: cleaning the hull of encrustations) or stored (for example: moved to a building, shed, or lot for winter storage).",
"A tract covered by the systematic planting of grape vines.",
"A data collection region lacking suitable source coverage and/or where data is not required.",
"A sheet of rock filling a fissure that sometimes shows as a terrain ridge. Amplifying Description: Especially a mass of igneous rock that has intruded upwards through strata.",
"A hill or mountain situated over an opening or openings in the Earth's crust through which lava, cinders, steam, and/or gases, are or have been expelled.",
"A solid man-made barrier of generally heavy material used as an enclosure, boundary, or for protection.",
"An aerodrome intended to be used either wholly or in part for the arrival, departure and surface movement of aircraft on water.",
"A tower-like structure associated with a dam or water source and used for the intake of water.",
"A structure that uses a water wheel or turbine to drive a mechanical process (for example: grinding grain into flour, cutting timber into lumber, or stripping bark from trees for use in tanning). Amplifying Description: A watermill that only generates electricity is more usually termed a 'hydroelectric plant'.",
"An artificial channel for a current of water, especially one built to provide water for industrial or agricultural purposes or for transporting water-borne materials. Amplifying Description: For example, a sluice, a flume, or a tailrace.",
"A tower supporting an elevated storage tank of water.",
"A tract for the treatment of water that consists of a bed of material where water is aerated or filtered.",
"A shaft sunk into the ground to reach and tap a supply of water intended for uses other than power generation, heating or the extraction of minerals. Amplifying Description: May be, for example, drilled to tap deep underground reservoirs or dug to reach a shallow water table. Dug wells are typically circular, lined with masonry, have a stone border and a structure built above then for lowering and raising a bucket.",
"A vertically descending part of a watercourse where it falls from a height (for example: over a rock or a precipice). Amplifying Description: In place names, commonly shortened to 'fall' or 'falls', for example, 'Niagara Falls'.",
"An establishment for storing, purifying, and supplying an area or town with water.",
"A building and associated equipment that is used to inspect and weigh motor vehicles. Amplifying Description: Located adjacent to a road and used to enforce a variety of motor vehicle safety regulations. Motor vehicles may be weighed by driving them onto a platform.",
"A collection of windmotors that are collocated and are organized as a single power generation unit.",
"A tower and associated equipment that generates electrical power from wind.",
"A system of vanes attached to a tower and driven by wind (excluding wind turbines).",
"A site where wild animals are kept for exhibition to the public, that may also support breeding and/or study."
};

unsigned char TDS4DOMAINS[]={
0  /*** Dummy Value ***/,
D_UTAN  /*** Aeration Basin ***/,
D_UTAN  /*** Aerial ***/,
D_UTAN  /*** Aerial Farm ***/,
D_AERO  /*** Aircraft Hangar ***/,
D_AERO  /*** Aircraft Revetment ***/,
D_POPU  /*** Amphitheatre ***/,
D_POPU  /*** Amusement Park ***/,
D_POPU  /*** Amusement Park Attraction ***/,
D_GENE  /*** Annotated Location ***/,
D_AERO  /*** Apron ***/,
D_INWA  /*** Aqueduct ***/,
D_UTAN  /*** Aquifer ***/,
D_POPU  /*** Arcade ***/,
D_POPU  /*** Archeological Site ***/,
D_PHYS  /*** Asphalt Lake ***/,
D_POPU  /*** Astronomical Observatory ***/,
D_POPU  /*** Barn ***/,
D_POAN  /*** Basin Gate ***/,
D_POPU  /*** Billboard ***/,
D_UTAN  /*** Blast-furnace ***/,
D_VEGE  /*** Bog ***/,
D_UTAN  /*** Borehole ***/,
D_UTAN  /*** Botanic Garden ***/,
D_BOUN  /*** Boundary Monument ***/,
D_GRTR  /*** Bridge ***/,
D_GRTR  /*** Bridge Pier ***/,
D_GRTR  /*** Bridge Span ***/,
D_GRTR  /*** Bridge Superstructure ***/,
D_GRTR  /*** Bridge Tower ***/,
D_VEGE  /*** Brush ***/,
D_UTAN  /*** Bucket Elevator ***/,
D_POPU  /*** Building ***/,
D_GRTR  /*** Building Superstructure ***/,
D_POPU  /*** Built-up Area ***/,
D_UTAN  /*** Cable ***/,
D_POPU  /*** Cableway ***/,
D_BOUN  /*** Cairn ***/,
D_POAN  /*** Camp ***/,
D_POPU  /*** Camp-site ***/,
D_INWA  /*** Canal ***/,
D_VEGE  /*** Cane ***/,
D_DEST  /*** Cantonment Area ***/,
D_POPU  /*** Caravan Park ***/,
D_GRTR  /*** Cart Track ***/,
D_POPU  /*** Castle ***/,
D_POPU  /*** Castle Complex ***/,
D_UTAN  /*** Catalytic Cracker ***/,
D_GRTR  /*** Causeway Structure ***/,
D_PHYS  /*** Cave Mouth ***/,
D_POPU  /*** Cemetery ***/,
D_POPU  /*** Checkpoint ***/,
D_INWA  /*** Cistern ***/,
D_VEGE  /*** Cleared Way ***/,
D_VEGE  /*** Conservation Area ***/,
D_UTAN  /*** Contaminated Region ***/,
D_GENE  /*** Control Point ***/,
D_POPU  /*** Control Tower ***/,
D_UTAN  /*** Conveyor ***/,
D_UTAN  /*** Cooling Facility ***/,
D_UTAN  /*** Cooling Tower ***/,
D_POPU  /*** Courtyard ***/,
D_UTAN  /*** Crane ***/,
D_PHYS  /*** Crevasse ***/,
D_PHYS  /*** Crevice ***/,
D_VEGE  /*** Crop Land ***/,
D_GRTR  /*** Crossing ***/,
D_POPU  /*** Cultural Context Location ***/,
D_GRTR  /*** Culvert ***/,
D_PHYS  /*** Cut ***/,
D_PHYS  /*** Cut Line ***/,
D_INWA  /*** Dam ***/,
D_BOUN  /*** Dataset ***/,
D_PHYS  /*** Depression ***/,
D_PHYS  /*** Desert ***/,
D_UTAN  /*** Dish Aerial ***/,
D_UTAN  /*** Disposal Site ***/,
D_INWA  /*** Ditch ***/,
D_DEST  /*** Dragon's Teeth ***/,
D_POPU  /*** Drive-in Theatre ***/,
D_POAN  /*** Dry Dock ***/,
D_UTAN  /*** Electric Power Station ***/,
D_GENE  /*** Elevation Contour ***/,
D_PHYS  /*** Embankment ***/,
D_UTAN  /*** Engine Test Cell ***/,
D_DEST  /*** Engineered Earthwork ***/,
D_PHYS  /*** Esker ***/,
D_UTAN  /*** Excavating Machine ***/,
D_UTAN  /*** Extraction Mine ***/,
D_POPU  /*** Facility ***/,
D_POPU  /*** Fairground ***/,
D_POPU  /*** Fence ***/,
D_GRTR  /*** Ferry Crossing ***/,
D_GRTR  /*** Ferry Station ***/,
D_UTAN  /*** Fire Hydrant ***/,
D_BOUN  /*** Firing Range ***/,
D_INWA  /*** Fish Farm Facility ***/,
D_INWA  /*** Fish Ladder ***/,
D_INWA  /*** Fish Weir ***/,
D_POPU  /*** Flagpole ***/,
D_UTAN  /*** Flare Pipe ***/,
D_POAN  /*** Floating Dry Dock ***/,
D_POAN  /*** Flood Control Structure ***/,
D_GRTR  /*** Ford ***/,
D_VEGE  /*** Forest ***/,
D_VEGE  /*** Forest Clearing ***/,
D_DEST  /*** Fortified Building ***/,
D_POPU  /*** Fountain ***/,
D_UTAN  /*** Fuel Storage Facility ***/,
D_UTAN  /*** Gantry ***/,
D_GRTR  /*** Gate ***/,
D_INWA  /*** Gauging Station ***/,
D_PHYS  /*** Geologic Fault ***/,
D_PHYS  /*** Geothermal Outlet ***/,
D_PHYS  /*** Glacier ***/,
D_POPU  /*** Golf Course ***/,
D_POPU  /*** Golf Driving Range ***/,
D_UTAN  /*** Grain Elevator ***/,
D_UTAN  /*** Grain Storage Structure ***/,
D_POPU  /*** Grandstand ***/,
D_VEGE  /*** Grassland ***/,
D_UTAN  /*** Greenhouse ***/,
D_POAN  /*** Harbour ***/,
D_DEST  /*** Hardened Aircraft Shelter ***/,
D_UTAN  /*** Heating Facility ***/,
D_VEGE  /*** Hedgerow ***/,
D_AERO  /*** Helipad ***/,
D_AERO  /*** Heliport ***/,
D_UTAN  /*** Holding Pen ***/,
D_VEGE  /*** Hop Field ***/,
D_UTAN  /*** Hopper ***/,
D_OCEN  /*** Hulk ***/,
D_VEGE  /*** Hummock ***/,
D_POPU  /*** Hut ***/,
D_UTAN  /*** Hydrocarbon Products Facility ***/,
D_UTAN  /*** Hydrocarbons Field ***/,
D_PHYS  /*** Ice Cliff ***/,
D_PHYS  /*** Ice Peak ***/,
D_GRTR  /*** Ice Route ***/,
D_PHYS  /*** Ice Shelf ***/,
D_PHYS  /*** Ice-cap ***/,
D_UTAN  /*** Industrial Farm ***/,
D_UTAN  /*** Industrial Furnace ***/,
D_INWA  /*** Inland Waterbody ***/,
D_POPU  /*** Installation ***/,
D_POPU  /*** Interest Site ***/,
D_BOUN  /*** International Date Line ***/,
D_PHYS  /*** Island ***/,
D_AERO  /*** Land Aerodrome ***/,
D_INWA  /*** Land Subject to Inundation ***/,
D_PHYS  /*** Land Water Boundary ***/,
D_PHYS  /*** Landslide Mass ***/,
D_AERO  /*** Launch Pad ***/,
D_POPU  /*** Light Support Structure ***/,
D_AITO  /*** Light Vessel ***/,
D_AITO  /*** Lighthouse ***/,
D_UTAN  /*** Liquid Diffuser ***/,
D_INWA  /*** Lock ***/,
D_VEGE  /*** Logging Site ***/,
D_POPU  /*** Lookout ***/,
D_VEGE  /*** Marsh ***/,
D_POPU  /*** Memorial Monument ***/,
D_DEST  /*** Military Installation ***/,
D_UTAN  /*** Mine Shaft Superstructure ***/,
D_DEST  /*** Minefield ***/,
D_UTAN  /*** Mineral Pile ***/,
D_DEST  /*** Missile Site ***/,
D_DEST  /*** Moat ***/,
D_POPU  /*** Mobile Home Park ***/,
D_AERO  /*** Mooring Mast ***/,
D_PHYS  /*** Moraine ***/,
D_GRTR  /*** Motor Vehicle Station ***/,
D_PHYS  /*** Mountain Pass ***/,
D_DEST  /*** Munition Storage Facility ***/,
D_GENE  /*** Named Location ***/,
D_INWA  /*** Natural Pool ***/,
D_POPU  /*** Non-building Structure ***/,
D_BOUN  /*** Non-spatial Metadata Entity Collection ***/,
D_UTAN  /*** Non-water Well ***/,
D_UTAN  /*** Nuclear Reactor Containment ***/,
D_VEGE  /*** Oasis ***/,
D_UTAN  /*** Office Park ***/,
D_POAN  /*** Offshore Construction ***/,
D_VEGE  /*** Orchard ***/,
D_POPU  /*** Outdoor Theatre Screen ***/,
D_POPU  /*** Overhead Obstruction ***/,
D_POPU  /*** Park ***/,
D_GRTR  /*** Parking Garage ***/,
D_UTAN  /*** Particle Accelerator ***/,
D_INWA  /*** Penstock ***/,
D_POPU  /*** Picnic Site ***/,
D_UTAN  /*** Pipeline ***/,
D_UTAN  /*** Pipeline Crossing Point ***/,
D_VEGE  /*** Plant Nursery ***/,
D_PHYS  /*** Polar Ice ***/,
D_POAN  /*** Port ***/,
D_UTAN  /*** Power Substation ***/,
D_GRTR  /*** Prepared Watercourse Crossing ***/,
D_POPU  /*** Public Square ***/,
D_UTAN  /*** Pumping Station ***/,
D_UTAN  /*** Pylon ***/,
D_INWA  /*** Qanat Shaft ***/,
D_POPU  /*** Racetrack ***/,
D_UTAN  /*** Radar Station ***/,
D_GRTR  /*** Railway ***/,
D_GRTR  /*** Railway Sidetrack ***/,
D_GRTR  /*** Railway Signal ***/,
D_GRTR  /*** Railway Turntable ***/,
D_GRTR  /*** Railway Yard ***/,
D_GRTR  /*** Ramp ***/,
D_INWA  /*** Rapids ***/,
D_UTAN  /*** Recycling Site ***/,
D_UTAN  /*** Retail Stand ***/,
D_VEGE  /*** Rice Field ***/,
D_UTAN  /*** Rig ***/,
D_INWA  /*** River ***/,
D_GRTR  /*** Road ***/,
D_GRTR  /*** Road Interchange ***/,
D_GRTR  /*** Roadside Rest Area ***/,
D_PHYS  /*** Rock Formation ***/,
D_GRTR  /*** Roundhouse ***/,
D_POPU  /*** Ruins ***/,
D_AERO  /*** Runway ***/,
D_PHYS  /*** Sabkha ***/,
D_UTAN  /*** Salt Evaporator ***/,
D_UTAN  /*** Salt Flat ***/,
D_PHYS  /*** Sand Dunes ***/,
D_POPU  /*** Scoreboard ***/,
D_AERO  /*** Seaplane Run ***/,
D_POPU  /*** Settlement ***/,
D_UTAN  /*** Settling Pond ***/,
D_UTAN  /*** Sewage Treatment Plant ***/,
D_POPU  /*** Shanty Town ***/,
D_GRTR  /*** Sharp Curve ***/,
D_UTAN  /*** Shear Wall ***/,
D_POPU  /*** Shed ***/,
D_POAN  /*** Ship Elevator ***/,
D_UTAN  /*** Shipping Container ***/,
D_POAN  /*** Shipyard ***/,
D_POPU  /*** Shopping Complex ***/,
D_POAN  /*** Shoreline Construction ***/,
D_POAN  /*** Shoreline Ramp ***/,
D_GRTR  /*** Sidewalk ***/,
D_POPU  /*** Ski-jump ***/,
D_POPU  /*** Ski-run ***/,
D_INWA  /*** Sluice Gate ***/,
D_POAN  /*** Small Craft Facility ***/,
D_UTAN  /*** Smokestack ***/,
D_OCEN  /*** Snag ***/,
D_PHYS  /*** Snow Field and/or Ice-field ***/,
D_SUMA  /*** Soil Surface Region ***/,
D_UTAN  /*** Solar Farm ***/,
D_UTAN  /*** Solar Panel ***/,
D_UTAN  /*** Space Facility ***/,
D_BOUN  /*** Spatial Metadata Entity Collection ***/,
D_INWA  /*** Spillway ***/,
D_POPU  /*** Sports Ground ***/,
D_GENE  /*** Spot Elevation ***/,
D_UTAN  /*** Stable ***/,
D_POPU  /*** Stadium ***/,
D_GRTR  /*** Stair ***/,
D_GRTR  /*** Steep Grade ***/,
D_PHYS  /*** Steep Terrain Face ***/,
D_AERO  /*** Stopway ***/,
D_UTAN  /*** Storage Depot ***/,
D_UTAN  /*** Storage Tank ***/,
D_UTAN  /*** Storm Drain ***/,
D_GRTR  /*** Street Lamp ***/,
D_UTAN  /*** Street Sign ***/,
D_POAN  /*** Structural Pile ***/,
D_UTAN  /*** Surface Bunker ***/,
D_VEGE  /*** Swamp ***/,
D_POPU  /*** Swimming Pool ***/,
D_UTAN  /*** Tank Farm ***/,
D_AERO  /*** Taxiway ***/,
D_BOUN  /*** Test Site ***/,
D_UTAN  /*** Tethered Balloon ***/,
D_VEGE  /*** Thicket ***/,
D_OCEN  /*** Tidal Water ***/,
D_POPU  /*** Tomb ***/,
D_UTAN  /*** Tower ***/,
D_OCEN  /*** Traffic Light ***/,
D_GRTR  /*** Trail ***/,
D_DEST  /*** Training Site ***/,
D_GRTR  /*** Transportation Block ***/,
D_GRTR  /*** Transportation Route Characteristic Change ***/,
D_GRTR  /*** Transportation Route Protection Structure ***/,
D_GRTR  /*** Transportation Station ***/,
D_VEGE  /*** Tree ***/,
D_VEGE  /*** Tundra ***/,
D_GRTR  /*** Tunnel ***/,
D_GRTR  /*** Tunnel Mouth ***/,
D_DEST  /*** Underground Bunker ***/,
D_POPU  /*** Underground Dwelling ***/,
D_UTAN  /*** Utility Cover ***/,
D_INWA  /*** Vanishing Point ***/,
D_DEST  /*** Vehicle Barrier ***/,
D_GRTR  /*** Vehicle Lot ***/,
D_POAN  /*** Vessel Lift ***/,
D_VEGE  /*** Vineyard ***/,
D_GENE  /*** Void Collection Area ***/,
D_PHYS  /*** Volcanic Dyke ***/,
D_PHYS  /*** Volcano ***/,
D_POPU  /*** Wall ***/,
D_AERO  /*** Water Aerodrome ***/,
D_INWA  /*** Water Intake Tower ***/,
D_UTAN  /*** Water Mill ***/,
D_INWA  /*** Water Race ***/,
D_UTAN  /*** Water Tower ***/,
D_UTAN  /*** Water Treatment Bed ***/,
D_UTAN  /*** Water Well ***/,
D_INWA  /*** Waterfall ***/,
D_UTAN  /*** Waterwork ***/,
D_GRTR  /*** Weigh Station ***/,
D_UTAN  /*** Wind Farm ***/,
D_UTAN  /*** Wind Turbine ***/,
D_UTAN  /*** Windmill ***/,
D_POPU  /*** Zoo ***/
};

int TDS4DOMAINSLEN = sizeof(TDS4DOMAINS)/ sizeof(unsigned char);

unsigned char TDS4STRATS[]={
0  /*** Dummy Value ***/,
S_APPL  /*** Aeration Basin ***/,
S_APPL  /*** Aerial ***/,
S_APPL  /*** Aerial Farm ***/,
S_APPL  /*** Aircraft Hangar ***/,
S_APPL  /*** Aircraft Revetment ***/,
S_APPL  /*** Amphitheatre ***/,
S_APPL  /*** Amusement Park ***/,
S_APPL  /*** Amusement Park Attraction ***/,
S_APPL  /*** Annotated Location ***/,
S_APPL  /*** Apron ***/,
S_APPL  /*** Aqueduct ***/,
S_APPL  /*** Aquifer ***/,
S_APPL  /*** Arcade ***/,
S_APPL  /*** Archeological Site ***/,
S_APPL  /*** Asphalt Lake ***/,
S_APPL  /*** Astronomical Observatory ***/,
S_APPL  /*** Barn ***/,
S_APPL  /*** Basin Gate ***/,
S_APPL  /*** Billboard ***/,
S_APPL  /*** Blast-furnace ***/,
S_APPL  /*** Bog ***/,
S_APPL  /*** Borehole ***/,
S_APPL  /*** Botanic Garden ***/,
S_APPL  /*** Boundary Monument ***/,
S_APPL  /*** Bridge ***/,
S_APPL  /*** Bridge Pier ***/,
S_APPL  /*** Bridge Span ***/,
S_APPL  /*** Bridge Superstructure ***/,
S_APPL  /*** Bridge Tower ***/,
S_APPL  /*** Brush ***/,
S_APPL  /*** Bucket Elevator ***/,
S_APPL  /*** Building ***/,
S_APPL  /*** Building Superstructure ***/,
S_APPL  /*** Built-up Area ***/,
S_APPL  /*** Cable ***/,
S_APPL  /*** Cableway ***/,
S_APPL  /*** Cairn ***/,
S_APPL  /*** Camp ***/,
S_APPL  /*** Camp-site ***/,
S_APPL  /*** Canal ***/,
S_APPL  /*** Cane ***/,
S_APPL  /*** Cantonment Area ***/,
S_APPL  /*** Caravan Park ***/,
S_APPL  /*** Cart Track ***/,
S_APPL  /*** Castle ***/,
S_APPL  /*** Castle Complex ***/,
S_APPL  /*** Catalytic Cracker ***/,
S_APPL  /*** Causeway Structure ***/,
S_APPL  /*** Cave Mouth ***/,
S_APPL  /*** Cemetery ***/,
S_APPL  /*** Checkpoint ***/,
S_APPL  /*** Cistern ***/,
S_APPL  /*** Cleared Way ***/,
S_APPL  /*** Conservation Area ***/,
S_APPL  /*** Contaminated Region ***/,
S_APPL  /*** Control Point ***/,
S_APPL  /*** Control Tower ***/,
S_APPL  /*** Conveyor ***/,
S_APPL  /*** Cooling Facility ***/,
S_APPL  /*** Cooling Tower ***/,
S_APPL  /*** Courtyard ***/,
S_APPL  /*** Crane ***/,
S_APPL  /*** Crevasse ***/,
S_APPL  /*** Crevice ***/,
S_APPL  /*** Crop Land ***/,
S_APPL  /*** Crossing ***/,
S_APPL  /*** Cultural Context Location ***/,
S_APPL  /*** Culvert ***/,
S_APPL  /*** Cut ***/,
S_APPL  /*** Cut Line ***/,
S_APPL  /*** Dam ***/,
S_APPL  /*** Dataset ***/,
S_APPL  /*** Depression ***/,
S_APPL  /*** Desert ***/,
S_APPL  /*** Dish Aerial ***/,
S_APPL  /*** Disposal Site ***/,
S_APPL  /*** Ditch ***/,
S_APPL  /*** Dragon's Teeth ***/,
S_APPL  /*** Drive-in Theatre ***/,
S_APPL  /*** Dry Dock ***/,
S_APPL  /*** Electric Power Station ***/,
S_APPL  /*** Elevation Contour ***/,
S_APPL  /*** Embankment ***/,
S_APPL  /*** Engine Test Cell ***/,
S_APPL  /*** Engineered Earthwork ***/,
S_APPL  /*** Esker ***/,
S_APPL  /*** Excavating Machine ***/,
S_APPL  /*** Extraction Mine ***/,
S_APPL  /*** Facility ***/,
S_APPL  /*** Fairground ***/,
S_APPL  /*** Fence ***/,
S_APPL  /*** Ferry Crossing ***/,
S_APPL  /*** Ferry Station ***/,
S_APPL  /*** Fire Hydrant ***/,
S_APPL  /*** Firing Range ***/,
S_APPL  /*** Fish Farm Facility ***/,
S_APPL  /*** Fish Ladder ***/,
S_APPL  /*** Fish Weir ***/,
S_APPL  /*** Flagpole ***/,
S_APPL  /*** Flare Pipe ***/,
S_APPL  /*** Floating Dry Dock ***/,
S_APPL  /*** Flood Control Structure ***/,
S_APPL  /*** Ford ***/,
S_APPL  /*** Forest ***/,
S_APPL  /*** Forest Clearing ***/,
S_APPL  /*** Fortified Building ***/,
S_APPL  /*** Fountain ***/,
S_APPL  /*** Fuel Storage Facility ***/,
S_APPL  /*** Gantry ***/,
S_APPL  /*** Gate ***/,
S_APPL  /*** Gauging Station ***/,
S_APPL  /*** Geologic Fault ***/,
S_APPL  /*** Geothermal Outlet ***/,
S_APPL  /*** Glacier ***/,
S_APPL  /*** Golf Course ***/,
S_APPL  /*** Golf Driving Range ***/,
S_APPL  /*** Grain Elevator ***/,
S_APPL  /*** Grain Storage Structure ***/,
S_APPL  /*** Grandstand ***/,
S_APPL  /*** Grassland ***/,
S_APPL  /*** Greenhouse ***/,
S_APPL  /*** Harbour ***/,
S_APPL  /*** Hardened Aircraft Shelter ***/,
S_APPL  /*** Heating Facility ***/,
S_APPL  /*** Hedgerow ***/,
S_APPL  /*** Helipad ***/,
S_APPL  /*** Heliport ***/,
S_APPL  /*** Holding Pen ***/,
S_APPL  /*** Hop Field ***/,
S_APPL  /*** Hopper ***/,
S_APPL  /*** Hulk ***/,
S_APPL  /*** Hummock ***/,
S_APPL  /*** Hut ***/,
S_APPL  /*** Hydrocarbon Products Facility ***/,
S_APPL  /*** Hydrocarbons Field ***/,
S_APPL  /*** Ice Cliff ***/,
S_APPL  /*** Ice Peak ***/,
S_APPL  /*** Ice Route ***/,
S_APPL  /*** Ice Shelf ***/,
S_APPL  /*** Ice-cap ***/,
S_APPL  /*** Industrial Farm ***/,
S_APPL  /*** Industrial Furnace ***/,
S_APPL  /*** Inland Waterbody ***/,
S_APPL  /*** Installation ***/,
S_APPL  /*** Interest Site ***/,
S_APPL  /*** International Date Line ***/,
S_APPL  /*** Island ***/,
S_APPL  /*** Land Aerodrome ***/,
S_APPL  /*** Land Subject to Inundation ***/,
S_APPL  /*** Land Water Boundary ***/,
S_APPL  /*** Landslide Mass ***/,
S_APPL  /*** Launch Pad ***/,
S_APPL  /*** Light Support Structure ***/,
S_APPL  /*** Light Vessel ***/,
S_APPL  /*** Lighthouse ***/,
S_APPL  /*** Liquid Diffuser ***/,
S_APPL  /*** Lock ***/,
S_APPL  /*** Logging Site ***/,
S_APPL  /*** Lookout ***/,
S_APPL  /*** Marsh ***/,
S_APPL  /*** Memorial Monument ***/,
S_APPL  /*** Military Installation ***/,
S_APPL  /*** Mine Shaft Superstructure ***/,
S_APPL  /*** Minefield ***/,
S_APPL  /*** Mineral Pile ***/,
S_APPL  /*** Missile Site ***/,
S_APPL  /*** Moat ***/,
S_APPL  /*** Mobile Home Park ***/,
S_APPL  /*** Mooring Mast ***/,
S_APPL  /*** Moraine ***/,
S_APPL  /*** Motor Vehicle Station ***/,
S_APPL  /*** Mountain Pass ***/,
S_APPL  /*** Munition Storage Facility ***/,
S_APPL  /*** Named Location ***/,
S_APPL  /*** Natural Pool ***/,
S_APPL  /*** Non-building Structure ***/,
S_APPL  /*** Non-spatial Metadata Entity Collection ***/,
S_APPL  /*** Non-water Well ***/,
S_APPL  /*** Nuclear Reactor Containment ***/,
S_APPL  /*** Oasis ***/,
S_APPL  /*** Office Park ***/,
S_APPL  /*** Offshore Construction ***/,
S_APPL  /*** Orchard ***/,
S_APPL  /*** Outdoor Theatre Screen ***/,
S_APPL  /*** Overhead Obstruction ***/,
S_APPL  /*** Park ***/,
S_APPL  /*** Parking Garage ***/,
S_APPL  /*** Particle Accelerator ***/,
S_APPL  /*** Penstock ***/,
S_APPL  /*** Picnic Site ***/,
S_APPL  /*** Pipeline ***/,
S_APPL  /*** Pipeline Crossing Point ***/,
S_APPL  /*** Plant Nursery ***/,
S_APPL  /*** Polar Ice ***/,
S_APPL  /*** Port ***/,
S_APPL  /*** Power Substation ***/,
S_APPL  /*** Prepared Watercourse Crossing ***/,
S_APPL  /*** Public Square ***/,
S_APPL  /*** Pumping Station ***/,
S_APPL  /*** Pylon ***/,
S_APPL  /*** Qanat Shaft ***/,
S_APPL  /*** Racetrack ***/,
S_APPL  /*** Radar Station ***/,
S_APPL  /*** Railway ***/,
S_APPL  /*** Railway Sidetrack ***/,
S_APPL  /*** Railway Signal ***/,
S_APPL  /*** Railway Turntable ***/,
S_APPL  /*** Railway Yard ***/,
S_APPL  /*** Ramp ***/,
S_APPL  /*** Rapids ***/,
S_APPL  /*** Recycling Site ***/,
S_APPL  /*** Retail Stand ***/,
S_APPL  /*** Rice Field ***/,
S_APPL  /*** Rig ***/,
S_APPL  /*** River ***/,
S_APPL  /*** Road ***/,
S_APPL  /*** Road Interchange ***/,
S_APPL  /*** Roadside Rest Area ***/,
S_APPL  /*** Rock Formation ***/,
S_APPL  /*** Roundhouse ***/,
S_APPL  /*** Ruins ***/,
S_APPL  /*** Runway ***/,
S_APPL  /*** Sabkha ***/,
S_APPL  /*** Salt Evaporator ***/,
S_APPL  /*** Salt Flat ***/,
S_APPL  /*** Sand Dunes ***/,
S_APPL  /*** Scoreboard ***/,
S_APPL  /*** Seaplane Run ***/,
S_APPL  /*** Settlement ***/,
S_APPL  /*** Settling Pond ***/,
S_APPL  /*** Sewage Treatment Plant ***/,
S_APPL  /*** Shanty Town ***/,
S_APPL  /*** Sharp Curve ***/,
S_APPL  /*** Shear Wall ***/,
S_APPL  /*** Shed ***/,
S_APPL  /*** Ship Elevator ***/,
S_APPL  /*** Shipping Container ***/,
S_APPL  /*** Shipyard ***/,
S_APPL  /*** Shopping Complex ***/,
S_APPL  /*** Shoreline Construction ***/,
S_APPL  /*** Shoreline Ramp ***/,
S_APPL  /*** Sidewalk ***/,
S_APPL  /*** Ski-jump ***/,
S_APPL  /*** Ski-run ***/,
S_APPL  /*** Sluice Gate ***/,
S_APPL  /*** Small Craft Facility ***/,
S_APPL  /*** Smokestack ***/,
S_APPL  /*** Snag ***/,
S_APPL  /*** Snow Field and/or Ice-field ***/,
S_APPL  /*** Soil Surface Region ***/,
S_APPL  /*** Solar Farm ***/,
S_APPL  /*** Solar Panel ***/,
S_APPL  /*** Space Facility ***/,
S_APPL  /*** Spatial Metadata Entity Collection ***/,
S_APPL  /*** Spillway ***/,
S_APPL  /*** Sports Ground ***/,
S_APPL  /*** Spot Elevation ***/,
S_APPL  /*** Stable ***/,
S_APPL  /*** Stadium ***/,
S_APPL  /*** Stair ***/,
S_APPL  /*** Steep Grade ***/,
S_APPL  /*** Steep Terrain Face ***/,
S_APPL  /*** Stopway ***/,
S_APPL  /*** Storage Depot ***/,
S_APPL  /*** Storage Tank ***/,
S_APPL  /*** Storm Drain ***/,
S_APPL  /*** Street Lamp ***/,
S_APPL  /*** Street Sign ***/,
S_APPL  /*** Structural Pile ***/,
S_APPL  /*** Surface Bunker ***/,
S_APPL  /*** Swamp ***/,
S_APPL  /*** Swimming Pool ***/,
S_APPL  /*** Tank Farm ***/,
S_APPL  /*** Taxiway ***/,
S_APPL  /*** Test Site ***/,
S_APPL  /*** Tethered Balloon ***/,
S_APPL  /*** Thicket ***/,
S_APPL  /*** Tidal Water ***/,
S_APPL  /*** Tomb ***/,
S_APPL  /*** Tower ***/,
S_APPL  /*** Traffic Light ***/,
S_APPL  /*** Trail ***/,
S_APPL  /*** Training Site ***/,
S_APPL  /*** Transportation Block ***/,
S_APPL  /*** Transportation Route Characteristic Change ***/,
S_APPL  /*** Transportation Route Protection Structure ***/,
S_APPL  /*** Transportation Station ***/,
S_APPL  /*** Tree ***/,
S_APPL  /*** Tundra ***/,
S_APPL  /*** Tunnel ***/,
S_APPL  /*** Tunnel Mouth ***/,
S_APPL  /*** Underground Bunker ***/,
S_APPL  /*** Underground Dwelling ***/,
S_APPL  /*** Utility Cover ***/,
S_APPL  /*** Vanishing Point ***/,
S_APPL  /*** Vehicle Barrier ***/,
S_APPL  /*** Vehicle Lot ***/,
S_APPL  /*** Vessel Lift ***/,
S_APPL  /*** Vineyard ***/,
S_APPL  /*** Void Collection Area ***/,
S_APPL  /*** Volcanic Dyke ***/,
S_APPL  /*** Volcano ***/,
S_APPL  /*** Wall ***/,
S_APPL  /*** Water Aerodrome ***/,
S_APPL  /*** Water Intake Tower ***/,
S_APPL  /*** Water Mill ***/,
S_APPL  /*** Water Race ***/,
S_APPL  /*** Water Tower ***/,
S_APPL  /*** Water Treatment Bed ***/,
S_APPL  /*** Water Well ***/,
S_APPL  /*** Waterfall ***/,
S_APPL  /*** Waterwork ***/,
S_APPL  /*** Weigh Station ***/,
S_APPL  /*** Wind Farm ***/,
S_APPL  /*** Wind Turbine ***/,
S_APPL  /*** Windmill ***/,
S_APPL  /*** Zoo ***/
};

int TDS4STRATSLEN = sizeof(TDS4STRATS)/ sizeof(unsigned char);


