/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
int TDS4_ATTR_NUM=460;

char *TDS4_attr_codes[] = {
"AHA",
"AVA",
"UTY",
"UTY2",
"UTY3",
"ADR",
"ADI",
"ZVA",
"ASU",
"ASU2",
"ASU3",
"NA8",
"ZI019_ASX",
"ZI019_ASU",
"ZI019_ASU2",
"ZI019_ASU3",
"ZI019_ASP",
"ZI019_ASP2",
"ZI019_ASP3",
"ZI019_SFS",
"AXS",
"AWP",
"ASY",
"FPT",
"AMA",
"AOO",
"APY",
"ATC",
"AQP",
"DPAC",
"DPAL",
"DPAU",
"AQN",
"AQO",
"AQO2",
"AQO3",
"AQTC",
"AQTL",
"AQTU",
"AYRC",
"AYRL",
"AYRU",
"ARA",
"ATB",
"BAT",
"BEL",
"BGT",
"BOC",
"BMC",
"BMC2",
"BMC3",
"RSA",
"BOT",
"BRN",
"BSC",
"BSC2",
"BSC3",
"BSU",
"BAC",
"PBY",
"PBY2",
"PBY3",
"BCC",
"AT005_CAB",
"AT005_CAB2",
"AT005_CAB3",
"TST",
"CAB",
"CAB2",
"CAB3",
"CAT",
"DMT",
"ZI071_CTX",
"ZI071_FFN",
"ZI071_FFN2",
"ZI071_FFN3",
"ZI071_UAO",
"CID",
"CPS",
"MWG",
"CAM",
"CST",
"CWT",
"CBP",
"CSO",
"CNS",
"CAA",
"CCT",
"CDA",
"CRM",
"CRA",
"ZI013_CSP",
"ZI013_CSP2",
"ZI013_CSP3",
"ZI013_FMM",
"ZI013_FMM2",
"ZI013_FMM3",
"ZI013_FFP",
"ZI013_FFP2",
"ZI013_FFP3",
"ZI013_IRG",
"TCS",
"CUL",
"CTC",
"CTL",
"RAD",
"DWT",
"DMD",
"DQS",
"DZC",
"DEV",
"DZP",
"DIM",
"DOF",
"SEP",
"ESC",
"EVA",
"FIC",
"ETY",
"EET",
"EQC",
"MZN",
"ETS",
"ETZ",
"COS",
"FCO",
"FFN",
"FFN2",
"FFN3",
"FTI",
"FCL",
"FER",
"FSC",
"FLO",
"FCS",
"BNF",
"TRE",
"FZR",
"SIC",
"GTC",
"HZD",
"ZI005_FNA1",
"ZI005_NFN1",
"ZI005_FNA2",
"ZI005_NFN2",
"ZI005_FNA",
"ZI005_NFN",
"GFT",
"GOT",
"LOG",
"CET",
"GUG",
"HTP",
"FHC",
"FHC2",
"FHC3",
"HST",
"HST2",
"HST3",
"HGT",
"HVA",
"HEI",
"HAF",
"ZVH",
"HSS",
"HHD",
"HCA",
"ZI025_WLE",
"HYP",
"HQC",
"IKO",
"IC2",
"IWT",
"BH141_AWBA",
"BH141_IBOA",
"BPWHAC",
"BPWHAL",
"BPWHAU",
"BPWSAC",
"BPWSAL",
"BPWSAU",
"BH141_SHDA",
"BH141_SLTA",
"BH141_WBHA",
"BWVCAC",
"BWVCAL",
"BWVCAU",
"BH141_AWBB",
"BH141_IBOB",
"BPWHBC",
"BPWHBL",
"BPWHBU",
"BPWSBC",
"BPWSBL",
"BPWSBU",
"BH141_SHDB",
"BH141_SLTB",
"BH141_WBHB",
"BWVCBC",
"BWVCBL",
"BWVCBU",
"CSC",
"CSC2",
"CSC3",
"LND",
"LEA",
"LZN",
"LCA",
"RTA",
"LC1",
"LC2",
"LC3",
"LC4",
"LUN",
"SRL",
"MDE",
"AZC",
"MNS",
"MFB",
"ZI014_PBY",
"ZI014_PBY2",
"ZI014_PBY3",
"ZI014_PPO",
"ZI014_PPO2",
"ZI014_PPO3",
"ZI014_PRW",
"ZI014_PRW2",
"ZI014_PRW3",
"MES",
"MEM",
"CCG",
"YSU",
"MST",
"MST2",
"MST3",
"MCX",
"MUB",
"NLT",
"SWT",
"NVS",
"LMC",
"STL",
"STL2",
"STL3",
"ZI006_MEM",
"OCS",
"ONE",
"OPT",
"OHC",
"OOC",
"NPL",
"TRA",
"PCF",
"PEC",
"KVA",
"POS",
"POS2",
"POS3",
"WVA",
"PFD",
"PFH",
"WDH",
"WVH",
"WDL",
"WVL",
"PVH",
"PWA",
"ZI004_PRE",
"ZI004_RCG",
"PPO",
"PPO2",
"PPO3",
"PYC",
"ZI032_GUG",
"ZI032_PYC",
"ZI032_PYM",
"ZI032_TOS",
"PYM",
"RAC",
"RAS",
"RWC",
"RRC",
"RRC2",
"RRC3",
"PRW",
"PRW2",
"PRW3",
"RLE",
"ZI037_REL",
"ZI037_RFA",
"RCG",
"ZI002_CCN",
"ZI002_CDR",
"ZSAX_RS0",
"ZSAX_RX3",
"ZSAX_RX4",
"RIP",
"RIT",
"RKF",
"SSR",
"SSR2",
"SSR3",
"RFD",
"RTN",
"RTN_ROI",
"RTN2",
"RTN_ROI2",
"RTN3",
"RTN_ROI3",
"RMWC",
"RMWL",
"RMWU",
"WD1",
"ZI016_WTC",
"ZI016_WD1",
"ZI016_ROC",
"WD2",
"CON",
"EXP",
"GB052_RIDH",
"GSGCHC",
"GSGCHL",
"GSGCHU",
"GB052_RIDL",
"GSGCLC",
"GSGCLL",
"GSGCLU",
"SHC",
"SDO",
"SAD",
"SDT",
"SSE",
"SBC",
"SHT",
"PWC",
"SHD",
"SLR",
"SLT",
"SDCC",
"SDCL",
"SDCU",
"STP",
"SWC",
"FAC",
"ZI001_NSD",
"ZI001_NSN",
"ZI001_NSP",
"ZI001_SSD",
"ZI001_SSN",
"ZI001_SSY",
"ZI001_VSC",
"ZI001_VSD",
"ZI001_VSN",
"NOS",
"OTH",
"SWW",
"SDSC",
"SDSL",
"SDSU",
"SSG",
"MCC",
"MCC2",
"MCC3",
"SSC",
"SBT",
"SBT2",
"SBT3",
"SPT",
"SBB",
"SGCC",
"SGCL",
"SGCU",
"CPA",
"TXP",
"TEL",
"WD3",
"SRD",
"TSM",
"TSM2",
"TSM3",
"THI",
"TYP",
"THR",
"TID",
"TTY",
"TOS",
"TTC",
"TTC2",
"TTC3",
"ZI017_GAW",
"ZI017_RGC",
"ZI017_RRA",
"ZI017_RIR",
"ZI017_TRT",
"LTN",
"SRE",
"DGC",
"TRP",
"TRS",
"TRS2",
"TRS3",
"TSCC",
"TSCL",
"TSCU",
"UBC",
"UMA",
"DMBC",
"DMBL",
"DMBU",
"UFI",
"URI",
"LNU",
"WDU",
"VEG",
"VSP",
"VSP2",
"VSP3",
"VST",
"VET",
"VCM",
"VCM2",
"VCM3",
"VDT",
"VOI",
"LOC",
"VCA",
"VCA2",
"VCA3",
"VCT",
"VCT2",
"VCT3",
"VOA",
"VGT",
"VLM",
"WTI",
"WLE",
"BA000_VDC",
"BA000_VDR",
"YWQ",
"WRT",
"ZI024_HYP",
"ZI024_YWQ",
"ZI024_SCC",
"WAD",
"OWO",
"WCC",
"WMT",
"WST",
"FRT",
"FRT2",
"FRT3",
"WEQ",
"WEQ2",
"WEQ3",
"WFT",
"WID",
"WD5",
"WT2",
"ZI018_WIT",
"WPI"
};

char *TDS4_attr_names[] = {
"Absolute Horizontal Accuracy (90%)",
"Absolute Vertical Accuracy (90%)",
"Accessible Utility Type",
"Accessible Utility Type [2]",
"Accessible Utility Type [3]",
"Address",
"Administrative Division",
"Aerodrome Elevation",
"Aerodrome Movement Area Surface Composition",
"Aerodrome Movement Area Surface Composition [2]",
"Aerodrome Movement Area Surface Composition [3]",
"Aerodrome Official Name",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Category",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Composition",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Composition [2]",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Composition [3]",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Preparation Method",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Preparation Method [2]",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Preparation Method [3]",
"Aerodrome Pavement Information : Aerodrome Pavement Functional Status",
"Aerodrome Surface Status",
"Aeronautical Obstacle Light Present",
"Airfield Symbol Type",
"Airfield Type",
"Amusement Attraction Type",
"Angle of Orientation",
"Apron Type",
"Aqueduct Type",
"Aquifer Composition",
"Aquifer Depth (interval closure)",
"Aquifer Depth (lower value)",
"Aquifer Depth (upper value)",
"Aquifer Name",
"Aquifer Overburden",
"Aquifer Overburden [2]",
"Aquifer Overburden [3]",
"Aquifer Thickness (interval closure)",
"Aquifer Thickness (lower value)",
"Aquifer Thickness (upper value)",
"Aquifer Yield Rating (interval closure)",
"Aquifer Yield Rating (lower value)",
"Aquifer Yield Rating (upper value)",
"Area",
"Attached Building",
"Barrier Top Type",
"Base Elevation",
"Basin Gate Type",
"Bog Type",
"Bottom Material Type",
"Bottom Material Type [2]",
"Bottom Material Type [3]",
"Branch Railway Type",
"Bridge Opening Type",
"Bridge Reference Number",
"Bridge Structure Type",
"Bridge Structure Type [2]",
"Bridge Structure Type [3]",
"Building Superstructure Type",
"Built-up Area Density Category",
"By-product",
"By-product [2]",
"By-product [3]",
"Bypass Condition",
"Cable : Cable Type",
"Cable : Cable Type [2]",
"Cable : Cable Type [3]",
"Cable Suspended Shape",
"Cable Type",
"Cable Type [2]",
"Cable Type [3]",
"Cableway Type",
"Canopy Cover",
"Cave Information : Cave Type",
"Cave Information : Feature Function",
"Cave Information : Feature Function [2]",
"Cave Information : Feature Function [3]",
"Cave Information : Underground Access Orientation",
"Cell Identifier",
"Cell Partition Scheme",
"Centerline Spacing",
"Conservation Area Management Category",
"Contained within Service Tunnel",
"Contained within Tunnel",
"Containment Berm Present",
"Contaminant Source",
"Controlled",
"Controlling Authority",
"Cover Closure Type",
"Covered Drain",
"Crane Mobility Type",
"Crane Type",
"Crop Information : Crop Species",
"Crop Information : Crop Species [2]",
"Crop Information : Crop Species [3]",
"Crop Information : Farming Method",
"Crop Information : Farming Method [2]",
"Crop Information : Farming Method [3]",
"Crop Information : Farming Pattern",
"Crop Information : Farming Pattern [2]",
"Crop Information : Farming Pattern [3]",
"Crop Information : Irrigation Method",
"Cross-sectional Profile",
"Cultural Context Type",
"Culvert Type",
"Cumulative Track Length",
"Curve Radius",
"Dam Type",
"Dammed",
"Data Quality Statement",
"Deck Count",
"Deck Level",
"Deepest Depth Below Surface Level",
"Diameter",
"Direction of Flow",
"Divided",
"Elevation Surface Category",
"Elevation Vertical Accuracy (90%)",
"Embankment Type",
"Engine Test Cell Type",
"Engineered Earthwork Type",
"Equivalent Scale Category",
"Extraction Mine Type",
"Extraction Specification",
"Extraction Specification Version",
"Facility Operational Status",
"Feature Configuration",
"Feature Function",
"Feature Function [2]",
"Feature Function [3]",
"Fence Type",
"Ferry Crossing Distance",
"Ferry Crossing Type",
"Flight Strip Capable",
"Floating",
"Flood Control Structure Type",
"Floor Count",
"Foliage Type",
"Fortified Building Type",
"Frozen Cover Type",
"Gate Use",
"Geodetic Datum",
"Geographic Name Information : (first) Full Name",
"Geographic Name Information : (first) Name Identifier",
"Geographic Name Information : (second) Full Name",
"Geographic Name Information : (second) Name Identifier",
"Geographic Name Information : Full Name",
"Geographic Name Information : Name Identifier",
"Geologic Fault Trace Visible",
"Geothermal Outlet Type",
"Gradient Length",
"Grading Type",
"Guyed",
"Hangar Type Category",
"Harbour Facility Function",
"Harbour Facility Function [2]",
"Harbour Facility Function [3]",
"Hazard Shelter Intended Use",
"Hazard Shelter Intended Use [2]",
"Hazard Shelter Intended Use [3]",
"Height Above Surface Level",
"Height Vertical Accuracy (90%)",
"Height of Object",
"Helipad Associated Facility",
"Highest Elevation",
"Historic Significance",
"Homogenous Habitation Distribution",
"Horizontal Clearance",
"Hydrographic Vertical Positioning Information : Water Level Effect",
"Hydrologic Persistence",
"Hypsography Portrayal Type",
"ICAO Location Indicator",
"ISO 3166-1 Country Code (alpha3)",
"Inland Water Type",
"Inland Waterbody Bank (1) : Above Water Bank Slope (first bank)",
"Inland Waterbody Bank (1) : Bank Orientation (first bank)",
"Inland Waterbody Bank (1) : Predominant Waterbody Bank Height (first bank) (interval closure)",
"Inland Waterbody Bank (1) : Predominant Waterbody Bank Height (first bank) (lower value)",
"Inland Waterbody Bank (1) : Predominant Waterbody Bank Height (first bank) (upper value)",
"Inland Waterbody Bank (1) : Predominant Waterbody Bank Slope (first bank) (interval closure)",
"Inland Waterbody Bank (1) : Predominant Waterbody Bank Slope (first bank) (lower value)",
"Inland Waterbody Bank (1) : Predominant Waterbody Bank Slope (first bank) (upper value)",
"Inland Waterbody Bank (1) : Shoreline Delineated (first bank)",
"Inland Waterbody Bank (1) : Shoreline Type (first bank)",
"Inland Waterbody Bank (1) : Waterbody Bank Height (first bank)",
"Inland Waterbody Bank (1) : Waterbody Bank Vegetation Cover (first bank) (interval closure)",
"Inland Waterbody Bank (1) : Waterbody Bank Vegetation Cover (first bank) (lower value)",
"Inland Waterbody Bank (1) : Waterbody Bank Vegetation Cover (first bank) (upper value)",
"Inland Waterbody Bank (2) : Above Water Bank Slope (second bank)",
"Inland Waterbody Bank (2) : Bank Orientation (second bank)",
"Inland Waterbody Bank (2) : Predominant Waterbody Bank Height (second bank) (interval closure)",
"Inland Waterbody Bank (2) : Predominant Waterbody Bank Height (second bank) (lower value)",
"Inland Waterbody Bank (2) : Predominant Waterbody Bank Height (second bank) (upper value)",
"Inland Waterbody Bank (2) : Predominant Waterbody Bank Slope (second bank) (interval closure)",
"Inland Waterbody Bank (2) : Predominant Waterbody Bank Slope (second bank) (lower value)",
"Inland Waterbody Bank (2) : Predominant Waterbody Bank Slope (second bank) (upper value)",
"Inland Waterbody Bank (2) : Shoreline Delineated (second bank)",
"Inland Waterbody Bank (2) : Shoreline Type (second bank)",
"Inland Waterbody Bank (2) : Waterbody Bank Height (second bank)",
"Inland Waterbody Bank (2) : Waterbody Bank Vegetation Cover (second bank) (interval closure)",
"Inland Waterbody Bank (2) : Waterbody Bank Vegetation Cover (second bank) (lower value)",
"Inland Waterbody Bank (2) : Waterbody Bank Vegetation Cover (second bank) (upper value)",
"Intersection Control Type",
"Intersection Control Type [2]",
"Intersection Control Type [3]",
"Land Morphology",
"Least Depth Below Surface Level",
"Length",
"Lifting Capacity",
"Linear Feature Arrangement",
"Load Class Type 1",
"Load Class Type 2",
"Load Class Type 3",
"Load Class Type 4",
"Located Underground",
"Location Referenced to Shoreline",
"Maintenance Date and Time",
"Man-made",
"Man-made Shoreline",
"Manufactured Building",
"Manufacturing Information : By-product",
"Manufacturing Information : By-product [2]",
"Manufacturing Information : By-product [3]",
"Manufacturing Information : Product",
"Manufacturing Information : Product [2]",
"Manufacturing Information : Product [3]",
"Manufacturing Information : Raw Material",
"Manufacturing Information : Raw Material [2]",
"Manufacturing Information : Raw Material [3]",
"Median Present",
"Memorandum",
"Military Environmental Hazard Category",
"Military Service Branch",
"Missile Site Type",
"Missile Site Type [2]",
"Missile Site Type [3]",
"Motorized Crossing",
"Multi-unit Building",
"Named Location Type",
"Natural Pool Type",
"Navigability Information",
"Navigation Landmark",
"Nomadic Seasonal Location",
"Nomadic Seasonal Location [2]",
"Nomadic Seasonal Location [3]",
"Note : Memorandum",
"Offshore Construction Primary Structure",
"One-way",
"Operating Cycle",
"Overhead Clearance",
"Overhead Obstruction Type",
"Parallel Line Count",
"Pedestrian Traversable",
"Physical Condition",
"Port of Entry",
"Power Line Maximum Voltage",
"Power Source",
"Power Source [2]",
"Power Source [3]",
"Predominant Average Water Velocity",
"Predominant Feature Depth",
"Predominant Feature Height",
"Predominant Maximum Water Depth",
"Predominant Maximum Water Velocity",
"Predominant Minimum Water Depth",
"Predominant Minimum Water Velocity",
"Predominant Vegetation Height",
"Predominant Water Depth",
"Process Step Information : Process Step Description",
"Process Step Information : Resource Content Originator",
"Product",
"Product [2]",
"Product [3]",
"Pylon Configuration",
"Pylon Information : Guyed",
"Pylon Information : Pylon Configuration",
"Pylon Information : Pylon Material",
"Pylon Information : Tower Shape",
"Pylon Material",
"Radar Antenna Configuration",
"Radar Station Function",
"Railway Class",
"Railway Use",
"Railway Use [2]",
"Railway Use [3]",
"Raw Material",
"Raw Material [2]",
"Raw Material [3]",
"Relative Level",
"Religious Information : Religious Designation",
"Religious Information : Religious Facility Type",
"Resource Content Originator",
"Restriction Information : Commercial Copyright Notice",
"Restriction Information : Commercial Distribution Restriction",
"Restriction Information : Security Attributes Group (resource classification)",
"Restriction Information : Security Attributes Group (resource non-intelligence community markings)",
"Restriction Information : Security Attributes Group (resource owner-producer)",
"Rig Present",
"Road Interchange Type",
"Rock Formation Structure",
"Roof Shape",
"Roof Shape [2]",
"Roof Shape [3]",
"Roofed",
"Route Designation",
"Route Designation (route designation type)",
"Route Designation [2]",
"Route Designation [2] (route designation type)",
"Route Designation [3]",
"Route Designation [3] (route designation type)",
"Route Median Width (interval closure)",
"Route Median Width (lower value)",
"Route Median Width (upper value)",
"Route Minimum Travelled Way Width",
"Route Pavement Information : Road Weather Restriction",
"Route Pavement Information : Route Minimum Travelled Way Width",
"Route Pavement Information : Route Surface Composition",
"Route Total Usable Width",
"Route Width Constriction Type",
"Route Width Expansion Type",
"Runway Direction (high end) : Runway Designator (high)",
"Runway Direction (high end) : Surface Slope (high) (interval closure)",
"Runway Direction (high end) : Surface Slope (high) (lower value)",
"Runway Direction (high end) : Surface Slope (high) (upper value)",
"Runway Direction (low end) : Runway Designator (low)",
"Runway Direction (low end) : Surface Slope (low) (interval closure)",
"Runway Direction (low end) : Surface Slope (low) (lower value)",
"Runway Direction (low end) : Surface Slope (low) (upper value)",
"Safe Horizontal Clearance",
"Sand Dune Orientation",
"Sand Dune Stabilized",
"Sand Dune Type",
"Seasonal Ice Limit",
"Shelter Belt",
"Shipping Container Type",
"Shoreline Construction Type",
"Shoreline Delineated",
"Shoreline Ramp Type",
"Shoreline Type",
"Soil Depth (interval closure)",
"Soil Depth (lower value)",
"Soil Depth (upper value)",
"Soil Type",
"Soil Wetness Condition",
"Solid Maritime Construction",
"Source Information : Non-spatial Source Date and Time",
"Source Information : Non-spatial Source Description",
"Source Information : Non-spatial Source Type",
"Source Information : Spatial Source Date and Time",
"Source Information : Spatial Source Description",
"Source Information : Spatial Source Type",
"Source Information : Vertical Source Category",
"Source Information : Vertical Source Date and Time",
"Source Information : Vertical Source Description",
"Span Count",
"Specified Domain Values(s)",
"Static Water Level",
"Stem Diameter (interval closure)",
"Stem Diameter (lower value)",
"Stem Diameter (upper value)",
"Street Sign Type",
"Structural Material Type",
"Structural Material Type [2]",
"Structural Material Type [3]",
"Structure Shape",
"Substation Type",
"Substation Type [2]",
"Substation Type [3]",
"Supported",
"Supported by Bridge Span",
"Surface Slope (interval closure)",
"Surface Slope (lower value)",
"Surface Slope (upper value)",
"Survey Control Point Type",
"Taxiway Type",
"Telescope Type",
"Terrain Gap Width",
"Terrain Morphology",
"Terrain Surface Material",
"Terrain Surface Material [2]",
"Terrain Surface Material [3]",
"Thickness",
"Thoroughfare Type",
"Through Route",
"Tide Influenced",
"Tomb Type",
"Tower Shape",
"Tower Type",
"Tower Type [2]",
"Tower Type [3]",
"Track Information : Railway Gauge",
"Track Information : Railway Gauge Classification",
"Track Information : Railway Power Method",
"Track Information : Railway in Road",
"Track Information : Track Type",
"Track or Lane Count",
"Traffic Restriction Type",
"Transportation Block Type",
"Transportation Route Protection Structure Type",
"Transportation System Type",
"Transportation System Type [2]",
"Transportation System Type [3]",
"Tree Spacing (interval closure)",
"Tree Spacing (lower value)",
"Tree Spacing (upper value)",
"Underbridge Clearance",
"Underground Mine Access",
"Undergrowth Density (interval closure)",
"Undergrowth Density (lower value)",
"Undergrowth Density (upper value)",
"Unique Entity Identifier",
"Unique Resource Identifier",
"Usable Length",
"Usable Width",
"Vegetation Characteristic",
"Vegetation Species",
"Vegetation Species [2]",
"Vegetation Species [3]",
"Vehicle Scale Count",
"Vehicle Type",
"Vertical Construction Material",
"Vertical Construction Material [2]",
"Vertical Construction Material [3]",
"Vertical Datum",
"Vertical Obstruction Identifier",
"Vertical Relative Location",
"Void Collection Reason",
"Void Collection Reason [2]",
"Void Collection Reason [3]",
"Void Collection Type",
"Void Collection Type [2]",
"Void Collection Type [3]",
"Volcanic Activity",
"Volcano Shape",
"Volume",
"Wall Type",
"Water Level Effect",
"Water Line : Sounding Datum",
"Water Line : Sounding Datum Name",
"Water Potability",
"Water Race Type",
"Water Resource Information : Hydrologic Persistence",
"Water Resource Information : Water Potability",
"Water Resource Information : Water Type",
"Water Well Construction Description",
"Waterbody Overhead Obstruction",
"Watercourse Channel Type",
"Watercourse Morphology",
"Watercourse Sink Type",
"Weapons Range Type",
"Weapons Range Type [2]",
"Weapons Range Type [3]",
"Well Equipment",
"Well Equipment [2]",
"Well Equipment [3]",
"Well Type",
"Width",
"Width at Top",
"Width of Second Travelled Way",
"Wireless Telecommunication Information : Wireless Telecommunication Type",
"World Port Index Identifier"
};

char *TDS4_attr_types[] = {
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"String",
"Integer",
"Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"String",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Float",
"Float",
"String",
"Short Integer",
"Float",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"String",
"String",
"Integer",
"String",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Float",
"String",
"String",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"String"
};

char *TDS4_attr_defns[] = {
"Either the difference between the recorded horizontal coordinate value(s) of a feature and its true position referenced to the same geodetic datum expressed as a linear error at 90 percent probability for a single coordinate value, or a circular error at 90 percent probability for a pair of coordinate values, or the reason that the value is absent.Unit of Measure: Metre",
"Either the difference between the recorded vertical position value of a feature and its true position referenced to the same vertical datum expressed as a linear error at 90 percent probability, or the reason that the value is absent.Unit of Measure: Metre",
"The type(s) of utility that can be accessed through a utility cover.",
"The type(s) of utility that can be accessed through a utility cover.",
"The type(s) of utility that can be accessed through a utility cover.",
"The postal address and/or electronic contact information for a facility, organisation or person.",
"The nature of an administrative division as established by an international body (for example: the United Nations), a supranational body (for example: the European Union), a State (for example: France), or a similar entity (for example: the Vatican) or organization (for example: the International Hydrographic Organization).",
"The vertical distance above Mean Sea Level (MSL) of the highest point of the landing area.Unit of Measure: Metre",
"The type of the predominant material of which a surface of the movement area is composed.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The primary official name of an aerodrome as designated by an appropriate authority.",
"The level of preparation of the aerodrome movement area surface, as a category.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The preparation technique(s) applied to a surface composition.",
"The preparation technique(s) applied to a surface composition.",
"The preparation technique(s) applied to a surface composition.",
"The functional status of the pavement of an aerodrome movement area.",
"The operational status of an aerodrome movement area, as a category.",
"An indication that an obstacle that constitutes a danger to air navigation is marked by a light or lights.",
"The type of airfield symbol designation.",
"The type of an airfield based on the size and/or paving of its runways.",
"The type of an amusement park attraction based on its geometric form, appearance, configuration, and/or use.",
"The angular distance in the horizontal plane measured from true north (0 degrees) clockwise to the major axis of the feature.Unit of Measure: Arc Degree",
"The type of an apron based upon its location on an aerodrome and its general purpose.",
"The type of an aqueduct based on its structure.",
"The type of permeable geologic formation that composes the aquifer.",
"The closure conditions of the two endpoints of a numeric interval.",
"The distance between the terrain surface and the upper surface of the aquifer.Unit of Measure: Metre",
"The distance between the terrain surface and the upper surface of the aquifer.Unit of Measure: Metre",
"The common or scientific name of an aquifer.",
"The type(s) and/or morphology(ies) of terrain material that overlie an aquifer.",
"The type(s) and/or morphology(ies) of terrain material that overlie an aquifer.",
"The type(s) and/or morphology(ies) of terrain material that overlie an aquifer.",
"The closure conditions of the two endpoints of a numeric interval.",
"The distance between the upper and lower surfaces of an aquifer.Unit of Measure: Metre",
"The distance between the upper and lower surfaces of an aquifer.Unit of Measure: Metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The estimated typical long-term yield from a single, properly sited and constructed well in the aquifer.Unit of Measure: Litre per Minute",
"The estimated typical long-term yield from a single, properly sited and constructed well in the aquifer.Unit of Measure: Litre per Minute",
"The area within the delineation of the feature.Unit of Measure: Square Metre",
"An indication that a building is physically contiguous (for example: shares a common wall) with one or more adjacent buildings.",
"The type of structure and/or material mounted on the top of a barrier (for example: a fence or a wall).",
"The vertical distance from a specified vertical datum to the terrain surface of or at the base of the feature.Unit of Measure: Metre",
"The type of a basin gate based on its structure and/or intended use.",
"The type of a bog or fen based on its morphology and/or dominant vegetation.",
"The primary type(s) of material composing the bottom of a body of water.",
"The primary type(s) of material composing the bottom of a body of water.",
"The primary type(s) of material composing the bottom of a body of water.",
"The function or configuration of a branch railway.",
"The type of structure or mechanism by which a bridge or bridge span is moved to allow passage of a vessel.",
"The unique identifier of a bridge in accordance with the provisions of terrain analysis databases (for example: PTADB or TTADB).",
"The type(s) of structural design of a bridge, bridge span, or bridge superstructure.",
"The type(s) of structural design of a bridge, bridge span, or bridge superstructure.",
"The type(s) of structural design of a bridge, bridge span, or bridge superstructure.",
"The type of a superstructure that extends above the general roofline of a building.",
"A general evaluation of the density of a built-up area, as a category.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The ease or ability to circumvent a destroyed section of bridge, tunnel or pass within a distance of two kilometres from the feature.",
"The type of a cable based on its use.",
"The type of a cable based on its use.",
"The type of a cable based on its use.",
"The shape assumed by a cable suspended by a series of pylons.",
"The type of a cable based on its use.",
"The type of a cable based on its use.",
"The type of a cable based on its use.",
"The type of a cableway based on structure and/or function.",
"The fraction of canopy cover within a defined area during the season of maximum foliage.Unit of Measure: Percent",
"The type of a cave based on how it was formed.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The ground slope of the floor of the entrance at the point of access for an underground feature (for example: a cave, tunnel or underground extraction mine) as a category.",
"The identifier that denotes a defined extent (for example: a rectangular cell) within a system (for example: an array of rectangular cells) of planar space partitioning.",
"The tesselation scheme used to create a planar space partitioning and assign identifiers to its cells.",
"The distance between the centrelines of the two travelled ways of a divided highway.Unit of Measure: Metre",
"The category of a protected area based on level of protection and the enabling laws of the controlling entity (for example: State) or rules of international organization (for example: as determined by the International Union for Conservation of Nature and Natural Resources (IUCN)).",
"The object (for example: a telecommunication cable or a power line) is located within a service tunnel.",
"The object is at least partially located within, or passes through, a tunnel.",
"An indication that a facility (for example: a storage tank, a drum storage area, or a liquid transfer area) is surrounded by an embankment or wall that provides a barrier to retain liquid (for example: leaked fuel oil).",
"The source(s) of contaminants present in a region.",
"An indication that a facility is controlled.",
"The controlling authority responsible for a facility or site.",
"The extent and/or nature of the cover (for example: a roof) of a structure.",
"An indication that a watercourse section is completely covered over and connects to uncovered watercourses at each end.",
"The type of mobility of a crane.",
"The type of a crane based on its design and/or method of operation.",
"The predominant species of a crop land.",
"The predominant species of a crop land.",
"The predominant species of a crop land.",
"The agricultural practice(s) in use within an agro-ecosystem.",
"The agricultural practice(s) in use within an agro-ecosystem.",
"The agricultural practice(s) in use within an agro-ecosystem.",
"The general arrangement(s) and/or pattern(s) of farming fields.",
"The general arrangement(s) and/or pattern(s) of farming fields.",
"The general arrangement(s) and/or pattern(s) of farming fields.",
"The method used to supply crops with water.",
"The cross-sectional profile of an opening (for example: a tunnel or the space under a bridge span).",
"The type of a cultural factor shared by a group of people and establishing a common context for their behaviour.",
"The type of a culvert based on its shape and fill.",
"The total cumulative length of track contained within the confines of the feature, exclusive of the branch or main trunk lines running into and/or out of the feature.Unit of Measure: Metre",
"The radius of curvature of a segment of a feature (or the feature as a whole, if applicable).Unit of Measure: Metre",
"The type of a dam based on function and/or structure.",
"An indication that a body of water is impounded by a dam.",
"A narrative or other textual description that records a general assessment of the quality of a resource (for example: a data instance, a data set or a data processing activity).",
"The number of vertically stacked decks, one over another, in a transportation structure (for example: a bridge or a tunnel).Unit of Measure: Unitless",
"The relative level of a deck within a set of vertically stacked decks, one over another, in a transportation structure (for example: on a bridge or in a tunnel).Unit of Measure: Unitless",
"The distance measured from ground or water level (uphill/upstream side of the feature) to the deepest point of the feature.Unit of Measure: Metre",
"The dimension of a circular, cylindrical, or spherical feature taken from boundary to boundary along a straight line passing through its centre.Unit of Measure: Metre",
"The bearing of movement or direction of the flow.Unit of Measure: Arc Degree",
"An indication that the lanes or tracks in a land transportation route (for example: a road or a railway), are horizontally separated (for example: by a median strip) and not adjoining.",
"The category of surface for which an elevation is determined.",
"Either the difference between a recorded elevation value and the true elevation referenced to the same vertical datum, expressed as a linear error at 90 percent probability, or the reason that the value is absent.Unit of Measure: Metre",
"The type of an embankment based on its use and/or relationship to the surrounding terrain.",
"The type of an engine test cell based on the purpose for which it was designed.",
"The type of an excavation and/or embankment created for the purpose of enhancing the defense of a site from armed attack.",
"The map scale that best represents the density of feature collection within the geospatial extent of a specified region, as a category.",
"The type of an extraction mine.",
"The specification that was used as the basis for defining the digital representation of the feature or data set.",
"The version of the specification that was used as the basis for defining the digital representation of the feature or data set.",
"The status of operation of a man-made structure, as a whole.",
"The type of multiplicity and/or configuration of a feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The type of a fence based on the type of materials used in its construction.",
"The length of a route in a body of water where a ferry crosses from one shoreline to another.Unit of Measure: Metre",
"The type of a ferry crossing based on the maneuverability of the vessel.",
"An indication that a road is designed to support emergency (for example: national defence) use as a runway.",
"An indication that an object is floating.",
"The type of a flood control structure based on its structure and/or intended use.",
"The number of floors in a structure (for example: a building).Unit of Measure: Unitless",
"The predominant foliage type of the vegetation.",
"The type of a building that is fortified or reinforced to provide for defense from armed attack.",
"The type of a covering of snow and/or ice based on its composition and structure.",
"The type of a gate (or similar route barrier) based on its intended use.",
"A datum describing the relationship of a two-dimensional coordinate system to the Earth.",
"A complete name that is used to designate the entity as that designation would normally be written by the originating culture on a map or chart.",
"The unique name identifier element in the NGA Geographic Names Data Base (GNDB).",
"A complete name that is used to designate the entity as that designation would normally be written by the originating culture on a map or chart.",
"The unique name identifier element in the NGA Geographic Names Data Base (GNDB).",
"A complete name that is used to designate the entity as that designation would normally be written by the originating culture on a map or chart.",
"The unique name identifier element in the NGA Geographic Names Data Base (GNDB).",
"An indication that a geologic fault is visible at the ground surface.",
"The type of a geothermal outlet based on its morphology.",
"The length of a road or railway segment having a significant gradient, specifically greater than or equal to 7 percent (%) for a road or greater than or equal to 3 percent (%) for a railway.Unit of Measure: Metre",
"The number of terrain feature sides on which either fill or cut material is exposed.",
"An indication that an object is guided, secured, or steadied by guy wires.",
"Hangar design code.",
"The primary function(s) of harbour facilities that are associated with a service or commercial operation of public interest.",
"The primary function(s) of harbour facilities that are associated with a service or commercial operation of public interest.",
"The primary function(s) of harbour facilities that are associated with a service or commercial operation of public interest.",
"The intended use(s) of a designated hazard protection shelter based on the kind of emergency.",
"The intended use(s) of a designated hazard protection shelter based on the kind of emergency.",
"The intended use(s) of a designated hazard protection shelter based on the kind of emergency.",
"The vertical distance measured from the lowest point of the base of the feature at ground or water level (downhill/downstream side) to the tallest point of the feature.Unit of Measure: Metre",
"Either the difference between a recorded height value and the true height referenced to the same ground level, expressed as a linear error at 90 percent probability, or the reason that the value is absent.Unit of Measure: Metre",
"The vertical distance measured from the base to the top of the feature that gives the greatest value.Unit of Measure: Metre",
"The type of facility or building that is associated with a freestanding helipad.",
"The elevation from a specified vertical datum to the highest point on a feature.Unit of Measure: Metre",
"The recognized historic significance of a site and/or facility, if any.",
"An indication that a settled area contains a relatively homogeneous distribution of dwellings.",
"The distance available to pass a load that extends laterally beyond the wheels of a vehicle.Unit of Measure: Metre",
"The relationship between the feature and surrounding (including covering and/or underlying) water.",
"The degree of persistence of water in an inland water body (for example: a spring, a flowing stream, a lake or a pond).",
"The type of a hypsographic portrayal line (for example: a contour line) based on the topography represented and/or portrayal interval.",
"The identifier that is assigned to a location in accordance with rules prescribed by the International Civil Aviation Organization (ICAO) in Document 7910.",
"The International Organization for Standardization (ISO 3166-1) three character code that designates a geopolitical entity (for example: a State).",
"The type of an inland water based on its principal characteristics.",
"The amount of upward inclination between the horizontal surface of the mean water level of a watercourse where it touches the bank and the top of the first usable break in slope, measured at the same point on the upper bank as the military gap width.Unit of Measure: Percent",
"The relative orientation of a bank of an inland waterbody based on the direction of predominant water flow in the adjacent waterbody.",
"The closure conditions of the two endpoints of a numeric interval.",
"The predominant height (the height of at least 50 percent) of the bank, measured from mean water level to the first break in slope above the mean water level.Unit of Measure: Metre",
"The predominant height (the height of at least 50 percent) of the bank, measured from mean water level to the first break in slope above the mean water level.Unit of Measure: Metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The predominant slope (the slope of at least 50 percent) of the bank, measured from mean water level to the first accessible break in slope above the mean water level.Unit of Measure: Percent",
"The predominant slope (the slope of at least 50 percent) of the bank, measured from mean water level to the first accessible break in slope above the mean water level.Unit of Measure: Percent",
"An indication that the delineation of a shoreline is definite.",
"The physical characteristics of a shoreline.",
"The height of the waterbody bank above the average water level.Unit of Measure: Metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The fraction of vegetation cover on the bank of a watercourse.Unit of Measure: Percent",
"The fraction of vegetation cover on the bank of a watercourse.Unit of Measure: Percent",
"The amount of upward inclination between the horizontal surface of the mean water level of a watercourse where it touches the bank and the top of the first usable break in slope, measured at the same point on the upper bank as the military gap width.Unit of Measure: Percent",
"The relative orientation of a bank of an inland waterbody based on the direction of predominant water flow in the adjacent waterbody.",
"The closure conditions of the two endpoints of a numeric interval.",
"The predominant height (the height of at least 50 percent) of the bank, measured from mean water level to the first break in slope above the mean water level.Unit of Measure: Metre",
"The predominant height (the height of at least 50 percent) of the bank, measured from mean water level to the first break in slope above the mean water level.Unit of Measure: Metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The predominant slope (the slope of at least 50 percent) of the bank, measured from mean water level to the first accessible break in slope above the mean water level.Unit of Measure: Percent",
"The predominant slope (the slope of at least 50 percent) of the bank, measured from mean water level to the first accessible break in slope above the mean water level.Unit of Measure: Percent",
"An indication that the delineation of a shoreline is definite.",
"The physical characteristics of a shoreline.",
"The height of the waterbody bank above the average water level.Unit of Measure: Metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The fraction of vegetation cover on the bank of a watercourse.Unit of Measure: Percent",
"The fraction of vegetation cover on the bank of a watercourse.Unit of Measure: Percent",
"The type of route intersection traffic control based on the method(s) of warning and/or control.",
"The type of route intersection traffic control based on the method(s) of warning and/or control.",
"The type of route intersection traffic control based on the method(s) of warning and/or control.",
"The shape and/or configuration of the land surface as a whole or in a localized area.",
"The distance measured from ground or water level (uphill/upstream side of the feature) to the highest point of a feature located completely underground.Unit of Measure: Metre",
"The dimension of a feature taken along its primary alignment of use and generally in the horizontal plane.Unit of Measure: Metre",
"The maximum weight that can be safely raised by a lifting device (for example: a crane).Unit of Measure: Tonne",
"The arrangement of parallel linear features on a single support structure including both directions (if applicable).",
"The dynamic live load weight-bearing capacity of a bridge or bridge span for one-way, wheeled vehicle traffic in MLC units.Unit of Measure: Military Load Class",
"The dynamic live load weight-bearing capacity of a bridge or bridge span for two-way, wheeled vehicle traffic in MLC units.Unit of Measure: Military Load Class",
"The dynamic live load weight-bearing capacity of a bridge or bridge span for one-way, tracked vehicle traffic in MLC units.Unit of Measure: Military Load Class",
"The dynamic live load weight-bearing capacity of a bridge or bridge span for two-way, tracked vehicle traffic in MLC units.Unit of Measure: Military Load Class",
"The feature (for example: a parking garage, storage tank, or a transportation station) is located underground.",
"The location of an object in relation to a land water boundary.",
"The date and, optionally, time that maintenance, based on a given Extraction Specification, was completed for the features falling within the geospatial extent of a specified region.",
"An indication that a feature is man-made.",
"An indication that a body of water is completely surrounded by a man-made shoreline.",
"An indication that a building is free-standing (detached) and self-contained and is built in a factory and then towed by a tractor to its semi-permanent site.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"An indication that the lanes or tracks of a divided land transportation route (for example: a road or a railway) are separated by a vertical median barrier.",
"A narrative or other textual description that records observation(s) and/or event(s) associated with a particular subject (for example: a data instance, a data set or a data processing activity).",
"The category(ies) of environmental hazards present in a region that affect military operations.",
"The branch of the armed forces of a nation.",
"The type of a missile site based on the class of missiles it houses.",
"The type of a missile site based on the class of missiles it houses.",
"The type of a missile site based on the class of missiles it houses.",
"An indication that a ferry is propelled across a waterbody by a motor located on either the vessel or the shore.",
"An indication that a building is divided into two or more distinct sets of rooms or other interior spaces that are internally fully-connected while being separated from each other and common areas by controlled access point(s) (for example: lockable doors) that enable physical privacy and security for its occupants.",
"The type of a location that normally does not appear as a specific, characterized object but that has a name that is required to be displayed in association with that location.",
"The type of a natural pool, generally based on its origin.",
"Information about the navigability of a body of water by ocean-going and/or large vessels.",
"An indication that a feature may serve as a navigation landmark, allowing for rapid and positive orientation of a navigator.",
"The season(s) in which a nomadic people are camped at a given location.",
"The season(s) in which a nomadic people are camped at a given location.",
"The season(s) in which a nomadic people are camped at a given location.",
"A narrative or other textual description that records observation(s) and/or event(s) associated with a particular subject (for example: a data instance, a data set or a data processing activity).",
"The type of primary structure of an offshore construction upon which various pieces of operation-specific equipment are affixed.",
"An indication that a thoroughfare is intended to be used only in a single direction.",
"The time(s) during which a feature is usable.",
"The least distance between the travelled way and any obstruction vertically above it.Unit of Measure: Metre",
"The type of an overhead obstruction based on its shape, structure and/or intended use.",
"The total number of nominally parallel lines within the feature.Unit of Measure: Unitless",
"An indication that a feature is traversable on foot.",
"The physical condition of a man-made structure, as a whole, including the inside and/or outside of the structure and any contained and/or associated equipment.",
"An indication that a facility is a port of entry for customs and immigration purposes.",
"The maximum voltage at which a power line is designed to operate.Unit of Measure: Kilovolt",
"The energy source(s) employed to generate power for off-site distribution.",
"The energy source(s) employed to generate power for off-site distribution.",
"The energy source(s) employed to generate power for off-site distribution.",
"The average water velocity, exclusive of high water due to runoff or low water due to drought.Unit of Measure: Metre per Second",
"The predominant depth (the depth of at least 50 percent) of the feature.Unit of Measure: Metre",
"The predominant height (the height of at least 50 percent) of the feature measured from the lowest point of the base at ground or water level (downhill side/downstream side).Unit of Measure: Metre",
"The average (seasonal) high water depth, exclusive of high water due to runoff or low water due to drought.Unit of Measure: Metre",
"The average maximum (seasonal high water) water velocity, exclusive of high water due to runoff or low water due to drought.Unit of Measure: Metre per Second",
"The average (seasonal) low water depth, exclusive of high water due to runoff or low water due to drought.Unit of Measure: Metre",
"The average minimum (seasonal low water) water velocity, exclusive of high water due to runoff or low water due to drought.Unit of Measure: Metre per Second",
"The predominant height (the height of at least 50 percent) of the vegetation.Unit of Measure: Metre",
"The predominant water depth (the depth of at least 50 percent), determined along a bank-to-bank cross section.Unit of Measure: Metre",
"A narrative or other textual description of a process step, including related processing parameters and/or tolerances.",
"The organization responsible for originating (creating) the content of the resource.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The configuration of a pylon or pole.",
"An indication that an object is guided, secured, or steadied by guy wires.",
"The configuration of a pylon or pole.",
"The primary type of material composing a pylon.",
"The general shape and/or structure of a tower.",
"The primary type of material composing a pylon.",
"The physical mounting and/or configuration of a radar antenna.",
"The primary purpose served by a radar station.",
"The class of a railway based on its importance in the general transportation network.",
"The use(s) to which a railway is put as part of a transportation system.",
"The use(s) to which a railway is put as part of a transportation system.",
"The use(s) to which a railway is put as part of a transportation system.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The relationship of the elevation of the terrain surface of or at the base of the feature and that of the surrounding terrain.",
"A designation denoting a religion or system of belief.",
"The type of a facility, building, structure or site that is designed and designated to be used for religious activities, based on its structure and/or the principal activity for which it was designed.",
"The organization responsible for originating (creating) the content of the resource.",
"A description of any commercial (or similar) copyright notice applicable to information regarding the feature or data set.",
"A description of any commercial (or similar) restrictions on the distribution of information regarding the feature or data set.",
"The highest level of classification applicable to the resource, or a portion of the resource, within the domain of classified national security information.",
"One or more indicators of the expansion or limitation on the distribution of an information resource or portion within the domain of information originating from non-intelligence components.",
"One or more indicators identifying the national government or international organization that have purview over the classification marking of an information resource or portion therein.",
"An indication that a rig is present.",
"The type of physical arrangement of a road interchange.",
"The structure of a significant outcropping of exposed rock.",
"The configuration(s) and/or appearance(s) of a roof.",
"The configuration(s) and/or appearance(s) of a roof.",
"The configuration(s) and/or appearance(s) of a roof.",
"An indication that a feature is covered by a roof.",
"The official designation assigned to a route.",
"The type of designation of a road network according to the nature of service that it is intended to provide, as designated by international, national and/or other administrative authorities.",
"The official designation assigned to a route.",
"The type of designation of a road network according to the nature of service that it is intended to provide, as designated by international, national and/or other administrative authorities.",
"The official designation assigned to a route.",
"The type of designation of a road network according to the nature of service that it is intended to provide, as designated by international, national and/or other administrative authorities.",
"The closure conditions of the two endpoints of a numeric interval.",
"The width of a divider that separates adjacent route lanes or tracks in a land transportation route.Unit of Measure: Metre",
"The width of a divider that separates adjacent route lanes or tracks in a land transportation route.Unit of Measure: Metre",
"The minimum width of the travelled way of a route.Unit of Measure: Metre",
"The type of weather conditions under which a road is usable.",
"The minimum width of the travelled way of a route.Unit of Measure: Metre",
"The composition(s) of a durable surface (for example: a pavement) intended to sustain ground traffic (for example: vehicular traffic or foot traffic).",
"The total usable width of the travelled way of a route.Unit of Measure: Metre",
"The type of a route width constriction based on the nature of the surrounding area.",
"The type of a route width expansion based on the nature of the expansion and/or surrounding area.",
"The designator of the runway that is used to uniquely identify it at an aerodrome.",
"The closure conditions of the two endpoints of a numeric interval.",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: Percent",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: Percent",
"The designator of the runway that is used to uniquely identify it at an aerodrome.",
"The closure conditions of the two endpoints of a numeric interval.",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: Percent",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: Percent",
"Minimum safe horizontal distance between adjacent structures on either side of a navigable channel.Unit of Measure: Metre",
"The characteristic alignment of a sand dune imposed by prevailing winds.Unit of Measure: Arc Degree",
"An indication that the height and location of a sand dune, or area of sand dunes, is unchanging.",
"The type of a sand dune based on its shape and/or structure.",
"The month of the seasonal limit of the presence of ice that poses a hazard to maritime traffic.",
"An indication that a feature (for example: a linear stand of trees) functions as a shelter belt, protecting other features (for example: roads, railways, cropland, and/or structures) from the effects of adverse weather.",
"The type of a shipping container based on its structural characteristics and/or intended use.",
"The type of a shoreline construction (for example: a pier, a wharf, or a quay).",
"An indication that the delineation of a shoreline is definite.",
"The type of a shoreline ramp based on its design and intended use.",
"The physical characteristics of a shoreline.",
"The closure conditions of the two endpoints of a numeric interval.",
"The depth of the soil or unconsolidated surface material.Unit of Measure: Metre",
"The depth of the soil or unconsolidated surface material.Unit of Measure: Metre",
"The soil type as specified by the Unified Soil Classification System (USCS).",
"General moisture content or condition of a soil.",
"An indication that a marine construction (for example: a pier, wharf, or quay) is solid, thereby blocking the free circulation of water underneath the construction.",
"The date and, optionally, time of collection of the data that was used to define the non-spatial representation of the digital feature or data set.",
"A description of the data that was used to define the non-spatial  representation of the digital feature or data set.",
"The type(s) of data that were used to define the digital representation of the non-spatial  component(s) of the feature or data set.",
"The date and, optionally, time of collection of the data that was used to define the spatial representation of the digital feature or data set.",
"A description of the data that was used to define the spatial representation of the digital feature or data set.",
"The type(s) of data that were used to define the digital representation of the spatial component(s) of the feature or data set.",
"The type of dataset and associated process that was used to define the digital representation of the vertical coordinate values of the feature or data set.",
"The date and, optionally, time of collection of the data that was used to define the digital representation of the vertical coordinate values of the digital feature or data set.",
"A description of the data that was used to define the digital representation of the vertical coordinate values of the digital feature or data set.",
"The number of spans in a bridge.Unit of Measure: Unitless",
"One or more intended attribute domain values for one or more enumeration or codelist attributes that are not currently valid members of their respective attribute ranges.",
"The natural level of the water table in a well, measured with respect to surface level when water is not being actively withdrawn.Unit of Measure: Metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The average diameter of the tree trunks in an area, measured at a height of approximately 1.5 metres or 4.5 feet on the high side (if on a hillside) above the surface of the ground.Unit of Measure: Metre",
"The average diameter of the tree trunks in an area, measured at a height of approximately 1.5 metres or 4.5 feet on the high side (if on a hillside) above the surface of the ground.Unit of Measure: Metre",
"The type of a street sign based on the nature of the information that it displays.",
"The primary type(s) of material composing a feature, exclusive of the surface.",
"The primary type(s) of material composing a feature, exclusive of the surface.",
"The primary type(s) of material composing a feature, exclusive of the surface.",
"The geometric form, appearance, and/or configuration of the feature as a whole.",
"The type of an electricity distribution substation based on its function(s).",
"The type of an electricity distribution substation based on its function(s).",
"The type of an electricity distribution substation based on its function(s).",
"An indication that a feature is physically supported by another feature.",
"The object is at least partially supported by, or passes across, a bridge span.",
"The closure conditions of the two endpoints of a numeric interval.",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: Percent",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: Percent",
"The type of a control point established by surveying methods based on method of establishment and/or intended use.",
"The type of an aircraft taxiway based on its connectivity to other aerodrome ground surfaces.",
"The type of a telescope based on its design, structure and/or intended use.",
"The minimum horizontal bridging distance necessary to cross a channel.Unit of Measure: Metre",
"The type of terrain morphology based on composition and/or configuration.",
"The type(s) of material that compose the surface layer of the terrain.",
"The type(s) of material that compose the surface layer of the terrain.",
"The type(s) of material that compose the surface layer of the terrain.",
"The distance between the two opposite surfaces of an object, usually the distance of smallest measure.Unit of Measure: Metre",
"The type of a thoroughfare based on its design.",
"An indication that a route (for example: a road) passes through (both into and out of) a place (for example: an urban area) without interruption.",
"An indication that a waterbody is affected by the tide.",
"The type of structure within which a corpse is entombed based on its method of construction, location, and/or occupancy.",
"The general shape and/or structure of a tower.",
"The type of a tower based on its intended use(s).",
"The type of a tower based on its intended use(s).",
"The type of a tower based on its intended use(s).",
"The distance between a single pair of rails of a railway, measured along the shortest distance from inside rail to inside rail.Unit of Measure: Metre",
"The classification of a railway based on the distance between a single pair of rails, measured along the shortest distance from inside rail to inside rail.",
"The method by which electrical power is distributed on a railway, if any.",
"An indication that a railway track is located within the bounds of a roadbed.",
"The type of function, configuration, and/or management of a railway track.",
"The total number of independent, parallel paths (for example: a railway track and/or a road lane) in both directions within a route.Unit of Measure: Unitless",
"The reason for traffic restriction based on the nature of the route.",
"The type of a transportation block based on its method of action.",
"The type of a transportation route protection structure based on its configuration and/or intended purpose.",
"The type of a transportation system based on the type(s) of vehicles employed and/or the nature(s) of the objects transported.",
"The type of a transportation system based on the type(s) of vehicles employed and/or the nature(s) of the objects transported.",
"The type of a transportation system based on the type(s) of vehicles employed and/or the nature(s) of the objects transported.",
"The closure conditions of the two endpoints of a numeric interval.",
"The average tree spacing between trees in a stand, determined from centre to centre of adjacent trees.Unit of Measure: Metre",
"The average tree spacing between trees in a stand, determined from centre to centre of adjacent trees.Unit of Measure: Metre",
"Clearance below bridge, measured from the lowest surface level to the base of the lower of either a cross beam or the lowest bridge deck.Unit of Measure: Metre",
"The means by which an underground mine is accessed from the surface.",
"The closure conditions of the two endpoints of a numeric interval.",
"The fraction of land within a defined area that is covered by undergrowth (for example: scrub, brush, and/or bush).Unit of Measure: Percent",
"The fraction of land within a defined area that is covered by undergrowth (for example: scrub, brush, and/or bush).Unit of Measure: Percent",
"The globally unique and persistent identifier of an entity (for example: feature or event) instance as specified by a Uniform Resource Name (URN) in accordance with the Internet Engineering Task Force (IETF) RFC2396 and RFC2141.",
"The globally unique and persistent identifier of a resource (for example: a dataset or a service) instance as specified by a Uniform Resource Identifier (URI) in accordance with the Internet Engineering Task Force (IETF) RFC2396.",
"The interior length of a structure (for example: an aircraft bunker or a lock).Unit of Measure: Metre",
"The interior width of a structure.Unit of Measure: Metre",
"The type of a vegetated area based on species, biome, physiography and/or structural organization.",
"The predominant species of a tract of vegetation.",
"The predominant species of a tract of vegetation.",
"The predominant species of a tract of vegetation.",
"The number of vehicle scales at a weigh station.Unit of Measure: Unitless",
"The type of a vehicle based on its use and/or mode of propulsion.",
"The type(s) of material that compose the load-bearing structure and/or exterior facing of a vertical construction (for example: a building or non-building structure).",
"The type(s) of material that compose the load-bearing structure and/or exterior facing of a vertical construction (for example: a building or non-building structure).",
"The type(s) of material that compose the load-bearing structure and/or exterior facing of a vertical construction (for example: a building or non-building structure).",
"A reference surface with respect to which elevations and/or depths are specified.",
"A unique identification code that identifies a feature that is a vertical obstruction to low-level flight.",
"The relationship between the feature and the underlying ground (terrain) or waterbody bottom.",
"The reason(s) that geospatial data was not collected.",
"The reason(s) that geospatial data was not collected.",
"The reason(s) that geospatial data was not collected.",
"The type(s) of geospatial data that were not collected.",
"The type(s) of geospatial data that were not collected.",
"The type(s) of geospatial data that were not collected.",
"The current level of activity of a volcano.",
"The classification by shape of a volcano.",
"The volume of a feature.Unit of Measure: Cubic Metre",
"The type of a wall based on structure and/or function.",
"The relationship between the feature and surrounding (including covering and/or underlying) water.",
"The tidal datum to which soundings and drying heights are referenced.",
"The name of the tidal datum to which soundings and drying heights are referenced.",
"The potability of water based on the type of treatment required before it is safe for human consumption.",
"The type of a water race based on its structure and/or intended purpose.",
"The degree of persistence of water in an inland water body (for example: a spring, a flowing stream, a lake or a pond).",
"The potability of water based on the type of treatment required before it is safe for human consumption.",
"The type of available water based on its composition.",
"A narrative or other textual description of the screening, casing, and/or finishing of a water well.",
"An indication that an object is an overhead obstruction over a navigable waterbody.",
"The type of trough-like depression that is normally occupied by a watercourse.",
"The type of a watercourse based on its shape and/or configuration.",
"The type of the sink of a watercourse.",
"The type of a weapons range based on its intended use(s).",
"The type of a weapons range based on its intended use(s).",
"The type of a weapons range based on its intended use(s).",
"The type(s) of equipment attached to or adjacent to a wellbore.",
"The type(s) of equipment attached to or adjacent to a wellbore.",
"The type(s) of equipment attached to or adjacent to a wellbore.",
"The type of a well, generally based on method of construction.",
"The dimension of a feature taken perpendicular to its primary alignment of use and generally in the horizontal plane.Unit of Measure: Metre",
"The width at the top of a feature.Unit of Measure: Metre",
"The width of a second travelled way that is the lesser width of the two travelled ways in a divided highway.Unit of Measure: Metre",
"The type of a wireless telecommunication service based on the mechanism(s) of transmission and/or the nature of the communication(s) supported.",
"The unique identifier element in the NGA World Port Index (Publication 150)."
};

