/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
int TDS6_ATTR_NUM=552;

char *TDS6_attr_codes[] = {
"ZI020_GE4",
"ZI020_GE44",
"ZI020_GE42",
"ZI020_GE43",
"AHA",
"AVA",
"UTY",
"UTY2",
"UTY3",
"ADR",
"ADI",
"ZVA",
"ASU",
"ASU2",
"ASU3",
"NA8",
"ZI019_ASX",
"ZI019_ASU",
"ZI019_ASU2",
"ZI019_ASU3",
"ZI019_ASP",
"ZI019_ASP2",
"ZI019_ASP3",
"ZI019_SFS",
"AXS",
"AWP",
"ASY",
"FPT",
"APT",
"APT2",
"APT3",
"AMA",
"AOO",
"APY",
"APU",
"APU2",
"APU3",
"ATC",
"AQP",
"AQP2",
"AQP3",
"DPAC",
"DPAL",
"DPAU",
"AQN",
"AQO",
"AQO2",
"AQO3",
"AQTC",
"AQTL",
"AQTU",
"AYRC",
"AYRL",
"AYRU",
"ARA",
"ATB",
"WDAC",
"WDAL",
"WDAU",
"BAT",
"BEL",
"BEN",
"BGT",
"BOC",
"BMC",
"BMC2",
"BMC3",
"RSA",
"BOT",
"BRN",
"BSC",
"BSC2",
"BSC3",
"BSU",
"BAC",
"PBY",
"PBY2",
"PBY3",
"BCC",
"AT005_CAB",
"AT005_CAB2",
"AT005_CAB3",
"TST",
"CAB",
"CAB2",
"CAB3",
"CAT",
"CSI",
"CSY",
"CDM",
"CDY",
"DMT",
"ZI071_CTX",
"ZI071_FFN",
"ZI071_FFN2",
"ZI071_FFN3",
"ZI071_UAO",
"CID",
"CPS",
"MWG",
"CCN",
"CDR",
"CNF",
"CAM",
"CST",
"CWT",
"CBP",
"CSO",
"CAA",
"CVT",
"CVT2",
"CVT3",
"CCT",
"CDA",
"CDL",
"CRM",
"CRA",
"ZI013_CSP",
"ZI013_CSP2",
"ZI013_CSP3",
"ZI013_FMM",
"ZI013_FMM2",
"ZI013_FMM3",
"ZI013_FFP",
"ZI013_FFP2",
"ZI013_FFP3",
"ZI013_IRG",
"ZI013_PIG",
"TCS",
"CTC",
"CTL",
"RAD",
"LDC",
"WOC",
"DFT",
"DWT",
"DMD",
"DQS",
"DZC",
"DEV",
"DZP",
"DIM",
"DOF",
"SEP",
"EPW",
"ESC",
"EVA",
"FIC",
"ETY",
"EET",
"EQC",
"MZN",
"ETS",
"ETZ",
"COS",
"FCO",
"FFN",
"FFN2",
"FFN3",
"ZI026_CTUC",
"ZI026_CTUL",
"ZI026_CTUU",
"ZI004_RCG",
"ZI026_SUR",
"FTI",
"FCL",
"FER",
"FSC",
"FLO",
"FCS",
"BNF",
"BC101_SST",
"TRE",
"FZR",
"SIC",
"GTC",
"HZD",
"ZI005_FNA",
"ZI005_FNA2",
"ZI005_FNA3",
"ZI005_NFN",
"ZI005_NFN2",
"ZI005_NFN3",
"GFT",
"GOT",
"LOG",
"CET",
"GUG",
"HTP",
"FHC",
"FHC2",
"FHC3",
"HST",
"HST2",
"HST3",
"HGT",
"HVA",
"HEI",
"HAF",
"ZVH",
"ZVH_AVA",
"ZVH_VDT",
"HSS",
"HHD",
"HCA",
"ZI025_MAN",
"ZI025_WLE",
"HQC",
"IKO",
"IWT",
"BH141_AWBA",
"BH141_AWBB",
"BH141_IBOA",
"BH141_IBOB",
"BPWHAC",
"BPWHAL",
"BPWHAU",
"BPWHBC",
"BPWHBL",
"BPWHBU",
"BPWSAC",
"BPWSAL",
"BPWSAU",
"BPWSBC",
"BPWSBL",
"BPWSBU",
"BH141_SHDA",
"BH141_SHDB",
"BH141_SLTA",
"BH141_SLTB",
"BH141_WBHA",
"BH141_WBHB",
"BWVCAC",
"BWVCAL",
"BWVCAU",
"BWVCBC",
"BWVCBL",
"BWVCBU",
"NAO",
"CSC",
"CSC2",
"CSC3",
"INU",
"LND",
"LEA",
"LZN",
"LCA",
"RTA",
"LC1",
"LC2",
"LC3",
"LC4",
"LUN",
"SRL",
"MAG",
"MDE",
"AZC",
"MNS",
"MFB",
"ZI014_PBY",
"ZI014_PBY2",
"ZI014_PBY3",
"ZI014_PPO",
"ZI014_PPO2",
"ZI014_PPO3",
"ZI014_PRW",
"ZI014_PRW2",
"ZI014_PRW3",
"BC040_LCN",
"BC040_LVN",
"BC040_EOL",
"BC040_PER",
"MAN",
"BC034_MRT",
"MWD",
"MES",
"MEM",
"CCG",
"YSU",
"MST",
"MST2",
"MST3",
"BSM",
"MCX",
"MUB",
"NLT",
"SWT",
"NVS",
"LMC",
"STL",
"STL2",
"STL3",
"ZI006_MEM",
"OCS",
"ONE",
"OPT",
"OHC",
"OOC",
"NPL",
"TRA",
"PSE",
"PRM",
"PCF",
"PLT",
"PLT2",
"PLT3",
"PEC",
"KVA",
"POS",
"POS2",
"POS3",
"WVA",
"PFD",
"PFH",
"WDH",
"WVH",
"WDL",
"WVL",
"PVH",
"PWA",
"PWAC",
"PWAL",
"PWAU",
"ZI004_PRE",
"PPO",
"PPO2",
"PPO3",
"PYC",
"ZI032_GUG",
"ZI032_PYC",
"ZI032_PYM",
"ZI032_TOS",
"PYM",
"RAC",
"RAS",
"RWC",
"RRC",
"RRC2",
"RRC3",
"PRW",
"PRW2",
"PRW3",
"RLE",
"ZI037_REL",
"ZI037_RFA",
"RCG",
"ZSAX_RS0",
"ZSAX_RX0",
"ZSAX_RX3",
"ZSAX_RX4",
"RIP",
"ROR",
"RIT",
"RTY",
"RKF",
"SSR",
"SSR2",
"SSR3",
"RFD",
"RTN",
"RTN2",
"RTN3",
"RIN_ROI",
"RIN_RTN",
"RIN_ROI2",
"RIN_RTN2",
"RIN_ROI3",
"RIN_RTN3",
"RMWC",
"RMWL",
"RMWU",
"WD1",
"ZI016_WTC",
"ZI016_WD1",
"ZI016_ROC",
"WD2",
"CON",
"EXP",
"GB052_RIDH",
"GB052_RIDL",
"GSGCHC",
"GSGCHL",
"GSGCHU",
"GSGCLC",
"GSGCLL",
"GSGCLU",
"SHC",
"SDO",
"SAD",
"SDT",
"SSE",
"SAX_RX7",
"SAX_RY2",
"SAX_RS1",
"SAX_RS2",
"SAX_RX9",
"SAX_RS3",
"SAX_RS4",
"SAX_RS5",
"SAX_RS6",
"SAX_RS8",
"SAX_RS9",
"SAX_RY0",
"SAX_RX1",
"SAX_RX2",
"SAX_RY1",
"SAX_RX5",
"SAX_RX6",
"SAX_RX8",
"SBC",
"SHT",
"PWC",
"SHD",
"SLR",
"SLT",
"SDCC",
"SDCL",
"SDCU",
"STP",
"SWC",
"FAC",
"ZI001_SDV",
"ZI001_SDP",
"ZI001_SRT",
"ZI001_SPS",
"ZI001_VSC",
"ZI001_VSD",
"ZI001_VSN",
"NOS",
"OTH",
"SPM",
"HGS",
"SWW",
"SDSC",
"SDSL",
"SDSU",
"SSG",
"MCC",
"MCC2",
"MCC3",
"SDQ",
"SSC",
"SBT",
"SBT2",
"SBT3",
"SPT",
"SBB",
"SGCC",
"SGCL",
"SGCU",
"SUY",
"TXP",
"TEL",
"WD3",
"SRD",
"TSM",
"TSM2",
"TSM3",
"THI",
"THR",
"TID",
"TTY",
"TOS",
"TTC",
"TTC2",
"TTC3",
"ZI017_GAW",
"ZI017_RGC",
"ZI017_RRA",
"ZI017_RIR",
"ZI017_TRT",
"LTN",
"SRE",
"DGC",
"TRP",
"TRS",
"TRS2",
"TRS3",
"TSCC",
"TSCL",
"TSCU",
"UBC",
"UMA",
"DMBC",
"DMBL",
"DMBU",
"UFI",
"URI",
"LNU",
"WDU",
"VEG",
"VSP",
"VSP2",
"VSP3",
"VTI",
"VET",
"VCS",
"VCS_VCR",
"VCS_VCD",
"VCM",
"VCM2",
"VCM3",
"VDT",
"VOI",
"LOC",
"VCA",
"VCA2",
"VCA3",
"VCT",
"VCT2",
"VCT3",
"VOA",
"VGT",
"VLM",
"WTI",
"WLE",
"BA000_VDC",
"BA000_VDR",
"YWQ",
"WRT",
"ZI024_ASE",
"ZI024_CLO",
"ZI024_CFR",
"ZI024_CYN",
"ZI024_HYP",
"ZI024_MGN",
"ZI024_TUR",
"ZI024_SUL",
"ZI024_TEP",
"ZI024_TDS",
"ZI024_WAC",
"ZI024_HAR",
"ZI024_YWQ",
"ZI024_SCC",
"ZI024_PHW",
"WAD",
"WBD",
"OWO",
"WCC",
"WMT",
"WST",
"FRT",
"FRT2",
"FRT3",
"WEQ",
"WEQ2",
"WEQ3",
"WFT",
"WID",
"WT2",
"ZI018_WIT",
"WPI"
};

char *TDS6_attr_names[] = {
"(Location Country) Designation : GENC Short URN-based Identifier",
"(Location Country) Designation : GENC Short URN-based Identifier (fourth)",
"(Location Country) Designation : GENC Short URN-based Identifier (second)",
"(Location Country) Designation : GENC Short URN-based Identifier (third)",
"Absolute Horizontal Accuracy (90%)",
"Absolute Vertical Accuracy (90%)",
"Accessible Utility Type",
"Accessible Utility Type [2]",
"Accessible Utility Type [3]",
"Address",
"Administrative Division",
"Aerodrome Elevation",
"Aerodrome Movement Area Surface Composition",
"Aerodrome Movement Area Surface Composition [2]",
"Aerodrome Movement Area Surface Composition [3]",
"Aerodrome Official Name",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Category",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Composition",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Composition [2]",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Composition [3]",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Preparation Method",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Preparation Method [2]",
"Aerodrome Pavement Information : Aerodrome Movement Area Surface Preparation Method [3]",
"Aerodrome Pavement Information : Aerodrome Pavement Functional Status",
"Aerodrome Surface Status",
"Aeronautical Obstacle Light Present",
"Airfield Symbol Type",
"Airfield Type",
"Airfield Use",
"Airfield Use [2]",
"Airfield Use [3]",
"Amusement Attraction Type",
"Angle of Orientation",
"Apron Type",
"Apron Usage",
"Apron Usage [2]",
"Apron Usage [3]",
"Aqueduct Type",
"Aquifer Composition",
"Aquifer Composition [2]",
"Aquifer Composition [3]",
"Aquifer Depth <interval closure>",
"Aquifer Depth <lower value>",
"Aquifer Depth <upper value>",
"Aquifer Name",
"Aquifer Overburden",
"Aquifer Overburden [2]",
"Aquifer Overburden [3]",
"Aquifer Thickness <interval closure>",
"Aquifer Thickness <lower value>",
"Aquifer Thickness <upper value>",
"Aquifer Yield Rating <interval closure>",
"Aquifer Yield Rating <lower value>",
"Aquifer Yield Rating <upper value>",
"Area",
"Attached Building",
"Average Water Depth <interval closure>",
"Average Water Depth <lower value>",
"Average Water Depth <upper value>",
"Barrier Top Type",
"Base Elevation",
"Basic Encyclopedia (BE) Number",
"Basin Gate Type",
"Bog Type",
"Bottom Material Type",
"Bottom Material Type [2]",
"Bottom Material Type [3]",
"Branch Railway Type",
"Bridge Opening Type",
"Bridge Reference Number",
"Bridge Structure Type",
"Bridge Structure Type [2]",
"Bridge Structure Type [3]",
"Building Superstructure Type",
"Built-up Area Density Category",
"By-product",
"By-product [2]",
"By-product [3]",
"Bypass Condition",
"Cable : Cable Type",
"Cable : Cable Type [2]",
"Cable : Cable Type [3]",
"Cable Suspended Shape",
"Cable Type",
"Cable Type [2]",
"Cable Type [3]",
"Cableway Type",
"Cadastral Source Identifier",
"Cadastral Source Identifier Type",
"Cadastral Source Measurement",
"Cadastral Source Type",
"Canopy Cover",
"Cave Information : Cave Type",
"Cave Information : Feature Function",
"Cave Information : Feature Function [2]",
"Cave Information : Feature Function [3]",
"Cave Information : Underground Access Orientation",
"Cell Identifier",
"Cell Partition Scheme",
"Centerline Spacing",
"Commercial Copyright Notice",
"Commercial Distribution Restriction",
"Confined",
"Conservation Area Management Category",
"Contained within Service Tunnel",
"Contained within Tunnel",
"Containment Berm Present",
"Contaminant Source",
"Controlling Authority",
"Conveyor Type",
"Conveyor Type [2]",
"Conveyor Type [3]",
"Cover Closure Type",
"Covered Drain",
"Covered Drain Length",
"Crane Mobility Type",
"Crane Type",
"Crop Information : Crop Species",
"Crop Information : Crop Species [2]",
"Crop Information : Crop Species [3]",
"Crop Information : Farming Method",
"Crop Information : Farming Method [2]",
"Crop Information : Farming Method [3]",
"Crop Information : Farming Pattern",
"Crop Information : Farming Pattern [2]",
"Crop Information : Farming Pattern [3]",
"Crop Information : Irrigation Method",
"Crop Information : Permanent Irrigation",
"Cross-sectional Profile",
"Culvert Type",
"Cumulative Track Length",
"Curve Radius",
"Dam Crest Length",
"Dam Crest Width",
"Dam Face Type",
"Dam Type",
"Dammed",
"Data Quality Statement",
"Deck Count",
"Deck Level",
"Deepest Depth Below Surface Level",
"Diameter",
"Direction of Flow",
"Divided",
"Electrical Power Generation Capacity",
"Elevation Surface Category",
"Elevation Vertical Accuracy (90%)",
"Embankment Type",
"Engine Test Cell Type",
"Engineered Earthwork Type",
"Equivalent Scale Category",
"Extraction Mine Type",
"Extraction Specification",
"Extraction Specification Version",
"Facility Operational Status",
"Feature Configuration",
"Feature Function",
"Feature Function [2]",
"Feature Function [3]",
"Feature Metadata : Cartographic Usability Range <interval closure>",
"Feature Metadata : Cartographic Usability Range <lower value>",
"Feature Metadata : Cartographic Usability Range <upper value>",
"Feature Metadata : Process Step Information : Resource Content Originator",
"Feature Metadata : Survey Coverage Category",
"Fence Type",
"Ferry Crossing Distance",
"Ferry Crossing Type",
"Flight Strip Capable",
"Floating",
"Flood Control Structure Type",
"Floor Count",
"Fog Signal : Fog Signal Type",
"Foliage Type",
"Fortified Building Type",
"Frozen Cover Type",
"Gate Use",
"Geodetic Datum",
"Geographic Name Information : Full Name",
"Geographic Name Information : Full Name (second)",
"Geographic Name Information : Full Name (third)",
"Geographic Name Information : Name Identifier",
"Geographic Name Information : Name Identifier (second)",
"Geographic Name Information : Name Identifier (third)",
"Geologic Fault Trace Visible",
"Geothermal Outlet Type",
"Gradient Length",
"Grading Type",
"Guyed",
"Hangar Type Category",
"Harbour Facility Function",
"Harbour Facility Function [2]",
"Harbour Facility Function [3]",
"Hazard Shelter Intended Use",
"Hazard Shelter Intended Use [2]",
"Hazard Shelter Intended Use [3]",
"Height Above Surface Level",
"Height Vertical Accuracy (90%)",
"Height of Object",
"Helipad Associated Facility",
"Highest Elevation",
"Highest Elevation <absolute vertical accuracy>",
"Highest Elevation <vertical datum>",
"Historic Significance",
"Homogenous Habitation Distribution",
"Horizontal Clearance",
"Hydrographic Vertical Positioning Information : Maritime Navigation Marked",
"Hydrographic Vertical Positioning Information : Water Level Effect",
"Hypsography Portrayal Type",
"ICAO Location Indicator",
"Inland Water Type",
"Inland Waterbody Bank : Above Water Bank Slope (first bank)",
"Inland Waterbody Bank : Above Water Bank Slope (second bank)",
"Inland Waterbody Bank : Bank Orientation (first bank)",
"Inland Waterbody Bank : Bank Orientation (second bank)",
"Inland Waterbody Bank : Predominant Waterbody Bank Height (first bank) <interval closure>",
"Inland Waterbody Bank : Predominant Waterbody Bank Height (first bank) <lower value>",
"Inland Waterbody Bank : Predominant Waterbody Bank Height (first bank) <upper value>",
"Inland Waterbody Bank : Predominant Waterbody Bank Height (second bank) <interval closure>",
"Inland Waterbody Bank : Predominant Waterbody Bank Height (second bank) <lower value>",
"Inland Waterbody Bank : Predominant Waterbody Bank Height (second bank) <upper value>",
"Inland Waterbody Bank : Predominant Waterbody Bank Slope (first bank) <interval closure>",
"Inland Waterbody Bank : Predominant Waterbody Bank Slope (first bank) <lower value>",
"Inland Waterbody Bank : Predominant Waterbody Bank Slope (first bank) <upper value>",
"Inland Waterbody Bank : Predominant Waterbody Bank Slope (second bank) <interval closure>",
"Inland Waterbody Bank : Predominant Waterbody Bank Slope (second bank) <lower value>",
"Inland Waterbody Bank : Predominant Waterbody Bank Slope (second bank) <upper value>",
"Inland Waterbody Bank : Shoreline Delineated (first bank)",
"Inland Waterbody Bank : Shoreline Delineated (second bank)",
"Inland Waterbody Bank : Shoreline Type (first bank)",
"Inland Waterbody Bank : Shoreline Type (second bank)",
"Inland Waterbody Bank : Waterbody Bank Height (first bank)",
"Inland Waterbody Bank : Waterbody Bank Height (second bank)",
"Inland Waterbody Bank : Waterbody Bank Vegetation Cover (first bank) <interval closure>",
"Inland Waterbody Bank : Waterbody Bank Vegetation Cover (first bank) <lower value>",
"Inland Waterbody Bank : Waterbody Bank Vegetation Cover (first bank) <upper value>",
"Inland Waterbody Bank : Waterbody Bank Vegetation Cover (second bank) <interval closure>",
"Inland Waterbody Bank : Waterbody Bank Vegetation Cover (second bank) <lower value>",
"Inland Waterbody Bank : Waterbody Bank Vegetation Cover (second bank) <upper value>",
"Installation Operator",
"Intersection Control Type",
"Intersection Control Type [2]",
"Intersection Control Type [3]",
"Inundation Type",
"Land Morphology",
"Least Depth Below Surface Level",
"Length",
"Lifting Capacity",
"Linear Feature Arrangement",
"Load Class Type 1",
"Load Class Type 2",
"Load Class Type 3",
"Load Class Type 4",
"Located Underground",
"Location Referenced to Shoreline",
"Magnetic Variation",
"Maintenance Date and Time",
"Man-made",
"Man-made Shoreline",
"Manufactured Building",
"Manufacturing Information : By-product",
"Manufacturing Information : By-product [2]",
"Manufacturing Information : By-product [3]",
"Manufacturing Information : Product",
"Manufacturing Information : Product [2]",
"Manufacturing Information : Product [3]",
"Manufacturing Information : Raw Material",
"Manufacturing Information : Raw Material [2]",
"Manufacturing Information : Raw Material [3]",
"Maritime Navigation Light : Light Characteristic Number",
"Maritime Navigation Light : Light Elevation",
"Maritime Navigation Light : Nominal Range",
"Maritime Navigation Light : Period of Light",
"Maritime Navigation Marked",
"Maritime Radiobeacon : Maritime Radiobeacon Type",
"Maximum Design Water Depth",
"Median Present",
"Memorandum",
"Military Environmental Hazard Category",
"Military Service Branch",
"Missile Site Type",
"Missile Site Type [2]",
"Missile Site Type [3]",
"Mobile Bridge Span",
"Motorized Crossing",
"Multi-unit Building",
"Named Location Type",
"Natural Pool Type",
"Navigability Information",
"Navigation Landmark",
"Nomadic Seasonal Location",
"Nomadic Seasonal Location [2]",
"Nomadic Seasonal Location [3]",
"Note : Memorandum",
"Offshore Construction Primary Structure",
"One-way",
"Operating Cycle",
"Overhead Clearance",
"Overhead Obstruction Type",
"Parallel Line Count",
"Pedestrian Traversable",
"Periodic Restriction Month Interval",
"Permanent",
"Physical Condition",
"Pipeline Type",
"Pipeline Type [2]",
"Pipeline Type [3]",
"Port of Entry",
"Power Line Maximum Voltage",
"Power Source",
"Power Source [2]",
"Power Source [3]",
"Predominant Average Water Velocity",
"Predominant Feature Depth",
"Predominant Feature Height",
"Predominant Maximum Water Depth",
"Predominant Maximum Water Velocity",
"Predominant Minimum Water Depth",
"Predominant Minimum Water Velocity",
"Predominant Vegetation Height",
"Predominant Water Depth",
"Predominant Water Depth <interval closure>",
"Predominant Water Depth <lower value>",
"Predominant Water Depth <upper value>",
"Process Step Information : Process Step Description",
"Product",
"Product [2]",
"Product [3]",
"Pylon Configuration",
"Pylon Information : Guyed",
"Pylon Information : Pylon Configuration",
"Pylon Information : Pylon Material",
"Pylon Information : Tower Shape",
"Pylon Material",
"Radar Antenna Configuration",
"Radar Station Function",
"Railway Class",
"Railway Use",
"Railway Use [2]",
"Railway Use [3]",
"Raw Material",
"Raw Material [2]",
"Raw Material [3]",
"Relative Level",
"Religious Information : Religious Designation",
"Religious Information : Religious Facility Type",
"Resource Content Originator",
"Restriction Information : Security Attributes Group <resource classification>",
"Restriction Information : Security Attributes Group <resource dissemination controls>",
"Restriction Information : Security Attributes Group <resource non-intelligence community markings>",
"Restriction Information : Security Attributes Group <resource owner-producer>",
"Rig Present",
"Road Interchange Ramp",
"Road Interchange Type",
"Roadway Type",
"Rock Formation Structure",
"Roof Shape",
"Roof Shape [2]",
"Roof Shape [3]",
"Roofed",
"Route Designation",
"Route Designation [2]",
"Route Designation [3]",
"Route Identification <route designation type>",
"Route Identification <route designation>",
"Route Identification [2] <route designation type>",
"Route Identification [2] <route designation>",
"Route Identification [3] <route designation type>",
"Route Identification [3] <route designation>",
"Route Median Width <interval closure>",
"Route Median Width <lower value>",
"Route Median Width <upper value>",
"Route Minimum Travelled Way Width",
"Route Pavement Information : Road Weather Restriction",
"Route Pavement Information : Route Minimum Travelled Way Width",
"Route Pavement Information : Route Surface Composition",
"Route Total Usable Width",
"Route Width Constriction Type",
"Route Width Expansion Type",
"Runway Direction : Runway Designator (high end)",
"Runway Direction : Runway Designator (low end)",
"Runway Direction : Surface Slope (high end) <interval closure>",
"Runway Direction : Surface Slope (high end) <lower value>",
"Runway Direction : Surface Slope (high end) <upper value>",
"Runway Direction : Surface Slope (low end) <interval closure>",
"Runway Direction : Surface Slope (low end) <lower value>",
"Runway Direction : Surface Slope (low end) <upper value>",
"Safe Horizontal Clearance",
"Sand Dune Orientation",
"Sand Dune Stabilized",
"Sand Dune Type",
"Seasonal Ice Limit",
"Security Attributes Group <resource SCI controls>",
"Security Attributes Group <resource atomic energy markings>",
"Security Attributes Group <resource classification reason>",
"Security Attributes Group <resource classified by>",
"Security Attributes Group <resource compilation reason>",
"Security Attributes Group <resource date of exempted source>",
"Security Attributes Group <resource declassification date>",
"Security Attributes Group <resource declassification event>",
"Security Attributes Group <resource declassification exception>",
"Security Attributes Group <resource derivatively classified by>",
"Security Attributes Group <resource derived from>",
"Security Attributes Group <resource display only to>",
"Security Attributes Group <resource foreign government information (open source)>",
"Security Attributes Group <resource foreign government information (protected source)>",
"Security Attributes Group <resource non-US controls>",
"Security Attributes Group <resource releasable to>",
"Security Attributes Group <resource special-access-required program identifier>",
"Security Attributes Group <resource type of exempted source>",
"Shelter Belt",
"Shipping Container Type",
"Shoreline Construction Type",
"Shoreline Delineated",
"Shoreline Ramp Type",
"Shoreline Type",
"Soil Depth <interval closure>",
"Soil Depth <lower value>",
"Soil Depth <upper value>",
"Soil Type",
"Soil Wetness Condition",
"Solid Maritime Construction",
"Source Information : Source Date and Time",
"Source Information : Source Description",
"Source Information : Source Type",
"Source Information : Spatial Source",
"Source Information : Vertical Source Category",
"Source Information : Vertical Source Date and Time",
"Source Information : Vertical Source Description",
"Span Count",
"Specified Domain Value(s)",
"Speed Limit (KPH)",
"Spillway Height",
"Static Water Level",
"Stem Diameter <interval closure>",
"Stem Diameter <lower value>",
"Stem Diameter <upper value>",
"Street Sign Type",
"Structural Material Type",
"Structural Material Type [2]",
"Structural Material Type [3]",
"Structurally-dissected",
"Structure Shape",
"Substation Type",
"Substation Type [2]",
"Substation Type [3]",
"Supported",
"Supported by Bridge Span",
"Surface Slope <interval closure>",
"Surface Slope <lower value>",
"Surface Slope <upper value>",
"Survey Point Type",
"Taxiway Type",
"Telescope Type",
"Terrain Gap Width",
"Terrain Morphology",
"Terrain Surface Material",
"Terrain Surface Material [2]",
"Terrain Surface Material [3]",
"Thickness",
"Through Route",
"Tide Influenced",
"Tomb Type",
"Tower Shape",
"Tower Type",
"Tower Type [2]",
"Tower Type [3]",
"Track Information : Railway Gauge",
"Track Information : Railway Gauge Classification",
"Track Information : Railway Power Method",
"Track Information : Railway in Road",
"Track Information : Track Type",
"Track or Lane Count",
"Traffic Restriction Type",
"Transportation Block Type",
"Transportation Route Protection Structure Type",
"Transportation System Type",
"Transportation System Type [2]",
"Transportation System Type [3]",
"Tree Spacing <interval closure>",
"Tree Spacing <lower value>",
"Tree Spacing <upper value>",
"Underbridge Clearance",
"Underground Mine Access",
"Undergrowth Density <interval closure>",
"Undergrowth Density <lower value>",
"Undergrowth Density <upper value>",
"Unique Entity Identifier",
"Unique Resource Identifier",
"Usable Length",
"Usable Width",
"Vegetation Characteristic",
"Vegetation Species",
"Vegetation Species [2]",
"Vegetation Species [3]",
"Vegetation Trafficability Impact",
"Vehicle Type",
"Vertical Clearance, Safe",
"Vertical Clearance, Safe <reference level remark>",
"Vertical Clearance, Safe <reference level>",
"Vertical Construction Material",
"Vertical Construction Material [2]",
"Vertical Construction Material [3]",
"Vertical Datum",
"Vertical Obstruction Identifier",
"Vertical Relative Location",
"Void Collection Reason",
"Void Collection Reason [2]",
"Void Collection Reason [3]",
"Void Collection Type",
"Void Collection Type [2]",
"Void Collection Type [3]",
"Volcanic Activity",
"Volcano Shape",
"Volume",
"Wall Type",
"Water Level Effect",
"Water Line : Sounding Datum",
"Water Line : Sounding Datum Name",
"Water Potability",
"Water Race Type",
"Water Resource Information : Arsenic Concentration",
"Water Resource Information : Chloride Concentration",
"Water Resource Information : Coliform Concentration",
"Water Resource Information : Cyanide Concentration",
"Water Resource Information : Hydrologic Persistence",
"Water Resource Information : Magnesium Concentration",
"Water Resource Information : Nephelometric Turbidity",
"Water Resource Information : Sulfate Concentration",
"Water Resource Information : Temperature",
"Water Resource Information : Total Dissolved Solids",
"Water Resource Information : Water Conductivity",
"Water Resource Information : Water Hardness",
"Water Resource Information : Water Potability",
"Water Resource Information : Water Type",
"Water Resource Information : pH",
"Water Well Construction Description",
"Waterbody Depth",
"Waterbody Overhead Obstruction",
"Watercourse Channel Type",
"Watercourse Morphology",
"Watercourse Sink Type",
"Weapons Range Type",
"Weapons Range Type [2]",
"Weapons Range Type [3]",
"Well Equipment",
"Well Equipment [2]",
"Well Equipment [3]",
"Well Type",
"Width",
"Width of Second Travelled Way",
"Wireless Telecommunication Information : Wireless Telecommunication Type",
"World Port Index Identifier"
};

char *TDS6_attr_types[] = {
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Float",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Integer",
"Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Short Integer",
"Short Integer",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"Short Integer",
"String",
"Short Integer",
"String",
"Short Integer",
"String",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Integer",
"String",
"Float",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"Float",
"String",
"String",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Float",
"Float",
"Short Integer",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Float",
"Short Integer",
"Short Integer",
"Float",
"String",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"String"
};

char *TDS6_attr_defns[] = {
"The short URN-like Uniform Resource Identifier (URI) for a geopolitical entity (for example: a State) or administrative subdivision (for example: a province) as specified by the Geopolitical Entities, Names, and Codes (GENC) Standard.",
"The short URN-like Uniform Resource Identifier (URI) for a geopolitical entity (for example: a State) or administrative subdivision (for example: a province) as specified by the Geopolitical Entities, Names, and Codes (GENC) Standard.",
"The short URN-like Uniform Resource Identifier (URI) for a geopolitical entity (for example: a State) or administrative subdivision (for example: a province) as specified by the Geopolitical Entities, Names, and Codes (GENC) Standard.",
"The short URN-like Uniform Resource Identifier (URI) for a geopolitical entity (for example: a State) or administrative subdivision (for example: a province) as specified by the Geopolitical Entities, Names, and Codes (GENC) Standard.",
"Either the difference between the recorded horizontal coordinate value(s) of a feature and its true position referenced to the same geodetic datum expressed as a linear error at 90 percent probability for a single coordinate value, or a circular error at 90 percent probability for a pair of coordinate values, or the reason that the value is absent.Unit of Measure: metre",
"Either the difference between the recorded vertical position value of a feature and its true position referenced to the same vertical datum expressed as a linear error at 90 percent probability, or the reason that the value is absent.Unit of Measure: metre",
"The type(s) of utility that can be accessed through a utility cover.",
"The type(s) of utility that can be accessed through a utility cover.",
"The type(s) of utility that can be accessed through a utility cover.",
"The postal address and/or electronic contact information for a facility, organisation or person.",
"The nature of an administrative division as established by an international body (for example: the United Nations), a supranational body (for example: the European Union), a State (for example: France), or a similar entity (for example: the Vatican) or organization (for example: the International Hydrographic Organization).",
"The vertical distance above Mean Sea Level (MSL) of the highest point of the landing area.Unit of Measure: metre",
"The type of the predominant material of which a surface of the movement area is composed.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The primary official name of an aerodrome as designated by an appropriate authority.",
"The level of preparation of the aerodrome movement area surface, as a category.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The type of the predominant material of which a surface of the movement area is composed.",
"The preparation technique(s) applied to a surface composition.",
"The preparation technique(s) applied to a surface composition.",
"The preparation technique(s) applied to a surface composition.",
"The functional status of the pavement of an aerodrome movement area.",
"The operational status of an aerodrome movement area, as a category.",
"An indication that an obstacle that constitutes a danger to air navigation is marked by a light or lights.",
"The type of airfield symbol designation.",
"The type of an airfield based on the size and/or paving of its runways.",
"The primary use(s) of an airfield.",
"The primary use(s) of an airfield.",
"The primary use(s) of an airfield.",
"The type of an amusement park attraction based on its geometric form, appearance, configuration, and/or use.",
"The angular distance in the horizontal plane measured from true north (0 degrees) clockwise to the major axis of the feature.Unit of Measure: arcDegree",
"The type of an apron based upon its location on an aerodrome and its general purpose.",
"The function(s) that may be performed on an apron.",
"The function(s) that may be performed on an apron.",
"The function(s) that may be performed on an apron.",
"The type of an aqueduct based on its structure.",
"The type(s) of permeable geologic formation that composes the aquifer.",
"The type(s) of permeable geologic formation that composes the aquifer.",
"The type(s) of permeable geologic formation that composes the aquifer.",
"The closure conditions of the two endpoints of a numeric interval.",
"The distance between the terrain surface and the upper surface of the aquifer.Unit of Measure: metre",
"The distance between the terrain surface and the upper surface of the aquifer.Unit of Measure: metre",
"The common or scientific name of an aquifer.",
"The type(s) and/or morphology(ies) of terrain material that overlie an aquifer.",
"The type(s) and/or morphology(ies) of terrain material that overlie an aquifer.",
"The type(s) and/or morphology(ies) of terrain material that overlie an aquifer.",
"The closure conditions of the two endpoints of a numeric interval.",
"The distance between the upper and lower surfaces of an aquifer.Unit of Measure: metre",
"The distance between the upper and lower surfaces of an aquifer.Unit of Measure: metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The estimated typical long-term yield from a single, properly sited and constructed well in the aquifer.Unit of Measure: litrePerMinute",
"The estimated typical long-term yield from a single, properly sited and constructed well in the aquifer.Unit of Measure: litrePerMinute",
"The area within the delineation of the feature.Unit of Measure: squareMetre",
"An indication that a building is physically contiguous (for example: shares a common wall) with one or more adjacent buildings.",
"The closure conditions of the two endpoints of a numeric interval.",
"The average water depth, exclusive of high water due to runoff or low water due to drought.Unit of Measure: metre",
"The average water depth, exclusive of high water due to runoff or low water due to drought.Unit of Measure: metre",
"The type of structure and/or material mounted on the top of a barrier (for example: a fence or a wall).",
"The vertical distance from a specified vertical datum to the terrain surface of or at the base of the feature.Unit of Measure: metre",
"The unique identifier of a feature as assigned in the Basic Encyclopedia (a compilation of identified installations and physical areas of potential significance as objectives for attack).",
"The type of a basin gate based on its structure and/or intended use.",
"The type of a bog or fen based on its morphology and/or dominant vegetation.",
"The primary type(s) of material composing the bottom of a body of water.",
"The primary type(s) of material composing the bottom of a body of water.",
"The primary type(s) of material composing the bottom of a body of water.",
"The function or configuration of a branch railway.",
"The type of structure or mechanism by which a bridge or bridge span is moved to allow passage of a vessel.",
"The unique identifier of a bridge in accordance with the provisions of terrain analysis databases (for example: PTADB or TTADB).",
"The type(s) of structural design of a bridge, bridge span, or bridge superstructure.",
"The type(s) of structural design of a bridge, bridge span, or bridge superstructure.",
"The type(s) of structural design of a bridge, bridge span, or bridge superstructure.",
"The type of a superstructure that extends above the general roofline of a building.",
"A general evaluation of the density of a built-up area, as a category.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The ease or ability to circumvent a destroyed section of bridge, tunnel or pass within a distance of two kilometres from the feature.",
"The type of a cable based on its use.",
"The type of a cable based on its use.",
"The type of a cable based on its use.",
"The shape assumed by a cable suspended by a series of pylons.",
"The type of a cable based on its use.",
"The type of a cable based on its use.",
"The type of a cable based on its use.",
"The type of a cableway based on structure and/or function.",
"The unique identifier of a land parcel as assigned by a land survey or data production system.",
"The name, description, Uniform Resource Locator (URL) and/or other information sufficient to unambiguously identify the land survey or data production system that assigned a cadastral source identifier to a land parcel.",
"A description of the observations and/or physical measurements taken to describe the location and extent of a unit of land (or water) for purposes of administration.",
"The type of resource that describes the location and extent of a unit of land (or water), typically for purposes of administration such as taxation or land rights transfer.",
"The fraction of canopy cover within a defined area during the season of maximum foliage.Unit of Measure: percent",
"The type of a cave based on its dominant method of formation.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The ground slope of the floor of the entrance at the point of access for an underground feature (for example: a cave, tunnel or underground extraction mine) as a category.",
"The identifier that denotes a defined extent (for example: a rectangular cell) within a system (for example: an array of rectangular cells) of planar space partitioning.",
"The tessellation scheme used to create a planar space partitioning and assign identifiers to its cells.",
"The distance between the centrelines of the two travelled ways of a divided highway.Unit of Measure: metre",
"A description of any commercial (or similar) copyright notice applicable to information regarding the feature or data set.",
"A description of any commercial (or similar) restrictions on the distribution of information regarding the feature or data set.",
"An indication that an aquifer is overlain by a confining bed consisting of a layer of rock, or of unconsolidated sediments, that possesses a very low hydraulic conductivity and thus retards the movement of water into and out of the aquifer.",
"The category of a protected area based on level of protection and the enabling laws of the controlling entity (for example: State) or rules of international organization (for example: as determined by the International Union for Conservation of Nature and Natural Resources (IUCN)).",
"The object (for example: a telecommunication cable or a power line) is located within a service tunnel.",
"The object is at least partially located within, or passes through, a tunnel.",
"An indication that a facility (for example: a storage tank, a drum storage area, or a liquid transfer area) is surrounded by an embankment or wall that provides a barrier to retain liquid (for example: leaked fuel oil).",
"The source(s) of contaminants present in a region.",
"The controlling authority responsible for a facility or site.",
"The type(s), or category(ies), of mechanical device that best characterizes the means by which articles or materials are being moved.",
"The type(s), or category(ies), of mechanical device that best characterizes the means by which articles or materials are being moved.",
"The type(s), or category(ies), of mechanical device that best characterizes the means by which articles or materials are being moved.",
"The extent and/or nature of the cover (for example: a roof) of a structure.",
"An indication that a watercourse section is completely covered over and connects to uncovered watercourses at each end.",
"The length of a watercourse section that is completely covered over and connects to uncovered watercourses at each end.Unit of Measure: metre",
"The type of mobility of a crane.",
"The type of a crane based on its design and/or method of operation.",
"The predominant species of a crop land.",
"The predominant species of a crop land.",
"The predominant species of a crop land.",
"The agricultural practice(s) in use within an agro-ecosystem.",
"The agricultural practice(s) in use within an agro-ecosystem.",
"The agricultural practice(s) in use within an agro-ecosystem.",
"The general arrangement(s) and/or pattern(s) of farming fields.",
"The general arrangement(s) and/or pattern(s) of farming fields.",
"The general arrangement(s) and/or pattern(s) of farming fields.",
"The method used to supply crops with water.",
"An indication that a field is continuously used for cultivation and permanent irrigation is required due to the natural aridity of the area.",
"The cross-sectional profile of an opening (for example: a tunnel or the space under a bridge span).",
"The type of a culvert based on its shape and fill.",
"The total cumulative length of track contained within the confines of the feature, exclusive of the branch or main trunk lines running into and/or out of the feature.Unit of Measure: metre",
"The radius of curvature of a segment of a feature (or the feature as a whole, if applicable).Unit of Measure: metre",
"The centreline distance measured along the crest of a dam, and in the horizontal plane.Unit of Measure: metre",
"The average distance across the crest of a dam.Unit of Measure: metre",
"The type of slope of the upstream face of a dam.",
"The type of a dam based on function and/or structure.",
"An indication that a body of water is impounded by a dam.",
"A narrative or other textual description that records a general assessment of the quality of a resource (for example: a data instance, a data set or a data processing activity).",
"The number of vertically stacked decks, one over another, in a transportation structure (for example: a bridge or a tunnel).Unit of Measure: unitless",
"The relative level of a deck within a set of vertically stacked decks, one over another, in a transportation structure (for example: on a bridge or in a tunnel).Unit of Measure: unitless",
"The distance measured from ground or water level (uphill/upstream side of the feature) to the deepest point of the feature.Unit of Measure: metre",
"The dimension of a circular, cylindrical, or spherical feature taken from boundary to boundary along a straight line passing through its centre.Unit of Measure: metre",
"The bearing of movement or direction of the flow.Unit of Measure: arcDegree",
"An indication that the lanes or tracks in a land transportation route (for example: a road or a railway), are horizontally separated (for example: by a median strip) and not adjoining.",
"The maximum electrical power generating capacity of a facility.Unit of Measure: megawatt",
"The category of surface for which an elevation is determined.",
"Either the difference between a recorded elevation value and the true elevation referenced to the same vertical datum, expressed as a linear error at 90 percent probability, or the reason that the value is absent.Unit of Measure: metre",
"The type of an embankment based on its use and/or relationship to the surrounding terrain.",
"The type of an engine test cell based on the purpose for which it was designed.",
"The type of an excavation and/or embankment created for the purpose of enhancing the defense of a site from armed attack.",
"The map scale that best represents the density of feature collection within the geospatial extent of a specified region, as a category.",
"The type of an extraction mine.",
"The specification that was used as the basis for defining the digital representation of the feature or data set.",
"The version of the specification that was used as the basis for defining the digital representation of the feature or data set.",
"The status of operation of a man-made structure, as a whole.",
"The type of multiplicity and/or configuration of a feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The purpose(s) of, or intended role(s) served by, the feature.",
"The closure conditions of the two endpoints of a numeric interval.",
"A scale interval within which a feature instance has been determined to be suitable for the purposes of topographic cartography.",
"A scale interval within which a feature instance has been determined to be suitable for the purposes of topographic cartography.",
"The organization responsible for originating (creating) the content of the resource.",
"A general evaluation of the coverage quality of a survey, as a category.",
"The type of a fence based on the type of materials used in its construction.",
"The length of a route in a body of water where a ferry crosses from one shoreline to another.Unit of Measure: metre",
"The type of a ferry crossing based on the maneuverability of the vessel.",
"An indication that a road is designed to support emergency (for example: national defence) use as a runway.",
"An indication that an object is floating.",
"The type of a flood control structure based on its structure and/or intended use.",
"The number of floors in a structure (for example: a building).Unit of Measure: unitless",
"The type of a fog signal based on its signal characteristics and method of generation.",
"The predominant foliage type of the vegetation.",
"The type of a building that is fortified or reinforced to provide for defense from armed attack.",
"The type of a covering of snow and/or ice based on its composition and structure.",
"The type of a gate (or similar route barrier) based on its intended use.",
"A datum describing the relationship of a two-dimensional coordinate system to the Earth.",
"A complete name that is used to designate the entity as that designation would normally be written by the originating culture on a map or chart.",
"A complete name that is used to designate the entity as that designation would normally be written by the originating culture on a map or chart.",
"A complete name that is used to designate the entity as that designation would normally be written by the originating culture on a map or chart.",
"The unique name identifier element in the NGA Geographic Names Data Base (GNDB).",
"The unique name identifier element in the NGA Geographic Names Data Base (GNDB).",
"The unique name identifier element in the NGA Geographic Names Data Base (GNDB).",
"An indication that a geologic fault is visible at the ground surface.",
"The type of a geothermal outlet based on its morphology.",
"The length of a road or railway segment having a significant gradient, specifically greater than or equal to 7 percent (%) for a road or greater than or equal to 3 percent (%) for a railway.Unit of Measure: metre",
"The number of terrain feature sides on which either fill or cut material is exposed.",
"An indication that an object is guided, secured, or steadied by guy wires.",
"Hangar design code.",
"The primary function(s) of harbour facilities that are associated with a service or commercial operation of public interest.",
"The primary function(s) of harbour facilities that are associated with a service or commercial operation of public interest.",
"The primary function(s) of harbour facilities that are associated with a service or commercial operation of public interest.",
"The intended use(s) of a designated hazard protection shelter based on the kind of emergency.",
"The intended use(s) of a designated hazard protection shelter based on the kind of emergency.",
"The intended use(s) of a designated hazard protection shelter based on the kind of emergency.",
"The vertical distance measured from the lowest point of the base of the feature at ground or water level (downhill/downstream side) to the tallest point of the feature.Unit of Measure: metre",
"Either the difference between a recorded height value and the true height referenced to the same ground level, expressed as a linear error at 90 percent probability, or the reason that the value is absent.Unit of Measure: metre",
"The vertical distance measured from the base to the top of the feature that gives the greatest value.Unit of Measure: metre",
"The type of facility or building that is associated with a freestanding helipad.",
"The elevation from a specified vertical datum to the highest point on a feature.Unit of Measure: metre",
"The difference between the recorded elevation of a feature and its true elevation referenced to the same vertical datum expressed as a linear error at 90 percent probability.Unit of Measure: metre",
"A reference surface with respect to which elevations and/or depths are specified.",
"The recognized historic significance of a site and/or facility, if any.",
"An indication that a settled area contains a relatively homogeneous distribution of dwellings.",
"The distance available to pass a load that extends laterally beyond the wheels of a vehicle.Unit of Measure: metre",
"An indication that a feature is significant to maritime safety of navigation and is marked (for example: by a light or beacon) by a maritime-specific navigational aid.",
"The relationship between the feature and surrounding (including covering and/or underlying) water.",
"The type of a hypsographic portrayal line (for example: a contour line) based on the topography represented and/or portrayal interval.",
"The identifier that is assigned to a location in accordance with rules prescribed by the International Civil Aviation Organization (ICAO) in Document 7910.",
"The type of an inland water based on its principal characteristics.",
"The amount of upward inclination between the horizontal surface of the mean water level of a watercourse where it touches the bank and the top of the first usable break in slope, measured at the same point on the upper bank as the military gap width.Unit of Measure: percent",
"The amount of upward inclination between the horizontal surface of the mean water level of a watercourse where it touches the bank and the top of the first usable break in slope, measured at the same point on the upper bank as the military gap width.Unit of Measure: percent",
"The relative orientation of a bank of an inland waterbody based on the direction of predominant water flow in the adjacent waterbody.",
"The relative orientation of a bank of an inland waterbody based on the direction of predominant water flow in the adjacent waterbody.",
"The closure conditions of the two endpoints of a numeric interval.",
"The predominant height (the height of at least 50 percent) of the bank, measured from mean water level to the first break in slope above the mean water level.Unit of Measure: metre",
"The predominant height (the height of at least 50 percent) of the bank, measured from mean water level to the first break in slope above the mean water level.Unit of Measure: metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The predominant height (the height of at least 50 percent) of the bank, measured from mean water level to the first break in slope above the mean water level.Unit of Measure: metre",
"The predominant height (the height of at least 50 percent) of the bank, measured from mean water level to the first break in slope above the mean water level.Unit of Measure: metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The predominant slope (the slope of at least 50 percent) of the bank, measured from mean water level to the first accessible break in slope above the mean water level.Unit of Measure: percent",
"The predominant slope (the slope of at least 50 percent) of the bank, measured from mean water level to the first accessible break in slope above the mean water level.Unit of Measure: percent",
"The closure conditions of the two endpoints of a numeric interval.",
"The predominant slope (the slope of at least 50 percent) of the bank, measured from mean water level to the first accessible break in slope above the mean water level.Unit of Measure: percent",
"The predominant slope (the slope of at least 50 percent) of the bank, measured from mean water level to the first accessible break in slope above the mean water level.Unit of Measure: percent",
"An indication that the delineation of a shoreline is definite.",
"An indication that the delineation of a shoreline is definite.",
"The physical characteristics of a shoreline.",
"The physical characteristics of a shoreline.",
"The height of the waterbody bank above the average water level.Unit of Measure: metre",
"The height of the waterbody bank above the average water level.Unit of Measure: metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The fraction of vegetation cover on the bank of a watercourse.Unit of Measure: percent",
"The fraction of vegetation cover on the bank of a watercourse.Unit of Measure: percent",
"The closure conditions of the two endpoints of a numeric interval.",
"The fraction of vegetation cover on the bank of a watercourse.Unit of Measure: percent",
"The fraction of vegetation cover on the bank of a watercourse.Unit of Measure: percent",
"The name of the company or authority operating an installation.",
"The type of route intersection traffic control based on the method(s) of warning and/or control.",
"The type of route intersection traffic control based on the method(s) of warning and/or control.",
"The type of route intersection traffic control based on the method(s) of warning and/or control.",
"The type of an inundation based on the cause of the flooding.",
"The shape and/or configuration of the land surface as a whole or in a localized area.",
"The distance measured from ground or water level (uphill/upstream side of the feature) to the highest point of a feature located completely underground.Unit of Measure: metre",
"The dimension of a feature taken along its primary alignment of use and generally in the horizontal plane.Unit of Measure: metre",
"The maximum weight that can be safely raised by a lifting device (for example: a crane).Unit of Measure: tonne",
"The arrangement of parallel linear features on a single support structure including both directions (if applicable).",
"The dynamic live load weight-bearing capacity of a bridge or bridge span for one-way, wheeled vehicle traffic in MLC units.Unit of Measure: militaryLoadClass",
"The dynamic live load weight-bearing capacity of a bridge or bridge span for two-way, wheeled vehicle traffic in MLC units.Unit of Measure: militaryLoadClass",
"The dynamic live load weight-bearing capacity of a bridge or bridge span for one-way, tracked vehicle traffic in MLC units.Unit of Measure: militaryLoadClass",
"The dynamic live load weight-bearing capacity of a bridge or bridge span for two-way, tracked vehicle traffic in MLC units.Unit of Measure: militaryLoadClass",
"The feature (for example: a parking garage, storage tank, or a transportation station) is located underground.",
"The location of an object in relation to a land water boundary.",
"The angular difference between True North and Magnetic North measured at a given position and date.Unit of Measure: arcDegree",
"The date and, optionally, time that maintenance, based on a given Extraction Specification, was completed for the features falling within the geospatial extent of a specified region.",
"An indication that a feature is man-made.",
"An indication that a body of water is completely surrounded by a man-made shoreline.",
"An indication that a building is free-standing (detached) and self-contained and is built in a factory and then towed by a tractor to its semi-permanent site.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal by-product(s) of a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The number of flashes/occultations in a group flashing/occulting light character.Unit of Measure: unitless",
"The maximum distance at which a light can be seen (or signal detected) in a homogeneous atmosphere in which the meteorological visibility is 10 nautical miles (clear weather as defined by the International Visibility Code).Unit of Measure: nauticalMile",
"The height of a light measured from a specified datum (for example: vertical or sounding), usually high water, as defined by the National agency.Unit of Measure: metre",
"The time occupied by an entire cycle of intervals of light and eclipse.Unit of Measure: second",
"An indication that a feature is significant to maritime safety of navigation and is marked (for example: by a light or beacon) by a maritime-specific navigational aid.",
"The type of an electronic aid to maritime navigation consisting of a radio transmitter that broadcasts distinctive and/or characteristic signals.",
"The maximum depth of water that the object was designed to hold.Unit of Measure: metre",
"An indication that the lanes or tracks of a divided land transportation route (for example: a road or a railway) are separated by a vertical median barrier.",
"A narrative or other textual description that records observation(s) and/or event(s) associated with a particular subject (for example: a data instance, a data set or a data processing activity).",
"The category(ies) of environmental hazards present in a region that affect military operations.",
"The branch of the armed forces of a nation.",
"The type of a missile site based on the class of missiles it houses.",
"The type of a missile site based on the class of missiles it houses.",
"The type of a missile site based on the class of missiles it houses.",
"An indication that a bridge span moves in some manner to allow passage underneath.",
"An indication that a ferry is propelled across a waterbody by a motor located on either the vessel or the shore.",
"An indication that a building is divided into two or more distinct sets of rooms or other interior spaces that are internally fully-connected while being separated from each other and common areas by controlled access point(s) (for example: lockable doors) that enable physical privacy and security for its occupants.",
"The type of a location that normally does not appear as a specific, characterized object but that has a name that is required to be displayed in association with that location.",
"The type of a natural pool, generally based on its origin.",
"Information about the navigability of a body of water by ocean-going and/or large vessels.",
"An indication that a feature may serve as a navigation landmark, allowing for rapid and positive orientation of a navigator.",
"The season(s) in which a nomadic people are camped at a given location.",
"The season(s) in which a nomadic people are camped at a given location.",
"The season(s) in which a nomadic people are camped at a given location.",
"A narrative or other textual description that records observation(s) and/or event(s) associated with a particular subject (for example: a data instance, a data set or a data processing activity).",
"The type of primary structure of an offshore construction upon which various pieces of operation-specific equipment are affixed.",
"An indication that a thoroughfare is intended to be used only in a single direction.",
"The time(s) during which a feature is usable.",
"The least distance between the travelled way and any obstruction vertically above it.Unit of Measure: metre",
"The type of an overhead obstruction based on its shape, structure and/or intended use.",
"The total number of nominally parallel lines within the feature.Unit of Measure: unitless",
"An indication that a feature is traversable on foot.",
"The month interval in which seasonal restrictions (for example: due to climate) are present.",
"An indication that a feature is permanent.",
"The physical condition of a man-made structure, as a whole, including the inside and/or outside of the structure and any contained and/or associated equipment.",
"The type of a pipeline or pipeline-associated equipment based on structure and/or intended use(s).",
"The type of a pipeline or pipeline-associated equipment based on structure and/or intended use(s).",
"The type of a pipeline or pipeline-associated equipment based on structure and/or intended use(s).",
"An indication that a facility is a port of entry for customs and immigration purposes.",
"The maximum voltage at which a power line is designed to operate.Unit of Measure: kilovolt",
"The energy source(s) employed to generate power for off-site distribution.",
"The energy source(s) employed to generate power for off-site distribution.",
"The energy source(s) employed to generate power for off-site distribution.",
"The average water velocity, exclusive of high water due to runoff or low water due to drought.Unit of Measure: metrePerSecond",
"The predominant depth (the depth of at least 50 percent) of the feature.Unit of Measure: metre",
"The predominant height (the height of at least 50 percent) of the feature measured from the lowest point of the base at ground or water level (downhill side/downstream side).Unit of Measure: metre",
"The average (seasonal) high water depth, exclusive of high water due to runoff or low water due to drought.Unit of Measure: metre",
"The average maximum (seasonal high water) water velocity, exclusive of high water due to runoff or low water due to drought.Unit of Measure: metrePerSecond",
"The average (seasonal) low water depth, exclusive of high water due to runoff or low water due to drought.Unit of Measure: metre",
"The average minimum (seasonal low water) water velocity, exclusive of high water due to runoff or low water due to drought.Unit of Measure: metrePerSecond",
"The predominant height (the height of at least 50 percent) of the vegetation.Unit of Measure: metre",
"The predominant water depth (the depth of at least 50 percent), determined along a bank-to-bank cross section.Unit of Measure: metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The predominant water depth (the depth of at least 50 percent), determined along a bank-to-bank cross section.Unit of Measure: metre",
"The predominant water depth (the depth of at least 50 percent), determined along a bank-to-bank cross section.Unit of Measure: metre",
"A narrative or other textual description of a process step, including related processing parameters and/or tolerances.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The principal product(s) resulting from a production, mining, or agricultural activity.",
"The configuration of a pylon or pole.",
"An indication that an object is guided, secured, or steadied by guy wires.",
"The configuration of a pylon or pole.",
"The primary type of material composing a pylon.",
"The general shape and/or structure of a tower.",
"The primary type of material composing a pylon.",
"The physical mounting and/or configuration of a radar antenna.",
"The primary purpose served by a radar station.",
"The class of a railway based on its importance in the general transportation network.",
"The use(s) to which a railway is put as part of a transportation system.",
"The use(s) to which a railway is put as part of a transportation system.",
"The use(s) to which a railway is put as part of a transportation system.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The principal 'raw', or input, material(s) involved in a production activity.",
"The relationship of the elevation of the terrain surface of or at the base of the feature and that of the surrounding terrain.",
"A designation denoting a religion or system of belief.",
"The type of a facility, building, structure or site that is designed and designated to be used for religious activities, based on its structure and/or the principal activity for which it was designed.",
"The organization responsible for originating (creating) the content of the resource.",
"The highest level of classification applicable to the resource, or a portion of the resource, within the domain of classified national security information.",
"Controls which identify the expansion or limitation on the distribution of the resource.",
"Information security classification markings for a classified resource originating from non-intelligence components of the US Department of Defense or the US Department of Energy.",
"The national government or international organization owner(s) and/or producer(s) of the resource.",
"An indication that a rig is present.",
"An indication that a road serves as a section of a road interchange, providing traffic access from one through road to another, but does not itself carry through traffic.",
"The type of physical arrangement of a road interchange.",
"The type of a roadway based on its design and/or location.",
"The structure of a significant outcropping of exposed rock.",
"The configuration(s) and/or appearance(s) of a roof.",
"The configuration(s) and/or appearance(s) of a roof.",
"The configuration(s) and/or appearance(s) of a roof.",
"An indication that a feature is covered by a roof.",
"The official designation assigned to a route.",
"The official designation assigned to a route.",
"The official designation assigned to a route.",
"The type of designation of a road network according to the nature of service that it is intended to provide, as designated by international, national and/or other administrative authorities.",
"The official type(s) and/or designation(s) assigned to a route.",
"The type of designation of a road network according to the nature of service that it is intended to provide, as designated by international, national and/or other administrative authorities.",
"The official type(s) and/or designation(s) assigned to a route.",
"The type of designation of a road network according to the nature of service that it is intended to provide, as designated by international, national and/or other administrative authorities.",
"The official type(s) and/or designation(s) assigned to a route.",
"The closure conditions of the two endpoints of a numeric interval.",
"The width of a divider that separates adjacent route lanes or tracks in a land transportation route.Unit of Measure: metre",
"The width of a divider that separates adjacent route lanes or tracks in a land transportation route.Unit of Measure: metre",
"The minimum width of the travelled way of a route.Unit of Measure: metre",
"The type of weather conditions under which a road is usable.",
"The minimum width of the travelled way of a route.Unit of Measure: metre",
"The composition(s) of a durable surface (for example: a pavement) intended to sustain ground traffic (for example: vehicular traffic or foot traffic).",
"The total usable width of the travelled way of a route.Unit of Measure: metre",
"The type of a route width constriction based on the nature of the surrounding area.",
"The type of a route width expansion based on the nature of the expansion and/or surrounding area.",
"The designator of the runway that is used to uniquely identify it at an aerodrome.",
"The designator of the runway that is used to uniquely identify it at an aerodrome.",
"The closure conditions of the two endpoints of a numeric interval.",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: percent",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: percent",
"The closure conditions of the two endpoints of a numeric interval.",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: percent",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: percent",
"Minimum safe horizontal distance between adjacent structures on either side of a navigable channel.Unit of Measure: metre",
"The characteristic direction of the steep slope face from the crest of a sand dune.Unit of Measure: arcDegree",
"An indication that the height and location of a sand dune, or area of sand dunes, is unchanging.",
"The type of a sand dune based on its shape and/or structure.",
"The month of the seasonal limit of the presence of ice that poses a hazard to maritime traffic.",
"The Controlled Access Program Coordination Office (CAPCO) authorized abbreviations for sensitive compartmented information control system(s) applicable to the resource.",
"One or more indicators identifying information controlled under the U.S. Atomic Energy Act.",
"The basis for the original classification decision regarding the resource.",
"The identity, by name or personal identifier, and position title of the original classification authority for the resource.",
"The reason that a portion or resource is marked with a higher and/or more restrictive mark than its components would indicate.",
"The year, month and day of publication or release of a resource source, or the most recent resource source, that was itself marked with a declassification constraint.",
"The specific year, month and day for declassification of the resource, based on the duration of the national security sensitivity of the resource, upon the occurrence of which the resource shall be automatically declassified.",
"A description of an event for declassification of the resource, based upon the duration of the national security sensitivity of the resource, upon the occurrence of which the resource shall be automatically declassified.",
"One or more exceptions to the nominal 25-year point for automatic declassification of the resource.",
"The identity, by name or personal identifier, of the derivative classification authority of the resource.",
"Citation of the authoritative source, or reference to multiple sources, of the classification markings used in a resource.",
"One or more indicators identifying the country or countries and/or international organization(s) to which classified information may be displayed based on the determination of an originator in accordance with established foreign disclosure procedures.",
"Indication(s) that the resource qualifies as foreign government information according to CAPCO guidelines for which the source(s) of the information is not concealed.",
"Indication(s) that the resource qualifies as foreign government information according to CAPCO guidelines for which the source(s) of the resource must be concealed when the information is disseminated in ICSIS shared spaces.",
"One or more indicators of the expansion or limitation on the distribution of an information resource or portion within the domain of information originating from non-US components.",
"The country or countries and/or international organization(s) to which the classified resource may be released based on the determination of an originator in accordance with established foreign disclosure procedures.",
"The registered trigraphic or digraphic code(s) for defense or intelligence programs for which resource special access is required.",
"The declassification marking of a source of the resource that causes the current, derivative resource to be exempted from automatic declassification.",
"An indication that a feature (for example: a linear stand of trees) functions as a shelter belt, protecting other features (for example: roads, railways, cropland, and/or structures) from the effects of adverse weather.",
"The type of a shipping container based on its structural characteristics and/or intended use.",
"The type of a shoreline construction (for example: a pier, a wharf, or a quay).",
"An indication that the delineation of a shoreline is definite.",
"The type of a shoreline ramp based on its design and intended use.",
"The physical characteristics of a shoreline.",
"The closure conditions of the two endpoints of a numeric interval.",
"The depth of the soil or unconsolidated surface material.Unit of Measure: metre",
"The depth of the soil or unconsolidated surface material.Unit of Measure: metre",
"The soil type as specified by the Unified Soil Classification System (USCS).",
"General moisture content or condition of a soil.",
"An indication that a marine construction (for example: a pier, wharf, or quay) is solid, thereby blocking the free circulation of water underneath the construction.",
"The date and, optionally, time of collection of the data set that was used to define the digital representation of the feature or data set.",
"A description of the data set that was used to define the digital representation of the feature or data set.",
"The type(s) of the data set(s) that were used to define the digital representation of the feature or data set.",
"An indication that the source data set was used to define the digital representation of the horizontal and possible vertical coordinate values of the resulting feature or data set.",
"The type of dataset and associated process that was used to define the digital representation of the vertical coordinate values of the feature or data set.",
"The date and, optionally, time of collection of the data that was used to define the digital representation of the vertical coordinate values of the digital feature or data set.",
"A description of the data that was used to define the digital representation of the vertical coordinate values of the digital feature or data set.",
"The number of spans in a bridge.Unit of Measure: unitless",
"One or more intended attribute domain values for one or more enumeration or codelist attributes that are not currently valid members of their respective attribute ranges.",
"The maximum vehicle speed legally permitted, expressed in kilometres per hour.Unit of Measure: kilometrePerHour",
"The vertical distance above ground or water level on the upstream side of the dam.Unit of Measure: metre",
"The natural level of the water table in a well, measured with respect to surface level when water is not being actively withdrawn.Unit of Measure: metre",
"The closure conditions of the two endpoints of a numeric interval.",
"The average diameter of the tree trunks in an area, measured at a height of approximately 1.5 metres or 4.5 feet on the high side (if on a hillside) above the surface of the ground.Unit of Measure: metre",
"The average diameter of the tree trunks in an area, measured at a height of approximately 1.5 metres or 4.5 feet on the high side (if on a hillside) above the surface of the ground.Unit of Measure: metre",
"The type of a street sign based on the nature of the information that it displays.",
"The primary type(s) of material composing a feature, exclusive of the surface.",
"The primary type(s) of material composing a feature, exclusive of the surface.",
"The primary type(s) of material composing a feature, exclusive of the surface.",
"An indication that at least 50 percent of the terrain within an area is covered by a large number of vertical structures that are separated by ground-level passageways (for example: walkways, alleys, roads).",
"The geometric form, appearance, and/or configuration of the feature as a whole.",
"The type of an electricity distribution substation based on its function(s).",
"The type of an electricity distribution substation based on its function(s).",
"The type of an electricity distribution substation based on its function(s).",
"An indication that a feature is physically supported by another feature.",
"The object is at least partially supported by, or passes across, a bridge span.",
"The closure conditions of the two endpoints of a numeric interval.",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: percent",
"The slope (rate of upward inclination of the surface from the horizontal) of the surface of a feature (for example: the terrain or a waterbody floor).Unit of Measure: percent",
"The type of a survey point based on the purpose for which it is established.",
"The type of an aircraft taxiway based on its connectivity to other aerodrome ground surfaces.",
"The type of a telescope based on its design, structure and/or intended use.",
"The minimum horizontal bridging distance necessary to cross a channel.Unit of Measure: metre",
"The type of terrain morphology based on composition and/or configuration.",
"The type(s) of material that compose the surface layer of the terrain.",
"The type(s) of material that compose the surface layer of the terrain.",
"The type(s) of material that compose the surface layer of the terrain.",
"The distance between the two opposite surfaces of an object, usually the distance of smallest measure.Unit of Measure: metre",
"An indication that a ground transportation route (for example: road, cart track or trail) is the most direct way through (both into and then out of) a built-up area or populated place.",
"An indication that a waterbody is affected by the tide.",
"The type of structure within which a corpse is entombed based on its method of construction, location, and/or occupancy.",
"The general shape and/or structure of a tower.",
"The type of a tower based on its intended use(s).",
"The type of a tower based on its intended use(s).",
"The type of a tower based on its intended use(s).",
"The distance between a single pair of rails of a railway, measured along the shortest distance from inside rail to inside rail.Unit of Measure: metre",
"The classification of a railway based on the distance between a single pair of rails, measured along the shortest distance from inside rail to inside rail.",
"The method by which electrical power is distributed on a railway, if any.",
"An indication that a railway track is located within the bounds of a roadbed.",
"The type of function, configuration, and/or management of a railway track.",
"The total number of independent, parallel paths (for example: a railway track and/or a road lane) in both directions within a route.Unit of Measure: unitless",
"The reason for traffic restriction based on the nature of the route.",
"The type of a transportation block based on its method of action.",
"The type of a transportation route protection structure based on its configuration and/or intended purpose.",
"The type of a transportation system based on the type(s) of vehicles employed and/or the nature(s) of the objects transported.",
"The type of a transportation system based on the type(s) of vehicles employed and/or the nature(s) of the objects transported.",
"The type of a transportation system based on the type(s) of vehicles employed and/or the nature(s) of the objects transported.",
"The closure conditions of the two endpoints of a numeric interval.",
"The average tree spacing between trees in a stand, determined from centre to centre of adjacent trees.Unit of Measure: metre",
"The average tree spacing between trees in a stand, determined from centre to centre of adjacent trees.Unit of Measure: metre",
"Clearance below bridge, measured from the lowest surface level to the base of the lower of either a cross beam or the lowest bridge deck.Unit of Measure: metre",
"The means by which an underground mine is accessed from the surface.",
"The closure conditions of the two endpoints of a numeric interval.",
"The fraction of land within a defined area that is covered by undergrowth (for example: scrub, brush, and/or bush).Unit of Measure: percent",
"The fraction of land within a defined area that is covered by undergrowth (for example: scrub, brush, and/or bush).Unit of Measure: percent",
"The globally unique and persistent identifier of an entity (for example: feature or event) instance as specified by a Uniform Resource Name (URN) in accordance with the Internet Engineering Task Force (IETF) RFC2396 and RFC2141.",
"The globally unique and persistent identifier of a resource (for example: a dataset or a service) instance as specified by a Uniform Resource Identifier (URI) in accordance with the Internet Engineering Task Force (IETF) RFC2396.",
"The interior length of a structure (for example: an aircraft bunker or a lock).Unit of Measure: metre",
"The interior width of a structure.Unit of Measure: metre",
"The type of a vegetated area based on species, biome, physiography and/or structural organization.",
"The predominant species of a tract of vegetation.",
"The predominant species of a tract of vegetation.",
"The predominant species of a tract of vegetation.",
"The degree of impact of vegetation on trafficability, based on the percent trafficability reduction from a smooth, vegetation-free terrain surface (zero percent reduction).Unit of Measure: percent",
"The type of a vehicle based on its use and/or mode of propulsion.",
"The safe vertical clearance of an object measured from the horizontal plane toward the object overhead.Unit of Measure: metre",
"Information pertaining to ensuring safe vertical clearance for vessels passing under potential overhead obstacles (for example: a bridge).",
"The sounding datum or reference water level from which the safe vertical clearance is specified.",
"The type(s) of material that compose the load-bearing structure and/or exterior facing of a vertical construction (for example: a building or non-building structure).",
"The type(s) of material that compose the load-bearing structure and/or exterior facing of a vertical construction (for example: a building or non-building structure).",
"The type(s) of material that compose the load-bearing structure and/or exterior facing of a vertical construction (for example: a building or non-building structure).",
"A reference surface with respect to which elevations and/or depths are specified.",
"A unique identification code that identifies a feature that is a vertical obstruction to low-level flight.",
"The relationship between the feature and the underlying ground (terrain) or waterbody bottom.",
"The reason(s) that geospatial data was not collected.",
"The reason(s) that geospatial data was not collected.",
"The reason(s) that geospatial data was not collected.",
"The type(s) of geospatial data that were not collected.",
"The type(s) of geospatial data that were not collected.",
"The type(s) of geospatial data that were not collected.",
"The current level of activity of a volcano.",
"The classification by shape of a volcano.",
"The volume of a feature.Unit of Measure: cubicMetre",
"The type of a wall based on structure and/or function.",
"The relationship between the feature and surrounding (including covering and/or underlying) water.",
"The tidal datum to which soundings and drying heights are referenced.",
"The name of the tidal datum to which soundings and drying heights are referenced.",
"The potability of water based on the type of treatment required before it is safe for human consumption.",
"The type of a water race based on its structure and/or intended purpose.",
"The mass of arsenic per volume of solution.Unit of Measure: gramPerCubicMetre",
"The mass of chloride per volume of solution.Unit of Measure: gramPerCubicMetre",
"The number of coliform bacteria colonies per volume of solution.Unit of Measure: unitless",
"The mass of inorganic cyanides per volume of solution.Unit of Measure: gramPerCubicMetre",
"The degree of persistence of water in an inland water body (for example: a spring, a flowing stream, a lake or a pond).",
"The mass of magnesium per volume of solution.Unit of Measure: gramPerCubicMetre",
"The cloudiness or haziness of a volume of solution as determined by its degree of light scattering.Unit of Measure: unitless",
"The mass of sulfate ions per volume of solution.Unit of Measure: gramPerCubicMetre",
"The thermal energy (heat) of a substance.Unit of Measure: degreeCelsius",
"The total mass of dissolved inorganic chemical constituents per volume of solution.Unit of Measure: gramPerCubicMetre",
"The electrical conductivity of water.Unit of Measure: microsiemensPerCentimetre",
"The 'hardness' of a sample of water as determined by the combined mass of calcium carbonate and magnesium carbonate per volume of solution.Unit of Measure: gramPerCubicMetre",
"The potability of water based on the type of treatment required before it is safe for human consumption.",
"The type of available water based on its composition.",
"The logarithm of the reciprocal of hydrogen ion (H+) concentration in gram atoms per liter of an aqueous solution.Unit of Measure: unitless",
"A narrative or other textual description of the screening, casing, and/or finishing of a water well.",
"The distance, measured vertically upward, from the bottom of an inland waterbody to a reference level datum.Unit of Measure: metre",
"An indication that an object is an overhead obstruction over a navigable waterbody.",
"The type of trough-like depression that is normally occupied by a watercourse.",
"The type of a watercourse based on its shape and/or configuration.",
"The type of the sink of a watercourse.",
"The type of a weapons range based on its intended use(s).",
"The type of a weapons range based on its intended use(s).",
"The type of a weapons range based on its intended use(s).",
"The type(s) of equipment attached to or adjacent to a wellbore.",
"The type(s) of equipment attached to or adjacent to a wellbore.",
"The type(s) of equipment attached to or adjacent to a wellbore.",
"The type of a well, generally based on method of construction.",
"The dimension of a feature taken perpendicular to its primary alignment of use and generally in the horizontal plane.Unit of Measure: metre",
"The width of a second travelled way that is the lesser width of the two travelled ways in a divided highway.Unit of Measure: metre",
"The type of a wireless telecommunication service based on the mechanism(s) of transmission and/or the nature of the communication(s) supported.",
"The unique identifier element in the NGA World Port Index (Publication 150)."
};

