/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
#include "share.h"
int UFD1_CLASS_NUM=145;

char *UFD1_class_codes[] = {
"FA001",
"FA000",
"AQ010",
"GB005",
"AK030",
"AK020",
"BB010",
"GB015",
"BH010",
"AL012",
"FA020",
"AK040",
"ZB020",
"DB010",
"BH015",
"ZB030",
"BB041",
"AQ040",
"AL015",
"AL020",
"AL025",
"AK060",
"BH020",
"AP010",
"AQ064",
"DB030",
"AL030",
"AF010",
"BI010",
"BA010",
"AT050",
"AT080",
"AL045",
"AQ060",
"AF030",
"AF040",
"EA010",
"BI020",
"AM010",
"AT010",
"AB000",
"BH030",
"AL060",
"AK070",
"BB090",
"DB090",
"AK090",
"AJ030",
"AL070",
"AQ070",
"BH040",
"FA015",
"BH050",
"AK190",
"AF070",
"BH070",
"BH075",
"AP040",
"AK100",
"AM020",
"EB010",
"BB005",
"GB030",
"GB035",
"AP020",
"BA030",
"BB140",
"BH080",
"BH090",
"BC050",
"BI030",
"ED010",
"SU001",
"AA010",
"AI020",
"AL130",
"DB150",
"ZD040",
"AL135",
"EA030",
"AA052",
"EA040",
"GB045",
"AK120",
"BB190",
"AQ113",
"AL170",
"AD010",
"AT030",
"AT040",
"AC000",
"AQ116",
"AA012",
"AK130",
"AN010",
"AN050",
"AN075",
"AN060",
"BH130",
"BH135",
"AA040",
"BH140",
"BH145",
"AP030",
"AL200",
"GB055",
"EB020",
"GB065",
"BB230",
"AL105",
"AC030",
"AL208",
"BB240",
"BI040",
"AL210",
"AD020",
"BH170",
"AK160",
"AQ125",
"AM060",
"AD030",
"SU002",
"ED020",
"AK170",
"AM070",
"GB075",
"AK050",
"ZD045",
"AL240",
"AP050",
"EC030",
"AQ130",
"AH060",
"AL250",
"AQ135",
"AQ140",
"EA050",
"ZD020",
"AL260",
"BA040",
"AM080",
"AA050",
"AJ050",
"AB010",
"AK180"
};

char *UFD1_class_names[] = {
"Administrative Area",
"Administrative Boundary",
"Aerial Cableway Lines/Ski Lift Lines",
"Airport/Airfield",
"Amusement Park",
"Amusement Park Attraction",
"Anchorage",
"Apron/Hardstand",
"Aqueduct",
"Archeological Site",
"Armistice Line",
"Athletic Field",
"Benchmark",
"Bluff/Cliff/Escarpment",
"Bog",
"Boundary Monument",
"Breakwater",
"Bridge/Overpass/Viaduct",
"Building",
"Built-Up Area",
"Cairn",
"Campground/Campsite",
"Canal",
"Cart Track",
"Causeway",
"Cave",
"Cemetery",
"Chimney/Smokestack",
"Cistern",
"Coastline/Shoreline",
"Communication Building",
"Communication Tower",
"Complex Outline",
"Control Tower",
"Cooling Tower",
"Crane",
"Cropland",
"Dam/Weir",
"Depot (Storage)",
"Disk/Dish",
"Disposal Site/Waste Pile",
"Ditch",
"Dragon Teeth",
"Drive In Theater",
"Drydock",
"Embankment/Fill",
"Fairgrounds",
"Feedlot/Stockyard",
"Fence",
"Ferry Crossing",
"Filtration Beds/Aeration Beds",
"Firing Range/Gunnery Range",
"Fish Hatchery/Fish Farm/Marine Farm",
"Fishing Pier/Promenade Pier",
"Flare Pipe",
"Ford",
"Fountain",
"Gate",
"Golf Course",
"Grain Bin/Silo",
"Grassland",
"Harbor",
"Helicopter Landing Pad",
"Heliport",
"Interchange",
"Island",
"Jetty",
"Lake/Pond",
"Land Subject to Inundation",
"Lighthouse",
"Lock",
"Marsh",
"Military Base",
"Mine",
"Mobile Home/Mobile Home Park",
"Monument",
"Mountain Pass",
"Named Location",
"Native Settlement",
"Nursery",
"Oil/Gas Field",
"Orchard/Plantation",
"Overrun/Stopway",
"Park",
"Pier/Wharf/Quay",
"Pipeline/Pipe",
"Plaza/City Square",
"Power Plant",
"Power Transmission Line",
"Power Transmission Pylon",
"Processing/Treatment Plant",
"Pumping Station",
"Quarry",
"Race Track",
"Railroad",
"Railroad Siding/Railroad Spur",
"Railroad Turntable",
"Railroad Yard/Marshalling Yard",
"Reservoir",
"Rice Field",
"Rig/Superstructure",
"River/Stream",
"River/Stream Vanishing Point",
"Road",
"Ruins",
"Runway",
"Scrub/Brush/Bush",
"Seaplane Base",
"Seawall",
"Settlement",
"Settling Basin/Sludge Pond",
"Shanty Town",
"Slipway/Patent Slip",
"Sluice Gate",
"Snow Shed/Rock Shed",
"Solar Panels",
"Spring/Water Hole",
"Stadium/Amphitheater",
"Station (Miscellaneous)",
"Storage Bunker/Storage Mound",
"Substation/Transformer Yard",
"Subway",
"Swamp",
"Swimming Pool",
"Tank",
"Taxiway",
"Tennis Court(s)",
"Text Description",
"Tower (Non-Communication)",
"Trail",
"Trees",
"Tunnel",
"Underground Bunker",
"Underground Dwelling",
"Vehicle Stopping Area/Rest Area",
"Vehicle Storage/Parking Area",
"Vineyards",
"Void Collection Area",
"Wall",
"Water (Except Inland)",
"Water Tower",
"Well",
"Windmill",
"Wrecking Yard/Scrap Yard",
"Zoo/Safari Park"
};

char *UFD1_class_defns[] = {
"An area controlled by administrative authority.",
"A line of demarcation between controlled areas.",
"Cables which are strung between elevated supports as part of a conveyor system on which cars, buckets, or other carrier units are suspended.  (See also AF020)",
"A defined area of land or water used for landing, take-off, and movement of aircraft including associated buildings and facilities.",
"A predominantly man-made facility equipped with recreational devices.  (See also AK090 and AK120)",
"A large structure located in an Amusement Park.",
"An area of water where vessels anchor or may anchor.",
"A defined paved or hard-packed area at an airport or heliport intended for aircraft parking.",
"A pipe or artificial channel designed to transport water from a remote source, usually by gravity.  (See also BH110)",
"A site or location where remains of ancient civilizations or human activity have been discovered.  (See also AL200)",
"Definition Is Not Available",
"An open area where sporting events, exercises, or games occur.",
"A reference mark on a permanent object indicating elevation relative to an established datum.",
"A steep, vertical, or overhanging face of rock or earth.  (See also DB110)",
"A poorly drained or periodically flooded area, excluding tidal waters, with soil rich in plant residue.",
"A marker identifying the location of a surveyed boundary line.",
"A structure which protects a shore area, harbor, anchorage, or basin from sea waves or swells by preventing them from reaching the protected area or reducing their magnitude.  (See also BB140 and BB042)",
"A man-made structure spanning and providing passage over a body of water, depression, or other obstacles.",
"A relatively permanent structure, roofed and usually walled and designed for some particular use.  (See also AL100)",
"An area containing a concentration of buildings and other structures.",
"A heap of stones piled up as a memorial or a landmark.  (See also AL090 and AL130)",
"A location for camping.  (See also AI020 and AQ140)",
"A man-made or improved natural waterway used for transportation.",
"An unimproved roadway.",
"A raised roadway of solid structure built primarily to provide a route across wet ground or intertidal area.",
"A natural subterranean chamber or series of chambers open to the Earth's surface.",
"An area of land for burying the dead.",
"A vertical structure containing a passage or flue for discharging smoke and gases of combustion.",
"A man-made container used for collection or storage of rain water.",
"The line where a land mass is in contact with a body of water.",
"A building in which communication signals are processed or controlled.",
"A relatively tall structure used for transmitting and/or receiving electronic communication signals.  (See also AQ060)",
"An outline delimiting an area in which two or more like features have the same function.",
"A tower-like structure that houses the persons and equipment used to control the flow of air, rail, or marine traffic.  (See also AL240)",
"A tower used to cool liquids.",
"A machine for lifting, shifting, and lowering objects or materials by means of a swinging boom or with the lifting apparatus supported on an overhead track.",
"An area that has been tilled for the planting of crops.  (See also EA040, EA050, and EA055)",
"A permanent barrier across a watercourse used to impound water or to control its flow.  (See also BI040)",
"An area used for the storage of products or supplies.  (See also AB000)",
"A concave object used for transmitting or receiving electronic signals.",
"A site for the collecting/depositing of refuse or discarded material.  (See also AB010, AM010 and AM040)",
"A channel constructed for the purpose of irrigation or drainage.",
"Regularly spaced concrete or metal barriers laid in single or multiple rows to prevent vehicle movement.",
"A place where motion pictures are shown while viewers remain in their vehicles.",
"A structure, providing support for a vessel, which has a means of removing water so that the bottom of the vessel can be exposed.",
"A raised long mound of earth or other material.  (See also BA051)",
"An area where permanent facilities exist to hold outdoor fairs, circuses or exhibitions.  (See also AK030 and AK120)",
"An enclosed area in which livestock are temporarily kept.",
"A man-made barrier of relatively light structure used as an enclosure or boundary.  (See also AL260)",
"A route in a body of water where a ferry crosses from one shoreline to another.",
"An area containing layers of material used to filter or aerate water.",
"An open area designated for the purpose of discharging or detonating firearms.",
"An enclosure of water used for the breeding and/or rearing of fish.",
"A structure extending into the water used as a platform for recreational purposes, not intended as a berthing place for vessels.",
"An open-ended pipe at which waste gases are burned.",
"A shallow place in a body of water used as a crossing.  (See also AQ062)",
"An artificial spring with water.",
"A barrier which controls passage to a road, railroad, tunnel, or bridge.",
"An area of land laid out for the game of golf.",
"An enclosed container, used for storing grain or fodder.  (See also AM011, AM070, and AM080)",
"An area composed of uncultured plants which have little or no woody tissue.",
"A natural or artificial improved body of water providing protection for vessels and anchorage and docking facilities.",
"An improved area used for take-off, and landing, by helicopters and other vertical take-off and landing aircraft.",
"A place designated for the landing and take-off of helicopters, including its buildings and facilities.",
"A connection designed to provide traffic access from one road to another.",
"A land mass smaller than a continent and surrounded by water.",
"A man-made barrier built out into, or in the water, primarily to restrain or direct currents and waves.  (See also AQ030 and BB040)",
"A body of water surrounded by land.  (See also BH130)",
"An area periodically covered by flood water, excluding tidal waters.  (See also BH095, ED010, and ED020)",
"A distinctive structure exhibiting light(s) designed to serve as an aid to navigation.  (See also BC040)",
"An enclosure with a pair or series of gates used for raising or lowering vessels as they pass from one water level to another.  (See also BI005)",
"An area of wet, often spongy ground that is subject to frequent or tidal inundations, but not considered to be continually under water.  It is characterized by the growth of non woody plants and by the lack of trees.  (Nautical Chart Manual, US National Oceanic and Atmospheric Administration - NOAA, 1992)  (See also BH090, BH095, and ED020)",
"A center of operations for a military organization.",
"An excavation made in the earth for the purpose of extracting natural deposits.  (See also AQ090)",
"A site for the permanent parking of trailer(s) used as dwellings and designed without a permanent foundation.  (See also AK060 and AQ140)",
"A structure erected or maintained as a memorial to a person or event.  (See also AL025 and AL090)",
"A natural route through a low place in a mountain range.",
"A geographic place on the earth, not normally appearing as a feature on a map, but having a name that is required to be placed on a map.",
"A concentration of native dwellings, generally of the hut type, which are not usually of substantial construction.",
"A place where shrubs, flowers, plants and trees are grown for transplanting, seed or grafting.",
"An area where oil and/or gas is pumped or otherwise removed from the ground.",
"An area covered by systematic plantings of trees which yield fruits, nuts or other products.  (See also EA010, EA050 and EA055)",
"An area beyond the take-off runway designated as able to support an airplane during an aborted take-off.",
"An area used for recreational or ornamental purposes.  (See also AK030, AK090 and AL170)",
"A structure primarily used as berthing places for vessels.",
"A tube for the conveyance of solids, liquids or gases.",
"An open area which serves as a public square in a city or town.  (See also AK120)",
"The building(s) and equipment necessary for the generation of electric power.  (See also AD020)",
"A system of above ground wires including their supports, which transmits electricity over distance.  (See also AT005, AT006 and AT060)",
"A pylon or pole used to support a power transmission line.",
"A site used for changing or refining a particular material.",
"A facility to move solids, liquids or gases by means of pressure or suction.",
"An excavation created by removal of stone by blasting or cutting.",
"A course for racing.",
"A rail or set of parallel rails on which a train or tram runs.",
"A stretch of railroad tracks connected to the main track by switch(es) - used for temporary storage and loading/unloading.",
"A rotating platform with railroad tracks used for turning locomotives or cars/carriages.",
"A system of tracks within defined limits, and associated features, provided for loading/unloading and assembling trains.",
"A man-made enclosure or area formed for the storage of water.  (See also BH080)",
"An area periodically covered with water used for growing rice.",
"A vertical structure fitted for drilling or lifting operations.",
"A natural flowing watercourse.",
"Point at which a river or stream passes into the ground.",
"An open way maintained for vehicular use.",
"The deteriorated remains of an unspecified structure.  (See also AL012)",
"A defined area, usually rectangular, used for the conventional landing and take-off of aircraft.  (Excludes GB045)",
"Low-growing woody plants.  (See also EC030)",
"An installation supporting aircraft capable of taking off and landing on water.",
"A structure built to protect the shore from erosion.",
"A concentration of small dwellings.",
"A site where solid matter is precipitated from a liquid by evaporating or settling.",
"A dense concentration of crude, improvised dwellings made from salvaged materials, usually located on the outskirts of cities and having few, if any, streets and no public facilities.",
"A prepared slope for launching and recovering vessels.",
"A gate used to regulate the flow of water.  (See also BI020 and BI039)",
"A shelter build to protect a section of road or railroad from snow/rock slides.",
"Units of solar cells for converting sunlight into electrical energy or heat.  (See also AD010)",
"A natural outflow of water from below the ground surface.  (See also AA050 and BH075)",
"An arena for holding and viewing events.",
"A stopping place for the transfer of passengers and/or freight.",
"A structure which may be covered or surrounded with earth which is resistant to ordnance where materials or products are stored.  (See also AH050)",
"A facility, along a power line route, in which electric current is transformed and/or distributed.",
"An underground, metropolitan electric railway or the tunnel through which it travels.",
"A low lying saturated area covered with water all or most of the year, where accumulating dead vegetation does not rapidly decay.  It can exist on flat-lying areas created by certain geomorphic environments.  The vegetation mainly consists of hydrophytic trees and/or scrubs whose roots are adapted to wet conditions, with an open to very dense canopy closure.  (See also BH090, BH095, and ED010)",
"A constructed basin used for swimming outdoors.",
"A container used for the storage of liquids or gases.  (See also AM011, AM020, and AM080)",
"A prepared surface providing access to/from runways and the aircraft parking area, terminal area, or service area, etc.",
"An area or site used for the sport of tennis.",
"An area in which a characteristic or an activity pertaining to the area can be described and possibly labeled on a product if deemed important at the time the product is being produced.",
"A relatively tall structure which may be used for observation, support, or storage, etc.  (See also AF030, AM080, AQ060, and BI050)",
"A path worn by the passage of people or animals.",
"Woody-perennial plants, having a self-supporting main stem or trunk.  (See also EA040, EB020 and EC015)",
"An underground or underwater passage, open at both ends, and usually containing a road or railroad.  (See also AQ090)",
"An underground facility used by the military either for location of command/control centers or for troop encampment.  (See also AL250)",
"Underground living quarters.  (See also AL040)",
"A roadside place usually having facilities for people and/or vehicles.",
"An open land area used for storing or parking vehicles or vessels (including recreational vehicles).  (See also AI020 and AK060)",
"An area covered by the systematic planting of grape vines.  (See also EA010, EA040 and EA055)",
"An area lacking suitable source coverage, or where data is not required.",
"A solid man-made barrier of heavy material used as an enclosure or boundary or for protection.  (See also AL070)",
"An area of water which normally has tidal fluctuations.",
"An elevated container and its supporting structure used to hold water.  (See also AM011, AM020, and AM070)",
"A hole drilled or dug into the earth or sea bed for the extraction of liquids or gases.  (See also BH170)",
"A wind-driven system of vanes attached to a tower like structure (excluding wind-generated power plants).",
"An area or site engaged in the wrecking, dismantling, storage, or resale of discarded products.  (See also AB000)",
"An area with a collection of live animals usually for public display."
};

unsigned char UFD1DOMAINS[]={
0  /*** Dummy Value ***/,
D_BOUN  /*** Administrative Area ***/,
D_BOUN  /*** Administrative Boundary ***/,
D_POPU  /*** Aerial Cableway Lines/Ski Lift Lines ***/,
D_AERO  /*** Airport/Airfield ***/,
D_POPU  /*** Amusement Park ***/,
D_POPU  /*** Amusement Park Attraction ***/,
D_OCEN  /*** Anchorage ***/,
D_AERO  /*** Apron/Hardstand ***/,
D_INWA  /*** Aqueduct ***/,
D_POPU  /*** Archeological Site ***/,
D_GENE  /*** Armistice Line ***/,
D_POPU  /*** Athletic Field ***/,
D_ELEV  /*** Benchmark ***/,
D_PHYS  /*** Bluff/Cliff/Escarpment ***/,
D_VEGE  /*** Bog ***/,
D_BOUN  /*** Boundary Monument ***/,
D_POAN  /*** Breakwater ***/,
D_GRTR  /*** Bridge/Overpass/Viaduct ***/,
D_POPU  /*** Building ***/,
D_POPU  /*** Built-Up Area ***/,
D_BOUN  /*** Cairn ***/,
D_POPU  /*** Campground/Campsite ***/,
D_INWA  /*** Canal ***/,
D_GRTR  /*** Cart Track ***/,
D_GRTR  /*** Causeway ***/,
D_PHYS  /*** Cave ***/,
D_POPU  /*** Cemetery ***/,
D_UTAN  /*** Chimney/Smokestack ***/,
D_INWA  /*** Cistern ***/,
D_PHYS  /*** Coastline/Shoreline ***/,
D_UTAN  /*** Communication Building ***/,
D_UTAN  /*** Communication Tower ***/,
D_GENE  /*** Complex Outline ***/,
D_POPU  /*** Control Tower ***/,
D_UTAN  /*** Cooling Tower ***/,
D_UTAN  /*** Crane ***/,
D_VEGE  /*** Cropland ***/,
D_INWA  /*** Dam/Weir ***/,
D_UTAN  /*** Depot (Storage) ***/,
D_UTAN  /*** Disk/Dish ***/,
D_UTAN  /*** Disposal Site/Waste Pile ***/,
D_INWA  /*** Ditch ***/,
D_DEST  /*** Dragon Teeth ***/,
D_POPU  /*** Drive In Theater ***/,
D_POAN  /*** Drydock ***/,
D_PHYS  /*** Embankment/Fill ***/,
D_POPU  /*** Fairgrounds ***/,
D_UTAN  /*** Feedlot/Stockyard ***/,
D_POPU  /*** Fence ***/,
D_GRTR  /*** Ferry Crossing ***/,
D_UTAN  /*** Filtration Beds/Aeration Beds ***/,
D_BOUN  /*** Firing Range/Gunnery Range ***/,
D_INWA  /*** Fish Hatchery/Fish Farm/Marine Farm ***/,
D_POAN  /*** Fishing Pier/Promenade Pier ***/,
D_UTAN  /*** Flare Pipe ***/,
D_GRTR  /*** Ford ***/,
D_POPU  /*** Fountain ***/,
D_GRTR  /*** Gate ***/,
D_POPU  /*** Golf Course ***/,
D_UTAN  /*** Grain Bin/Silo ***/,
D_VEGE  /*** Grassland ***/,
D_POAN  /*** Harbor ***/,
D_AERO  /*** Helicopter Landing Pad ***/,
D_AERO  /*** Heliport ***/,
D_GRTR  /*** Interchange ***/,
D_PHYS  /*** Island ***/,
D_POAN  /*** Jetty ***/,
D_INWA  /*** Lake/Pond ***/,
D_INWA  /*** Land Subject to Inundation ***/,
D_AITO  /*** Lighthouse ***/,
D_INWA  /*** Lock ***/,
D_VEGE  /*** Marsh ***/,
D_DEST  /*** Military Base ***/,
D_UTAN  /*** Mine ***/,
D_POPU  /*** Mobile Home/Mobile Home Park ***/,
D_POPU  /*** Monument ***/,
D_PHYS  /*** Mountain Pass ***/,
D_GENE  /*** Named Location ***/,
D_POPU  /*** Native Settlement ***/,
D_VEGE  /*** Nursery ***/,
D_UTAN  /*** Oil/Gas Field ***/,
D_VEGE  /*** Orchard/Plantation ***/,
D_AERO  /*** Overrun/Stopway ***/,
D_POPU  /*** Park ***/,
D_POAN  /*** Pier/Wharf/Quay ***/,
D_UTAN  /*** Pipeline/Pipe ***/,
D_POPU  /*** Plaza/City Square ***/,
D_UTAN  /*** Power Plant ***/,
D_UTAN  /*** Power Transmission Line ***/,
D_UTAN  /*** Power Transmission Pylon ***/,
D_UTAN  /*** Processing/Treatment Plant ***/,
D_UTAN  /*** Pumping Station ***/,
D_UTAN  /*** Quarry ***/,
D_POPU  /*** Race Track ***/,
D_GRTR  /*** Railroad ***/,
D_GRTR  /*** Railroad Siding/Railroad Spur ***/,
D_GRTR  /*** Railroad Turntable ***/,
D_GRTR  /*** Railroad Yard/Marshalling Yard ***/,
D_INWA  /*** Reservoir ***/,
D_VEGE  /*** Rice Field ***/,
D_UTAN  /*** Rig/Superstructure ***/,
D_INWA  /*** River/Stream ***/,
D_INWA  /*** River/Stream Vanishing Point ***/,
D_GRTR  /*** Road ***/,
D_POPU  /*** Ruins ***/,
D_AERO  /*** Runway ***/,
D_VEGE  /*** Scrub/Brush/Bush ***/,
D_AERO  /*** Seaplane Base ***/,
D_POAN  /*** Seawall ***/,
D_POPU  /*** Settlement ***/,
D_UTAN  /*** Settling Basin/Sludge Pond ***/,
D_POPU  /*** Shanty Town ***/,
D_POAN  /*** Slipway/Patent Slip ***/,
D_INWA  /*** Sluice Gate ***/,
D_GRTR  /*** Snow Shed/Rock Shed ***/,
D_UTAN  /*** Solar Panels ***/,
D_INWA  /*** Spring/Water Hole ***/,
D_POPU  /*** Stadium/Amphitheater ***/,
D_GRTR  /*** Station (Miscellaneous) ***/,
D_UTAN  /*** Storage Bunker/Storage Mound ***/,
D_UTAN  /*** Substation/Transformer Yard ***/,
D_GRTR  /*** Subway ***/,
D_VEGE  /*** Swamp ***/,
D_POPU  /*** Swimming Pool ***/,
D_UTAN  /*** Tank ***/,
D_AERO  /*** Taxiway ***/,
D_POPU  /*** Tennis Court(s) ***/,
D_GENE  /*** Text Description ***/,
D_UTAN  /*** Tower (Non-Communication) ***/,
D_GRTR  /*** Trail ***/,
D_VEGE  /*** Trees ***/,
D_GRTR  /*** Tunnel ***/,
D_DEST  /*** Underground Bunker ***/,
D_POPU  /*** Underground Dwelling ***/,
D_GRTR  /*** Vehicle Stopping Area/Rest Area ***/,
D_GRTR  /*** Vehicle Storage/Parking Area ***/,
D_VEGE  /*** Vineyards ***/,
D_GENE  /*** Void Collection Area ***/,
D_POPU  /*** Wall ***/,
D_OCEN  /*** Water (Except Inland) ***/,
D_UTAN  /*** Water Tower ***/,
D_INWA  /*** Well ***/,
D_UTAN  /*** Windmill ***/,
D_UTAN  /*** Wrecking Yard/Scrap Yard ***/,
D_POPU  /*** Zoo/Safari Park ***/
};

int UFD1DOMAINSLEN = sizeof(UFD1DOMAINS)/ sizeof(unsigned char);

unsigned char UFD1STRATS[]={
0  /*** Dummy Value ***/,
S_APPL  /*** Administrative Area ***/,
S_APPL  /*** Administrative Boundary ***/,
S_APPL  /*** Aerial Cableway Lines/Ski Lift Lines ***/,
S_APPL  /*** Airport/Airfield ***/,
S_APPL  /*** Amusement Park ***/,
S_APPL  /*** Amusement Park Attraction ***/,
S_APPL  /*** Anchorage ***/,
S_APPL  /*** Apron/Hardstand ***/,
S_APPL  /*** Aqueduct ***/,
S_APPL  /*** Archeological Site ***/,
S_APPL  /*** Armistice Line ***/,
S_APPL  /*** Athletic Field ***/,
S_APPL  /*** Benchmark ***/,
S_APPL  /*** Bluff/Cliff/Escarpment ***/,
S_APPL  /*** Bog ***/,
S_APPL  /*** Boundary Monument ***/,
S_APPL  /*** Breakwater ***/,
S_APPL  /*** Bridge/Overpass/Viaduct ***/,
S_APPL  /*** Building ***/,
S_APPL  /*** Built-Up Area ***/,
S_APPL  /*** Cairn ***/,
S_APPL  /*** Campground/Campsite ***/,
S_APPL  /*** Canal ***/,
S_APPL  /*** Cart Track ***/,
S_APPL  /*** Causeway ***/,
S_APPL  /*** Cave ***/,
S_APPL  /*** Cemetery ***/,
S_APPL  /*** Chimney/Smokestack ***/,
S_APPL  /*** Cistern ***/,
S_APPL  /*** Coastline/Shoreline ***/,
S_APPL  /*** Communication Building ***/,
S_APPL  /*** Communication Tower ***/,
S_APPL  /*** Complex Outline ***/,
S_APPL  /*** Control Tower ***/,
S_APPL  /*** Cooling Tower ***/,
S_APPL  /*** Crane ***/,
S_APPL  /*** Cropland ***/,
S_APPL  /*** Dam/Weir ***/,
S_APPL  /*** Depot (Storage) ***/,
S_APPL  /*** Disk/Dish ***/,
S_APPL  /*** Disposal Site/Waste Pile ***/,
S_APPL  /*** Ditch ***/,
S_APPL  /*** Dragon Teeth ***/,
S_APPL  /*** Drive In Theater ***/,
S_APPL  /*** Drydock ***/,
S_APPL  /*** Embankment/Fill ***/,
S_APPL  /*** Fairgrounds ***/,
S_APPL  /*** Feedlot/Stockyard ***/,
S_APPL  /*** Fence ***/,
S_APPL  /*** Ferry Crossing ***/,
S_APPL  /*** Filtration Beds/Aeration Beds ***/,
S_APPL  /*** Firing Range/Gunnery Range ***/,
S_APPL  /*** Fish Hatchery/Fish Farm/Marine Farm ***/,
S_APPL  /*** Fishing Pier/Promenade Pier ***/,
S_APPL  /*** Flare Pipe ***/,
S_APPL  /*** Ford ***/,
S_APPL  /*** Fountain ***/,
S_APPL  /*** Gate ***/,
S_APPL  /*** Golf Course ***/,
S_APPL  /*** Grain Bin/Silo ***/,
S_APPL  /*** Grassland ***/,
S_APPL  /*** Harbor ***/,
S_APPL  /*** Helicopter Landing Pad ***/,
S_APPL  /*** Heliport ***/,
S_APPL  /*** Interchange ***/,
S_APPL  /*** Island ***/,
S_APPL  /*** Jetty ***/,
S_APPL  /*** Lake/Pond ***/,
S_APPL  /*** Land Subject to Inundation ***/,
S_APPL  /*** Lighthouse ***/,
S_APPL  /*** Lock ***/,
S_APPL  /*** Marsh ***/,
S_APPL  /*** Military Base ***/,
S_APPL  /*** Mine ***/,
S_APPL  /*** Mobile Home/Mobile Home Park ***/,
S_APPL  /*** Monument ***/,
S_APPL  /*** Mountain Pass ***/,
S_APPL  /*** Named Location ***/,
S_APPL  /*** Native Settlement ***/,
S_APPL  /*** Nursery ***/,
S_APPL  /*** Oil/Gas Field ***/,
S_APPL  /*** Orchard/Plantation ***/,
S_APPL  /*** Overrun/Stopway ***/,
S_APPL  /*** Park ***/,
S_APPL  /*** Pier/Wharf/Quay ***/,
S_APPL  /*** Pipeline/Pipe ***/,
S_APPL  /*** Plaza/City Square ***/,
S_APPL  /*** Power Plant ***/,
S_APPL  /*** Power Transmission Line ***/,
S_APPL  /*** Power Transmission Pylon ***/,
S_APPL  /*** Processing/Treatment Plant ***/,
S_APPL  /*** Pumping Station ***/,
S_APPL  /*** Quarry ***/,
S_APPL  /*** Race Track ***/,
S_APPL  /*** Railroad ***/,
S_APPL  /*** Railroad Siding/Railroad Spur ***/,
S_APPL  /*** Railroad Turntable ***/,
S_APPL  /*** Railroad Yard/Marshalling Yard ***/,
S_APPL  /*** Reservoir ***/,
S_APPL  /*** Rice Field ***/,
S_APPL  /*** Rig/Superstructure ***/,
S_APPL  /*** River/Stream ***/,
S_APPL  /*** River/Stream Vanishing Point ***/,
S_APPL  /*** Road ***/,
S_APPL  /*** Ruins ***/,
S_APPL  /*** Runway ***/,
S_APPL  /*** Scrub/Brush/Bush ***/,
S_APPL  /*** Seaplane Base ***/,
S_APPL  /*** Seawall ***/,
S_APPL  /*** Settlement ***/,
S_APPL  /*** Settling Basin/Sludge Pond ***/,
S_APPL  /*** Shanty Town ***/,
S_APPL  /*** Slipway/Patent Slip ***/,
S_APPL  /*** Sluice Gate ***/,
S_APPL  /*** Snow Shed/Rock Shed ***/,
S_APPL  /*** Solar Panels ***/,
S_APPL  /*** Spring/Water Hole ***/,
S_APPL  /*** Stadium/Amphitheater ***/,
S_APPL  /*** Station (Miscellaneous) ***/,
S_APPL  /*** Storage Bunker/Storage Mound ***/,
S_APPL  /*** Substation/Transformer Yard ***/,
S_APPL  /*** Subway ***/,
S_APPL  /*** Swamp ***/,
S_APPL  /*** Swimming Pool ***/,
S_APPL  /*** Tank ***/,
S_APPL  /*** Taxiway ***/,
S_APPL  /*** Tennis Court(s) ***/,
S_APPL  /*** Text Description ***/,
S_APPL  /*** Tower (Non-Communication) ***/,
S_APPL  /*** Trail ***/,
S_APPL  /*** Trees ***/,
S_APPL  /*** Tunnel ***/,
S_APPL  /*** Underground Bunker ***/,
S_APPL  /*** Underground Dwelling ***/,
S_APPL  /*** Vehicle Stopping Area/Rest Area ***/,
S_APPL  /*** Vehicle Storage/Parking Area ***/,
S_APPL  /*** Vineyards ***/,
S_APPL  /*** Void Collection Area ***/,
S_APPL  /*** Wall ***/,
S_APPL  /*** Water (Except Inland) ***/,
S_APPL  /*** Water Tower ***/,
S_APPL  /*** Well ***/,
S_APPL  /*** Windmill ***/,
S_APPL  /*** Wrecking Yard/Scrap Yard ***/,
S_APPL  /*** Zoo/Safari Park ***/
};

int UFD1STRATSLEN = sizeof(UFD1STRATS)/ sizeof(unsigned char);


