/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
int UFD2_ATTR_NUM=161;

char *UFD2_attr_codes[] = {
"ACE",
"ACE_EVAL_METHOD_CD",
"ALE",
"ALE_EVAL_METHOD_CD",
"ACC",
"ORIGINATOR",
"ATN",
"APT",
"ZV3",
"AOO",
"ATC",
"BE_NUMBER",
"BST",
"BOT",
"BSM",
"BSC",
"BUD",
"BFC",
"BAC",
"BCC",
"CAB",
"COD",
"COE",
"SEC_CLS_AUTHORITY",
"COMMENTS",
"COMM_CPYRT_NOTICE",
"COMPLETENESS_CODE",
"COF",
"COC",
"CRM",
"CRA",
"CET",
"DFT",
"DMT",
"DEP",
"DOF",
"COMM_LIC_TIER_NOTICE",
"EBT",
"EXS",
"SPEC_ID",
"FTP",
"FPT",
"FTC",
"FCO",
"CREATION_DATE",
"SCALE",
"FTI",
"FCL",
"FER",
"FRT",
"GTC",
"GAW",
"GFID",
"SGC",
"GUG",
"HGT",
"ZV2",
"HWT",
"HYC",
"HFC",
"IKO",
"IWO",
"KVA",
"LMC",
"LEN",
"LEG",
"LFA",
"LC1",
"LC2",
"LC3",
"LC4",
"LOC",
"MAC",
"MCC",
"MCS",
"MVC",
"MED",
"MWG",
"WD1",
"MIN",
"MST",
"SEC_CLS_AUTH_MULT",
"NAM",
"NM3",
"NM4",
"NFN",
"NFI",
"NST",
"SEC_CLS_AUTH_DESC",
"NPL",
"OPERATOR",
"ORIG_SOURCE_DATE",
"ORIG_SOURCE_INFO",
"ORIGINATING_SOURCE",
"OWO",
"OHB",
"OHC",
"OCC",
"PRM",
"PPT",
"PPC",
"PFG",
"PHT",
"VH3",
"PRO",
"RSA",
"RRC",
"RGC",
"RRA",
"REL",
"RSTRN_FOREIGN_GOV",
"RSTRN_DECLASS",
"RSTRN_DCLS_XMPT_CD",
"RSTRN_DSEM_CTRL_IC",
"RSTRN_DSEM_CTRL_NIC",
"RSTRN_RELEASIBILITY",
"RIT",
"RST",
"RTT",
"RTN",
"SDO",
"SEC_CLASS",
"SEC_CLASS_SYS_ID",
"SEC_CD_CNTRL",
"YSU",
"SHP",
"SLT",
"SWC",
"SCC",
"SSC",
"SSR",
"SCB",
"SMC",
"TXT",
"TID",
"TTC",
"LTN",
"TRF",
"TST",
"TUC",
"TRA",
"TRE",
"UPDATE_SOURCE_DATE",
"UPDATE_SOURCE_INFO",
"UPDATE_SOURCE",
"USG",
"VEG",
"VDC",
"VDR",
"VRR",
"VCA",
"VCT",
"VGT",
"WTC",
"WFT",
"SWT",
"WID",
"WOC",
"WT2",
"WGP",
"Z_VALUE_TYPE"
};

char *UFD2_attr_names[] = {
"Absolute Circular Error",
"Absolute Circular Error Evaluation Method",
"Absolute Linear Error",
"Absolute Linear Error Evaluation Method",
"Accuracy Category",
"Agency that Supplied the Data",
"Aids to Navigation",
"Airfield Type",
"Airfield/Aerodrome elevation",
"Angle of Orientation",
"Aqueduct Type Category",
"Basic Encyclopedia Number",
"Boundary Status Type",
"Bridge Opening Type",
"Bridge Span Mobility",
"Bridge/Bridge Superstructure Category",
"Brush/Undergrowth Density Code",
"Building Function Category",
"Built-Up Area Classification",
"Bypass Condition Category",
"Cable Classification",
"Certainty of Delineation",
"Certainty of Existence",
"Classification Authority",
"Comments",
"Commercial Copyright Notice",
"Completeness Code",
"Complex Outline Function",
"Conspicuous Category",
"Crane Mobility Type",
"Crane Type Category",
"Cut/Embankment Type Category",
"Dam Face Type",
"Density Measure (% of Tree/Canopy Cover)",
"Depth Below Surface Level",
"Direction of Flow",
"Distribution of Commercial Data",
"Educational Building Type",
"Existence Category",
"Extraction Specification ID",
"Fabrication Type",
"Facility Priority Type",
"Farming Type Category",
"Feature Configuration",
"Feature Creation Date",
"Feature Scale (e.g., 50000, 100000)",
"Fence Type Indicator",
"Ferry Crossing Length",
"Ferry Type",
"Firing Range Type",
"Gate Type Category",
"Gauge Width",
"Global Feature ID",
"Gradient/Slope",
"Guyed or Unguyed Category",
"Height Above Surface Level",
"Highest Z-Value",
"House of Worship Type",
"Hydrological Category",
"Hydrological Form Category",
"ICAO Designator",
"Inland Water Obstruction",
"Kilovolt Capacity Attribute",
"Landmark Category",
"Length/Diameter",
"Length/Diameter in Meters With Greater Precision",
"Light Function Aeronautical",
"Load Class Type 1",
"Load Class Type 2",
"Load Class Type 3",
"Load Class Type 4",
"Location Category",
"Maritime Area Category",
"Material Composition Category",
"Material Composition Secondary",
"Maximum Vertical Clearance",
"Median Category",
"Median Width with greater than 1 meter resolution",
"Minimum Traveled Way Width",
"Mining Category",
"Missile Site Type",
"Multiple Classification Authority Sources",
"Name",
"Name 3",
"Name 4",
"Name Identifier",
"Named Feature Identifier",
"Navigation System Types",
"Non-standard Classification Authority",
"Number of Parallel Lines",
"Operator ID",
"Originating Source Date",
"Originating Source Information",
"Originating Source Name",
"Over Water Obstruction",
"Overall Height of Bridge",
"Overhead Clearance Category",
"Overhead Clearance Category Code",
"Permanency",
"Populated Place Type",
"Power Plant Category",
"Predominant Feature Height With greater than 1 meter resolution",
"Predominant Height",
"Predominant Vegetation Height Range (3)",
"Product Category",
"Rail Siding/Spur Attribute",
"Railroad Categories",
"Railroad Gauge Category",
"Railroad Power Source",
"Religious Denomination",
"Restrctions on Foreign Government Access",
"Restriction Declassification",
"Restriction Declassification Exemptions",
"Restrictions on Dissemination Control IC",
"Restrictions on Dissemination Control Non-IC",
"Restrictions on Releasibility",
"Road Interchange Type",
"Road/Runway Surface Type",
"Route Intended Use",
"Route Number",
"Sand Dune Orientation",
"Security Classification",
"Security Classification System Identifier",
"Security Codeword Control",
"Service Branch",
"Shape of Beacon",
"Shoreline Type Category",
"Soil Wetness Condition",
"Spring/Well Characteristic Category",
"Structure Shape Category",
"Structure Shape of Roof",
"Surface Condition Attribute",
"Surface Material Category",
"Text Attribute",
"Tidal/Non-Tidal Category",
"Tower Type Category",
"Track/Lane Number",
"Traffic Flow",
"Transmission Line Suspension",
"Transportation Use Category",
"Traversability",
"Tree Type Category",
"Update/Review Source Date",
"Update/Review Source Information",
"Update/Review Source Name",
"Usage",
"Vegetation Characteristics",
"Vertical (Sounding) Datum Category",
"Vertical Datum Record",
"Vertical Reference Category",
"Void Collection Attribute",
"Void Collection Type",
"Volcanic Geologic Type",
"Weather Type Category",
"Well Feature Type",
"Well/Spring Feature Type",
"Width",
"Width of Crest",
"Width of Second Traveled Way",
"Width with greater than 1 meter resolution",
"Z-Coordinate Type"
};

char *UFD2_attr_types[] = {
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Integer",
"Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Float",
"Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Date",
"Long Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"String",
"Integer",
"Short Integer",
"Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Integer",
"Short Integer",
"Integer",
"Float",
"Short Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Float",
"Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"String",
"Integer",
"String",
"Date",
"String",
"Short Integer",
"Short Integer",
"Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Date",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Float",
"Float",
"Float",
"Short Integer"
};

char *UFD2_attr_defns[] = {
"The absolute horizontal accuracy of the data's coordinates",
"The code that indicates the method by which the absolute circular error was derived.",
"The absolute vertical accuracy of the data's coordinates",
"The code that indicates the method by which the absolute linear error was derived.",
"Accuracy of geographic position.",
"This field is used to describe the organization or agency with which the originating author/creator of the data is associated.",
"Indicates whether a feature is marked or unmarked by an aid to navigation.",
"Unique airfield type.",
"The highest point of an airport's usable runways measured in meters from mean sea level.",
"The angular distance measured from true north (0 deg) clockwise to the major axis of the feature. If the feature is square",
"Type of aqueduct.",
"Unique number associated with a feature which is used to identify the feature in other national or intelligence data bases.",
"Identifies the status of a boundary.",
"The type of structure or mechanism by which a portion of a bridge is moved to allow passage of a vessel.",
"Identifies bridge spans that move in some manner allowing passage underneath the span.",
"Structural design characteristics.",
"Density of brush or undergrowth.",
"Type or purpose of the building.",
"The indication of the relative density of the Built-Up Area.",
"The ease or ability to circumvent a destroyed section of bridge",
"Classifies the function of a cable.",
"Indicates knowledge of the feature's limits or information.",
"Indicates knowledge of the feature's existence.",
"The code that represents the type of classification authority used to derive a classification for data.",
"An open text field for additional information.",
"This field is used when a data set includes commercial products or any other copyrighted data. Example: Copyright 2000 Space Imaging",
"Identifies if the extraction is 100% complete IAW the specification identified in the SPEC_ID attribute.",
"The primary functional use of the area covered by an AL045 Complex Outline feature.  (See use and attribute values below.)",
"A conspicuous object is easily identifiable and plainly visible under varying conditions of light from harbours",
"Indicates the mobility of a crane type.  (See CRA.)",
"Type of crane.",
"Identifies the number of sides that are used as a cut or an embankment.",
"Type of face of a dam.",
"Canopy cover measured by percent within area of feature during the summer season.",
"Distance measured from the highest point at surface level to the lowest point of the feature below the surface. Recorded values are positive numbers.",
"Bearing of movement or direction of the flow.",
"This field is used to identify the distribution of commercial or other restricted data.",
"Identifies the type of educational building.",
"The state or condition of the feature.",
"The particular specification that was used for the extraction process.",
"Denotes the type of fabrication industry as light or heavy.  Light fabrication industries are characterized by light steel or woodframe buildings and lack heavy equipment.  Heavy fabrication industries are characterized by large heavy steel frame buildings and may utilize large cranes for heavy lifting.",
"Indicates the priority status of the airfield.",
"Type of field pattern or use.",
"Configuration of feature.",
"Calendar date/time when feature was created in the GIFD.",
"The scale to which a feature or feature set was collected.",
"Type of fence.",
"Length of crossing between shore points.",
"Indicates the maneuverability of a ferry vessel.",
"Type of firing range.",
"The classification of the type of barrier or gate.",
"The width of a single pair of rails",
"No Definition Available",
"Percentage of slope.  (i.e. The change in height divided by the horizontal distance over which the change takes place",
"Presence of support wires.",
"Distance measured from the lowest point of the base at ground or water level (downhill side/downstream side) to the tallest point of the feature.",
"Elevation above a given datum to the highest portion of the feature.",
"Type of house of worship used.",
"Identifies the annual water content of the feature.",
"Form or configuration of the hydrological feature.",
"International Civil Aviation Organization location identifier as designated in ICAO document 7910.",
"An indicator that a feature in an inland water body is an obstruction to vessel movement.",
"Maximum voltage available on the line",
"Indicates whether a feature  is used for rapid and positive orientation when size",
"No Definition Available",
"A measurement of the longer of two linear axes in meters. For a square feature",
"Type of lighting provided or type of lighting system used.",
"Military Load Classification (weight bearing capacity) Type 1.  (See STANAGs 2021 and 2253 for method of calculation)",
"Military Load Classification (weight bearing capacity) Type 2.  (See STANAGs 2021 and 2253 for method of calculation)",
"Military Load Classification (weight bearing capacity) Type 3.  (See STANAGs 2021 and 2253 for method of calculation)",
"Military Load Classification (weight bearing capacity) Type 4.  (See STANAGs 2021 and 2253 for method of calculation)",
"Status of  feature relative to surrounding area or water.",
"Area in which certain activities or factors of significance to navigation or operations apply.",
"Characteristics of primary material composition of feature.",
"Secondary material composition of feature.",
"The greatest distance between the traveled way and any obstruction vertically above it.",
"Presence of a divider between multiple lanes/rails.",
"The measured distance at map scale between connecting",
"Minimum width of the traveled way",
"No Definition Available",
"Class of missile at site.",
"This field is used to describe the list of multiple individual sources used to derive a classification for data.",
"Any identifier or code.",
"Name of the political entity on one side (relative to NM4) of a boundary line.",
"Name of the political entity on the other side (relative to NM3) of a boundary line.",
"Textual identifier of a unique name associated with a feature within an external names database.  (See also NFI)",
"Textual identifier of a unique feature within an external names database.  (See also NFN)",
"Type of equipment or system used in electronic navigation (primary system).",
"This field is used to describe non-standard classification authority used to derive a classification for data.",
"Total number of parallel lines within the feature.",
"ID of the operator that loaded the data or created the Extraction Record feature.",
"The date/time of the original source that was used for the extraction/ingest/creation of a feature.",
"Details about the originating source of the data.",
"The name of the ORIGINAL source of the data.",
"Indicates the presence of an obstruction over an area of navigable water.",
"Vertical distance measured from the lowest point at ground or water level to the highest portion of bridge (including superstructure).",
"The least distance between the traveled way and any obstruction vertically above it. (Ref. STANAG 2253)",
"The coded distance between the traveled way and any obstruction vertically above it. (Ref. STANAG 2253).",
"Indicates whether an object is temporary or permanent.  See EXS 11 and EXS 18.",
"The type of populated place.",
"Energy source used to generate power.",
"Predominant height within delineation of feature.",
"Height of 51% or more of the feature. If not obtainable",
"A range of predominant height (in meters) of vegetation within delineated area of feature (Third Range).",
"Principal material involved or product resulting from activity at site.",
"Type of connecting track.",
"The type of railroad system used to support various transportation uses.",
"The type of gauge used.",
"Source of electrical power for railroad.",
"Name of religious order at site.",
"Indicates foreign government information is included in U.S. controlled data.",
"The event upon which the declassification of the data occurs. A value of MR (Manual Review) signals that this data must be reviewed at such time that declassification is desired.",
"The code that indicates the reason that an object must remain classified beyond the 10 or 25 years automatic declassification.",
"This field is used when applicable to describe intelligence community dissemination and control of the data set or product.  This will need to reflect dissemination and control restrictions of the ORIGINATING_SOURCE.",
"This field is used when applicable to describe non-intelligence community dissemination and control of the data set or product. This will need to reflect dissemination and control restrictions of the ORIGINATING_SOURCE. This element may contain multiple dissemination control markings.",
"Denotes the countries or organizations that the data is releasable to. (This field is required when the source denotes country or organization releasability restrictions.)",
"The unique interchange design.",
"The physical surface composition of a road or runway.",
"Intended use of the route.",
"Official route number (I-95",
"Characteristic alignment of the dune as caused by the prevailing winds.",
"This field is used to describe the highest classification of the data. There MUST be one and only one classification for each feature or dataset.",
"The identifier that represents a particular SECURITY-CLASSIFICATION-SYSTEM.",
"This field is used to describe the SCI control system or systems applicable to the data set.",
"Identifies a specific military organization.",
"Describes the characteristic geometric form of the beacon.",
"The physical characteristic of the shoreline area.",
"General moisture content or condition of a soil.",
"Type of available water.",
"Geometric form",
"Roof shape.",
"Quality of the feature surface.",
"Surface material composition excluding internal structural material.",
"Narrative or other description.",
"Identifies whether a feature is affected by tidal water.",
"Appearance or configuration of the feature.",
"The number of track(s) or lanes of the feature",
"Encodes the general destination of traffic.",
"Types of suspension of power transmission lines between pylons.",
"Identifies the primary user",
"Indicates whether the feature is traversable by foot.",
"Type of tree coverage.",
"The date/time of the source that was used for the review or update of a feature.",
"Details about the update source of the data. This field is normally populated with an Image ID or a Sheet Number.",
"The name of the update source of the data.",
"No Definition Available",
"Type of plant or plantings.",
"The tidal datum to which soundings and drying heights are referenced.  It is usually taken to correspond to a low water stage of the tide.  (Also known as Chart Sounding Datum).",
"Name of Vertical Datum when VDC (Vertical Datum Category) is 999 (other).",
"Relative location referenced to sounding datum",
"Reason data is not collected.",
"Identifies type of missing information.",
"The type of geologic formation created by volcanic activity.",
"Weather conditions under which a feature is usable.",
"Type of well.",
"Identifies the type of spring or water-hole.",
"A measurement of the shorter of two linear axes.  For a square feature",
"Predominant distance across the crest of the dam",
"Minimum width of a second traveled way implementing the shorter width distance",
"A measurement of the shorter of two linear axes.  For a square feature",
"A field that indicates how the Z coordinate value(s) on the feature was determined."
};

