/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
#include "share.h"
int UFD2_CLASS_NUM=207;

char *UFD2_class_codes[] = {
"FA001",
"FA000",
"AQ010",
"AQ020",
"GB010",
"GB005",
"AK030",
"AK020",
"BB010",
"GB015",
"BH010",
"AL012",
"DA005",
"AE010",
"AK040",
"EC010",
"AP041",
"BC010",
"ZB020",
"AC010",
"DB010",
"BH015",
"ZB030",
"BB041",
"AQ045",
"AQ050",
"AQ055",
"AQ040",
"AL015",
"AL018",
"AL020",
"AL025",
"AK060",
"BH020",
"AP010",
"AC020",
"AQ064",
"DB030",
"AL030",
"AF010",
"BI010",
"EC040",
"BA010",
"AT050",
"AT080",
"AL045",
"AQ060",
"AF020",
"AF030",
"AF040",
"DB060",
"EA010",
"AQ065",
"DB070",
"BI020",
"AM010",
"AT010",
"AB000",
"BH030",
"AL060",
"AK070",
"BB090",
"AT020",
"DB090",
"AK090",
"AJ030",
"AL070",
"AQ070",
"AQ080",
"BH040",
"FA015",
"BH050",
"BB110",
"AK190",
"AF070",
"BH060",
"BH070",
"BA023",
"AH050",
"BH075",
"AL080",
"AP040",
"ZD019",
"DB115",
"AK100",
"AK101",
"AM020",
"AM030",
"AK110",
"EB010",
"BB043",
"DA010",
"BB005",
"EA020",
"GB030",
"GB035",
"EA055",
"BH077",
"AL100",
"AP020",
"BA030",
"BB140",
"BH080",
"BH090",
"GB040",
"BC050",
"BI030",
"EE010",
"ED010",
"SU001",
"AA010",
"AM040",
"AL120",
"AI020",
"AL130",
"AQ110",
"DB150",
"ZD040",
"AL135",
"EA030",
"EC020",
"AC040",
"AA052",
"EA040",
"GB045",
"AK120",
"AL140",
"BH110",
"BB190",
"AL165",
"AQ113",
"AL170",
"AD010",
"AT030",
"AT040",
"AC000",
"AQ116",
"AA012",
"AK130",
"AT045",
"AN010",
"AN050",
"AN075",
"AN060",
"BB220",
"BH120",
"BH130",
"GB050",
"BH135",
"AA040",
"BH140",
"BH145",
"AP030",
"AL200",
"GB055",
"BH155",
"BH150",
"DB170",
"EB020",
"GB065",
"BB230",
"BH160",
"AL105",
"AC030",
"AL208",
"AL019",
"BB240",
"BI040",
"AL210",
"BH165",
"BH170",
"AK160",
"AQ125",
"AM060",
"AD030",
"ED020",
"AK170",
"AM070",
"GB075",
"AT060",
"AT070",
"AK050",
"AL209",
"FA100",
"ZD045",
"AM031",
"AL240",
"AP050",
"FA165",
"EC030",
"AQ130",
"AH060",
"AQ135",
"AQ140",
"EA050",
"ZD020",
"DB180",
"AL260",
"BA040",
"BI050",
"AM080",
"BH180",
"AA050",
"AJ050",
"AJ051",
"AB010",
"AK180"
};

char *UFD2_class_names[] = {
"Administrative Area",
"Administrative Boundary",
"Aerial Cableway Lines/Ski Lift Lines",
"Aerial Cableway Pylon/Ski Pylon",
"Airport Lighting",
"Airport/Airfield",
"Amusement Park",
"Amusement Park Attraction",
"Anchorage",
"Apron/Hardstand",
"Aqueduct",
"Archeological Site",
"Asphalt Lake",
"Assembly Plant",
"Athletic Field",
"Bamboo/Cane",
"Barrier",
"Beacon",
"Benchmark",
"Blast Furnace",
"Bluff/Cliff/Escarpment",
"Bog",
"Boundary Monument",
"Breakwater",
"Bridge Span",
"Bridge Superstructure",
"Bridge Tower/Bridge Pylon",
"Bridge/Overpass/Viaduct",
"Building",
"Building Superstructure Addition",
"Built-Up Area",
"Cairn",
"Campground/Campsite",
"Canal",
"Cart Track",
"Catalytic Cracker",
"Causeway",
"Cave",
"Cemetery",
"Chimney/Smokestack",
"Cistern",
"Cleared Way/Cut Line/Firebreak",
"Coastline/Shoreline",
"Communication Building",
"Communication Tower",
"Complex Outline",
"Control Tower",
"Conveyor",
"Cooling Tower",
"Crane",
"Crevice/Crevasse",
"Cropland",
"Culvert",
"Cut",
"Dam/Weir",
"Depot (Storage)",
"Disk/Dish",
"Disposal Site/Waste Pile",
"Ditch",
"Dragon Teeth",
"Drive In Theater",
"Drydock",
"Early Warning Radar Site",
"Embankment/Fill",
"Fairgrounds",
"Feed Lot/Stockyard/Holding Pen",
"Fence",
"Ferry Crossing",
"Ferry Site",
"Filtration Beds/Aeration Beds",
"Firing Range/Gunnery Range",
"Fish Hatchery/Fish Farm/Marine Farm",
"Fish Traps/Fish Weirs",
"Fishing Pier/Promenade Pier",
"Flare Pipe",
"Flume",
"Ford",
"Foreshore (Precise IHO)",
"Fortification",
"Fountain",
"Gantry",
"Gate",
"General Miscellaneous Feature",
"Geothermal Feature",
"Golf Course",
"Golf Driving Range",
"Grain Bin/Silo",
"Grain Elevator",
"Grandstand",
"Grassland",
"Groin",
"Ground Surface Element",
"Harbor",
"Hedgerow",
"Helicopter Landing Pad",
"Heliport",
"Hops",
"Hummock",
"Hut",
"Interchange",
"Island",
"Jetty",
"Lake/Pond",
"Land Subject to Inundation",
"Launch Pad",
"Lighthouse",
"Lock",
"Logging Area",
"Marsh",
"Military Base",
"Mine",
"Mineral Pile",
"Missile Site",
"Mobile Home/Mobile Home Park",
"Monument",
"Mooring Mast",
"Mountain Pass",
"Named Location",
"Native Settlement",
"Nursery",
"Oasis",
"Oil/Gas Facilities",
"Oil/Gas Field",
"Orchard/Plantation",
"Overrun/Stopway",
"Park",
"Particle Accelerator",
"Penstock",
"Pier/Wharf/Quay",
"Pipeline Or Pipe Crossing Point",
"Pipeline/Pipe",
"Plaza/City Square",
"Power Plant",
"Power Transmission Line",
"Power Transmission Pylon",
"Processing/Treatment Plant",
"Pumping Station",
"Quarry",
"Race Track",
"Radar Transmitter",
"Railroad",
"Railroad Siding/Railroad Spur",
"Railroad Turntable",
"Railroad Yard/Marshalling Yard",
"Ramp (Maritime)",
"Rapids",
"Reservoir",
"Revetment (Airfield/Equipment/Facilities )",
"Rice Field",
"Rig/Superstructure",
"River/Stream",
"River/Stream Vanishing Point",
"Road",
"Ruins",
"Runway",
"Salt Evaporator",
"Salt Pan",
"Sand Dune/Sand Hills",
"Scrub/Brush/Bush",
"Seaplane Base",
"Seawall",
"Sebkha",
"Settlement",
"Settling Basin/Sludge Pond",
"Shanty Town",
"Shed",
"Slipway/Patent Slip",
"Sluice Gate",
"Snow Shed/Rock Shed",
"Spillway",
"Spring/Water Hole",
"Stadium/Amphitheater",
"Station (Miscellaneous)",
"Storage Bunker/Storage Mound",
"Substation/Transformer Yard",
"Swamp",
"Swimming Pool",
"Tank",
"Taxiway",
"Telephone Line/Telegraph Line",
"Telephone-Telegraph Pylon/Pole",
"Tennis Court(s)",
"Tent Dwellings",
"Test Area",
"Text Description",
"Timber Yard",
"Tower (Non-Communication)",
"Trail",
"Training Area",
"Trees",
"Tunnel",
"Underground Bunker",
"Vehicle Stopping Area/Rest Area",
"Vehicle Storage/Parking Area",
"Vineyards",
"Void Collection Area",
"Volcano",
"Wall",
"Water (Except Inland)",
"Water Intake Tower",
"Water Tower",
"Waterfall",
"Well",
"Windmill",
"Windmotor",
"Wrecking Yard/Scrap Yard",
"Zoo/Safari Park"
};

char *UFD2_class_defns[] = {
"An area controlled by administrative authority.",
"A line of demarcation between controlled areas.",
"Cables which are strung between elevated supports as part of a conveyor system on which cars, buckets, or other carrier units are suspended.",
"A tower supporting steel cables which convey cars, buckets, or other suspended carrier units.",
"Lights used to: define and outline airport components (e.g., perimeters, runways, and taxiways); guide aircraft while on the ground; and provide guidance to aircraft on approach for landing.",
"A defined area of land or water used for landing, take-off, and movement of aircraft including associated buildings and facilities.",
"A predominantly man-made facility equipped with recreational devices.  Generally containing entertainment facilities of various kinds and numerous vendors of food, souvenirs, etc..",
"A large structure located in an Amusement Park.     (NOTE -- Generally, the Amusement Park Attraction is not a Building.)",
"An area of water where vessels anchor or may anchor.",
"A defined paved or hard-packed area at an airport or heliport intended for aircraft parking.",
"A pipe or artificial channel designed to transport water from a remote source, usually by gravity.",
"A site or location where remains of ancient civilizations or human activity have been discovered.",
"A natural pool of liquid asphalt.",
"A building or group of buildings used for the purpose of combining manufactured parts to make a completed product.",
"An open area (not associated with a stadium) where sporting events, exercises, or games occur.",
"Woody, tree-like grass usually characterized by extremely dense growth.",
"A permanent obstruction placed across a transportation route to prevent vehicular traffic.",
"A fixed visual or electronic aid to navigation.",
"A reference mark on a permanent object indicating elevation relative to an established datum.",
"A heat chamber used for smelting iron ore.",
"Bluff/Cliff :  A steep, vertical, or overhanging face of rock or earth. Escarpment :  A natural relief feature with a sharp break in slope separating two comparatively level or more gently sloping surfaces.",
"A poorly drained or periodically flooded area, excluding tidal waters, with soil rich in plant residue.",
"A marker identifying the location of a surveyed boundary line.",
"A structure which protects a shore area, harbor, anchorage, or basin from sea waves or swells by preventing them from reaching the protected area or reducing their magnitude.",
"A section of the bridge deck between successive supports such as pillars, piers, or abutments.",
"Those elements of the Bridge structure that are above the lowest deck.",
"A tower or pylon from which a Bridge's deck is suspended.",
"A man-made structure spanning and providing passage over a body of water, depression, or other obstacles.",
"A relatively permanent structure, roofed and usually walled, and designed for some particular use.",
"A supplemental portion of a Building which rises from the roof but is not considered to be part of the general roof line.",
"An area containing a concentration of buildings and other structures and usually in conjunction with a well-defined road/street pattern.",
"A heap of stones piled up as a memorial or a landmark.",
"A location for camping.",
"A man-made or improved natural waterway used for transportation.",
"An unimproved natural travelled way that can accommodate four-wheel or tracked vehicles and carts.",
"A refinery unit in which petroleum separation is carried out in the presence of a catalyst.",
"A raised roadway of solid structure built primarily to provide a route across wet ground or intertidal area.",
"A natural subterranean chamber or series of chambers open to the Earth's surface.",
"An area of land for burying the dead.",
"A vertical structure containing a passage or flue for discharging smoke and gases of combustion.",
"A man-made container used for collection or storage of rain water.",
"A man-made clearing in a cultural area or through a stand of trees, designed to provide access for a road, railroad, pipeline or power transmission line, or for boundary demarcation, survey line-of-sight, or to impede the progress of forest fires",
"The line where a land mass, including Island, is in contact with a body of open water at Mean High Water.",
"A building in which communication signals are processed or controlled.",
"A relatively tall structure used for transmitting and/or receiving electronic communication signals.",
"An outline delimiting an area in which two or more like features have the same function.",
"A tower-like structure that houses the persons and equipment used to control the flow of air, rail, or marine traffic.",
"An apparatus for moving materials from place to place on a moving belt or series of rollers.",
"A tower used to cool liquids.",
"A machine for lifting, shifting, and lowering objects or materials by means of a swinging boom or with the lifting apparatus supported on an overhead track.",
"A narrow fissure, crack, or rift in the Earth's surface, snow, or ice.",
"An area that has been tilled for the planting of crops (including ground left fallow on a seasonal basis).",
"A sewer or drain crossing under a road, track, or embankment, without affecting the construction of the crossed feature.",
"An excavation of the Earth's surface to provide passage for a Road, Railroad, Canal, etc.",
"A permanent man-made barrier across a watercourse used to impound water or to control its flow.",
"An area used for the storage of products or supplies.",
"A concave object used for transmitting or receiving electronic signals.",
"A site for the collection/depositing of refuse or discarded material.",
"A channel constructed for the purpose of irrigation or drainage.",
"Regularly spaced concrete or metal barriers laid in single or multiple rows to prevent vehicle movement.",
"A place where motion pictures are shown while viewers remain in their vehicles.",
"A structure, providing support for a vessel, which has a means of removing water so that the bottom of the vessel can be exposed.",
"An installation utilizing long range radar to detect approaching aircraft or missiles.",
"A raised long mound of earth or other material.",
"An area where permanent facilities exist to hold outdoor fairs, circuses, or exhibitions.",
"An enclosed area in which livestock are temporarily kept.",
"A man-made barrier of relatively light structure used as an enclosure or boundary.",
"A route in a body of water where a ferry crosses from one shoreline to another.",
"A point where a ferry takes on or discharges its load.",
"An area containing layers of materials used to filter or aerate water.",
"An open area designated for the purpose of discharging or detonating firearms.",
"An enclosure of water used for the breeding and/or rearing of fish.",
"A fence or enclosure set in water to catch fish.",
"A structure extending into the water used as a platform for recreational purposes, not intended as a berthing place for vessels.",
"An open-ended pipe from which waste gases are burned.",
"An open, inclined channel which carries water for use in such operations as mining or logging.",
"A shallow place in a body of water used as a crossing.",
"Area between the low water line defined by Mean Low Water Springs (MLWS) or Mean Low Low Water (MLLW) as appropriate and the normal limit of wave action above Mean High Water Springs (MHWS) or Mean High High Water (MHHW) as appropriate.  The same condition may exist in non-contiguous off-shore areas.",
"A facility constructed for the military defense of a site.",
"An artificial spring with water.",
"A frame structure raised on side supports so as to span over or around something.",
"A barrier which controls passage to a road, railroad, tunnel or bridge.",
"Any feature deemed important for a particular mission or user and which is not covered by any other feature coding in this catalog.",
"A terrain surface feature controlled by or derived from the heat of the Earth's interior.",
"An area of land laid out for the game of golf.",
"A parcel or tract of land used for practicing golf shots.",
"An enclosed container used for storing grain or fodder.",
"A tall structure, equipped for loading, unloading, processing, and storing grain.",
"A usually roofed structure for special viewing of events and having tiers of seats or standing room for spectators.",
"An area composed of uncultured plants which have little or no woody tissue.",
"A structure which normally projects outward from a shoreline and which protects a beach from erosion by disrupting the longshore movement of sand and other sediments, not by preventing waves from reaching the shoreline.",
"The surface soil characteristics of the earth.",
"A natural or artificial improved body of water providing protection for vessels and anchorage and docking facilities.",
"A continuous growth of shrubbery planted as a fence, boundary, or a wind break.",
"An improved area used for take-off, and landing, by helicopters and other vertical take-off and landing aircraft.",
"A place designated for the landing and take-off of helicopters, including its buildings and facilities.",
"An area covered by the systematic planting of hop vines.",
"An area of higher elevation within a swamp, bog, or marsh.",
"A small simple or crude house or shelter.",
"A connection designed to provide traffic access from one road to another.",
"A land mass smaller than a continent and surrounded by water.",
"A man-made barrier built out into, or in the water, primarily to restrain or direct currents and waves.",
"A body of water surrounded by land where no appreciable current or flow pattern is evident.",
"An area periodically covered by flood water, excluding tidal waters.",
"A designated area or structure from which a rocket or missile is launched.",
"A distinctive structure exhibiting light(s) designed to serve as an aid in navigation.",
"An enclosure, controlling the water level, with a pair or series of gates used for raising or lowering vessels as they pass from one water level to another.",
"An area of forest or vegetation being exploited for lumber resources.",
"An area of wet, often spongy ground that is subject to frequent tidal inundations, but not considered to be continually under water.  It is characterized by the growth of non woody plants and by the lack of trees.",
"A center of operations for a military organization.",
"An excavation made in the earth for the purpose of extracting natural deposits of commercial or strategic value.",
"A man-made heap of mining or quarrying products excluding waste materials.",
"An area with related facilities for storing and launching missiles.",
"An area maintained for the parking of inhabited mobile homes.",
"A structure erected or maintained as a memorial to a person or event.",
"A tower-like structure used to secure an airship.",
"A natural route through a low place in a mountain range.",
"A geographic place on the earth, not normally appearing as a feature on a map, but having a name that is required to be placed on a map.",
"A concentration of native dwellings, generally of the hut type, which are not usually of substantial construction.",
"A place where shrubs, flowers, plants and trees are grown for transplanting, seed, or grafting.",
"A small, isolated, fertile or green area in a desert region usually having a spring or well.",
"An area involved in the production or distribution of oil or natural gas.",
"An area where oil and/or gas is pumped or otherwise removed from the ground.",
"An area covered by systematic plantings of trees which yield fruits, nuts, or other products.",
"An area beyond the take-off runway designated as able to support an airplane during an aborted take-off.",
"A predominantly natural area used for recreational or ornamental purposes.",
"An apparatus for imparting high velocities to charged particles.",
"A pipeline or channel generally used by hydroelectric plants or water mills to transport water by gravity and under pressure.",
"A structure primarily used as berthing places for vessels.",
"A traversable site extending across a pipeline or pipe that acts as a passageway for cross country movement of vehicles or troops.",
"A tube for the conveyance of solids, liquids, or gases.",
"An open area which serves as a public square in a city or town.",
"The building(s) and equipment necessary for the generation of electric power.",
"A system of above ground wires including their supports, which transmits electricity over distance.",
"A pylon or pole used to support a power transmission line.",
"A site used for changing or refining a particular material.",
"A facility to move solids, liquids, or gases by means of pressure or suction.",
"An excavation created by removal of stone by blasting or cutting.",
"A closed circuit land based course, not associated with a stadium, used for any type of racing.",
"A device for transmitting and receiving radar emissions.",
"A rail or set of parallel rails on which a train or tram runs.",
"A stretch of railroad tracks connected to the main track by switches - used for temporary storage and loading/unloading.",
"A rotating platform with railroad tracks used for turning locomotives or cars/carriages.",
"A system of tracks within defined limits, and associated features, provided for loading/unloading and assembling trains.",
"A partially submerged hard surfaced area on a shoreline for launching and retrieving vessels or vehicles.",
"A place in a stream or river where the current is swift and the surface is usually broken by boulders and rocks.",
"A man-made enclosure or area formed for the storage of water.",
"A barricade which protects an aircraft, equipment, or facilities from hostile action.",
"An area periodically covered with water used for growing rice.",
"A vertical structure fitted for drilling or lifting operations.",
"A natural flowing watercourse.",
"A point at which a river or stream passes into the ground.",
"An open way maintained for vehicular use",
"The deteriorated remains of an unspecified structure.",
"A defined area, usually rectangular, used for the conventional landing and take-off of aircraft.",
"Shallow pools, normally man-made, used for the natural evaporation of water for the collection of salt.",
"A flat area of natural surface salt deposits.",
"Ridges or hills of sand.",
"Low-growing woody plants",
"An installation supporting aircraft capable of taking off and landing on water.",
"A structure built to protect the shore from erosion.",
"A natural depression in arid or semi-arid regions whose bed is covered with salt encrusted clayey soil.",
"A concentration of small dwellings.",
"A site where solid matter is precipitated from a liquid by evaporating or settling.",
"A dense concentration of crude, improvised dwellings made from salvaged materials, usually located on the outskirts of cities, and having few, if any, streets and no facilities.",
"A storage facility usually characterized by one or more open sides, support pillars, and a roof.",
"A prepared slope for launching and recovering vessels.",
"A gate used to regulate the flow of water.",
"A shelter built to protect a section of road or railroad from snow/rock slides.",
"A passage for surplus water to run over or around a dam.",
"A natural outflow of water from below the ground surface.",
"An arena for holding and viewing events.",
"A stopping place for the transfer of passengers and/or freight.",
"A reinforced structure which may be covered or surrounded with earth which is resistant to ordinance where materials or products are stored.",
"A facility, along a power line route, in which electric current is transformed and/or distributed.",
"A low lying saturated area covered with water all or most of the year, where accumulating dead vegetation does not rapidly decay.  It can exist on flat-lying areas created by certain geomorphic environments.  The vegetation consists mainly of hydrophytic trees and/or scrubs whose roots are adapted to wet conditions, with an open to very dense canopy closure.   (NOTE -- On a comparative note, the Swamp feature will support Trees and woody growth, but a Marsh does not.)",
"A constructed basin used for swimming outdoors.",
"A container used for the storage of liquids or gases.",
"A prepared surface providing access to/from runways and the aircraft parking area, terminal area, or service area, etc.",
"A system of above ground wires, including their supports, which transmit electrical signals over distance.",
"A pylon or pole used to support a telephone or telegraph line.",
"An area or site used for the sport of tennis.",
"Dwellings (used primarily by nomadic people) that are constructed of canvas, hides, woven mats, or bark, stretched over or held up by poles, and are of a permanent nature.",
"Area for the testing of technical products.",
"An area in which a characteristic or an activity pertaining to the area can be described and possibly labeled on a product if deemed important.",
"An open area for the storage of wooden lumber and timbers.",
"A relatively tall structure which may be used for observation, support, or storage.",
"A path worn by the passage of people or animals.     (NOTE -- Generally, a Trail is not sufficiently wide enough to accommodate four-wheeled vehicles or carts.)",
"An area reserved for training.",
"Woody-perennial plants, having a self-supporting main stem or trunk.",
"An underground or underwater passage, open at both ends, and usually containing a road or railroad.",
"An underground facility used by the military either for location of command/control centers or for troop encampment.",
"A roadside place usually having facilities for people and/or vehicles.",
"An open land area used for storing or parking vehicles or vessels (including recreational vehicles).",
"An area covered by the systematic planting of grape vines.",
"An area lacking suitable source coverage, or where data is not required.",
"A mountain or hill, often conical, formed around a vent in the earth's crust through which molten rock, ash, or gases are or have been expelled.",
"A solid man-made barrier of heavy material used as an enclosure or boundary or for protection.",
"An area of water which normally has tidal fluctuations.",
"A tower-like structure associated with a dam or water source and used for the intake of water.",
"An elevated container and its supporting structure used to hold water.",
"A vertical or near vertical descent of water.",
"A hole drilled or dug into the earth or sea bed for the extraction of liquids or gases.",
"A wind-driven system of vanes attached to a tower like structure (excluding wind-generated power plants).",
"A modern structure used for wind power.",
"An area or site engaged in the wrecking, dismantling, storage, or resale of discarded products.",
"An area with a collection of live animals usually for public display."
};

unsigned char UFD2DOMAINS[]={
0  /*** Dummy Value ***/,
D_BOUN  /*** Administrative Area ***/,
D_BOUN  /*** Administrative Boundary ***/,
D_POPU  /*** Aerial Cableway Lines/Ski Lift Lines ***/,
D_POPU  /*** Aerial Cableway Pylon/Ski Pylon ***/,
D_AERO  /*** Airport Lighting ***/,
D_AERO  /*** Airport/Airfield ***/,
D_POPU  /*** Amusement Park ***/,
D_POPU  /*** Amusement Park Attraction ***/,
D_OCEN  /*** Anchorage ***/,
D_AERO  /*** Apron/Hardstand ***/,
D_INWA  /*** Aqueduct ***/,
D_POPU  /*** Archeological Site ***/,
D_PHYS  /*** Asphalt Lake ***/,
D_UTAN  /*** Assembly Plant ***/,
D_POPU  /*** Athletic Field ***/,
D_VEGE  /*** Bamboo/Cane ***/,
D_GRTR  /*** Barrier ***/,
D_AITO  /*** Beacon ***/,
D_ELEV  /*** Benchmark ***/,
D_UTAN  /*** Blast Furnace ***/,
D_PHYS  /*** Bluff/Cliff/Escarpment ***/,
D_VEGE  /*** Bog ***/,
D_BOUN  /*** Boundary Monument ***/,
D_POAN  /*** Breakwater ***/,
D_GRTR  /*** Bridge Span ***/,
D_GRTR  /*** Bridge Superstructure ***/,
D_GRTR  /*** Bridge Tower/Bridge Pylon ***/,
D_GRTR  /*** Bridge/Overpass/Viaduct ***/,
D_POPU  /*** Building ***/,
D_GRTR  /*** Building Superstructure Addition ***/,
D_POPU  /*** Built-Up Area ***/,
D_BOUN  /*** Cairn ***/,
D_POPU  /*** Campground/Campsite ***/,
D_INWA  /*** Canal ***/,
D_GRTR  /*** Cart Track ***/,
D_UTAN  /*** Catalytic Cracker ***/,
D_GRTR  /*** Causeway ***/,
D_PHYS  /*** Cave ***/,
D_POPU  /*** Cemetery ***/,
D_UTAN  /*** Chimney/Smokestack ***/,
D_INWA  /*** Cistern ***/,
D_VEGE  /*** Cleared Way/Cut Line/Firebreak ***/,
D_PHYS  /*** Coastline/Shoreline ***/,
D_UTAN  /*** Communication Building ***/,
D_UTAN  /*** Communication Tower ***/,
D_GENE  /*** Complex Outline ***/,
D_POPU  /*** Control Tower ***/,
D_UTAN  /*** Conveyor ***/,
D_UTAN  /*** Cooling Tower ***/,
D_UTAN  /*** Crane ***/,
D_PHYS  /*** Crevice/Crevasse ***/,
D_VEGE  /*** Cropland ***/,
D_GRTR  /*** Culvert ***/,
D_PHYS  /*** Cut ***/,
D_INWA  /*** Dam/Weir ***/,
D_UTAN  /*** Depot (Storage) ***/,
D_UTAN  /*** Disk/Dish ***/,
D_UTAN  /*** Disposal Site/Waste Pile ***/,
D_INWA  /*** Ditch ***/,
D_DEST  /*** Dragon Teeth ***/,
D_POPU  /*** Drive In Theater ***/,
D_POAN  /*** Drydock ***/,
D_DEST  /*** Early Warning Radar Site ***/,
D_PHYS  /*** Embankment/Fill ***/,
D_POPU  /*** Fairgrounds ***/,
D_UTAN  /*** Feed Lot/Stockyard/Holding Pen ***/,
D_POPU  /*** Fence ***/,
D_GRTR  /*** Ferry Crossing ***/,
D_GRTR  /*** Ferry Site ***/,
D_UTAN  /*** Filtration Beds/Aeration Beds ***/,
D_BOUN  /*** Firing Range/Gunnery Range ***/,
D_INWA  /*** Fish Hatchery/Fish Farm/Marine Farm ***/,
D_OCEN  /*** Fish Traps/Fish Weirs ***/,
D_POAN  /*** Fishing Pier/Promenade Pier ***/,
D_UTAN  /*** Flare Pipe ***/,
D_UTAN  /*** Flume ***/,
D_GRTR  /*** Ford ***/,
D_PHYS  /*** Foreshore (Precise IHO) ***/,
D_DEST  /*** Fortification ***/,
D_POPU  /*** Fountain ***/,
D_UTAN  /*** Gantry ***/,
D_GRTR  /*** Gate ***/,
D_GENE  /*** General Miscellaneous Feature ***/,
D_PHYS  /*** Geothermal Feature ***/,
D_POPU  /*** Golf Course ***/,
D_POPU  /*** Golf Driving Range ***/,
D_UTAN  /*** Grain Bin/Silo ***/,
D_UTAN  /*** Grain Elevator ***/,
D_POPU  /*** Grandstand ***/,
D_VEGE  /*** Grassland ***/,
D_POAN  /*** Groin ***/,
D_SUMA  /*** Ground Surface Element ***/,
D_POAN  /*** Harbor ***/,
D_VEGE  /*** Hedgerow ***/,
D_AERO  /*** Helicopter Landing Pad ***/,
D_AERO  /*** Heliport ***/,
D_VEGE  /*** Hops ***/,
D_VEGE  /*** Hummock ***/,
D_POPU  /*** Hut ***/,
D_GRTR  /*** Interchange ***/,
D_PHYS  /*** Island ***/,
D_POAN  /*** Jetty ***/,
D_INWA  /*** Lake/Pond ***/,
D_INWA  /*** Land Subject to Inundation ***/,
D_AERO  /*** Launch Pad ***/,
D_AITO  /*** Lighthouse ***/,
D_INWA  /*** Lock ***/,
D_VEGE  /*** Logging Area ***/,
D_VEGE  /*** Marsh ***/,
D_DEST  /*** Military Base ***/,
D_UTAN  /*** Mine ***/,
D_UTAN  /*** Mineral Pile ***/,
D_DEST  /*** Missile Site ***/,
D_POPU  /*** Mobile Home/Mobile Home Park ***/,
D_POPU  /*** Monument ***/,
D_AERO  /*** Mooring Mast ***/,
D_PHYS  /*** Mountain Pass ***/,
D_GENE  /*** Named Location ***/,
D_POPU  /*** Native Settlement ***/,
D_VEGE  /*** Nursery ***/,
D_VEGE  /*** Oasis ***/,
D_UTAN  /*** Oil/Gas Facilities ***/,
D_UTAN  /*** Oil/Gas Field ***/,
D_VEGE  /*** Orchard/Plantation ***/,
D_AERO  /*** Overrun/Stopway ***/,
D_POPU  /*** Park ***/,
D_UTAN  /*** Particle Accelerator ***/,
D_INWA  /*** Penstock ***/,
D_POAN  /*** Pier/Wharf/Quay ***/,
D_GRTR  /*** Pipeline Or Pipe Crossing Point ***/,
D_UTAN  /*** Pipeline/Pipe ***/,
D_POPU  /*** Plaza/City Square ***/,
D_UTAN  /*** Power Plant ***/,
D_UTAN  /*** Power Transmission Line ***/,
D_UTAN  /*** Power Transmission Pylon ***/,
D_UTAN  /*** Processing/Treatment Plant ***/,
D_UTAN  /*** Pumping Station ***/,
D_UTAN  /*** Quarry ***/,
D_POPU  /*** Race Track ***/,
D_UTAN  /*** Radar Transmitter ***/,
D_GRTR  /*** Railroad ***/,
D_GRTR  /*** Railroad Siding/Railroad Spur ***/,
D_GRTR  /*** Railroad Turntable ***/,
D_GRTR  /*** Railroad Yard/Marshalling Yard ***/,
D_POAN  /*** Ramp (Maritime) ***/,
D_INWA  /*** Rapids ***/,
D_INWA  /*** Reservoir ***/,
D_AERO  /*** Revetment (Airfield/Equipment/Facilities ) ***/,
D_VEGE  /*** Rice Field ***/,
D_UTAN  /*** Rig/Superstructure ***/,
D_INWA  /*** River/Stream ***/,
D_INWA  /*** River/Stream Vanishing Point ***/,
D_GRTR  /*** Road ***/,
D_POPU  /*** Ruins ***/,
D_AERO  /*** Runway ***/,
D_UTAN  /*** Salt Evaporator ***/,
D_UTAN  /*** Salt Pan ***/,
D_PHYS  /*** Sand Dune/Sand Hills ***/,
D_VEGE  /*** Scrub/Brush/Bush ***/,
D_AERO  /*** Seaplane Base ***/,
D_POAN  /*** Seawall ***/,
D_PHYS  /*** Sebkha ***/,
D_POPU  /*** Settlement ***/,
D_UTAN  /*** Settling Basin/Sludge Pond ***/,
D_POPU  /*** Shanty Town ***/,
D_POPU  /*** Shed ***/,
D_POAN  /*** Slipway/Patent Slip ***/,
D_INWA  /*** Sluice Gate ***/,
D_GRTR  /*** Snow Shed/Rock Shed ***/,
D_INWA  /*** Spillway ***/,
D_INWA  /*** Spring/Water Hole ***/,
D_POPU  /*** Stadium/Amphitheater ***/,
D_GRTR  /*** Station (Miscellaneous) ***/,
D_UTAN  /*** Storage Bunker/Storage Mound ***/,
D_UTAN  /*** Substation/Transformer Yard ***/,
D_VEGE  /*** Swamp ***/,
D_POPU  /*** Swimming Pool ***/,
D_UTAN  /*** Tank ***/,
D_AERO  /*** Taxiway ***/,
D_UTAN  /*** Telephone Line/Telegraph Line ***/,
D_UTAN  /*** Telephone-Telegraph Pylon/Pole ***/,
D_POPU  /*** Tennis Court(s) ***/,
D_POPU  /*** Tent Dwellings ***/,
D_BOUN  /*** Test Area ***/,
D_GENE  /*** Text Description ***/,
D_UTAN  /*** Timber Yard ***/,
D_UTAN  /*** Tower (Non-Communication) ***/,
D_GRTR  /*** Trail ***/,
D_DEST  /*** Training Area ***/,
D_VEGE  /*** Trees ***/,
D_GRTR  /*** Tunnel ***/,
D_DEST  /*** Underground Bunker ***/,
D_GRTR  /*** Vehicle Stopping Area/Rest Area ***/,
D_GRTR  /*** Vehicle Storage/Parking Area ***/,
D_VEGE  /*** Vineyards ***/,
D_GENE  /*** Void Collection Area ***/,
D_PHYS  /*** Volcano ***/,
D_POPU  /*** Wall ***/,
D_OCEN  /*** Water (Except Inland) ***/,
D_INWA  /*** Water Intake Tower ***/,
D_UTAN  /*** Water Tower ***/,
D_INWA  /*** Waterfall ***/,
D_INWA  /*** Well ***/,
D_UTAN  /*** Windmill ***/,
D_UTAN  /*** Windmotor ***/,
D_UTAN  /*** Wrecking Yard/Scrap Yard ***/,
D_POPU  /*** Zoo/Safari Park ***/
};

int UFD2DOMAINSLEN = sizeof(UFD2DOMAINS)/ sizeof(unsigned char);

unsigned char UFD2STRATS[]={
0  /*** Dummy Value ***/,
S_APPL  /*** Administrative Area ***/,
S_APPL  /*** Administrative Boundary ***/,
S_APPL  /*** Aerial Cableway Lines/Ski Lift Lines ***/,
S_APPL  /*** Aerial Cableway Pylon/Ski Pylon ***/,
S_APPL  /*** Airport Lighting ***/,
S_APPL  /*** Airport/Airfield ***/,
S_APPL  /*** Amusement Park ***/,
S_APPL  /*** Amusement Park Attraction ***/,
S_APPL  /*** Anchorage ***/,
S_APPL  /*** Apron/Hardstand ***/,
S_APPL  /*** Aqueduct ***/,
S_APPL  /*** Archeological Site ***/,
S_APPL  /*** Asphalt Lake ***/,
S_APPL  /*** Assembly Plant ***/,
S_APPL  /*** Athletic Field ***/,
S_APPL  /*** Bamboo/Cane ***/,
S_APPL  /*** Barrier ***/,
S_APPL  /*** Beacon ***/,
S_APPL  /*** Benchmark ***/,
S_APPL  /*** Blast Furnace ***/,
S_APPL  /*** Bluff/Cliff/Escarpment ***/,
S_APPL  /*** Bog ***/,
S_APPL  /*** Boundary Monument ***/,
S_APPL  /*** Breakwater ***/,
S_APPL  /*** Bridge Span ***/,
S_APPL  /*** Bridge Superstructure ***/,
S_APPL  /*** Bridge Tower/Bridge Pylon ***/,
S_APPL  /*** Bridge/Overpass/Viaduct ***/,
S_APPL  /*** Building ***/,
S_APPL  /*** Building Superstructure Addition ***/,
S_APPL  /*** Built-Up Area ***/,
S_APPL  /*** Cairn ***/,
S_APPL  /*** Campground/Campsite ***/,
S_APPL  /*** Canal ***/,
S_APPL  /*** Cart Track ***/,
S_APPL  /*** Catalytic Cracker ***/,
S_APPL  /*** Causeway ***/,
S_APPL  /*** Cave ***/,
S_APPL  /*** Cemetery ***/,
S_APPL  /*** Chimney/Smokestack ***/,
S_APPL  /*** Cistern ***/,
S_APPL  /*** Cleared Way/Cut Line/Firebreak ***/,
S_APPL  /*** Coastline/Shoreline ***/,
S_APPL  /*** Communication Building ***/,
S_APPL  /*** Communication Tower ***/,
S_APPL  /*** Complex Outline ***/,
S_APPL  /*** Control Tower ***/,
S_APPL  /*** Conveyor ***/,
S_APPL  /*** Cooling Tower ***/,
S_APPL  /*** Crane ***/,
S_APPL  /*** Crevice/Crevasse ***/,
S_APPL  /*** Cropland ***/,
S_APPL  /*** Culvert ***/,
S_APPL  /*** Cut ***/,
S_APPL  /*** Dam/Weir ***/,
S_APPL  /*** Depot (Storage) ***/,
S_APPL  /*** Disk/Dish ***/,
S_APPL  /*** Disposal Site/Waste Pile ***/,
S_APPL  /*** Ditch ***/,
S_APPL  /*** Dragon Teeth ***/,
S_APPL  /*** Drive In Theater ***/,
S_APPL  /*** Drydock ***/,
S_APPL  /*** Early Warning Radar Site ***/,
S_APPL  /*** Embankment/Fill ***/,
S_APPL  /*** Fairgrounds ***/,
S_APPL  /*** Feed Lot/Stockyard/Holding Pen ***/,
S_APPL  /*** Fence ***/,
S_APPL  /*** Ferry Crossing ***/,
S_APPL  /*** Ferry Site ***/,
S_APPL  /*** Filtration Beds/Aeration Beds ***/,
S_APPL  /*** Firing Range/Gunnery Range ***/,
S_APPL  /*** Fish Hatchery/Fish Farm/Marine Farm ***/,
S_APPL  /*** Fish Traps/Fish Weirs ***/,
S_APPL  /*** Fishing Pier/Promenade Pier ***/,
S_APPL  /*** Flare Pipe ***/,
S_APPL  /*** Flume ***/,
S_APPL  /*** Ford ***/,
S_APPL  /*** Foreshore (Precise IHO) ***/,
S_APPL  /*** Fortification ***/,
S_APPL  /*** Fountain ***/,
S_APPL  /*** Gantry ***/,
S_APPL  /*** Gate ***/,
S_APPL  /*** General Miscellaneous Feature ***/,
S_APPL  /*** Geothermal Feature ***/,
S_APPL  /*** Golf Course ***/,
S_APPL  /*** Golf Driving Range ***/,
S_APPL  /*** Grain Bin/Silo ***/,
S_APPL  /*** Grain Elevator ***/,
S_APPL  /*** Grandstand ***/,
S_APPL  /*** Grassland ***/,
S_APPL  /*** Groin ***/,
S_APPL  /*** Ground Surface Element ***/,
S_APPL  /*** Harbor ***/,
S_APPL  /*** Hedgerow ***/,
S_APPL  /*** Helicopter Landing Pad ***/,
S_APPL  /*** Heliport ***/,
S_APPL  /*** Hops ***/,
S_APPL  /*** Hummock ***/,
S_APPL  /*** Hut ***/,
S_APPL  /*** Interchange ***/,
S_APPL  /*** Island ***/,
S_APPL  /*** Jetty ***/,
S_APPL  /*** Lake/Pond ***/,
S_APPL  /*** Land Subject to Inundation ***/,
S_APPL  /*** Launch Pad ***/,
S_APPL  /*** Lighthouse ***/,
S_APPL  /*** Lock ***/,
S_APPL  /*** Logging Area ***/,
S_APPL  /*** Marsh ***/,
S_APPL  /*** Military Base ***/,
S_APPL  /*** Mine ***/,
S_APPL  /*** Mineral Pile ***/,
S_APPL  /*** Missile Site ***/,
S_APPL  /*** Mobile Home/Mobile Home Park ***/,
S_APPL  /*** Monument ***/,
S_APPL  /*** Mooring Mast ***/,
S_APPL  /*** Mountain Pass ***/,
S_APPL  /*** Named Location ***/,
S_APPL  /*** Native Settlement ***/,
S_APPL  /*** Nursery ***/,
S_APPL  /*** Oasis ***/,
S_APPL  /*** Oil/Gas Facilities ***/,
S_APPL  /*** Oil/Gas Field ***/,
S_APPL  /*** Orchard/Plantation ***/,
S_APPL  /*** Overrun/Stopway ***/,
S_APPL  /*** Park ***/,
S_APPL  /*** Particle Accelerator ***/,
S_APPL  /*** Penstock ***/,
S_APPL  /*** Pier/Wharf/Quay ***/,
S_APPL  /*** Pipeline Or Pipe Crossing Point ***/,
S_APPL  /*** Pipeline/Pipe ***/,
S_APPL  /*** Plaza/City Square ***/,
S_APPL  /*** Power Plant ***/,
S_APPL  /*** Power Transmission Line ***/,
S_APPL  /*** Power Transmission Pylon ***/,
S_APPL  /*** Processing/Treatment Plant ***/,
S_APPL  /*** Pumping Station ***/,
S_APPL  /*** Quarry ***/,
S_APPL  /*** Race Track ***/,
S_APPL  /*** Radar Transmitter ***/,
S_APPL  /*** Railroad ***/,
S_APPL  /*** Railroad Siding/Railroad Spur ***/,
S_APPL  /*** Railroad Turntable ***/,
S_APPL  /*** Railroad Yard/Marshalling Yard ***/,
S_APPL  /*** Ramp (Maritime) ***/,
S_APPL  /*** Rapids ***/,
S_APPL  /*** Reservoir ***/,
S_APPL  /*** Revetment (Airfield/Equipment/Facilities ) ***/,
S_APPL  /*** Rice Field ***/,
S_APPL  /*** Rig/Superstructure ***/,
S_APPL  /*** River/Stream ***/,
S_APPL  /*** River/Stream Vanishing Point ***/,
S_APPL  /*** Road ***/,
S_APPL  /*** Ruins ***/,
S_APPL  /*** Runway ***/,
S_APPL  /*** Salt Evaporator ***/,
S_APPL  /*** Salt Pan ***/,
S_APPL  /*** Sand Dune/Sand Hills ***/,
S_APPL  /*** Scrub/Brush/Bush ***/,
S_APPL  /*** Seaplane Base ***/,
S_APPL  /*** Seawall ***/,
S_APPL  /*** Sebkha ***/,
S_APPL  /*** Settlement ***/,
S_APPL  /*** Settling Basin/Sludge Pond ***/,
S_APPL  /*** Shanty Town ***/,
S_APPL  /*** Shed ***/,
S_APPL  /*** Slipway/Patent Slip ***/,
S_APPL  /*** Sluice Gate ***/,
S_APPL  /*** Snow Shed/Rock Shed ***/,
S_APPL  /*** Spillway ***/,
S_APPL  /*** Spring/Water Hole ***/,
S_APPL  /*** Stadium/Amphitheater ***/,
S_APPL  /*** Station (Miscellaneous) ***/,
S_APPL  /*** Storage Bunker/Storage Mound ***/,
S_APPL  /*** Substation/Transformer Yard ***/,
S_APPL  /*** Swamp ***/,
S_APPL  /*** Swimming Pool ***/,
S_APPL  /*** Tank ***/,
S_APPL  /*** Taxiway ***/,
S_APPL  /*** Telephone Line/Telegraph Line ***/,
S_APPL  /*** Telephone-Telegraph Pylon/Pole ***/,
S_APPL  /*** Tennis Court(s) ***/,
S_APPL  /*** Tent Dwellings ***/,
S_APPL  /*** Test Area ***/,
S_APPL  /*** Text Description ***/,
S_APPL  /*** Timber Yard ***/,
S_APPL  /*** Tower (Non-Communication) ***/,
S_APPL  /*** Trail ***/,
S_APPL  /*** Training Area ***/,
S_APPL  /*** Trees ***/,
S_APPL  /*** Tunnel ***/,
S_APPL  /*** Underground Bunker ***/,
S_APPL  /*** Vehicle Stopping Area/Rest Area ***/,
S_APPL  /*** Vehicle Storage/Parking Area ***/,
S_APPL  /*** Vineyards ***/,
S_APPL  /*** Void Collection Area ***/,
S_APPL  /*** Volcano ***/,
S_APPL  /*** Wall ***/,
S_APPL  /*** Water (Except Inland) ***/,
S_APPL  /*** Water Intake Tower ***/,
S_APPL  /*** Water Tower ***/,
S_APPL  /*** Waterfall ***/,
S_APPL  /*** Well ***/,
S_APPL  /*** Windmill ***/,
S_APPL  /*** Windmotor ***/,
S_APPL  /*** Wrecking Yard/Scrap Yard ***/,
S_APPL  /*** Zoo/Safari Park ***/
};

int UFD2STRATSLEN = sizeof(UFD2STRATS)/ sizeof(unsigned char);


