/************
GAIT (Geospatial Analysis Integrity Tool) is a geospatial data validation tool developed by the Institute for Defense Analyses (IDA) for the National Geospatial-Intelligence Agency (NGA).  

This source code was used to generate GAIT 26 executable software in accordance with Amendment 6 to Task Order DH-8-3815 under Contract HQ0034-14-D-0001.

IDA is furnishing this item "as is". IDA was not tasked or funded to generate developer documentation or to provide support for this source code. IDA does not provide any warranty of the item whatsoever, whether express, implied, or statutory, including, but not limited to, any warranty of fitness for a particular purpose or any warranty that the contents of the item will be error-free. In no event shall NGA or IDA be held liable for damages arising, directly or indirectly, from the use of this source code. 

This material may be reproduced by the U.S. Government pursuant to its unlimited use rights under DFARS 252.227-7014 [Feb 2014].

The Institute for Defense Analyses (IDA) is a Federally Funded Research and Development Center that provides scientific and technical expertise on issues important to national security to the Office of the Secretary of Defense, Joint Staff, Unified Commands, and Defense Agencies. 

© 2017 Institute for Defense Analyses
  4850 Mark Center Drive
  Alexandria, Virginia 22311-1882
  703.845-2000
  www.ida.org
************/
int UFD3_ATTR_NUM=125;

char *UFD3_attr_codes[] = {
"ACE",
"ACE_EVAL_METHOD_CD",
"ALE",
"ALE_EVAL_METHOD_CD",
"ACC",
"ORIGINATOR",
"ATN",
"APT",
"ZV3",
"AOO",
"ATC",
"BOT",
"BSM",
"BSC",
"BUD",
"BFC",
"BCC",
"COD",
"COE",
"SEC_CLS_AUTHORITY",
"COMMENTS",
"COMM_CPYRT_NOTICE",
"COMPLETENESS_CODE",
"DMT",
"DEP",
"COMM_LIC_TIER_NOTICE",
"ELA",
"EXS",
"SPEC_ID",
"FTP",
"FTC",
"FCO",
"FCM",
"CREATION_DATE",
"SCALE",
"FTI",
"FER",
"FRT",
"GAW",
"GFID",
"SGC",
"GUG",
"HGT",
"ZV2",
"HWT",
"HYC",
"IKO",
"LMC",
"LEN",
"LEG",
"LEN_",
"LFA",
"LC1",
"LC2",
"LC3",
"LC4",
"LOC",
"MCC",
"MVC",
"MED",
"WD1",
"MIN",
"MST",
"SEC_CLS_AUTH_MULT",
"NAM",
"NFN",
"NFI",
"NST",
"SEC_CLS_AUTH_DESC",
"NPL",
"OPERATOR",
"ORIG_SOURCE_DATE",
"ORIG_SOURCE_INFO",
"ORIGINATING_SOURCE",
"OWO",
"OHB",
"OCC",
"PRM",
"PPC",
"PFG",
"PHT",
"VH3",
"PRO",
"RRC",
"RGC",
"RRA",
"REL",
"RSTRN_FOREIGN_GOV",
"RSTRN_DECLASS",
"RSTRN_DCLS_XMPT_CD",
"RSTRN_DSEM_CTRL_IC",
"RSTRN_DSEM_CTRL_NIC",
"RSTRN_RELEASIBILITY",
"RIT",
"RST",
"RTT",
"RTN",
"SEC_CLASS",
"SEC_CLASS_SYS_ID",
"SEC_CD_CNTRL",
"YSU",
"SSC",
"SSR",
"SMC",
"TXT",
"LTN",
"TUC",
"TRA",
"TRE",
"UPDATE_SOURCE_DATE",
"UPDATE_SOURCE_INFO",
"UPDATE_SOURCE",
"WDU",
"USG",
"USE_",
"LNU",
"VEG",
"VOI",
"WST",
"WTC",
"WID",
"WOC",
"WT2",
"WGP",
"Z_VALUE_TYPE"
};

char *UFD3_attr_names[] = {
"Absolute Circular Error",
"Absolute Circular Error Evaluation Method",
"Absolute Linear Error",
"Absolute Linear Error Evaluation Method",
"Accuracy Category",
"Agency that Supplied the Data",
"Aids to Navigation",
"Airfield Type",
"Airfield/Aerodrome elevation",
"Angle of Orientation",
"Aqueduct Type Category",
"Bridge Opening Type",
"Bridge Span Mobility",
"Bridge/Bridge Superstructure Category",
"Brush/Undergrowth Density Code",
"Building Function Category",
"Bypass Condition Category",
"Certainty of Delineation",
"Certainty of Existence",
"Classification Authority",
"Comments",
"Commercial Copyright Notice",
"Completeness Code",
"Density Measure (% of Tree/Canopy Cover)",
"Depth Below Surface Level",
"Distribution of Commercial Data",
"Elevation Accuracy",
"Existence Category",
"Extraction Specification ID",
"Fabrication Type",
"Farming Type Category",
"Feature Configuration",
"Feature Construction Material Code",
"Feature Creation Date",
"Feature Scale (e.g., 50000, 100000)",
"Fence Type Indicator",
"Ferry Type",
"Firing Range Type",
"Gauge Width",
"Global Feature ID",
"Gradient/Slope",
"Guyed or Unguyed Category",
"Height Above Surface Level",
"Highest Z-Value",
"House of Worship Type",
"Hydrological Category",
"ICAO Designator",
"Landmark Category",
"Length/Diameter",
"Length/Diameter in Meters With Greater Precision",
"Length/Diameter2",
"Light Function Aeronautical",
"Load Class Type 1",
"Load Class Type 2",
"Load Class Type 3",
"Load Class Type 4",
"Location Category",
"Material Composition Category",
"Maximum Vertical Clearance",
"Median Category",
"Minimum Traveled Way Width",
"Mining Category",
"Missile Site Type",
"Multiple Classification Authority Sources",
"Name",
"Name Identifier",
"Named Feature Identifier",
"Navigation System Types",
"Non-standard Classification Authority",
"Number of Parallel Lines",
"Operator ID",
"Originating Source Date",
"Originating Source Information",
"Originating Source Name",
"Over Water Obstruction",
"Overall Height of Bridge",
"Overhead Clearance Category Code",
"Permanency",
"Power Plant Category",
"Predominant Feature Height With greater than 1 meter resolution",
"Predominant Height",
"Predominant Vegetation Height Range",
"Product Category",
"Railroad Categories",
"Railroad Gauge Category",
"Railroad Power Source",
"Religious Denomination",
"Restrctions on Foreign Government Access",
"Restriction Declassification",
"Restriction Declassification Exemptions",
"Restrictions on Dissemination Control IC",
"Restrictions on Dissemination Control Non-IC",
"Restrictions on Releasibility",
"Road Interchange Type",
"Road/Runway Surface Type",
"Route Intended Use",
"Route Number",
"Security Classification",
"Security Classification System Identifier",
"Security Codeword Control",
"Service Branch",
"Structure Shape Category",
"Structure Shape of Roof",
"Surface Material Category",
"Text Attribute",
"Track/Lane Number",
"Transportation Use Category",
"Traversability",
"Tree Type Category",
"Update/Review Source Date",
"Update/Review Source Information",
"Update/Review Source Name",
"Usable Width",
"Usage",
"Usage2",
"Useable Length",
"Vegetation Characteristics",
"Vertical Obstruction Identifier",
"Water Sink Type",
"Weather Type Category",
"Width",
"Width of Crest",
"Width of Second Traveled Way",
"Width with greater than 1 meter resolution",
"Z-Coordinate Type"
};

char *UFD3_attr_types[] = {
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Float",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Date",
"Long Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Integer",
"String",
"Short Integer",
"Short Integer",
"Float",
"Float",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Integer",
"Float",
"Integer",
"Short Integer",
"Integer",
"Integer",
"Integer",
"Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"Short Integer",
"String",
"Integer",
"String",
"Date",
"String",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Float",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"String",
"String",
"String",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"String",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Short Integer",
"Short Integer",
"Date",
"String",
"Short Integer",
"Integer",
"Short Integer",
"Short Integer",
"Integer",
"Short Integer",
"String",
"Short Integer",
"Short Integer",
"Integer",
"Float",
"Float",
"Float",
"Short Integer"
};

char *UFD3_attr_defns[] = {
"The absolute horizontal accuracy of the data's coordinates",
"The code that indicates the method by which the absolute circular error was derived.",
"The absolute vertical accuracy of the data's coordinates",
"The code that indicates the method by which the absolute linear error was derived.",
"Accuracy of geographic position.",
"This field is used to describe the organization or agency with which the originating author/creator of the data is associated.",
"Indicates whether a feature is marked or unmarked by an aid to navigation.",
"Unique airfield type.",
"The highest point of an airport's usable runways measured in meters from mean sea level.",
"The angular distance measured from true north (0 deg) clockwise to the major axis of the feature. If the feature is square, the axis 0 through 89 deg shall be recorded. If the feature is circular, 360 deg shall be recorded.",
"Type of aqueduct.",
"The type of structure or mechanism by which a portion of a bridge is moved to allow passage of a vessel.",
"Identifies bridge spans that move in some manner allowing passage underneath the span.",
"Structural design characteristics.",
"Density of brush or undergrowth.",
"Type or purpose of the building.",
"The ease or ability to circumvent a destroyed section of bridge, tunnel or pass within a 2 kilometer distance on each side of the feature.  Bypass condition will not consider other bridges in bypass determination.",
"Indicates knowledge of the feature's limits or information.",
"Indicates knowledge of the feature's existence.",
"The code that represents the type of classification authority used to derive a classification for data.",
"An open text field for additional information.",
"This field is used when a data set includes commercial products or any other copyrighted data. Example: Copyright 2000 Space Imaging",
"Identifies if the extraction is 100% complete IAW the specification identified in the SPEC_ID attribute.",
"Canopy cover measured by percent within area of feature during the summer season.",
"Distance measured from the highest point at surface level to the lowest point of the feature below the surface. Recorded values are positive numbers.",
"This field is used to identify the distribution of commercial or other restricted data.",
"Indicates whether the ZVL value is accurately known.",
"The state or condition of the feature.",
"The particular specification that was used for the extraction process.",
"Denotes the type of fabrication industry as light or heavy.  Light fabrication industries are characterized by light steel or woodframe buildings and lack heavy equipment.  Heavy fabrication industries are characterized by large heavy steel frame buildings and may utilize large cranes for heavy lifting.",
"Type of field pattern or use.",
"Configuration of feature.",
"A code indicating the construction materials comprising the feature.",
"Calendar date/time when feature was created in the GIFD.",
"The scale to which a feature or feature set was collected.",
"Type of fence.",
"Indicates the maneuverability of a ferry vessel.",
"Type of firing range.",
"The width of a single pair of rails, measured along the shortest distance from inside rail to inside rail.",
"No Definition Available",
"Percentage of slope.  (i.e. The change in height divided by the horizontal distance over which the change takes place, times one hundred ((h2-h1)/d)*100.)",
"Presence of support wires.",
"Distance measured from the lowest point of the base at ground or water level (downhill side/downstream side) to the tallest point of the feature.",
"Elevation above a given datum to the highest portion of the feature.",
"Type of house of worship used.",
"Identifies the annual water content of the feature.",
"International Civil Aviation Organization location identifier as designated in ICAO document 7910.",
"Indicates whether a feature  is used for rapid and positive orientation when size, shape, or location make it prominent in relation to surroundings. Easily recognized from line of sight - ground or air.",
"Definition Is Not Available",
"A measurement of the longer of two linear axes in meters. For a square feature, measure either axis. For a round feature, measure the diameter. For a bridge, the length is the distance between the bridge abutments.",
"No Definition Available",
"Type of lighting provided or type of lighting system used.",
"Military Load Classification (weight bearing capacity) Type 1.  (See STANAGs 2021 and 2253 for method of calculation)",
"Military Load Classification (weight bearing capacity) Type 2.  (See STANAGs 2021 and 2253 for method of calculation)",
"Military Load Classification (weight bearing capacity) Type 3.  (See STANAGs 2021 and 2253 for method of calculation)",
"Military Load Classification (weight bearing capacity) Type 4.  (See STANAGs 2021 and 2253 for method of calculation)",
"Status of  feature relative to surrounding area or water.",
"Characteristics of primary material composition of feature.",
"The greatest distance between the traveled way and any obstruction vertically above it.",
"Presence of a divider between multiple lanes/rails.",
"Minimum width of the traveled way, excluding hard pavements and shoulders (in decimetres).",
"Definition Is Not Available",
"Class of missile at site.",
"This field is used to describe the list of multiple individual sources used to derive a classification for data.",
"Any identifier or code.",
"Textual identifier of a unique name associated with a feature within an external names database.  (See also NFI)",
"Textual identifier of a unique feature within an external names database.  (See also NFN)",
"Type of equipment or system used in electronic navigation (primary system).",
"This field is used to describe non-standard classification authority used to derive a classification for data.",
"Total number of parallel lines within the feature.",
"ID of the operator that loaded the data or created the Extraction Record feature.",
"The date/time of the original source that was used for the extraction/ingest/creation of a feature.",
"Details about the originating source of the data.",
"The name of the ORIGINAL source of the data.",
"Indicates the presence of an obstruction over an area of navigable water.",
"Vertical distance measured from the lowest point at ground or water level to the highest portion of bridge (including superstructure).",
"The coded distance between the traveled way and any obstruction vertically above it. (Ref. STANAG 2253).",
"Indicates whether an object is temporary or permanent.  See EXS 11 and EXS 18.",
"Energy source used to generate power.",
"Predominant height within delineation of feature.",
"Height of 51% or more of the feature. If not obtainable, then the average height of the feature will be used.",
"A range of predominant height (in meters) of vegetation within delineated area of feature (Third Range).",
"Principal material involved or product resulting from activity at site.",
"The type of railroad system used to support various transportation uses.",
"The type of gauge used.",
"Source of electrical power for railroad.",
"Name of religious order at site.",
"Indicates foreign government information is included in U.S. controlled data.",
"The event upon which the declassification of the data occurs. A value of MR (Manual Review) signals that this data must be reviewed at such time that declassification is desired.",
"The code that indicates the reason that an object must remain classified beyond the 10 or 25 years automatic declassification.",
"This field is used when applicable to describe intelligence community dissemination and control of the data set or product.  This will need to reflect dissemination and control restrictions of the ORIGINATING_SOURCE.",
"This field is used when applicable to describe non-intelligence community dissemination and control of the data set or product. This will need to reflect dissemination and control restrictions of the ORIGINATING_SOURCE. This element may contain multiple dissemination control markings.",
"Denotes the countries or organizations that the data is releasable to. (This field is required when the source denotes country or organization releasability restrictions.)",
"The unique interchange design.",
"The physical surface composition of a road or runway.",
"Intended use of the route.",
"Official route number (I-95, M-2, A-1, etc.) assigned to the feature.",
"This field is used to describe the highest classification of the data. There MUST be one and only one classification for each feature or dataset.",
"The identifier that represents a particular SECURITY-CLASSIFICATION-SYSTEM.",
"This field is used to describe the SCI control system or systems applicable to the data set.",
"Identifies a specific military organization.",
"Geometric form, appearance, or configuration of the feature.",
"Roof shape.",
"Surface material composition excluding internal structural material.",
"Narrative or other description.",
"The number of track(s) or lanes of the feature, including both directions.",
"Identifies the primary user, function, or authority of the transportation system.",
"Indicates whether the feature is traversable by foot.",
"Type of tree coverage.",
"The date/time of the source that was used for the review or update of a feature.",
"Details about the update source of the data. This field is normally populated with an Image ID or a Sheet Number.",
"The name of the update source of the data.",
"The interior width of a feature that is useable by a vehicle, aircraft or watercraft located within that feature.  This would apply to such features as locks and aircraft bunkers which may have different exterior and interior dimensions.  A measurement of the shorter of the two linear axes.  For a square feature, measure either axis.  For a round feature, width shall be equal to LNU.",
"Definition Is Not Available",
"No Definition Available",
"The interior length of a feature that is useable by a vehicle, aircraft or watercraft located within that feature.  This would apply to such features as locks and aircraft bunkers which may have different exterior and interior dimensions.  A measurement of the longer of the  two linear axes. For a square feature, measure either axis. For a round feature, measure the diameter.",
"Type of plant or plantings.",
"Identification code that uniquely identifies a feature that is a vertical obstruction to low-level flight.  (1-2 First two characters of NA4 - Country Code; 3-6 World Aeronautical Chart (WAC) Identifier; 7-10 Unique Obstruction Identification Number; 11 Producer Code)",
"Definition Is Not Available",
"Weather conditions under which a feature is usable.",
"A measurement of the shorter of two linear axes.  For a square feature, measure either axis.  For a round feature, width shall be equal to LEN.  For a bridge, the width is the measurement perpendicular to the axis between the abutments.",
"Predominant distance across the crest of the dam, measured perpendicular to the centerline of its length along the crest.",
"Minimum width of a second traveled way implementing the shorter width distance, excluding hard pavements and shoulders (in decimetres).",
"A measurement of the shorter of two linear axes.  For a square feature, measure either axis.  For a round feature, width shall be equal to LEN.  For a bridge, the width is the measurement perpendicular to the axis between the abutments.",
"A field that indicates how the Z coordinate value(s) on the feature was determined."
};

